### ISSUE TITLE
MeshRouter download link broken?

### ISSUE THREAD

**Issue by MordyT** [Ylianst/MeshCentral#1036]
2 separate servers...

The download link for MeshRouter does not work. It's pointing to:
https://mesh.domain.tld/meshagents?meshaction=winrouter
and it downloads a files "meshagents.html", but fails to finish the download.

Previous downloads of router still work. 

Logs show:
`ERR: ReferenceError: Cannot access 'domain' before initialization
    at obj.handleMeshAgentRequest (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\webserver.js:3240:13)
    at Layer.handle [as handle_request] (C:\Program Files\Open Source\MeshCentral\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Program Files\Open Source\MeshCentral\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Program Files\Open Source\MeshCentral\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Program Files\Open Source\MeshCentral\node_modules\express\lib\router\layer.js:95:5)
    at C:\Program Files\Open Source\MeshCentral\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Program Files\Open Source\MeshCentral\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Program Files\Open Source\MeshCentral\node_modules\express\lib\router\index.js:275:10)
    at C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\webserver.js:3593:24
    at Layer.handle [as handle_request] (C:\Program Files\Open Source\MeshCentral\node_modules\express\lib\router\layer.js:95:5)`

**Comment by Ylianst** [comment]
You right! Working on it.

**Comment by Ylianst** [comment]
Published MeshCentral v0.5.0-l with a fix. Let me know if it works.

**Comment by MordyT** [comment]
Appears to be working. Thanks!
