### ISSUE TITLE
Error: ENOENT: no such file or directory, uv_cwd

### ISSUE THREAD

**Issue by GnaXi** [Ylianst/MeshCentral#1059]
I've just updated to the latest version of Meshcentral (0.5.0-s) and is no longer able to start it.
I get the following error:
internal/bootstrap/switches/does_own_process_state.js:128
  cachedCwd = rawMethods.cwd();
                         ^

Error: ENOENT: no such file or directory, uv_cwd
    at process.wrappedCwd [as cwd] (internal/bootstrap/switches/does_own_process_state.js:128:26)
    at Object.resolve (path.js:978:47)
    at patchProcessObject (internal/bootstrap/pre_execution.js:89:28)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:16:3)
    at internal/main/run_main_module.js:7:1 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
}

**Comment by GnaXi** [comment]
Nevermind. I made a backup of my data folder and reinstalled it.
Everything is working again! :)

**Comment by Ylianst** [comment]
That is weird. It's not an exception in the MeshCentral code. I wonder what happened.
