### ISSUE TITLE
Error when settings up LDAP

### ISSUE THREAD

**Issue by orthelan** [Ylianst/MeshCentral#1080]
I recieve the following error when trying to run meshcentral with LDAP configured:

```
ERR: /opt/meshcentral/node_modules/meshcentral/meshcentral.js:935
            if (obj.config.domains[i].limits == null) { obj.config.domains[i].limits = {}; }
                                                                                     ^

TypeError: Cannot create property 'limits' on string 'ldap'
    at Object.CreateMeshCentralServer.obj.StartEx1b (/opt/meshcentral/node_modules/meshcentral/meshcentral.js:935:86)
    at /opt/meshcentral/node_modules/meshcentral/meshcentral.js:875:29
    at /opt/meshcentral/node_modules/meshcentral/db.js:64:13
    at /opt/meshcentral/node_modules/meshcentral/db.js:1086:25
    at newArguments.(anonymous function) (/opt/meshcentral/node_modules/nedb/lib/executor.js:29:17)
    at Cursor.execFn (/opt/meshcentral/node_modules/nedb/lib/datastore.js:484:12)
    at callback (/opt/meshcentral/node_modules/nedb/lib/cursor.js:126:19)
    at /opt/meshcentral/node_modules/nedb/lib/cursor.js:193:12
    at /opt/meshcentral/node_modules/nedb/lib/datastore.js:329:14
    at Object.async.eachSeries (/opt/meshcentral/node_modules/nedb/node_modules/async/lib/async.js:130:20)
{ Error: Command failed: /usr/bin/node /opt/meshcentral/node_modules/meshcentral --launch 2893
/opt/meshcentral/node_modules/meshcentral/meshcentral.js:935
            if (obj.config.domains[i].limits == null) { obj.config.domains[i].limits = {}; }
                                                                                     ^

TypeError: Cannot create property 'limits' on string 'ldap'
    at Object.CreateMeshCentralServer.obj.StartEx1b (/opt/meshcentral/node_modules/meshcentral/meshcentral.js:935:86)
    at /opt/meshcentral/node_modules/meshcentral/meshcentral.js:875:29
    at /opt/meshcentral/node_modules/meshcentral/db.js:64:13
    at /opt/meshcentral/node_modules/meshcentral/db.js:1086:25
    at newArguments.(anonymous function) (/opt/meshcentral/node_modules/nedb/lib/executor.js:29:17)
    at Cursor.execFn (/opt/meshcentral/node_modules/nedb/lib/datastore.js:484:12)
    at callback (/opt/meshcentral/node_modules/nedb/lib/cursor.js:126:19)
    at /opt/meshcentral/node_modules/nedb/lib/cursor.js:193:12
    at /opt/meshcentral/node_modules/nedb/lib/datastore.js:329:14
    at Object.async.eachSeries (/opt/meshcentral/node_modules/nedb/node_modules/async/lib/async.js:130:20)

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:194:15)
    at maybeClose (internal/child_process.js:970:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:189:13)
    at Pipe._handle.close (net.js:600:12)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   '/usr/bin/node /opt/meshcentral/node_modules/meshcentral --launch 2893' }
```

My LDAP configuration looks like this:

```
   "auth": "ldap",
   "ldapUserName": "DisplayName",
   "ldapUserBinaryKey": "objectSid",
   "ldapOptions": {
           "url": "ldap:172.16.0.33:389",
           "bindDN": "CN=user,CN=Users,DC=example,DC=com",
           "bindCredentials": "password",
           "searchBase": "DC=example,DC=com",
           "searchFilter": "(sAMAccountName={{username}})"
   }
```

**Comment by Ylianst** [comment]
Thanks for the report, checking this now!

**Comment by Ylianst** [comment]
The problem here is the your configuration is it the wrong place in the config.json document. You should be placing `"auth": "ldap"` within one of the domains. instead, It's been placed in the domain section itself which is not valid. Change it like this:

```
  "domains": {
    "": {
      "auth": "ldap",
      "ldapUserName": "DisplayName",
      "ldapUserBinaryKey": "objectSid",
      "ldapOptions": {
           "url": "ldap:172.16.0.33:389",
           "bindDN": "CN=user,CN=Users,DC=example,DC=com",
           "bindCredentials": "password",
           "searchBase": "DC=example,DC=com",
           "searchFilter": "(sAMAccountName={{username}})"
      }
    }
  }
```

**Comment by Ylianst** [comment]
Thanks for the report. Just pushed an update in GitHub that will display the following when the domain configuration is not right in config.json:

`ERROR: Invalid domain configuration in config.json.`

Hopefully, that will help guide users in the same situation.

**Comment by orthelan** [comment]
That fixed it. Thank you for the pointer.
