### ISSUE TITLE
MC router unhandled exception

### ISSUE THREAD

**Issue by amenolo** [Ylianst/MeshCentral#1114]
**MC router version**: 1.0.7396
**OS version**: Windows 10 1909 x64 (brand new installation) along with .NET Framework 3.5/4.8

![exception](https://user-images.githubusercontent.com/29974944/78473666-bc5d4f00-7742-11ea-9237-00bdacd8a1d3.png)

**Details**:

```
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at MeshCentralRouter.MainForm.getRegValue(String name, String value)
   at MeshCentralRouter.MainForm.MainForm_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
MeshCentralRouter
    Assembly Version: 1.0.7396.29345
    Win32 Version: 1.0.7396.29345
    CodeBase: file:///C:/Users/amenolo/Desktop/MeshCentralRouter.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
```
Tested with compatibility settings too, no luck.

Anyway if CONTINUE selected, program seems to run flawless but I wonder...maybe I'm missing some optional requirement?

Thanks!

**Comment by Ylianst** [comment]
Perfect, thanks for the detailed report. Should not be too difficult to fix. I will work on it.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.5.1-f with a fix for this. You will need to update the server and re-download MeshCentral Router. Let me know if it works.

**Comment by amenolo** [comment]
You did the trick, issue solved 👍 

BTW do you confirm at the moment ain't no way to avoid Windows Defender false positive (for Agent too, as you know)? Matter of digital signature issue, right?

![defender](https://user-images.githubusercontent.com/29974944/78509189-b2603e00-778c-11ea-86fb-a36e22f00aab.png)

thanks

**Comment by amenolo** [comment]
You did the trick, issue solved 👍 

BTW do you confirm at the moment ain't no way to avoid Windows Defender false positive (for Agent too, as you know)? Matter of digital signature, right?

![defender](https://user-images.githubusercontent.com/29974944/78509189-b2603e00-778c-11ea-86fb-a36e22f00aab.png)

thanks

**Comment by Ylianst** [comment]
Thanks. So right, I can't do anything about Windows Defender. If you have your own code-signing certificate, you can use it yourself, but the open source version is currently signed by a self-signed certificate.

**Comment by Ylianst** [comment]
Will close this since router is fixed. Feel free to open other issue for other topics.
