### ISSUE TITLE
update problem

### ISSUE THREAD

**Issue by coolwormgit** [Ylianst/MeshCentral#1122]
hello , i have server on windows 10 and updated today i get those errors

-------- 3/27/2020, 9:18:01 PM ---- 0.5.0-w --------

BadRequestError: request aborted
    at IncomingMessage.onAborted (C:\Program Files\Open Source\MeshCentral\node_modules\raw-body\index.js:231:10)
    at IncomingMessage.emit (events.js:197:13)
    at abortIncoming (_http_server.js:450:9)
    at socketOnClose (_http_server.js:443:3)
    at TLSSocket.emit (events.js:202:15)
    at _handle.close (net.js:611:12)
    at Socket.done (_tls_wrap.js:412:7)
    at Object.onceWrapper (events.js:285:13)
    at Socket.emit (events.js:197:13)
    at TCP._handle.close (net.js:611:12)

i noticed that a lot of my devices looks connected but doesnt have remote, files etc.....

thanks

**Comment by Ylianst** [comment]
Sadly, there is not sufficient information to help. What NodeJS version are you using? MeshCentral version? Are you running a reverse proxy? Are plug-in's enabled?

Since the error is not directly in MeshCentral code, is there anything that would cause connections to the server to close?
