### ISSUE TITLE
Removing a user which has an active session crashes the server

### ISSUE THREAD

**Issue by guerby** [Ylianst/MeshCentral#1167]
Removing a user which has an active meshcentral session crashes the server with the following backtrace.

Edge case, unimportant since systemd will automatically restart the server in my case

debian 10.3
node v10.15.2
mescentral 0.5.1-w

```
Apr 16 13:33:42 meshcentral node[13705]: ERR: /root/meshcentral/node_modules/meshcentral/meshrelay.js:346
Apr 16 13:33:42 meshcentral node[13705]:                             var event = { etype: 'relay', action: 'relaylog', domain: domain.id, userid: user._id, username: parent.users[user._id].name, msg: msg + ' \"'
Apr 16 13:33:42 meshcentral node[13705]:                                                                                                                                                     ^
Apr 16 13:33:42 meshcentral node[13705]: TypeError: Cannot read property 'name' of undefined
Apr 16 13:33:42 meshcentral node[13705]:     at closeBothSides (/root/meshcentral/node_modules/meshcentral/meshrelay.js:346:149)
Apr 16 13:33:42 meshcentral node[13705]:     at WebSocket.<anonymous> (/root/meshcentral/node_modules/meshcentral/meshrelay.js:322:9)
Apr 16 13:33:42 meshcentral node[13705]:     at WebSocket.emit (events.js:194:15)
Apr 16 13:33:42 meshcentral node[13705]:     at WebSocket.emitClose (/root/meshcentral/node_modules/express-ws/node_modules/ws/lib/websocket.js:172:10)
Apr 16 13:33:42 meshcentral node[13705]:     at TLSSocket.socketOnClose (/root/meshcentral/node_modules/express-ws/node_modules/ws/lib/websocket.js:781:15)
Apr 16 13:33:42 meshcentral node[13705]:     at TLSSocket.emit (events.js:194:15)
Apr 16 13:33:42 meshcentral node[13705]:     at _handle.close (net.js:600:12)
Apr 16 13:33:42 meshcentral node[13705]:     at Socket.done (_tls_wrap.js:388:7)
Apr 16 13:33:42 meshcentral node[13705]:     at Object.onceWrapper (events.js:277:13)
Apr 16 13:33:42 meshcentral node[13705]:     at Socket.emit (events.js:189:13)
Apr 16 13:33:42 meshcentral node[13705]:     at TCP._handle.close (net.js:600:12)
Apr 16 13:33:42 meshcentral node[13705]: { Error: Command failed: /usr/bin/node /root/meshcentral/node_modules/meshcentral --launch 13705
Apr 16 13:33:42 meshcentral node[13705]: /root/meshcentral/node_modules/meshcentral/meshrelay.js:346
Apr 16 13:33:42 meshcentral node[13705]:                             var event = { etype: 'relay', action: 'relaylog', domain: domain.id, userid: user._id, username: parent.users[user._id].name, msg: msg + ' \"'
Apr 16 13:33:42 meshcentral node[13705]:                                                                                                                                                     ^
Apr 16 13:33:42 meshcentral node[13705]: TypeError: Cannot read property 'name' of undefined
Apr 16 13:33:42 meshcentral node[13705]:     at closeBothSides (/root/meshcentral/node_modules/meshcentral/meshrelay.js:346:149)
Apr 16 13:33:42 meshcentral node[13705]:     at WebSocket.<anonymous> (/root/meshcentral/node_modules/meshcentral/meshrelay.js:322:9)
Apr 16 13:33:42 meshcentral node[13705]:     at WebSocket.emit (events.js:194:15)
Apr 16 13:33:42 meshcentral node[13705]:     at WebSocket.emitClose (/root/meshcentral/node_modules/express-ws/node_modules/ws/lib/websocket.js:172:10)
Apr 16 13:33:42 meshcentral node[13705]:     at TLSSocket.socketOnClose (/root/meshcentral/node_modules/express-ws/node_modules/ws/lib/websocket.js:781:15)
Apr 16 13:33:42 meshcentral node[13705]:     at TLSSocket.emit (events.js:194:15)
Apr 16 13:33:42 meshcentral node[13705]:     at _handle.close (net.js:600:12)
Apr 16 13:33:42 meshcentral node[13705]:     at Socket.done (_tls_wrap.js:388:7)
Apr 16 13:33:42 meshcentral node[13705]:     at Object.onceWrapper (events.js:277:13)
Apr 16 13:33:42 meshcentral node[13705]:     at Socket.emit (events.js:189:13)
Apr 16 13:33:42 meshcentral node[13705]:     at TCP._handle.close (net.js:600:12)
Apr 16 13:33:42 meshcentral node[13705]:     at ChildProcess.exithandler (child_process.js:294:12)
Apr 16 13:33:42 meshcentral node[13705]:     at ChildProcess.emit (events.js:194:15)
Apr 16 13:33:42 meshcentral node[13705]:     at maybeClose (internal/child_process.js:970:16)
Apr 16 13:33:42 meshcentral node[13705]:     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
Apr 16 13:33:42 meshcentral node[13705]:   killed: false,
Apr 16 13:33:42 meshcentral node[13705]:   code: 1,
Apr 16 13:33:42 meshcentral node[13705]:   signal: null,
Apr 16 13:33:42 meshcentral node[13705]:   cmd:
Apr 16 13:33:42 meshcentral node[13705]:    '/usr/bin/node /root/meshcentral/node_modules/meshcentral --launch 13705' }
Apr 16 13:33:42 meshcentral node[13705]: ERROR: MeshCentral failed with critical error, check MeshErrors.txt. Restarting in 5 seconds...
```

**Comment by Ylianst** [comment]
Nice catch! Committed the fix for this, it will be in the next published version.

**Comment by Ylianst** [comment]
MeshCentral v0.5.1-x is out.
