### ISSUE TITLE
Active user deletion

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#1210]
Hey Ylianst, 

When i log in as an normal user and, i want to remove myself as that user, meshcentral crashes
The user is not deleted !

the serverlogs shows the following error:
-------- 2020-4-21 12:52:29 PM ---- 0.5.11 --------

/home/administrator/node_modules/meshcentral/webserver.js:1936
        var otpemail = (parent.mailserver != null) && (req.session.tokenemail);
                                                                   ^

TypeError: Cannot read property 'tokenemail' of null
    at handleRootRequestLogin (/home/administrator/node_modules/meshcentral/webserver.js:1936:68)
    at handleRootRequestEx (/home/administrator/node_modules/meshcentral/webserver.js:1904:13)
    at /home/administrator/node_modules/meshcentral/webserver.js:1552:40
    at /home/administrator/node_modules/meshcentral/webserver.js:485:36
    at AsyncWrap.<anonymous> (/home/administrator/node_modules/meshcentral/pass.js:31:88)
    at AsyncWrap.wrap.ondone (internal/crypto/pbkdf2.js:36:48)

os: Ubuntu 18.04.4-lts
nodejs 10.20.1
node 12.15.0

**Comment by Ylianst** [comment]
Thank you! Just checked in a fix for this, will be in v0.5.12 when it's next published.

**Comment by petervanv** [comment]
fixed, and thx for the quick soluition
