### ISSUE TITLE
MeshCentral fails to start with TLSOffload & agent configuration enabled

### ISSUE THREAD

**Issue by davscot** [Ylianst/MeshCentral#1395]
Hi Ylian,

I'm testing MeshCentral behind HAProxy and ran into trouble with TLSOffload enabled in MeshCentral.

When TLSOffload is enabled, along with AgentPort, MeshCentral fails to start with the following error displayed:

```
ERR: net.js:1366

    throw new ERR_SERVER_ALREADY_LISTEN();
    ^

Error [ERR_SERVER_ALREADY_LISTEN]: Listen method has been called more than once without closing.
    at Server.listen (net.js:1366:11)
    at Function.serverListen [as listen] (/opt/meshcentral/node_modules/express-ws/lib/index.js:42:40)
    at StartAltWebServer (/opt/meshcentral/node_modules/meshcentral/webserver.js:4749:40)
    at Server.<anonymous> (/opt/meshcentral/node_modules/meshcentral/webserver.js:4694:88)
    at Object.onceWrapper (events.js:286:20)
    at Server.emit (events.js:198:13)
    at emitCloseNT (net.js:1619:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
{ Error: Command failed: /usr/bin/node /opt/meshcentral/node_modules/meshcentral --launch 3449
net.js:1366
    throw new ERR_SERVER_ALREADY_LISTEN();
    ^

Error [ERR_SERVER_ALREADY_LISTEN]: Listen method has been called more than once without closing.
    at Server.listen (net.js:1366:11)
    at Function.serverListen [as listen] (/opt/meshcentral/node_modules/express-ws/lib/index.js:42:40)
    at StartAltWebServer (/opt/meshcentral/node_modules/meshcentral/webserver.js:4749:40)
    at Server.<anonymous> (/opt/meshcentral/node_modules/meshcentral/webserver.js:4694:88)
    at Object.onceWrapper (events.js:286:20)
    at Server.emit (events.js:198:13)
    at emitCloseNT (net.js:1619:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:203:15)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   '/usr/bin/node /opt/meshcentral/node_modules/meshcentral --launch 3449' }
```
Without this specific agent setting enabled TLSOffloading works fine and MeshCentral starts without any issues.

A few questions I have regarding TLSOffload for agents:

1. Is it possible to have TLSOffload settings specifically for agent as you do for Mps and MeshCentral itself?
2. I use a commercial wildcard cert for MeshCentral web interface and default self signed certs for agent and mps services. Is it possible to define a CertUrl setting for web interface and another specifically for agents? Or is the CertUrl setting already designed to be used for agents?

**Environment specs for troubleshooting error above:**
MeshCentral ver: 0.5.38
OS running MeshCentral: Ubuntu 20.04 LTS (64bit)
NodeJS ver: 10.19.0
NPM ver: 6.14.5
MeshCentral running on built in DB.

Please let me know if you require any further details to assist with troubleshooting.

Thanks,

David.

**Comment by Ylianst** [comment]
Looking into this now!

**Comment by Ylianst** [comment]
Could you send over your config.json with "xxxxx" for any private portions? I can't replicate this problem.

I will also work on adding more options for the agentport.

**Comment by davscot** [comment]
Hi Ylian,

Thanks for your quick response.

MeshCentral service now starts although the agents port is not reachable via HAProxy with TLSOffloading configured.

I can get both MeshCentral web interface and agent port working through HAProxy without TLSOffloading using TCP layer 4, however agents connected to MeshCentral show their public IP as the internal reverse proxy address.

TCP layer 4 protocol unfortunately doesn't support  X-Forwarded-For header therefore I must use HTTP layer 7 protocol and can only use this with TLSOffloading enabled in HAProxy.

(Not sure if this is common for HAProxy requiring TLSOffloading with HTTP layer 7 protocol set, I may just be limited with features in the OPNSense plugin version as I have spent hours trying to configure this with no joy).

**Please see below my findings since your latest update to v0.5.39.**

**AgentPortTls option not enabled**
- MeshCentral webui works as expected.
- Navigating to agent hostname eg, agent-meshcentral.mydomain.com displays the following error in web browser:
```
TypeError: Cannot read property 'x-forwarded-for' of undefined
    at /opt/meshcentral/node_modules/meshcentral/webserver.js:4096:43
    at Layer.handle [as handle_request] (/opt/meshcentral/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/meshcentral/node_modules/express/lib/router/index.js:317:13)
    at /opt/meshcentral/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/opt/meshcentral/node_modules/express/lib/router/index.js:335:12)
    at next (/opt/meshcentral/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/opt/meshcentral/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/opt/meshcentral/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/meshcentral/node_modules/express/lib/router/index.js:317:13)
    at /opt/meshcentral/node_modules/express/lib/router/index.js:284:7

```
Usually when navigating to the agent hostname I get a blank page with "/" which is how I know it is working.

**AgentPortTls option enabled**
- MeshCentral webui works as expected.
- Navigating to agent hostname eg, agent-meshcentral.mydomain.com displays the following error in web browser:

`502 Bad Gateway
The server returned an invalid or incomplete response.`

Is it possible to TLSoffload agent conenction eg. "_AgentTlsOffload": true,? I'm hoping by doing this will resolve the issue I am experiencing.

I welcome any suggestions / feedback from your self and the community.

David.

**Comment by Ylianst** [comment]
Thanks for the report back. I just submitted a fix for the `'x-forwarded-for' of undefined` problem. My fault, easy fix. It will be in v0.5.41 when I next release it.

When setting AgentPortTLs to true, I am going to guess you are getting the expected response. HAproxy is making an HTTP request without TLS and MeshCentral is responding with TLS, so the received response is not right.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.5.41. That should fix it.

**Comment by davscot** [comment]
Ylian,

Fantastic work, problem solved! Both webui and agent works via TLSOffloading through OPNsense HAproxy plugin!

"AgentPortTls": true, is also handy for those whom want to port forward directly keeping SSL and reverse proxy / TLSoffload the webui.

Thanks for your efforts!

David.

**Comment by Scaff31** [comment]
Hello @davscot,

Could you help me to configure meshcentral behind the OPNsense HAproxy plugin?
With a tutorial or a procedure

Thank

**Comment by davscot** [comment]
Hi @Scaff31,

Sure I can provide a few screenshots of what is needed. So that we don't take over this post please send me an email public-17b2f@wisscot.com and I'll reply with some steps.

How urgent is this?

David.
