### ISSUE TITLE
TypeError: Cannot read property 'CertificateTableAddress' of undefined

### ISSUE THREAD

**Issue by SohnyBohny** [Ylianst/MeshCentral#14]
Installed via npm on Ubuntu Server 16.04 I get following error:

```
MeshCentral HTTP redirection web server running on port 81.
{ [Error: Command failed: /bin/sh -c /usr/bin/nodejs ..../meshcentral/node_modules/meshcentral/meshcentral --launch
..../meshcentral/node_modules/meshcentral/exeHandler.js:257
        if (options.peinfo.CertificateTableAddress != 0) { options.state.endIndex = options.peinfo.CertificateTableAddress; }
                          ^

TypeError: Cannot read property 'CertificateTableAddress' of undefined
    at Object.module.exports.hashExecutableFile (..../meshcentral/node_modules/meshcentral/exeHandler.js:257:27)
    at Object.CreateMeshCentralServer.obj.updateMeshAgentsTable (..../meshcentral/node_modules/meshcentral/meshcentral.js:988:32)
    at Object.CreateMeshCentralServer.obj.StartEx3 (..../meshcentral/node_modules/meshcentral/meshcentral.js:407:13)
    at ..../meshcentral/node_modules/meshcentral/meshcentral.js:376:21
    at Object.obj.GetMeshServerCertificate (..../meshcentral/node_modules/meshcentral/certoperations.js:292:89)
    at CreateMeshCentralServer.obj.StartEx2 (..../meshcentral/node_modules/meshcentral/meshcentral.js:374:35)
    at Server.<anonymous> (..../meshcentral/node_modules/meshcentral/redirserver.js:99:13)
    at Server.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Server.emit (events.js:166:7)
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c /usr/bin/nodejs ..../node_modules/meshcentral/meshcentral --launch' }
ERROR: MeshCentral failed with critical error, check MeshErrors.txt. Restarting in 5 seconds...

```

**Comment by Ylianst** [comment]
Thanks for the report. I will try to fix as soon as possible. Hopefully in the next few days as most. This is not good! You can try to NPM install an older version of MeshCentral for now until I fix this.

Ylian
________________________________

**Comment by SohnyBohny** [comment]
I had installed nodejs version v4.2.6 (latest in official ubuntu repository).

After upgrading to nodejs v8.11.3 it does work now.

Sorry for the confusion
