### ISSUE TITLE
Parsing Error After 0.3.1-d Update

### ISSUE THREAD

**Issue by scottalanmiller** [Ylianst/MeshCentral#150]
Error: Parse error on line 171:
...s
 * @typedef {{
 *   type: u2f.Messag
---------------------^
Expecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'INVALID'
    at Parser.parseError (/opt/meshcentral/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:268:19)
    at Parser.parse (/opt/meshcentral/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:337:30)
    at HandlebarsEnvironment.parse (/opt/meshcentral/node_modules/handlebars/dist/cjs/handlebars/compiler/base.js:46:43)
    at compileInput (/opt/meshcentral/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:515:19)
    at ret (/opt/meshcentral/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:524:18)
    at ExpressHandlebars._renderTemplate (/opt/meshcentral/node_modules/express-handlebars/lib/express-handlebars.js:247:12)
    at ExpressHandlebars.<anonymous> (/opt/meshcentral/node_modules/express-handlebars/lib/express-handlebars.js:173:21)

**Comment by scottalanmiller** [comment]
Did a fresh install, copied over the config file, and the parsing error remains.

**Comment by scottalanmiller** [comment]
This error eventually comes up on the console...

{ Error: Command failed: /root/.nvm/versions/node/v11.4.0/bin/node /opt/meshcentral2/node_modules/meshcentral --launch
/opt/meshcentral2/node_modules/meshcentral/db.js:413
                            func({ nodes: nodeCount, meshes: meshCount, powerEvents: powerCount, users: userCount, nodeInterfaces: nodeInterfaceCount, notes: noteCount, connectEvent: nodeLastConnectCount, smbios: nodeSmbiosCount, total: totalCount });
                                                                                     ^

ReferenceError: powerCount is not defined
    at /opt/meshcentral2/node_modules/meshcentral/db.js:413:86
    at newArguments.(anonymous function) (/opt/meshcentral2/node_modules/nedb/lib/executor.js:29:17)
    at Cursor.execFn (/opt/meshcentral2/node_modules/nedb/lib/datastore.js:445:12)
    at callback (/opt/meshcentral2/node_modules/nedb/lib/cursor.js:126:19)
    at /opt/meshcentral2/node_modules/nedb/lib/cursor.js:193:12
    at /opt/meshcentral2/node_modules/nedb/lib/datastore.js:329:14
    at Object.async.eachSeries (/opt/meshcentral2/node_modules/nedb/node_modules/async/lib/async.js:130:20)
    at /opt/meshcentral2/node_modules/nedb/lib/datastore.js:323:11
    at fn (/opt/meshcentral2/node_modules/nedb/node_modules/async/lib/async.js:582:34)
    at Immediate.<anonymous> (/opt/meshcentral2/node_modules/nedb/node_modules/async/lib/async.js:498:34)
    at processImmediate (timers.js:632:19)

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:194:15)
    at maybeClose (internal/child_process.js:978:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   '/root/.nvm/versions/node/v11.4.0/bin/node /opt/meshcentral2/node_modules/meshcentral --launch' }
ERROR: MeshCentral failed with critical error, check MeshErrors.txt. Restarting in 5 seconds...

**Comment by Ylianst** [comment]
Thanks for the detailed report. I saw this and rushed back into the office to fix it. Working on it now.

**Comment by Ylianst** [comment]
Published MeshCentral v0.3.1-e with a fix.

**Comment by scottalanmiller** [comment]
Using NeDB right now.  After a fresh install of "e", seeing the same issue.

**Comment by Ylianst** [comment]
Oh sorry. I fixed the "ReferenceError: powerCount is not defined" only. Working on the first issue now.

**Comment by Ylianst** [comment]
Do you have "Minify": true in your config.json by any chance?

**Comment by Ylianst** [comment]
I guessed right! I get the same problem with minify set to true... working on it.

**Comment by scottalanmiller** [comment]
I am indeed using minify :)

**Comment by Ylianst** [comment]
Published v0.3.1-f with many minification fixes. Should work now.

**Comment by scottalanmiller** [comment]
It worked!  Thanks so much.

**Comment by Ylianst** [comment]
Perfect. Thanks for reporting.
