### ISSUE TITLE
Adding Device Groups from Python app

### ISSUE THREAD

**Issue by sadnub** [Ylianst/MeshCentral#1551]
Hello,

I am having issues calling the wss:// url from a python app. Here is what I have so far:

```
    import asyncio
    import ssl
    import websockets
    import time
    from base64 import b64encode
    from Cryptodome.Cipher import AES
    import secrets

    def get_auth_token(self, key):
        key = bytes.fromhex(key)
        key1 = key[0:32]
        msg = '{{"userid":"{}", "domainid":"{}", "time":{}}}'.format(f"user//{settings.MESH_USERNAME}", "", int(time.time()))
        iv = secrets.token_bytes(12)

        a = AES.new(key1, AES.MODE_GCM, iv)
        msg, tag = a.encrypt_and_digest(bytes(msg, 'utf-8'))

        return b64encode(iv + tag + msg, altchars=b"@$").decode("utf-8")

    async def wssCall(self):

        #ssl_context = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
        #ssl_context.check_hostname = False
        #ssl_context.verify_mode = ssl.CERT_NONE
        
        token = self.get_auth_token(settings.MESH_TOKEN_KEY)
        uri = f"wss://meshcentral/control.ashx?auth={token}"

        async with websockets.connect(
            uri, ssl_context
        ) as websocket:

            await websocket.send({ "action": "createmesh", "meshname": "NewDeviceGroup", "meshtype": 2, "responseid": "meshctrl" })
            output = await websocket.recv()
            print(f"< {output}")

            await websocket.send({ "action": "createInviteLink", "expire": 8, "flags": 0, "meshname": "NewDeviceGroup", "responseid": 'meshctrl' })
            output = await websocket.recv()
            print(f"< {output}")

    def handle(self, *args, **kwargs):
        asyncio.get_event_loop().run_until_complete(self.wssCall())
```

During the handshake, I am getting this:

```
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/app/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/app/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/env/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/env/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/app/agents/management/commands/initial_mesh_setup.py", line 52, in handle
    asyncio.get_event_loop().run_until_complete(self.wssCall())
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/app/agents/management/commands/initial_mesh_setup.py", line 39, in wssCall
    async with websockets.connect(
  File "/app/env/lib/python3.8/site-packages/websockets/client.py", line 517, in __aenter__
    return await self
  File "/app/env/lib/python3.8/site-packages/websockets/client.py", line 535, in __await_impl__
    transport, protocol = await self._create_connection()
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1050, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1080, in _create_connection_transport
    await waiter
  File "/usr/local/lib/python3.8/asyncio/sslproto.py", line 529, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/local/lib/python3.8/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.8/ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108)
```

I wasn't sure if there was a specific SSL or TLS version I need to use. I was messing with the SSL setting with no luck. Also I followed the implementation of the meshctrl.js file. to get the above so I may have just did something wrong.

Thanks!

**Comment by Ylianst** [comment]
I don't know Python, but it does look like a TLS connection issue. If someone known Python, would love to get an answer on this. It would be nice to have sample Python code that connects to MeshCentral exactly this this.

**Comment by krayon007** [comment]
A guick google suggests this error is returned if you try to establish a TLS connection but accidentally connect to a non TLS port. Are you sure you are connecting to the correct port number?

**Comment by sadnub** [comment]
Wow I can't believe I missed that! I forgot I am TLS offloading to a reverse proxy and I changed the url to this.

uri = f"ws://meshcentral:443/control.ashx?auth={token}"

Note the ws:// and specifying port 443.. 

Thanks!

**Comment by Ylianst** [comment]
Nice!

**Comment by sadnub** [comment]
Creating the device group seems to work, the return data seems strange. 

```
from django.core.management.base import BaseCommand
from django.conf import settings
import asyncio
import ssl
import websockets
import time
from base64 import b64encode
from Cryptodome.Cipher import AES
import secrets
import json


class Command(BaseCommand):
    help = "Sets up initial mesh central configuration"

    def get_auth_token(self, key):
        key = bytes.fromhex(key)
        key1 = key[0:32]
        msg = '{{"userid":"{}", "domainid":"{}", "time":{}}}'.format(f"user//{settings.MESH_USERNAME}", "", int(time.time()))
        iv = secrets.token_bytes(12)

        a = AES.new(key1, AES.MODE_GCM, iv)
        msg, tag = a.encrypt_and_digest(bytes(msg, 'utf-8'))

        return b64encode(iv + tag + msg, altchars=b"@$").decode("utf-8")

    async def websocket_call(self):

        token = self.get_auth_token(settings.MESH_TOKEN_KEY)
        uri = f"ws://meshcentral:443/control.ashx?auth={token}"

        async with websockets.connect(
            uri
        ) as websocket:

            # Create Device Group
            await websocket.send(json.dumps({"action":"createmesh","meshname":"MeshGroup","meshtype":2,"responseid":"python"}))
            output = await websocket.recv()
            print(f"{output}")

            # Get Mesh download exe link
            await websocket.send(json.dumps({"action":"createInviteLink","expire":8,"flags":0,"meshname":"Mesh Group","responseid":"python"}))
            output = await websocket.recv()
            print(f"{output}")

    def handle(self, *args, **kwargs):
        asyncio.get_event_loop().run_until_complete(self.websocket_call())
```

I'm trying to run this within a django command btw. What is strange is the Device Group is created in mesh central, but it returns this:

```
{"action":"serverinfo","serverinfo":{"name":"mesh.example.com","mpsname":"mesh.example","mpsport":4433,"port":443,"emailcheck":false,"domainauth":false,"serverTime":1593226746981,"languages":["en","cs","de","es","fr","hi","ja","ko","nl","pt","ru","zh-chs"],"tlshash":"9548635E86B155ED068D30B25B4A25E2B4FFC7443ABC76BA82FADD1A791B2BD952CBF05B4A51CEC51BCC447EF5707058","https":true,"redirport":80}}
```
Then the createInviteLink action returns this:

```
{"action":"userinfo","userinfo":{"_id":"user//mesh","name":"mesh","creation":1593129246,"links":{"mesh//yb1795NAUB$8M8PlIE6VtZs7DRVzV3yu5FZDWM9wEfj9DtWg3zXfEBoqlsQUCrlh":{"rights":4294967295}},"email":"example@example.com","emailVerified":true,"siteadmin":4294967295,"pastlogin":1593222628,"login":1593222628}}
```

I was looking in the meshuser.js (I think that is where the server code is), and didn't see a default action that would return this output.

Any ideas?

**Comment by jsastriawan** [comment]
This normal. This is typical information sent by server to give UI some information. You can safely ignore those and only parse certain messages you need. Additionally this websocket will also send node events too.
