### ISSUE TITLE
Error mongo (node:18011)

### ISSUE THREAD

**Issue by desarrollocdb** [Ylianst/MeshCentral#1589]
Hello, I update these errors very frequently. Any solution option? The system works but after a while I have had to restart the server to detect new computers.

```
-------- 2020-7-7 6:43:06 PM ---- 0.5.77 --------

(node:18011) UnhandledPromiseRejectionWarning: MongoError: The dotted field 'isatap.{5831EEDC-A9C0-4F61-A2EE-DC6362D4E9E8}' in 'netif2.isatap.{5831EEDC-A9C0-4F61-A2EE-DC6362D4E9E8}' is not valid for storage.
    at Function.create (/opt/meshcentral/node_modules/mongodb/lib/core/error.js:51:12)
    at toError (/opt/meshcentral/node_modules/mongodb/lib/utils.js:149:22)
    at coll.s.topology.update (/opt/meshcentral/node_modules/mongodb/lib/operations/common_functions.js:376:39)
    at handler (/opt/meshcentral/node_modules/mongodb/lib/core/sdam/topology.js:913:24)
    at fn (/opt/meshcentral/node_modules/mongodb/lib/cmap/connection_pool.js:356:13)
    at handleOperationResult (/opt/meshcentral/node_modules/mongodb/lib/core/sdam/server.js:493:5)
    at MessageStream.messageHandler (/opt/meshcentral/node_modules/mongodb/lib/cmap/connection.js:272:5)
    at MessageStream.emit (events.js:198:13)
    at processIncomingData (/opt/meshcentral/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/opt/meshcentral/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
(node:18011) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)


-------- 2020-7-7 6:43:06 PM ---- 0.5.77 --------

(node:18011) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by Ylianst** [comment]
Interesting. I will look into this.

**Comment by Ylianst** [comment]
Looking at the [MongoDB documentation](https://docs.mongodb.com/manual/reference/limits/#Restrictions-on-Field-Names), you could not have a dot (.) in a field name before MongoDB 3.6. Are you using a version of MongoDB before 3.6?

I am going to add a warning for older MongoDB databases, but let me know what version you are running. Thanks.

**Comment by Ylianst** [comment]
Ok, Added server warning message for MongoDB older than 3.6:

![image](https://user-images.githubusercontent.com/1319013/86976523-7c39ae00-c12f-11ea-9fd2-faed71a53739.png)

![image](https://user-images.githubusercontent.com/1319013/86976552-907dab00-c12f-11ea-92a7-a72f3c9f889c.png)

This warning will be in MeshCentral v0.5.81.

**Comment by desarrollocdb** [comment]
this is the version

![image](https://user-images.githubusercontent.com/26174637/86981720-05aba900-c14d-11ea-957a-d7ee94f11b83.png)

**Comment by desarrollocdb** [comment]
![image](https://user-images.githubusercontent.com/26174637/86982230-62f42a00-c14e-11ea-99a3-469e320b0f0b.png)


I have updated the server and application. I will wait a few days to see if the alerts come back

**Comment by Ylianst** [comment]
Perfect, that should solve it.

**Comment by Ylianst** [comment]
I will close, please re-open if needed.
