### ISSUE TITLE
Can an MC2 server bound to AD be configured to prompt for username and password

### ISSUE THREAD

**Issue by tlcarpenter** [Ylianst/MeshCentral#1627]
I installed MC2 on an AD-bound Windows 10 system, configured MC2 to use "auth": "sspi", and was then able to access the MC2 console while logged in to Windows (on the system running MC2) with an AD account and without MC2 prompting for additional authentication (as expected). I tried accessing the MC2 console from another system (Xubuntu workstation) using Firefox, but I was unsuccessful; I tried adding the MC2's URL to various Firefox 'about:config' preferences but that didn't work. My question is can MC2 be configured to bind to an Active Directory domain and prompt users for their AD credentials whether they are accessing the MC2 console from another AD-bound system or not?

Not to sandwich two issues into one help request, but I tried editing "config.js" on the MC2 server to instead use "auth": "ldap" and related options ("url", "bindDN", "bindCredentials", "searchBase", and "searchFilter") to force the use of usernames and passwords. If I log on to the system running MC2 using an AD account and then try to access the MC2 console with the same AD account (using MS Edge as the browser), it appears the MC2 console tries to process the login, but times out and the error "Can't connect securely to this page" is displayed. 'mesherrors' indicates there's an issue with TLS,

-------- 7/20/2020, 12:04:02 PM ---- 0.5.89 --------

events.js:287
      throw er; // Unhandled 'error' event
      ^

Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1474:34)
    at TLSSocket.emit (events.js:310:20)
    at TLSSocket._finishInit (_tls_wrap.js:917:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:687:12)
Emitted 'error' event on LdapAuth instance at:
    at LdapAuth._handleError (C:\Program Files\Open Source\MeshCentral\node_modules\ldapauth-fork\lib\ldapauth.js:185:8)
    at Client.emit (events.js:310:20)
    at Backoff.<anonymous> (C:\Program Files\Open Source\MeshCentral\node_modules\ldapjs\lib\client\client.js:1228:12)
    at Backoff.emit (events.js:310:20)
    at Backoff.backoff (C:\Program Files\Open Source\MeshCentral\node_modules\backoff\lib\backoff.js:41:14)
    at C:\Program Files\Open Source\MeshCentral\node_modules\ldapjs\lib\client\client.js:1214:15
    at f (C:\Program Files\Open Source\MeshCentral\node_modules\once\once.js:25:25)
    at TLSSocket.onResult (C:\Program Files\Open Source\MeshCentral\node_modules\ldapjs\lib\client\client.js:1016:7)
    at Object.onceWrapper (events.js:417:26)
    at TLSSocket.emit (events.js:310:20) {
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
}

p.s. After entering the information above I spoke with our AD admins and learned that our DC's FQDN is actually an alias used for round-robin DNS for three DCs and I suspect is the cause of the TLS issue I ran into.

**Comment by tlcarpenter** [comment]
WRT to issues I ran into using "auth": "sspi" - this actually does work, all the problems were due to firewall settings, i.e. added an allow rule on the hardware firewall in front of the system running MC2 and temporarily disabled the Windows Defender Firewall on the Windows 10 system running MC2. After that could connect to the MC2 console from other systems and also didn't have to do anything special to Firefox's config to connect or to be prompted for username/password.

As for binding MC2 to AD using "auth": "ldap" - still need to figure this out but I'll submit this as a new issue if need be.
