### ISSUE TITLE
MC won't start after update to 0.5.91

### ISSUE THREAD

**Issue by uldiseihenbergs** [Ylianst/MeshCentral#1638]
Here info from log:
Installing archiver...
MeshCentral HTTP redirection server running on port 80.
MeshCentral v0.5.91, WAN mode.
Loaded web certificate from "https://192.168.50.248:443/", host: "reducted.com"
SHA384 cert hash: 45317be4c3952a492000ed2841b9f4c0291f846dfc3b7700d86c1060ec129a413376e1eb0784084dda0e6c17e7e20212
SHA384 key hash: 878ba8dc32d56204171d5dad433fc48027f6f97a218681a3fb40026dd2bf0aff85b8cbc97e2e1fb4cce5fd81d4f3fe01
ERR: /home/node/meshcentral/node_modules/readdir-glob/index.js:62
async function* exploreWalkAsync(dir, path, followSyslinks, useStat, strict) {
^

SyntaxError: Unexpected token *
at createScript (vm.js:80:10)
at Object.runInThisContext (vm.js:139:10)
at Module._compile (module.js:616:28)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/home/node/meshcentral/node_modules/archiver/lib/core.js:9:12)
{ Error: Command failed: /usr/local/bin/node /home/node/meshcentral/node_modules/meshcentral/meshcentral.js --launch 8
/home/node/meshcentral/node_modules/readdir-glob/index.js:62
async function* exploreWalkAsync(dir, path, followSyslinks, useStat, strict) {
^

SyntaxError: Unexpected token *
at createScript (vm.js:80:10)
at Object.runInThisContext (vm.js:139:10)
at Module._compile (module.js:616:28)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/home/node/meshcentral/node_modules/archiver/lib/core.js:9:12)

at ChildProcess.exithandler (child_process.js:275:12)
at emitTwo (events.js:131:20)
at ChildProcess.emit (events.js:214:7)
at maybeClose (internal/child_process.js:925:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
killed: false,
code: 1,
signal: null,
cmd: '/usr/local/bin/node /home/node/meshcentral/node_modules/meshcentral/meshcentral.js --launch 8' }
ERROR: MeshCentral failed with critical error, check MeshErrors.txt. Restarting in 5 seconds...

**Comment by Ylianst** [comment]
Oh hear, this looks like a problem with one of the dependencies. Looking into it now.

**Comment by Ylianst** [comment]
What NodeJS version are you using? Type `node -v` to get the version. Thanks.

**Comment by Ylianst** [comment]
Ok, Archiver 5.0.0 module was just released 5 hours ago and broke things. Working on it now.

**Comment by uldiseihenbergs** [comment]
i'm on docker, and still running it on version:
`$ node -v
v8.10.0`

**Comment by Ylianst** [comment]
Just published MeshCentral v0.5.92 with a fix for this. It will now install `archiver@4.0.2` which will work.

You can `npm install meshcentral` again, or you can probably delete `node_modules/archiver` and do `npm install archiver@4.0.2` to get back online.

Let me know if it fixes it. Thanks for the report.

**Comment by uldiseihenbergs** [comment]
OK, new docker image built, now it starts just fine! as always, thanks for a quick fix.
