### ISSUE TITLE
Trying to change a password seems to cause MeshCentral to Crash

### ISSUE THREAD

**Issue by cjmny** [Ylianst/MeshCentral#1734]
On 0.6.16.  If you try to change a user password, MeshCentral will crash.  When you are able to log back in, the password has not been changed.

**Comment by Ylianst** [comment]
Can you specify how you change the password? What screen is used? (screenshot appreciated).

Also, go in the "My Server" tab, click "Show server error log" and cut & paste any errors here? Thanks.

**Comment by cjmny** [comment]
I'm sorry for that dreadful bug report. I'll get a screenshot when I'm back on a desktop. The password was changed through the "My Account" tab. 

Here Is a quick snippet of the error log:

home/meshcentral/node_modules/meshcentral/webserver.js:1876
        if ((typeof domain.passwordrequirements.oldpasswordban == 'number') && (domain.passwordrequirements.oldpasswordban > 0)) {
                                                ^

TypeError: Cannot read property 'oldpasswordban' of undefined
    at Object.obj.checkOldUserPasswords (/home/meshcentral/node_modules/meshcentral/webserver.js:1876:49)
    at /home/meshcentral/node_modules/meshcentral/meshuser.js:2377:36
    at /home/meshcentral/node_modules/meshcentral/webserver.js:1865:28
    at PBKDF2.ondone (/home/meshcentral/node_modules/meshcentral/pass.js:31:88)

**Comment by Ylianst** [comment]
Got it, working on a fix now!

**Comment by Ylianst** [comment]
Published MeshCentral v0.6.17 with a fix for this. Let me know and close this issue if it works.
