### ISSUE TITLE
Error when adding Google Backup Client ID & Secret

### ISSUE THREAD

**Issue by drnikcuk** [Ylianst/MeshCentral#1753]
Running on latest version - 0.6.20

When enabling google drive via the Gui i was seeing the following error:
```
ERR: module.js:549
    throw err;
    ^

Error: Cannot find module 'googleapis'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at WebSocket.processWebSocketData (/home/nik/meshcentral/node_modules/meshcentral/meshuser.js:4679:42)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at Receiver.receiverOnMessage (/home/nik/meshcentral/node_modules/express-ws/node_modules/ws/lib/websocket.js:720:20)
    at emitOne (events.js:116:13)
    at Receiver.emit (events.js:211:7)
    at Receiver.dataMessage (/home/nik/meshcentral/node_modules/express-ws/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/home/nik/meshcentral/node_modules/express-ws/node_modules/ws/lib/receiver.js:346:17)
    at Receiver.startLoop (/home/nik/meshcentral/node_modules/express-ws/node_modules/ws/lib/receiver.js:133:22)
    at Receiver._write (/home/nik/meshcentral/node_modules/express-ws/node_modules/ws/lib/receiver.js:69:10)
    at doWrite (_stream_writable.js:397:12)
    at writeOrBuffer (_stream_writable.js:383:5)
```

The fix was to run, 
npm i -S googleapis@30.0.0

I'm not sure if this is a dependency that should be covered by install ?

Thanks

**Comment by Ylianst** [comment]
Did you install MeshCentral on Windows using the MeshCentral Windows installer?

**Comment by Ylianst** [comment]
Just updated MeshCentral Installer to v2.8, added "googleapis". If that was not the problem, please re-open and add details.

**Comment by drnikcuk** [comment]
> Did you install MeshCentral on Windows using the MeshCentral Windows installer?

Soryr should have said, running on Ubuntu 18.04.5 LTS
