### ISSUE TITLE
RDP from CHROME

### ISSUE THREAD

**Issue by alesribic73** [Ylianst/MeshCentral#1833]
We use chrome in our company.  When i click RDP application it download. When i run it, it throws error: Application can not be started. Installation is on Windows server.

Details:

PLATFORM VERSION INFO
	Windows 			: 10.0.19041.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.8.4240.0 built by: NET48REL1LAST_B
	clr.dll 			: 4.8.4220.0 built by: NET48REL1LAST_C
	dfdll.dll 			: 4.8.4240.0 built by: NET48REL1LAST_B
	dfshim.dll 			: 10.0.19041.1 (WinBuild.160101.0800)

SOURCES
	Deployment url			: file:///C:/Users/xxxxx/Downloads/MeshMiniRouter%20(1).application

IDENTITIES
	Deployment Identity		: MeshMiniRouter.application, Version=2.0.0.29, Culture=neutral, PublicKeyToken=2e8c763d6917d840, processorArchitecture=msil

APPLICATION SUMMARY
	* Online only application.
	* Trust url parameter is set.
ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\xxxxx\Downloads\MeshMiniRouter (1).application resulted in exception. Following failure messages were detected:
		+ Deployment and application do not have matching security zones.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [18. 09. 2020 13:46:28] : Activation of C:\Users\xxxxx\Downloads\MeshMiniRouter (1).application has started.
	* [18. 09. 2020 13:46:28] : Processing of deployment manifest has successfully completed.
	* [18. 09. 2020 13:46:28] : Installation of the application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [18. 09. 2020 13:46:28] System.Deployment.Application.InvalidDeploymentException (Zone)
		- Deployment and application do not have matching security zones.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.DownloadManager.DownloadApplicationManifest(AssemblyManifest deploymentManifest, String targetDir, Uri deploymentUri, IDownloadNotification notification, DownloadOptions options, Uri& appSourceUri, String& appManifestPath)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

**Comment by yomono** [comment]
According to the official guide [HERE](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2UserGuide.pdf):

ClickOnceSet: to “true” or “false” to allow or disallow browser ClickOncefeatures. When enabled, browsers running on Windows will be shown extra options to allow RDP and other sessions thru the MeshCentral server. This requires ClickOnce browser support that is built-in to IE and available as add-in to Chrome and Firefox. Default is true.

so.. do you have the required extension installed?

**Comment by alesribic73** [comment]
Hi

Thanks for this. I have googled this and i got only authentication problem results....

Regards
