### ISSUE TITLE
Strange Error in Logs 0.6.48

### ISSUE THREAD

**Issue by asasin114** [Ylianst/MeshCentral#1852]
Thought I should bring this up. I have not seen this issue since upgrading to 0.6.49 a couple hours ago so I believe it is resolved in my case but I had these strange errors popping up every couple minutes:

**Error 1**
TypeError: Cannot read property 'getFileMapsForNode' of null
    at Object.obj.handleAdminReq (C:\Program Files\Open Source\MeshCentral\meshcentral-data\plugins\filedist\filedist.js:147:20)
    at Object.obj.handleAdminReq (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\pluginHandler.js:523:40)
    at obj.handlePluginAdminReq (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\webserver.js:4576:34)
    at Layer.handle [as handle_request] (C:\Program Files\Open Source\MeshCentral\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Program Files\Open Source\MeshCentral\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Program Files\Open Source\MeshCentral\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Program Files\Open Source\MeshCentral\node_modules\express\lib\router\layer.js:95:5)
    at C:\Program Files\Open Source\MeshCentral\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Program Files\Open Source\MeshCentral\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Program Files\Open Source\MeshCentral\node_modules\express\lib\router\index.js:275:10)
    at C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\webserver.js:4730:24
    at Layer.handle [as handle_request] (C:\Program Files\Open Source\MeshCentral\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Program Files\Open Source\MeshCentral\node_modules\express\lib\router\index.js:317:13)
    at C:\Program Files\Open Source\MeshCentral\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Program Files\Open Source\MeshCentral\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Program Files\Open Source\MeshCentral\node_modules\express\lib\router\index.js:275:10)

**Error 2**
TypeError: Cannot read property 'getScriptTree' of null
    at Object.obj.handleAdminReq (C:\Program Files\Open Source\MeshCentral\meshcentral-data\plugins\scripttask\scripttask.js:224:20)
    at Object.obj.handleAdminReq (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\pluginHandler.js:523:40)
    at obj.handlePluginAdminReq (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\webserver.js:4576:34)
    at Layer.handle [as handle_request] (C:\Program Files\Open Source\MeshCentral\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Program Files\Open Source\MeshCentral\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Program Files\Open Source\MeshCentral\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Program Files\Open Source\MeshCentral\node_modules\express\lib\router\layer.js:95:5)
    at C:\Program Files\Open Source\MeshCentral\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Program Files\Open Source\MeshCentral\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Program Files\Open Source\MeshCentral\node_modules\express\lib\router\index.js:275:10)
    at C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\webserver.js:4730:24
    at Layer.handle [as handle_request] (C:\Program Files\Open Source\MeshCentral\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Program Files\Open Source\MeshCentral\node_modules\express\lib\router\index.js:317:13)
    at C:\Program Files\Open Source\MeshCentral\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Program Files\Open Source\MeshCentral\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Program Files\Open Source\MeshCentral\node_modules\express\lib\router\index.js:275:10)

**Comment by Ylianst** [comment]
What plugins do you have installed?

**Comment by asasin114** [comment]
Event Log, File Distribution, Route Plus, Script Task, and Work From Home. I could probably get rid of everything but Work From Home and File Distribution at this point. I will need Script Task at some point but not right at the moment.

**Comment by ryanblenis** [comment]
I can't seem to repeat it, but it sounds like the plugins failed to load. What was the version you were on when getting the errors?

**Comment by asasin114** [comment]
@ryanblenis, when I was receiving the errors I was running 0.6.48. I have since upgraded to 0.6.49 and do not appear to have the errors anymore.

**Comment by asasin114** [comment]
The errors have started popping up again on 0.6.49

**Comment by asasin114** [comment]
The errors seem to have resolved themselves within the next update. Going to close at this point.
