### ISSUE TITLE
MeshMiniRouter.application cannot be started

### ISSUE THREAD

**Issue by PathfinderNetworks** [Ylianst/MeshCentral#1868]
I was playing around tonight with the new 0.6.55 version of MeshCentral and was trying out some things I haven't looked at in quite some time. 
One of them is the RDP link in the General tab for each device.  I'm using Microsoft Edge.  When I click the link it downloads the MeshMiniRouter.application file. When I try to run the file it begins the installation process but then fails with an error stating the application cannot be started.  The details of the error are below. 
I don't know that this is an issue that started with 0.6.55.  I hadn't actually tried to use that RDP option until now. 

ERROR DETAILS
	Following errors were detected during this operation.
	* [10/1/2020 10:59:38 PM] System.Deployment.Application.InvalidDeploymentException (Zone)
		- Deployment and application do not have matching security zones.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.DownloadManager.DownloadApplicationManifest(AssemblyManifest deploymentManifest, String targetDir, Uri deploymentUri, IDownloadNotification notification, DownloadOptions options, Uri& appSourceUri, String& appManifestPath)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

**Comment by Ylianst** [comment]
I am sort of looking at getting rid of ClickOnce support and the MiniMeshRouter. Instead, you can download the MeshCentral Router and if you associate "mcrouter://" to the executable, you can accomplish the same result on all browsers. Another problem I have with ClickOnce is that if your using a self-signed TLS cert on your server, it often can't work. You click ignore cert warning on IE, but ClickOnce will still fail. When launching MeshCentral Router, I can pass in the TLS cert hash in the URL and perform security validation that always works correctly.

So, my plan is to replace the RDP link from ClickOnce to mcrouter://

**Comment by si458** [comment]
no reference to clickonce anymore in the source code apart from examples, so closing issue as complete
