### ISSUE TITLE
0.6.60 crash

### ISSUE THREAD

**Issue by Extcee** [Ylianst/MeshCentral#1889]
Hello

Over the last couple of days I seem to be having some issues on 0.6.60.

I would log into Mesh and then it would immediately kick me out, show server disconnected - post the following in logs, and then start back up do the same thing in an endless cycle.

`-------- 10/12/2020, 5:28:19 PM ---- 0.6.59 --------

/home/meshcentral/node_modules/meshcentral/meshagent.js:1478
        if (obj.agentInfo.capabilities & 0x40) return;
                          ^

TypeError: Cannot read property 'capabilities' of undefined
    at ChangeAgentCoreInfo (/home/meshcentral/node_modules/meshcentral/meshagent.js:1478:27)
    at Timeout._onTimeout (/home/meshcentral/node_modules/meshcentral/meshagent.js:1482:69)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)

-------- 10/12/2020, 5:28:34 PM ---- 0.6.59 --------

/home/meshcentral/node_modules/meshcentral/meshagent.js:1478
        if (obj.agentInfo.capabilities & 0x40) return;
                          ^

TypeError: Cannot read property 'capabilities' of undefined
    at ChangeAgentCoreInfo (/home/meshcentral/node_modules/meshcentral/meshagent.js:1478:27)
    at Timeout._onTimeout (/home/meshcentral/node_modules/meshcentral/meshagent.js:1482:69)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)

-------- 10/12/2020, 5:28:48 PM ---- 0.6.59 --------

/home/meshcentral/node_modules/meshcentral/meshagent.js:1478
        if (obj.agentInfo.capabilities & 0x40) return;
                          ^

TypeError: Cannot read property 'capabilities' of undefined
    at ChangeAgentCoreInfo (/home/meshcentral/node_modules/meshcentral/meshagent.js:1478:27)
    at Timeout._onTimeout (/home/meshcentral/node_modules/meshcentral/meshagent.js:1482:69)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)

-------- 10/12/2020, 6:49:16 PM ---- 0.6.60 --------

/home/meshcentral/node_modules/mongodb/lib/utils.js:132
      throw err;
      ^

TypeError: Cannot read property 'tag' of undefined
    at /home/meshcentral/node_modules/meshcentral/meshuser.js:665:194
    at /home/meshcentral/node_modules/meshcentral/db.js:1006:82
    at /home/meshcentral/node_modules/mongodb/lib/utils.js:731:5
    at handleCallback (/home/meshcentral/node_modules/mongodb/lib/utils.js:128:55)
    at cursor.close (/home/meshcentral/node_modules/mongodb/lib/cursor.js:841:66)
    at handleCallback (/home/meshcentral/node_modules/mongodb/lib/utils.js:128:55)
    at completeClose (/home/meshcentral/node_modules/mongodb/lib/cursor.js:929:16)
    at Cursor.close (/home/meshcentral/node_modules/mongodb/lib/cursor.js:948:12)
    at cursor._next (/home/meshcentral/node_modules/mongodb/lib/cursor.js:841:27)
    at handleCallback (/home/meshcentral/node_modules/mongodb/lib/core/cursor.js:32:5)
    at _setCursorNotifiedImpl (/home/meshcentral/node_modules/mongodb/lib/core/cursor.js:685:38)
    at self._endSession (/home/meshcentral/node_modules/mongodb/lib/core/cursor.js:694:39)
    at Cursor._endSession (/home/meshcentral/node_modules/mongodb/lib/core/cursor.js:395:7)
    at _setCursorNotifiedImpl (/home/meshcentral/node_modules/mongodb/lib/core/cursor.js:694:10)
    at setCursorNotified (/home/meshcentral/node_modules/mongodb/lib/core/cursor.js:685:3)
    at setCursorDeadAndNotified (/home/meshcentral/node_modules/mongodb/lib/core/cursor.js:678:3)

`

As this is on a VM I quickly restored it back to a backup from a few days ago, and it appears to work fine again for a short-while, and then repeats the same error, but I do have auto-update enabled.

The VM is an LXC on proxmox, running Ubuntu 18.04.4 LTS if that helps.

Thanks :)

**Comment by Ylianst** [comment]
Working on this now! Thanks for the report.

**Comment by Ylianst** [comment]
I am publishing a new version shortly and will have this fixed.

**Comment by Ylianst** [comment]
MeshCentral v0.6.61 published with a fix for this. Let me know if it works.

**Comment by djsakisd** [comment]
@Ylianst  It works fine now (I too was facing the same issue with server crash & restart and had to downgrade 0.6.58) , i can confirm that 0.6.6 have fixed it.

Thank you.
