### ISSUE TITLE
Server update failed.

### ISSUE THREAD

**Issue by trentdavis** [Ylianst/MeshCentral#1890]
Hi, I was trying to update my server in order to test the new tray application, but suddenly the server update function no longer works.  I have tried selecting latest version or stable version, but when I log back into the server the version remains at 0.5.72.

I have even tried the serverupdate function in the console, but no luck.

What could be causing this?

**Comment by Ylianst** [comment]
Are there any errors in the "mesherrors.txt" file in "meshcentral-data"?

In general this can be normal if MeshCentral is not allowed to write it's own files. In that case the self-update system will not work. You can update manually: SSH into your machine, stop MeshCentral, rename "node_modules" to "node_modules_back", run "npm install meshcentral" and start the server again.

If you have any more details, I would be interested.

**Comment by trentdavis** [comment]
There's no mesherrors.txt file.  also when I execute your above instructions, I get the following:

C:\Program Files\Open Source\MeshCentral>npm install meshcentral
npm WARN saveError ENOENT: no such file or directory, open 'C:\Program Files\Open Source\MeshCentral\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Program Files\Open Source\MeshCentral\package.json'
npm WARN MeshCentral No description
npm WARN MeshCentral No repository field.
npm WARN MeshCentral No README data
npm WARN MeshCentral No license field.

+ meshcentral@0.6.62
added 140 packages from 139 contributors and audited 140 packages in 24.598s

14 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

But now the service doesn't start, and returns the error 1067.  The service terminated unexpectedly.

**Comment by trentdavis** [comment]
I was able to recover the server by restoring the node_modules folder, but not sure how to move forward with the update.

**Comment by adsgreen** [comment]
I have a similar problem moving to 0.7.37.
Also - there is no "mesherrors.txt" file created but this is the created in the console.

`Starting self upgrade to: 0.7.37
Error: Command failed: /home/ec2-user/.nvm/versions/node/v12.13.1/bin/node /home/ec2-user/node_modules/meshcentral --launch 32025

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:215:7)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  killed: false,
  code: 200,
  signal: null,
  cmd: '/home/ec2-user/.nvm/versions/node/v12.13.1/bin/node /home/ec2-user/node_modules/meshcentral --launch 32025'
}
ERROR: MeshCentral failed with critical error, check MeshErrors.txt. Restarting in 5 seconds.
..
MeshCentral HTTP redirection server running on port 80.
MeshCentral v0.7.10, WAN mode.
MeshCentral Intel(R) AMT server running on xxxxxxx.com:4433.
MeshCentral HTTPS server running on xxxxxxx.com:443.
`

It then recovers and restarts automatically back to the previous version

**Comment by adsgreen** [comment]
Interesting observation...
Clicking the UI "update server link" fails with the above error.
However, using the server console command "serverupdate" works fine.

**Comment by OutbackMatt** [comment]
Similar problem

I notices a npm error when trying to install manually
Removed NodeJS (sudo apt remove nodejs) then reinstalled  = fixed

**Comment by trentdavis** [comment]
How did you reinstall NodeJS?

**Comment by trentdavis** [comment]
Nevermind.  Uninstalled NodeJS, did a windows reinstall (Backed up the data folder first) and then restored.  Fixed the problem.
Thanks for the insight! @OutbackMatt
