### ISSUE TITLE
Error while download recorded session

### ISSUE THREAD

**Issue by evgeniysevost** [Ylianst/MeshCentral#1911]
Hi Meshcentral team!

I found a problem while downloading Recorded session (sessionRecording).

If you rename your computer to "Имя Фамилия", connect, the server will record the session and you will try to download it, mashcentral will generate 500 errors and log it:

```
ERR: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Content-Disposition"],
    at ServerResponse.setHeader (_http_outgoing.js:550:3),
    at ServerResponse.header (/meshcentral/node_modules/express/lib/response.js:771:10),
    at ServerResponse.header (/meshcentral/node_modules/express/lib/response.js:774:12),
    at handleGetRecordings (/meshcentral/node_modules/meshcentral/webserver.js:3029:13),
    at Layer.handle [as handle_request] (/meshcentral/node_modules/express/lib/router/layer.js:95:5),
    at next (/meshcentral/node_modules/express/lib/router/route.js:137:13),
    at Route.dispatch (/meshcentral/node_modules/express/lib/router/route.js:112:3),
    at Layer.handle [as handle_request] (/meshcentral/node_modules/express/lib/router/layer.js:95:5),
    at /meshcentral/node_modules/express/lib/router/index.js:281:22,
    at Function.process_params (/meshcentral/node_modules/express/lib/router/index.js:335:12),
```
You have already fixed similar ones, https://github.com/Ylianst/MeshCentral/issues/174 .

**Comment by Ylianst** [comment]
Thanks for the report, I just fixed all "Content-Disposition" problems in the code and pushed it to GitHub. Fix will be in MeshCentral v0.6.66 when it's next published, probably Monday.

**Comment by Ylianst** [comment]
MeshCentral v0.6.66 is published. Should be fixed in that one.

**Comment by evgeniysevost** [comment]
The problem has been solved in this version, I confirm. 

Nuance, the filename of the downloaded record is "recording.mcrec". 
Expected relaysession-$DATE-$TIME-$MESHCENT_USERNAME-$REMOTEHOSTNAME-$SESSIONNAME.mcrec

But this does not apply to this issue. Thank you, I am closing issue.

**Comment by Ylianst** [comment]
There must be a character in the username that it not acceptable for the HTTP header and/or file name. If you happen to know what it is in your case, I can remove that character and use the rest for the filename.
