### ISSUE TITLE
 I get error when i tray to download a file from a pc 

### ISSUE THREAD

**Issue by Electricity2015** [Ylianst/MeshCentral#1921]
Meshcentral is crashing and I get this error when i tray to download a file from a pc 

-------- 10/27/2020, 7:09:42 PM ---- 0.6.67 --------

/home/mc/node_modules/meshcentral/meshdevicefile.js:206
                        setContentDispositionHeader(this.res, 'application/octet-stream', filename, cmd.size, 'file.bin');
                                                                                          ^

ReferenceError: filename is not defined
    at WebSocket.<anonymous> (/home/mc/node_modules/meshcentral/meshdevicefile.js:206:91)
    at WebSocket.emit (events.js:321:20)
    at Receiver.receiverOnMessage (/home/mc/node_modules/express-ws/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (events.js:321:20)
    at Receiver.dataMessage (/home/mc/node_modules/express-ws/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/home/mc/node_modules/express-ws/node_modules/ws/lib/receiver.js:346:17)
    at Receiver.startLoop (/home/mc/node_modules/express-ws/node_modules/ws/lib/receiver.js:133:22)
    at Receiver._write (/home/mc/node_modules/express-ws/node_modules/ws/lib/receiver.js:69:10)
    at doWrite (_stream_writable.js:454:12)
    at writeOrBuffer (_stream_writable.js:436:5)
    at Receiver.Writable.write (_stream_writable.js:327:11)
    at TLSSocket.socketOnData (/home/mc/node_modules/express-ws/node_modules/ws/lib/websocket.js:795:35)
    at TLSSocket.emit (events.js:321:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at TLSSocket.Readable.push (_stream_readable.js:214:10)

**Comment by Electricity2015** [comment]
![image](https://user-images.githubusercontent.com/8312565/97341112-50cd0180-188d-11eb-8b89-21c8dcfd6081.png)

**Comment by Ylianst** [comment]
Working on this now!!

**Comment by Ylianst** [comment]
MeshCentral v0.6.68 is published with a fix for this.

**Comment by Electricity2015** [comment]
It is working again.

Thanks.
