### ISSUE TITLE
File transfer causes MeshCentral server to crash on 0.6.66

### ISSUE THREAD

**Issue by PathfinderNetworks** [Ylianst/MeshCentral#1923]
Since upgrading to version 0.6.66 I'm seeing a pretty major bug.  When I attempt to upload or download files from a device (using the Files tab) the MeshCentral server will immediately crash as soon as I begin the file transfer.  Happens both by clicking on a file to download it from the remote device or by choosing a local file and clicking OK to upload to the remote device.

**Comment by PathfinderNetworks** [comment]
The servererrors.txt file is showing this:

-------- 10/27/2020, 7:10:11 PM ---- 0.6.66 --------

c:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\meshdevicefile.js:206
                        setContentDispositionHeader(this.res, 'application/octet-stream', filename, cmd.size, 'file.bin');
                                                                                          ^

ReferenceError: filename is not defined
    at WebSocket.<anonymous> (c:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\meshdevicefile.js:206:91)
    at WebSocket.emit (events.js:314:20)
    at Receiver.receiverOnMessage (c:\Program Files\Open Source\MeshCentral\node_modules\express-ws\node_modules\ws\lib\websocket.js:720:20)
    at Receiver.emit (events.js:314:20)
    at Receiver.dataMessage (c:\Program Files\Open Source\MeshCentral\node_modules\express-ws\node_modules\ws\lib\receiver.js:414:14)
    at Receiver.getData (c:\Program Files\Open Source\MeshCentral\node_modules\express-ws\node_modules\ws\lib\receiver.js:346:17)
    at Receiver.startLoop (c:\Program Files\Open Source\MeshCentral\node_modules\express-ws\node_modules\ws\lib\receiver.js:133:22)
    at Receiver._write (c:\Program Files\Open Source\MeshCentral\node_modules\express-ws\node_modules\ws\lib\receiver.js:69:10)
    at writeOrBuffer (_stream_writable.js:352:12)
    at Receiver.Writable.write (_stream_writable.js:303:10)
    at TLSSocket.socketOnData (c:\Program Files\Open Source\MeshCentral\node_modules\express-ws\node_modules\ws\lib\websocket.js:795:35)
    at TLSSocket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:303:12)
    at readableAddChunk (_stream_readable.js:279:9)
    at TLSSocket.Readable.push (_stream_readable.js:218:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)

**Comment by Ylianst** [comment]
This is fixed in v0.6.68, look at #1921. I did a high priority fix for this one.

**Comment by PathfinderNetworks** [comment]
Thanks!  I didn't notice the other report.  I'll update my server shortly.

**Comment by Ylianst** [comment]
No worries, thanks for reporting it.
