### ISSUE TITLE
Translate.js does not automatically install html-minifier

### ISSUE THREAD

**Issue by Yvan-Masson** [Ylianst/MeshCentral#1967]
Hi,

I finally took the time to install node.js and npm to be able to work on translation, as written in `translate/readme.txt`. I am using Debian testing, so `nodejs` package is in version `12.19.0~dfsg-1` and `npm` is in version `7.0.9+ds-1` (and the latter comes with a ton of dependencies).

But the following command failed:

```
$ node translate.js translateall
Installing jsdom...
Installing minify-js...
Installing html-minifier...
internal/modules/cjs/loader.js:834
  throw err;
  ^

Error: Cannot find module 'html-minifier'
Require stack:
- /home/yvan/pas-de-sauvegarde/MeshCentral/translate/translate.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at startEx (/home/yvan/pas-de-sauvegarde/MeshCentral/translate/translate.js:161:36)
    at start (/home/yvan/pas-de-sauvegarde/MeshCentral/translate/translate.js:154:20)
    at InstallModules (/home/yvan/pas-de-sauvegarde/MeshCentral/translate/translate.js:924:121)
    at /home/yvan/pas-de-sauvegarde/MeshCentral/translate/translate.js:946:9
    at ChildProcess.exithandler (child_process.js:299:7)
    at ChildProcess.emit (events.js:314:20) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/yvan/pas-de-sauvegarde/MeshCentral/translate/translate.js' ]
}
```
After manually running `npm install html-minifier`, the above command succeeds. As `translate.js` already installs some libraries, maybe it should also install html-minifier?

Regards,
Yvan

**Comment by Ylianst** [comment]
You can see in your report that the tool tried to auto-install `html-minifier`. Not sure what happened that the install did not work.

**Comment by Yvan-Masson** [comment]
Oh sorry I suppose I was a bit tired when reading the script output…

So I just uninstalled html-minifier (had to run `npm uninstall html-minifier` twice, don't know why) and re-run `node translate.js translateall`: it failed with the same error, so at least it is reproducible.

**Comment by si458** [comment]
this has been fixed recently hopefully 🤞
