### ISSUE TITLE
Error: Cannot find module './amt/amt-ider.js'

### ISSUE THREAD

**Issue by motapek** [Ylianst/MeshCentral#203]
After install 0.3.2-z (sudo npm install meshcentral) I get error

-------- 4/26/2019, 8:34:49 PM ---- 0.3.2-z --------
internal/modules/cjs/loader.js:584
    throw err;
    ^
Error: Cannot find module './amt/amt-ider.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.module.exports.CreateWebServer (/opt/meshcentral/node_modules/meshcentral/webserver.js:60:27)
    at AsyncWrap.<anonymous> (/opt/meshcentral/node_modules/meshcentral/meshcentral.js:767:59)
    at AsyncWrap.wrap.ondone (internal/crypto/random.js:57:8)

**Comment by Ylianst** [comment]
Update again, next version fixes this.

On Apr 26, 2019 11:39 AM, motapek <notifications@github.com> wrote:

After install 0.3.2-z (sudo npm install meshcentral) I get error

-------- 4/26/2019, 8:34:49 PM ---- 0.3.2-z --------
internal/modules/cjs/loader.js:584
throw err;
^
Error: Cannot find module './amt/amt-ider.js'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
at Function.Module._load (internal/modules/cjs/loader.js:508:25)
at Module.require (internal/modules/cjs/loader.js:637:17)
at require (internal/modules/cjs/helpers.js:22:18)
at Object.module.exports.CreateWebServer (/opt/meshcentral/node_modules/meshcentral/webserver.js:60:27)
at AsyncWrap. (/opt/meshcentral/node_modules/meshcentral/meshcentral.js:767:59)
at AsyncWrap.wrap.ondone (internal/crypto/random.js:57:8)

**Comment by motapek** [comment]
It's OK
