### ISSUE TITLE
To have both a local administrator account and ldap users ?

### ISSUE THREAD

**Issue by Philippe34** [Ylianst/MeshCentral#2042]
Hi,

Meshcentral 0.7.10 on centOS 8.
For the first connexion, I created a administrator user (admin) and I could add devices group, install agent, etc ...
Now I'd like to add users. For that, I thought to use the ldap authentication. I installed the ldapauth-fork and added in config.json domains:

"auth": "ldap",
"ldapUserName": "uid"
"ldapUserKey": "uid",
      "ldapOptions": {
        "url": "ldap://ldap1.domain.fr:389",
        "searchBase": "ou=xxx,dc=xxx,dc=fr",
        "searchFilter": "(uid={{username}})"
      }

It works with an user in LDAP, mais now I can't log with the local administrator account (admin). It is refused.
How can I have both local account and ldap account. Is it possible ?

Thanks. I appreciate very much meshCentral. Thay's a great job.

**Comment by Ylianst** [comment]
Hi. You are exactly right that when you enable LDAP, you don't have the login screen anymore and so, you can't login using your local administrator account. My recommendation is to upgrade your LDAP account to an administration account. To do this, use the administrator account recovery commands that are available on the MeshCentral command line. You can see then when you type 'node node_modules/meshcentral --help', it's the bottom section:

```
MeshCentral v0.7.10, remote computer management web portal.
This software is open source under Apache 2.0 license.
Details at: https://www.meshcommander.com/meshcentral2

Run as a background service
   --install/uninstall               Install MeshCentral as a background service.
   --start/stop/restart              Control MeshCentral background service.

Run standalone, console application
   --user [username]                 Always login as [username] if account exists.
   --port [number]                   Web server port number.
   --redirport [number]              Creates an additional HTTP server to redirect users to the HTTPS server.
   --exactports                      Server must run with correct ports or exit.
   --noagentupdate                   Server will not update mesh agent native binaries.
   --listuserids                     Show a list of a user identifiers in the database.
   --cert [name], (country), (org)   Create a web server certificate with [name] server name.
                                     country and organization can optionally be set.

Server recovery commands, use only when MeshCentral is offline.
   --createaccount [userid]          Create a new user account.
   --resetaccount [userid]           Unlock an account, disable 2FA and set a new account password.
   --adminaccount [userid]           Promote account to site administrator.
   --removeaccount [userid]          Remove a user account.
```

These are useful if you loose your administrator account, but in your case you should do:

```
node node_modules/meshcentral --adminaccount user\\ldapuserid
```

If you are not sure what your account userid is, try this:

```
node node_modules/meshcentral --showusers
```

It will list all accounts, look for the "_id" of your account and use that in --adminaccount command.

Hope that helps,
Ylian

**Comment by Philippe34** [comment]
@Ylianst 
Thank you very for your help. You gave the right method.
So after logging with my ldap account (myuid), I promoted it to admin account:

`node_modules/meshcentral --adminaccount user//myuid`

After logging, I could verify that myuid user ldap was an admin, but he wasn't seeing the devices group that I had created with the local admin. I commented the auth ldap in config.json to be able to reconnect with the local admin and to add the devices group to myuid ldap user. Now it's OK. I came back with auth ldap configuration and I can continue to administrate meshcentral under the identity of myuid .Excellent

If I'm logging now with a standard ldap user, I can add my devices group, but it is surprising to have the menu to change the password. I tried, but it did not work of course in my case ( because I did not put a "bindDN" and a "bindCredentials" ? ).

Just a last question please. I'd like to have a rescue ldap server, like this: 

```
"url": "ldap://ldap1.domain.fr:389",
"url": "ldap://ldap2.domain.fr:389",
```

Will it work ?

I tried ldaps, but it failed. I have to investigate why. I can see "self signed certificate in certificate chaine".
But I can continue with ldap and not use ldaps.

Dec  3 21:45:42 vm-mesh node[2649]: ERR: events.js:292
Dec  3 21:45:42 vm-mesh node[2649]:      throw er; // Unhandled 'error' event
Dec  3 21:45:42 vm-mesh node[2649]:      ^
Dec  3 21:45:42 vm-mesh node[2649]: Error: self signed certificate in certificate chain
Dec  3 21:45:42 vm-mesh node[2649]:    at TLSSocket.onConnectSecure (_tls_wrap.js:1501:34)
Dec  3 21:45:42 vm-mesh node[2649]:    at TLSSocket.emit (events.js:315:20)
Dec  3 21:45:42 vm-mesh node[2649]:    at TLSSocket._finishInit (_tls_wrap.js:936:8)
Dec  3 21:45:42 vm-mesh node[2649]:    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:710:12)
Dec  3 21:45:42 vm-mesh node[2649]: Emitted 'error' event on LdapAuth instance at:
Dec  3 21:45:42 vm-mesh node[2649]:    at LdapAuth._handleError (/opt/meshcentral/node_modules/ldapauth-fork/lib/ldapauth.js:185:8)
Dec  3 21:45:42 vm-mesh node[2649]:    at Client.emit (events.js:315:20)
Dec  3 21:45:42 vm-mesh node[2649]:    at Backoff.<anonymous> (/opt/meshcentral/node_modules/ldapjs/lib/client/client.js:1036:12)
Dec  3 21:45:42 vm-mesh node[2649]:    at Backoff.emit (events.js:315:20)
Dec  3 21:45:42 vm-mesh node[2649]:    at Backoff.backoff (/opt/meshcentral/node_modules/backoff/lib/backoff.js:41:14)
Dec  3 21:45:42 vm-mesh node[2649]:    at /opt/meshcentral/node_modules/ldapjs/lib/client/client.js:1020:15
Dec  3 21:45:42 vm-mesh node[2649]:    at f (/opt/meshcentral/node_modules/once/once.js:25:25)
Dec  3 21:45:42 vm-mesh node[2649]:    at TLSSocket.onResult (/opt/meshcentral/node_modules/ldapjs/lib/client/client.js:810:7)
Dec  3 21:45:42 vm-mesh node[2649]:    at Object.onceWrapper (events.js:422:26)
Dec  3 21:45:42 vm-mesh node[2649]:    at TLSSocket.emit (events.js:315:20) {
Dec  3 21:45:42 vm-mesh node[2649]:  code: 'SELF_SIGNED_CERT_IN_CHAIN'
Dec  3 21:45:42 vm-mesh node[2649]: }
Dec  3 21:45:42 vm-mesh node[2649]: Error: Command failed: /usr/bin/node /opt/meshcentral/node_modules/meshcentral --launch 2649
Dec  3 21:45:42 vm-mesh node[2649]: events.js:292
Dec  3 21:45:42 vm-mesh node[2649]:      throw er; // Unhandled 'error' event
Dec  3 21:45:42 vm-mesh node[2649]:      ^
Dec  3 21:45:42 vm-mesh node[2649]: Error: self signed certificate in certificate chain
Dec  3 21:45:42 vm-mesh node[2649]:    at TLSSocket.onConnectSecure (_tls_wrap.js:1501:34)
Dec  3 21:45:42 vm-mesh node[2649]:    at TLSSocket.emit (events.js:315:20)
Dec  3 21:45:42 vm-mesh node[2649]:    at TLSSocket._finishInit (_tls_wrap.js:936:8)
Dec  3 21:45:42 vm-mesh node[2649]:    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:710:12)
Dec  3 21:45:42 vm-mesh node[2649]: Emitted 'error' event on LdapAuth instance at:
Dec  3 21:45:42 vm-mesh node[2649]:    at LdapAuth._handleError (/opt/meshcentral/node_modules/ldapauth-fork/lib/ldapauth.js:185:8)
Dec  3 21:45:42 vm-mesh node[2649]:    at Client.emit (events.js:315:20)
Dec  3 21:45:42 vm-mesh node[2649]:    at Backoff.<anonymous> (/opt/meshcentral/node_modules/ldapjs/lib/client/client.js:1036:12)
Dec  3 21:45:42 vm-mesh node[2649]:    at Backoff.emit (events.js:315:20)
Dec  3 21:45:42 vm-mesh node[2649]:    at Backoff.backoff (/opt/meshcentral/node_modules/backoff/lib/backoff.js:41:14)
Dec  3 21:45:42 vm-mesh node[2649]:    at /opt/meshcentral/node_modules/ldapjs/lib/client/client.js:1020:15
Dec  3 21:45:42 vm-mesh node[2649]:    at f (/opt/meshcentral/node_modules/once/once.js:25:25)
Dec  3 21:45:42 vm-mesh node[2649]:    at TLSSocket.onResult (/opt/meshcentral/node_modules/ldapjs/lib/client/client.js:810:7)
Dec  3 21:45:42 vm-mesh node[2649]:    at Object.onceWrapper (events.js:422:26)
Dec  3 21:45:42 vm-mesh node[2649]:    at TLSSocket.emit (events.js:315:20) {
Dec  3 21:45:42 vm-mesh node[2649]:  code: 'SELF_SIGNED_CERT_IN_CHAIN'
Dec  3 21:45:42 vm-mesh node[2649]: }
Dec  3 21:45:42 vm-mesh node[2649]:    at ChildProcess.exithandler (child_process.js:303:12)
Dec  3 21:45:42 vm-mesh node[2649]:    at ChildProcess.emit (events.js:327:22)
Dec  3 21:45:42 vm-mesh node[2649]:    at maybeClose (internal/child_process.js:1021:16)
Dec  3 21:45:42 vm-mesh node[2649]:    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
Dec  3 21:45:42 vm-mesh node[2649]:  killed: false,
Dec  3 21:45:42 vm-mesh node[2649]:  code: 1,
Dec  3 21:45:42 vm-mesh node[2649]:  signal: null,
Dec  3 21:45:42 vm-mesh node[2649]:  cmd: '/usr/bin/node /opt/meshcentral/node_modules/meshcentral --launch 2649'
Dec  3 21:45:42 vm-mesh node[2649]: }
Dec  3 21:45:42 vm-mesh node[2649]: ERROR: MeshCentral failed with critical error, check MeshErrors.txt. Restarting in 5 seconds.

**Comment by Ylianst** [comment]
Oh good. Thanks for the report. Note that if you had started the server with an empty database and configured with LDAP, the first user to login using LDAP would have been administrator. However, you did exactly the right thing in your case.

If you see an option to change the password in "My Account" tab when in LDAP mode, that is a bug. I need to remove that.

For your issue of having two LDAP servers. I have to investigate this. The option would be more like:

```
"url": [ "ldap://ldap1.domain.fr:389", "ldap://ldap2.domain.fr:389" ]
```

However, I would need to look and see if I can enable this.

**Comment by Philippe34** [comment]
I tried the option with 2 ldap servers

`"url": [ "ldap://ldap1.domain.fr:389", "ldap://ldap2.domain.fr:389" ]`

It's already working in MeshCentral !
I stopped the first ldap server, and automatically, the second ldap server had been used.

Thanks @Ylianst 

The ticket can be closed for me. It's very satisfying like that.

**Comment by Ylianst** [comment]
Oh excellent!!! Nice. Thanks for reporting back.
