### ISSUE TITLE
v0.3.2-z update, MC2 won't start

### ISSUE THREAD

**Issue by FATeknollogee** [Ylianst/MeshCentral#208]
```
MeshCentral HTTP redirection server running on port 80.
MeshCentral v0.3.2-z, WAN mode.
{ Error: Command failed: /usr/bin/node /opt/meshcentral/node_modules/meshcentral --launch
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module './amt/amt-ider.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.module.exports.CreateWebServer (/opt/meshcentral/node_modules/meshcentral/webserver.js:60:27)
    at AsyncWrap.<anonymous> (/opt/meshcentral/node_modules/meshcentral/meshcentral.js:767:59)
    at AsyncWrap.wrap.ondone (internal/crypto/random.js:57:8)

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:194:15)
    at maybeClose (internal/child_process.js:970:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:189:13)
    at Pipe._handle.close (net.js:597:12)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   '/usr/bin/node /opt/meshcentral/node_modules/meshcentral --launch' }
ERROR: MeshCentral failed with critical error, check MeshErrors.txt. Restarting in 5 seconds...

**Comment by Ylianst** [comment]
Update to latest version to fix this. MeshCentral v0.3.3-b is current.

**Comment by Ylianst** [comment]
I just unpublished v0.3.2-z to make sure this does not happen. Please use the latest version.

**Comment by FATeknollogee** [comment]
Thank you, will go & update.

**Comment by Ylianst** [comment]
Closing this one as I am sure this is fixed.
