### ISSUE TITLE
Clicking "Show server error log" under My Server causes crash with mongo

### ISSUE THREAD

**Issue by datapharmer** [Ylianst/MeshCentral#2097]
When clicking show server error log in version 0.7.30 it causes meshcentral to crash and restart.

    at cursor._next (/home/ec2-user/node_modules/mongodb/lib/cursor.js:834:20)
    at self._initializeCursor (/home/ec2-user/node_modules/mongodb/lib/core/cursor.js:736:9)
    at Object.cursor.topology.selectServer.err [as callback] (/home/ec2-user/node_modules/mongodb/lib/core/cursor.js:432:11)
    at Timeout.waitQueueMember.timer.setTimeout [as _onTimeout] (/home/ec2-user/node_modules/mongodb/lib/core/sdam/topology.js:443:25)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

This happens consistently regardless of whether mesherrors.txt is present. It appears it is running the instance out of memory and the kernel is killing the process. Not sure why this would be the case for loading a non-existent or very small text file.

**Comment by dinger1986** [comment]
@si458 really old mesh version

**Comment by si458** [comment]
should be well fixed by now, please try updating and reopen if issue still exists
