### ISSUE TITLE
"Unable to perform authentication" since 0.7.41 

### ISSUE THREAD

**Issue by vtacquet** [Ylianst/MeshCentral#2150]
![image](https://user-images.githubusercontent.com/5128967/103983236-34025380-5185-11eb-9461-068d2f001708.png)

2FA is enabled

0.7.40 is still working fine, all versions after .40 give the error.

in front: caddy proxy with Lets Encrypt
  "Settings": {
...
    "TLSOffload": true
    "Cert": "some.domain.com"
...
  "Domains": {
...
      "CertUrl": "https://some.domain.com/",
...

**Comment by Ylianst** [comment]
Oh, I think I can fix that. However, if you change:

```
"TLSOffload": true
```

to

```
"TLSOffload": "127.0.0.1"
```

That may fix it. Instead of 127.0.0.1, you should put the private IP address of Caddy. This is more secure that using "true" and will likely fix the problem until put out a fix for this.

**Comment by Ylianst** [comment]
In "meshcentral-data", if you can post the last few errors in the "mesherrors.txt" file, that would be great. I would not need to guess what the problem is. Thanks.

**Comment by vtacquet** [comment]
tried with 
    "TLSOffload": "caddy.docker_default"
and with
    "TLSOffload": "caddy"
and with IP
    "TLSOffload": "172.18.0.13"

none of the options are working


last error in mesherror.txt is still about the version prior to the name resolution fix

-------- 1/2/2021, 1:20:15 PM ---- 0.7.31 --------

/meshcentral/node_modules/proxy-addr/index.js:163
    throw new TypeError('invalid IP address: ' + str)
    ^

TypeError: invalid IP address: caddy
    at parseipNotation (/meshcentral/node_modules/proxy-addr/index.js:163:11)
    at compileRangeSubnets (/meshcentral/node_modules/proxy-addr/index.js:126:23)
    at Function.compile (/meshcentral/node_modules/proxy-addr/index.js:112:23)
    at exports.compileTrust (/meshcentral/node_modules/express/lib/utils.js:238:20)
    at Function.set (/meshcentral/node_modules/express/lib/application.js:372:34)
    at serverStart (/meshcentral/node_modules/meshcentral/webserver.js:4887:68)
    at /meshcentral/node_modules/meshcentral/webserver.js:262:17
    at /meshcentral/node_modules/meshcentral/db.js:1181:107
    at newArguments.<computed> (/meshcentral/node_modules/nedb/lib/executor.js:29:17)
    at Cursor.execFn (/meshcentral/node_modules/nedb/lib/datastore.js:484:12)

**Comment by vtacquet** [comment]
I already disabled 2FA before upgrading just to confirm it is not 2FA, and the error remains

**Comment by Ylianst** [comment]
Oh. So, on older versions like 0.7.31, it does not support performing DNS resolving for "TLSOffload" option. So this is expected to fail.

```
"TLSOffload": "caddy"
"TLSOffload": "caddy.docker_default"
```

It will only work on very latest versions. `"TLSOffload": "172.18.0.13"` should work??

**Comment by vtacquet** [comment]
correct but with the newer versions neither "true", "<ip>" or "<name>" is working, I can no longer connect

**Comment by Ylianst** [comment]
When you see the "Unable to perform authentication". Can you open your browser console and cut & paste any errors you see?

**Comment by vtacquet** [comment]
noauth-2 - meshcentral.js:50

**Comment by Ylianst** [comment]
Ha! Hold on.

**Comment by Ylianst** [comment]
If you run:

```
node node_modules/meshcentral --debug web
```

You will see the exact problem, but looking into this.

**Comment by vtacquet** [comment]
![image](https://user-images.githubusercontent.com/5128967/103985313-ff909680-5188-11eb-9165-6fdad79ed42f.png)

**Comment by vtacquet** [comment]
oh wait I used the wrong build

**Comment by Ylianst** [comment]
OHHH!!! Ok. In the settings section of the config.json, add this:

```
"cookieipcheck" : false
```

This will fix it for now. I need to look at why the port number was encoded in the cookie.

**Comment by vtacquet** [comment]
![image](https://user-images.githubusercontent.com/5128967/103985481-4ed6c700-5189-11eb-926f-6753d71c9403.png)

**Comment by Ylianst** [comment]
Yes, I see. Same problem, the port number is encoded in the cookie's IP address and so, being rejected.

**Comment by vtacquet** [comment]
![image](https://user-images.githubusercontent.com/5128967/103985679-aa08b980-5189-11eb-8a24-ad807b881db7.png)

Perfect, thank you very much @Ylianst !

**Comment by Ylianst** [comment]
If I can fix that, in future version you can put turn on "cookieipcheck" for extra security.

**Comment by vtacquet** [comment]
I can also confirm the Address part is working as expected and is now showing the real IP address and no longer the internal proxy IP ! 
![image](https://user-images.githubusercontent.com/5128967/103985952-331ff080-518a-11eb-908e-c58340394c3a.png)

**Comment by Ylianst** [comment]
Yes, but it should not be showing the port numbers. The problem is Caddy seems to be setup to put the port number in the 'x-forwarded-for' header which is not expected. If you can change the configuration to remove the port, that would be great. I just finished making a change to detect and remove the port if present.

**Comment by Ylianst** [comment]
I suspect the problem was not MeshCentral, but a change to the Caddy configuration.

**Comment by Ylianst** [comment]
MeshCentral v0.7.45 is out. I was releasing it anyway and added this fix. Let me know if it works. Ports should not show up and you can re-enable `cookieipcheck`. Let me know what you see.

**Comment by vtacquet** [comment]
Ports are still showing with .45 
![image](https://user-images.githubusercontent.com/5128967/103988890-1afea000-518f-11eb-984e-2d3cf98fb3a9.png)

**Comment by Ylianst** [comment]
Arg. Ok, I must not have caught it at the right place.

**Comment by vtacquet** [comment]
If it can help you... it seems that all Windows machines are only showing agent IPs and all Linux machines are showing agent IPs and ports !

![image](https://user-images.githubusercontent.com/5128967/103989925-b7757200-5190-11eb-9bde-3a5fee4ad3c1.png)

**Comment by Ylianst** [comment]
Oh, interesting.

**Comment by Ylianst** [comment]
In the next version of MeshCentral, v0.7.47, you can now go in the "My Server / Trace" tab and have the server show the incoming HTTP headers in real time. Once it's released, if you can capture a few headers and send them over, it's going to be easier to see what is going on.

![image](https://user-images.githubusercontent.com/1319013/104111239-8aaa8300-5294-11eb-9302-f910cd911385.png)

This new feature will make it easier to debug reverse-proxy issues.
