### ISSUE TITLE
missing image-size throw an unhandled exception 

### ISSUE THREAD

**Issue by cr-sh** [Ylianst/MeshCentral#2313]
The node module image-size was not installed by npm on the first run and its lack isn't handled by the loader.js so a server crash will occur.

I'm using a subdomain with the SessionRecording enabled (config attached for your convenience).

Reading the code I figured out that the key sessionrecording.index is required in config to catch the installation of image-size module.

I think a proper handling of this exception is desirable :)

### --> Here the log:

```
ERR: internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'image-size'
Require stack:
- /opt/meshcentral/node_modules/meshcentral/mcrec.js
- /opt/meshcentral/node_modules/meshcentral/meshaccelerator.js
- /opt/meshcentral/node_modules/meshcentral/certoperations.js
- /opt/meshcentral/node_modules/meshcentral/meshcentral.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at processBlock (/opt/meshcentral/node_modules/meshcentral/mcrec.js:136:42)
    at /opt/meshcentral/node_modules/meshcentral/mcrec.js:281:21
    at FSReqCallback.wrapper [as oncomplete] (fs.js:539:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/meshcentral/node_modules/meshcentral/mcrec.js',
    '/opt/meshcentral/node_modules/meshcentral/meshaccelerator.js',
    '/opt/meshcentral/node_modules/meshcentral/certoperations.js',
    '/opt/meshcentral/node_modules/meshcentral/meshcentral.js'
  ]
}
Error: Command failed: /usr/bin/node /opt/meshcentral/node_modules/meshcentral --launch 23134
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'image-size'
Require stack:
- /opt/meshcentral/node_modules/meshcentral/mcrec.js
- /opt/meshcentral/node_modules/meshcentral/meshaccelerator.js
- /opt/meshcentral/node_modules/meshcentral/certoperations.js
- /opt/meshcentral/node_modules/meshcentral/meshcentral.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at processBlock (/opt/meshcentral/node_modules/meshcentral/mcrec.js:136:42)
    at /opt/meshcentral/node_modules/meshcentral/mcrec.js:281:21
    at FSReqCallback.wrapper [as oncomplete] (fs.js:539:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/meshcentral/node_modules/meshcentral/mcrec.js',
    '/opt/meshcentral/node_modules/meshcentral/meshaccelerator.js',
    '/opt/meshcentral/node_modules/meshcentral/certoperations.js',
    '/opt/meshcentral/node_modules/meshcentral/meshcentral.js'
  ]
}

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:327:22)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: '/usr/bin/node /opt/meshcentral/node_modules/meshcentral --launch 23134'
}
ERROR: MeshCentral failed with critical error, check MeshErrors.txt. Restarting in 5 seconds...
```

### --> Here my config:

```
{
   "settings": {
      "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
      "WANonly": true,
      "cert": "my.domain.tld",
      "Port": 443,
      "TlsOffload": "10.10.10.10",
      "_minify": true,
      "selfupdate": true,
      "localdiscovery": {
         "name": "CONNECT DOMAIN",
         "info": "MC2 CONNECT DOMAIN"
      },
      "minify": true,
      "clickonce": true,
      "webrtc": true,
      "SessionTime": 30,
      "RedirPort": 80,
      "AgentPong": 300
   },
   "_letsencrypt": {
      "email": "my@email.tld",
      "names": "connect.domain.tld",
      "rsaKeySize": 3072,
      "production": true
 },
   "smtp": {
      "host": "mail.domain.tld",
      "port": 587,
      "from": "connect@domain.tld",
      "user": "connect@domain.tld",
      "pass": "very.secret",
      "tls": false
   },
   "domains": {
      "connect": {
         "certUrl": "https://10.10.10.10:443/",
         "title": "TLD-CONNECT",
         "title2": "my.domain.tld/connect",
         "newaccounts": false,
         "footer": "supah company",
         "passwordRequirements": {
                 "min": 12,
                 "reset": 90,
                 "force2factor": true,
                 "oldPasswordBan": 4,
                 "banCommonPassword": true
         },
         "SessionRecording": {
         "filepath": "/opt/meshcentral/audit",
         "protocols": [ 1, 2, 5 ]
        }
      }
   }
}
```

**Comment by Ylianst** [comment]
Thanks for reporting this. Currently MeshCentral only installs "image-size" if "index":true is added in the session recording, but it makes use of it even if that is not set.

"SessionRecording": {
    "index": true,
    "filepath": "/opt/meshcentral/audit",
    "protocols": [ 1, 2, 5 ]
}

I just fixed it to install when "SessionRecording" is added. That will be in v0.7.73. Once published, let me know if that works.

**Comment by Ylianst** [comment]
FYI. MeshCentral v0.7.73 has been released.

**Comment by cr-sh** [comment]
I can confirm it's ok now. Thanks for the blazing-fast fix, as usual :)
