### ISSUE TITLE
fresh install broken starting with version 0.7.85

### ISSUE THREAD

**Issue by wh1te909** [Ylianst/MeshCentral#2388]
Ubuntu 20.04.2 LTS
node 12.21.0

Seems to be caused by `--no-save` being added in commit 19cfae4295973a17a2030157f4e296a81cf66c35
Removing the `--no-save` fixes the issue

To reproduce (using nginx in front of mesh and mongo for db):
```bash
sudo mkdir -p /meshcentral/meshcentral-data
sudo chown ${USER}:${USER} -R /meshcentral
cd /meshcentral
npm install meshcentral@latest
```

config.json:
```json
{
  "settings": {
    "Cert": "mesh.example.com",
    "MongoDb": "mongodb://127.0.0.1:27017",
    "MongoDbName": "meshcentral",
    "WANonly": true,
    "Minify": 1,
    "Port": 4430,
    "AliasPort": 443,
    "RedirPort": 800,
    "AllowLoginToken": true,
    "AllowFraming": true,
    "AgentPong": 300,
    "AllowHighQualityDesktop": true,
    "TlsOffload": "127.0.0.1",
    "agentCoreDump": false,
    "Compression": true,
    "WsCompression": true,
    "AgentWsCompression": true,
    "MaxInvalidLogin": { "time": 5, "count": 5, "coolofftime": 30 }
  },
  "domains": {
    "": {
      "Title": "test",
      "Title2": "test",
      "NewAccounts": false,
      "CertUrl": "https://mesh.example.com:443/",
      "GeoLocation": true,
      "CookieIpCheck": false,
      "mstsc": true
    }
  }
}
```

```bash
tactical@rmmtest:/meshcentral$ node node_modules/meshcentral
Installing archiver@4.0.2...
Installing node-rdpjs-2...
Installing mongodb...
Installing saslprep...
Installing archiver@4.0.2...
Installing node-rdpjs-2...
Installing mongodb...
Installing otplib@10.2.3...
ERR: internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '../../package.json'
Require stack:
- /meshcentral/node_modules/mongodb/lib/core/utils.js
- /meshcentral/node_modules/mongodb/lib/core/index.js
- /meshcentral/node_modules/mongodb/index.js
- /meshcentral/node_modules/meshcentral/meshcentral.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at makeClientMetadata (/meshcentral/node_modules/mongodb/lib/core/utils.js:239:16)
    at new Topology (/meshcentral/node_modules/mongodb/lib/core/sdam/topology.js:122:19)
    at new NativeTopology (/meshcentral/node_modules/mongodb/lib/topologies/native_topology.js:47:5)
    at createTopology (/meshcentral/node_modules/mongodb/lib/operations/connect.js:560:16)
    at /meshcentral/node_modules/mongodb/lib/operations/connect.js:335:14
    at parseConnectionString (/meshcentral/node_modules/mongodb/lib/core/uri_parser.js:727:3) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/meshcentral/node_modules/mongodb/lib/core/utils.js',
    '/meshcentral/node_modules/mongodb/lib/core/index.js',
    '/meshcentral/node_modules/mongodb/index.js',
    '/meshcentral/node_modules/meshcentral/meshcentral.js'
  ]
}
Error: Command failed: /usr/bin/node /meshcentral/node_modules/meshcentral --launch 5701
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '../../package.json'
Require stack:
- /meshcentral/node_modules/mongodb/lib/core/utils.js
- /meshcentral/node_modules/mongodb/lib/core/index.js
- /meshcentral/node_modules/mongodb/index.js
- /meshcentral/node_modules/meshcentral/meshcentral.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at makeClientMetadata (/meshcentral/node_modules/mongodb/lib/core/utils.js:239:16)
    at new Topology (/meshcentral/node_modules/mongodb/lib/core/sdam/topology.js:122:19)
    at new NativeTopology (/meshcentral/node_modules/mongodb/lib/topologies/native_topology.js:47:5)
    at createTopology (/meshcentral/node_modules/mongodb/lib/operations/connect.js:560:16)
    at /meshcentral/node_modules/mongodb/lib/operations/connect.js:335:14
    at parseConnectionString (/meshcentral/node_modules/mongodb/lib/core/uri_parser.js:727:3) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/meshcentral/node_modules/mongodb/lib/core/utils.js',
    '/meshcentral/node_modules/mongodb/lib/core/index.js',
    '/meshcentral/node_modules/mongodb/index.js',
    '/meshcentral/node_modules/meshcentral/meshcentral.js'
  ]
}

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:326:22)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: '/usr/bin/node /meshcentral/node_modules/meshcentral --launch 5701'
}
ERROR: MeshCentral failed with critical error, check mesherrors.txt. Restarting in 5 seconds...
```

**Comment by Ylianst** [comment]
Fixing now!

**Comment by Ylianst** [comment]
MeshCentral v0.7.88 published with a fix for this. Let me know if it works.

**Comment by wh1te909** [comment]
fixed thank you!
