### ISSUE TITLE
Error: Cannot find module 'archiver'

### ISSUE THREAD

**Issue by uldiseihenbergs** [Ylianst/MeshCentral#2394]
Hello, cross-posting this issue from my docker build repo, i can't reproduce myself with the same version installed. any clue?
originally asked here: https://github.com/uldiseihenbergs/meshcentral-builds/issues/3

```Installing nodemailer...,
Installing otplib@10.2.3...,
Installing archiver@4.0.2...,
Installing nodemailer...,
MeshCentral HTTP redirection server running on port 80.,
MeshCentral v0.7.87, WAN mode.,
ERR: module.js:549,
    throw err;,
    ^,
,
Error: Cannot find module 'archiver',
    at Function.Module._resolveFilename (module.js:547:15),
    at Function.Module._load (module.js:474:25),
    at Module.require (module.js:596:17),
    at require (internal/module.js:11:18),
    at Duplex.<anonymous> (/home/node/meshcentral/node_modules/meshcentral/meshcentral.js:2546:43),
    at emitNone (events.js:106:13),
    at Duplex.emit (events.js:208:7),
    at finishMaybe (_stream_writable.js:614:14),
    at afterWrite (_stream_writable.js:465:3),
    at _combinedTickCallback (internal/process/next_tick.js:144:20),
{ Error: Command failed: /usr/local/bin/node /home/node/meshcentral/node_modules/meshcentral/meshcentral.js --launch 7,
module.js:549,
    throw err;,
    ^,
,
Error: Cannot find module 'archiver',
    at Function.Module._resolveFilename (module.js:547:15),
    at Function.Module._load (module.js:474:25),
    at Module.require (module.js:596:17),
    at require (internal/module.js:11:18),
    at Duplex.<anonymous> (/home/node/meshcentral/node_modules/meshcentral/meshcentral.js:2546:43),
    at emitNone (events.js:106:13),
    at Duplex.emit (events.js:208:7),
    at finishMaybe (_stream_writable.js:614:14),
    at afterWrite (_stream_writable.js:465:3),
    at _combinedTickCallback (internal/process/next_tick.js:144:20),
,
    at ChildProcess.exithandler (child_process.js:275:12),
    at emitTwo (events.js:131:20),
    at ChildProcess.emit (events.js:214:7),
    at maybeClose (internal/child_process.js:925:16),
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5),
  killed: false,,
  code: 1,,
  signal: null,,
  cmd: '/usr/local/bin/node /home/node/meshcentral/node_modules/meshcentral/meshcentral.js --launch 7' },
ERROR: MeshCentral failed with critical error, check mesherrors.txt. Restarting in 5 seconds...,```

**Comment by uldiseihenbergs** [comment]
just rebuilded docker image to 0.7.89, and user reported this as resolved :) so closing this issue now..
