### ISSUE TITLE
DesktopMultiplex - Causes server restart

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#2509]
Dear Ylianst 

I have enabled the Desktop multiplex feature after seen your post in Youtube Channel.

After enabling  "desktopMultiplex" : true,  i am getting below error message and server restart frequently.

My server Config.
OS -Windows Server 2019
Meshcentral Ver - 0.8.9
Database - MongoDB
Plugins - Disabled

```
**Error Message**

-------- 13/4/2021, 10:08:58 am ---- 0.8.9 --------

C:\M-ACCESS\node_modules\meshcentral\meshdesktopmultiplex.js:922
        if (obj.deskMultiplexor != null) { if (obj.deskMultiplexor.removePeer(obj) == true) { delete parent.desktoprelays[obj.nodeid]; } }
                                                                   ^

TypeError: obj.deskMultiplexor.removePeer is not a function
    at Object.CreateMeshRelayEx2.obj.close (C:\M-ACCESS\node_modules\meshcentral\meshdesktopmultiplex.js:922:68)
    at WebSocket.<anonymous> (C:\M-ACCESS\node_modules\meshcentral\meshdesktopmultiplex.js:1075:13)
    at WebSocket.emit (events.js:327:22)
    at WebSocket.emitClose (C:\M-ACCESS\node_modules\express-ws\node_modules\ws\lib\websocket.js:172:10)
    at Receiver.receiverOnFinish (C:\M-ACCESS\node_modules\express-ws\node_modules\ws\lib\websocket.js:710:20)
    at Receiver.emit (events.js:315:20)
    at finish (internal/streams/writable.js:657:10)
    at finishMaybe (internal/streams/writable.js:644:9)
    at afterWrite (internal/streams/writable.js:473:3)
    at afterWriteTick (internal/streams/writable.js:453:10)

```

**Comment by Ylianst** [comment]
You are right. Thank you for reporting this. I made a fix and it will be in MeshCentral v0.8.10.

**Comment by VINISHVV** [comment]
Quick fix... I will test once  v0.8.10 is Live.

**Comment by Ylianst** [comment]
MeshCentral v0.8.10 is live now. Let me know if it fixes it.

**Comment by VINISHVV** [comment]
@Ylianst 
Thanks its resolved.

**Comment by VINISHVV** [comment]
@Ylianst 

Issue not fixed. Still getting below errors.

_____________________________________________________________________________________
------- 15/4/2021, 12:07:26 pm ---- 0.8.12 --------

C:\M-ACCESS\node_modules\meshcentral\meshdesktopmultiplex.js:97
        if (peer.req.query.browser) {
                     ^

TypeError: Cannot read property 'query' of undefined
    at Object.CreateDesktopMultiplexor.obj.addPeer (C:\M-ACCESS\node_modules\meshcentral\meshdesktopmultiplex.js:97:22)
    at C:\M-ACCESS\node_modules\meshcentral\meshdesktopmultiplex.js:1038:41
    at C:\M-ACCESS\node_modules\meshcentral\meshdesktopmultiplex.js:801:46
    at C:\M-ACCESS\node_modules\meshcentral\meshdesktopmultiplex.js:716:21
    at C:\M-ACCESS\node_modules\meshcentral\meshdesktopmultiplex.js:747:82
    at FSReqCallback.wrapper [as oncomplete] (fs.js:638:5)

**Comment by Ylianst** [comment]
Different problem, but working on it now.

**Comment by Ylianst** [comment]
Thanks for reporting. Fix will be in MeshCentral v0.8.13.

**Comment by VINISHVV** [comment]
Thanks Ylianst.
Updated v0.8.14,  seems everything working fine....

**Comment by Ylianst** [comment]
Excellent. Thank you for reporting back and closing issue.
