### ISSUE TITLE
DesktopMulitplex Error: Cannot find module 'image-size'

### ISSUE THREAD

**Issue by rowds15** [Ylianst/MeshCentral#2512]
Version 0.8.12
DesktopMultiplex True

error when enabling DesktopMultiplex receiving the following below

```
Error: Cannot find module 'image-size'
node: Require stack:
node: - node_modules/meshcentral/meshdesktopmultiplex.js
node: - node_modules/meshcentral/webserver.js
node: - node_modules/meshcentral/meshcentral.js
node: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
node: at Function.Module._load (internal/modules/cjs/loader.js:841:27)
node: at Module.require (internal/modules/cjs/loader.js:1025:19)
node: at require (internal/modules/cjs/helpers.js:72:18)
node: at Object.CreateDesktopMultiplexor.obj.processAgentData (node_modules/meshcentral/meshdesktopmultiplex.js:569:34)
node: at node_modules/meshcentral/meshdesktopmultiplex.js:422:21
node: at recordData (node_modules/meshcentral/meshdesktopmultiplex.js:731:17)
node: at Object.CreateDesktopMultiplexor.obj.processData (node_modules/meshcentral/meshdesktopmultiplex.js:418:13)
node: at WebSocket.<anonymous> (node_modules/meshcentral/meshdesktopmultiplex.js:1061:72)
node: at WebSocket.emit (events.js:315:20) {
node: code: 'MODULE_NOT_FOUND',
node: requireStack: [
node: 'node_modules/meshcentral/meshdesktopmultiplex.js',
node: 'node_modules/meshcentral/webserver.js',
node: 'node_modules/meshcentral/meshcentral.js'
node: ]
node: }
```

**Comment by Ylianst** [comment]
That module should be auto-installed next time you run the server. One possibility is that your running the server in higher security mode where the server can't self-update and can not install new modules. In that case, just stop the server and run:

```
npm install image-size
```

You need to run this command in the folder above the "meshcentral-data" and "node_modules" folder. After that, run the server again, it should work.

**Comment by rowds15** [comment]
Ok this has fixed the issue.

Thank you
