### ISSUE TITLE
LDAP auth with self signed certificate

### ISSUE THREAD

**Issue by elkekou** [Ylianst/MeshCentral#2546]
Hi Ylianst,

thank you for your wonderfull tool, it was exactly what i'm looking for.

I'm trying to integrate meshcentral in my enterprise and with my ldap server (self signed certificate). But i'm really not comfortable with nodejs.

I'll try to read documentation of ldapauth-fork (library you seem to use) but does not really found how to tell meshcentral to not checking the ssl certificate.

Here is error i got when i trying authentification on my ldap.
```
Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1088:34)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket._finishInit (_tls_wrap.js:666:8)
Emitted 'error' event at:
    at LdapAuth._handleError (/home/mesh/node_modules/ldapauth-fork/lib/ldapauth.js:185:8)
    at Client.emit (events.js:198:13)
    at Backoff.<anonymous> (/home/mesh/node_modules/ldapjs/lib/client/client.js:1036:12)
    at Backoff.emit (events.js:198:13)
    at Backoff.backoff (/home/mesh/node_modules/backoff/lib/backoff.js:41:14)
    at /home/mesh/node_modules/ldapjs/lib/client/client.js:1020:15
    at f (/home/mesh/node_modules/once/once.js:25:25)
    at TLSSocket.onResult (/home/mesh/node_modules/ldapjs/lib/client/client.js:810:7)
    at Object.onceWrapper (events.js:286:20)
    at TLSSocket.emit (events.js:198:13)
{ Error: Command failed: /usr/bin/node /home/mesh/node_modules/meshcentral --launch 22523
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1088:34)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket._finishInit (_tls_wrap.js:666:8)
Emitted 'error' event at:
    at LdapAuth._handleError (/home/mesh/node_modules/ldapauth-fork/lib/ldapauth.js:185:8)
    at Client.emit (events.js:198:13)
    at Backoff.<anonymous> (/home/mesh/node_modules/ldapjs/lib/client/client.js:1036:12)
    at Backoff.emit (events.js:198:13)
    at Backoff.backoff (/home/mesh/node_modules/backoff/lib/backoff.js:41:14)
    at /home/mesh/node_modules/ldapjs/lib/client/client.js:1020:15
    at f (/home/mesh/node_modules/once/once.js:25:25)
    at TLSSocket.onResult (/home/mesh/node_modules/ldapjs/lib/client/client.js:810:7)
    at Object.onceWrapper (events.js:286:20)
    at TLSSocket.emit (events.js:198:13)

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:203:15)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:607:12)
  killed: false,
```

And the part of my conf file : 

```
  "domains": {
    "": {
      "auth": "ldap",
      "ldapUserName": "uid",
      "ldapOptions": {
        "url": "ldaps://ldap.domain.com:636",
        "searchBase": "ou=people,dc=domain,dc=com",
        "searchFilter": "(uid={{username}})"
      }
    }
  },
```

Thank you for help.

**Comment by nzalev** [comment]
The module in use is `ldapauth-fork`. Usually any libary that has to perform certificate verification will have a flag to turn verification off, though not recommended if communicating over the internet.

I can look into ldapauth-fork and see if it has an option to turn verification off. If so, I can add a config option that allows meshcentral to do this. I will not be available until this weekend, however.

I will reiterate though, certificate verification is to prevent man in the middle attacks. It is generally a better option to get a free cert through letsencrypt.

**Comment by elkekou** [comment]
I thank you for your response,

i'm currently not at work for several days. I'll test this when returning at work.

i'm completely aware about security issue by disabling tls verification.
But in my case it's not a big deal, and let's encrypt' use it's complicated, because this is a completly offline network.

Thank you again.

**Comment by Ylianst** [comment]
I think @nzalev has the right answer. If your having a problem adding the TLS option, let me know.
