### ISSUE TITLE
Web-SSH, after login, MeshCentral server crashed

### ISSUE THREAD

**Issue by hunter-nl** [Ylianst/MeshCentral#2565]
I'm trying the new Web-SSH. The remote session starts and prompt with the login. After providing the credentials and clicking on OK, the meshcentral server crashed.
This is the error:

```
`-------- 4/30/2021, 11:34:18 AM ---- 0.8.26 --------

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'ssh2'
Require stack:
- /opt/meshcentral/node_modules/meshcentral/apprelays.js
- /opt/meshcentral/node_modules/meshcentral/webserver.js
- /opt/meshcentral/node_modules/meshcentral/meshcentral.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at WebSocket.<anonymous> (/opt/meshcentral/node_modules/meshcentral/apprelays.js:242:36)
    at WebSocket.emit (events.js:314:20)
    at Receiver.receiverOnMessage (/opt/meshcentral/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:314:20)
    at Receiver.dataMessage (/opt/meshcentral/node_modules/ws/lib/receiver.js:422:14)
    at Receiver.getData (/opt/meshcentral/node_modules/ws/lib/receiver.js:352:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/meshcentral/node_modules/meshcentral/apprelays.js',
    '/opt/meshcentral/node_modules/meshcentral/webserver.js',
    '/opt/meshcentral/node_modules/meshcentral/meshcentral.js'
  ]
}


-------- 4/30/2021, 11:39:06 AM ---- 0.8.26 --------

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'ssh2'
Require stack:
- /opt/meshcentral/node_modules/meshcentral/apprelays.js
- /opt/meshcentral/node_modules/meshcentral/webserver.js
- /opt/meshcentral/node_modules/meshcentral/meshcentral.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at WebSocket.<anonymous> (/opt/meshcentral/node_modules/meshcentral/apprelays.js:242:36)
    at WebSocket.emit (events.js:314:20)
    at Receiver.receiverOnMessage (/opt/meshcentral/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:314:20)
    at Receiver.dataMessage (/opt/meshcentral/node_modules/ws/lib/receiver.js:422:14)
    at Receiver.getData (/opt/meshcentral/node_modules/ws/lib/receiver.js:352:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/meshcentral/node_modules/meshcentral/apprelays.js',
    '/opt/meshcentral/node_modules/meshcentral/webserver.js',
    '/opt/meshcentral/node_modules/meshcentral/meshcentral.js'
  ]
}

```

**Comment by hunter-nl** [comment]
Thank you. Solved.
