### ISSUE TITLE
Chat Broken

### ISSUE THREAD

**Issue by merlinweb** [Ylianst/MeshCentral#257]
Hi,
today I'm trying to establish a chat session with a co worker, but it's not working
It opens a new tab with following lines:

`ReferenceError: domain is not defined
    at handleMessengerRequest (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\webserver.js:1491:113)
    at Layer.handle [as handle_request] (C:\Program Files\Open Source\MeshCentral\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Program Files\Open Source\MeshCentral\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Program Files\Open Source\MeshCentral\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Program Files\Open Source\MeshCentral\node_modules\express\lib\router\layer.js:95:5)
    at C:\Program Files\Open Source\MeshCentral\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Program Files\Open Source\MeshCentral\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Program Files\Open Source\MeshCentral\node_modules\express\lib\router\index.js:275:10)
    at C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\webserver.js:2639:24
    at Layer.handle [as handle_request] (C:\Program Files\Open Source\MeshCentral\node_modules\express\lib\router\layer.js:95:5)`

We used before without any problem, I guess something gone wrong

Hope this helps

Cheers
Merlinweb

**Comment by Ylianst** [comment]
You are right! Thank you for reporting this. Just fixed it, it will be in the next release in a few hours.

**Comment by Ylianst** [comment]
Published MeshCentral v0.3.5-n with a fix for this, also terminal on Linux was improved.

**Comment by merlinweb** [comment]
Yeah !
Now Chat works like a charms, tested now with a couple of users

Thanks for quick fix, I close Issue

Cheers

Merlinweb
