### ISSUE TITLE
Meshcentral freequent restart - Version 0.8.29

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#2602]
Dear @Ylianst 

getting below error and server restart frequently. Please do the needful.
MC Version -0.8.29
OS - Windows server 2019
Pugin - Not active
____________________________________________________________________________________________________________________________

C:\M-ACCESS\node_modules\meshcentral\meshrelay.js:542
        obj.peer.req.query.p = req.query.p;
                 ^

TypeError: Cannot read property 'req' of undefined
    at WebSocket.<anonymous> (C:\M-ACCESS\node_modules\meshcentral\meshrelay.js:542:18)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (C:\M-ACCESS\node_modules\express-ws\node_modules\ws\lib\websocket.js:720:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (C:\M-ACCESS\node_modules\express-ws\node_modules\ws\lib\receiver.js:405:14)
    at C:\M-ACCESS\node_modules\express-ws\node_modules\ws\lib\receiver.js:371:23
    at C:\M-ACCESS\node_modules\express-ws\node_modules\ws\lib\permessage-deflate.js:307:9
    at C:\M-ACCESS\node_modules\express-ws\node_modules\ws\lib\permessage-deflate.js:389:7
    at afterWrite (internal/streams/writable.js:466:5)
    at onwrite (internal/streams/writable.js:446:7)

**Comment by VINISHVV** [comment]
@Ylianst 
Thank you. This error not showing in latest version.
