### ISSUE TITLE
Meshcentral router Stop working

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#2610]
Dear @Ylianst 

I have approximate 6000+ system connected with meshcentral. when i login to meshcentral router application it will automatically close after input my 2F auth code.

The debug file generated showing below errors.

```
UnhandledExceptionEventSink: System.ArgumentException: Error during serialization or deserialization using the JSON JavaScriptSerializer. The length of the string exceeds the value set on the maxJsonLength property.
Parameter name: input
at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(JavaScriptSerializer serializer, String input, Type type, Int32 depthLimit)
at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize[T](String input)
at MeshCentralRouter.MeshCentralServer.processServerData(String data)
at MeshCentralRouter.MeshCentralServer.xwebclient.ProcessWsBuffer(Byte[] data, Int32 offset, Int32 len, Int32 op)
at MeshCentralRouter.MeshCentralServer.xwebclient.ProcessBuffer(Byte[] buffer, Int32 offset, Int32 len)
at MeshCentralRouter.MeshCentralServer.xwebclient.OnTlsDataSink(IAsyncResult ar)
at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
at System.Net.Security._SslStream.ProcessFrameBody(Int32 readBytes, Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security._SslStream.ReadFrameCallback(AsyncProtocolRequest asyncRequest)
at System.Net.AsyncProtocolRequest.CompleteRequest(Int32 result)
at System.Net.FixedSizeReader.CheckCompletionBeforeNextRead(Int32 bytes)
at System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult)
at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Net.ContextAwareResult.Complete(IntPtr userToken)
at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
UnhandledExceptionEventSink: System.ArgumentException: Error during serialization or deserialization using the JSON JavaScriptSerializer. The length of the string exceeds the value set on the maxJsonLength property.
Parameter name: input
at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(JavaScriptSerializer serializer, String input, Type type, Int32 depthLimit)
at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize[T](String input)
at MeshCentralRouter.MeshCentralServer.processServerData(String data)
at MeshCentralRouter.MeshCentralServer.xwebclient.ProcessWsBuffer(Byte[] data, Int32 offset, Int32 len, Int32 op)
at MeshCentralRouter.MeshCentralServer.xwebclient.ProcessBuffer(Byte[] buffer, Int32 offset, Int32 len)
at MeshCentralRouter.MeshCentralServer.xwebclient.OnTlsDataSink(IAsyncResult ar)
at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
at System.Net.Security._SslStream.ProcessFrameBody(Int32 readBytes, Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security._SslStream.ReadFrameCallback(AsyncProtocolRequest asyncRequest)
at System.Net.AsyncProtocolRequest.CompleteRequest(Int32 result)
at System.Net.FixedSizeReader.CheckCompletionBeforeNextRead(Int32 bytes)
at System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult)
at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Net.ContextAwareResult.Complete(IntPtr userToken)
at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
```

**Comment by Ylianst** [comment]
Hi. I have an updated version of the [MeshCentral Router here](https://info.meshcentral.com/downloads/MeshCentral2/MeshCentralRouter.exe). It will ignore any JSON decoding errors.

In addition, if you run "MeshCentralRouter.exe -debug" it will generate a "debug.log" that will show the exact data that caused the problem. If you can send back this log, that would be great.

Thanks,
Ylian

**Comment by Ylianst** [comment]
Wow, you are fast. Looking at this now.

**Comment by Ylianst** [comment]
Ok, new version of [MeshCentral Router here](https://info.meshcentral.com/downloads/MeshCentral2/MeshCentralRouter.exe) with a fix for the error above. Can you try it and let me know if you get any more errors? Thanks.

**Comment by VINISHVV** [comment]
Dear Ylian,

Now i am not getting any errors in debug mode. But none of my systems/ nodes are showing in Meshcentral router.

**Comment by Ylianst** [comment]
Can you delete the debug.log, login once using MeshCentral Router with debug enabled and [send me the log](https://www.meshcommander.com/contact-information). My guess is that one of the computer names or other information must have a special character that MeshCentral Router is not handling right and causing the list of computers to be ignored. Or, maybe the list is just too long?

Anyway, with the debug.log, I would be able to re-create the issues.

**Comment by Ylianst** [comment]
Oh, I may know the problem... working on it now. It's clear the JSON is too big now. Working on a fix.

**Comment by VINISHVV** [comment]
Dear Ylian,

Perfect Fix !!.  Thank you.
