### ISSUE TITLE
Feedback on MeshCentral Assistant direct server connection

### ISSUE THREAD

**Issue by Ylianst** [Ylianst/MeshCentral#2624]
Just published MeshCentral v0.8.35 with an improved MeshCentral Assistant for Windows. In this version, if you have a "meshagent.msh" file in the same folder as "MeshCentralAssistant.exe", then you have the option to have MeshCentral Assistant directly connect to the server. No agent required. The connection is user initiated.

Since this is early work, there is no Desktop, Terminal or Files... you can open MeshCentral Messenger and do some agent console commands for now.

![MC2-AssistantDirectConnect](https://user-images.githubusercontent.com/1319013/117899514-23213600-b27c-11eb-981b-017d35df076a.png)

The idea would be to use this for user initiated support. I would love to get feedback on this approach. Would it be useful?

**Comment by PetieM** [comment]
I feel like this could be great for people who are squeamish about having a permanently installed remote access tool but still want to be able to receive help if needed. I haven't worked with MeshCentral Assistant at all yet though. How is the deployment process? Given that this also needs a .msh file, I'm thinking it would be a great idea to have some way to easily deploy both together.

Also, I'm not sure if I'm reading the screenshot right but if this is set up with no agent installed, does the endpoint appear in MeshCentral but offline or does it appear dynamically when the user requests help?

**Comment by Ylianst** [comment]
There is no real deployment process for MeshCentral Assistant right now, you put in on the remote machine and add it to the auto-start when users login in, but this was not automated yet.

Yes, this is certainly a very different usage. Right now, the device will show up the first time the user connects and the device will stay on the server until the user connects again. I guess you can create a device group that auto-removes offline devices and have Assistant connect to that group.

I am certainly work more on deployment in the future for this tool, probably will be in the "Add Agent" as a new option once it has desktop/files features.

**Comment by VINISHVV** [comment]
Dear Ylian,

Good starting...... I understand this is only a starting and your will implement many features beyond our imaginations.
The only problem i have noticed, placing the "meshagent.msh" file in same folder but you have not mentioned from where we can create this file.

**Comment by Ylianst** [comment]
You can get the meshagent.msh file when you install a MeshAgent, it will be with the executable. Another trick you can use is add ?debug=1 and click "Add Agent", you will see an extra link to download it.

![image](https://user-images.githubusercontent.com/1319013/118009679-1d226800-b303-11eb-88a0-e4ef40bbcb36.png)

In the future, I will make this easy, but this is an experimental feature.

**Comment by PetieM** [comment]
> Yes, this is certainly a very different usage. Right now, the device will show up the first time the user connects and the device will stay on the server until the user connects again. I guess you can create a device group that auto-removes offline devices and have Assistant connect to that group.

That's more or less how I figured this would work and I think makes sense.

> You can get the meshagent.msh file when you install a MeshAgent, it will be with the executable. Another trick you can use is add ?debug=1 and click "Add Agent", you will see an extra link to download it.

This exactly answers the primary question I brought up originally - having the ability to easily grab a .msh file to go along with this makes it much more usable, even if it is a hidden feature at the moment.

**Comment by Ylianst** [comment]
Right now, this is not an announced feature and so, experts like you can try it.... but I will add an easy way.

Another nice thing about MeshCentral Assistant is that since it's for user initiated support connections, I can safely code-sign the tool. Hopefully I will get a code signing cert soon. I will not sign the meshagent, but Assistant, Router, Installer could be signed.

**Comment by VINISHVV** [comment]
> You can get the meshagent.msh file when you install a MeshAgent, it will be with the executable. Another trick you can use is add ?debug=1 and click "Add Agent", you will see an extra link to download it.
> 
> ![image](https://user-images.githubusercontent.com/1319013/118009679-1d226800-b303-11eb-88a0-e4ef40bbcb36.png)
> 
> In the future, I will make this easy, but this is an experimental feature.

Thanks Ylian. 

I have done few testings and it's working properly. Since I am currently using meshcentral assistant in my office for our tech support. It's an amazing tool and I am awaiting for more features.

**Comment by Mfinadmin** [comment]
Dear Ylian, 

Great.......It's a good tool. 
I can understand it's only a beta /concept model you will do more supported features in upcoming days... 

If possible please activate the Desktop access in this concept version, so that we can check the main functionalities....

**Comment by AntonAndreevichMoroz** [comment]
I would like to see the chat inside the Assistant, not in the browser.  do i need to open a separate request for this?

**Comment by VINISHVV** [comment]
Dear Ylian.

Today i have noticed few issues.

in windows server 2012/2019 PC's when i run Assistant app with .Msh file i am getting below errors. If i delete my .msh file then MeshAssist will works fine.

___________________________________________________________________________________________
UnhandledExceptionEventSink: System.NullReferenceException: Object reference not set to an instance of an object.
   at MeshAssistant.MainForm..ctor(String[] args)
   at MeshAssistant.Program.Main(String[] args)
___________________________________________________________________________________________

Below Error Message is showing in Windows 7 PC's.
___________________________________________________________________________________________

UnhandledExceptionEventSink: System.MissingMethodException: Method not found: 'System.Security.Cryptography.RSA System.Security.Cryptography.RSA.Create(Int32)'.
   at MeshAssistant.MeshCentralAgent.LoadAgentCertificate()
   at MeshAssistant.MeshCentralAgent..ctor()
   at MeshAssistant.MainForm..ctor(String[] args)
   at MeshAssistant.Program.Main(String[] args)
___________________________________________________________________________________________

**Comment by Mfinadmin** [comment]
Dear Ylian, 
Latest version of Meshcentral assistant also doesn't works with the  .msh file.

**Comment by Ylianst** [comment]
It's been a lot of work over the last 5 days, but just published MeshCentral v0.8.40 with the .msh file now included within MeshCentral Assistant automatically and MeshCentral Assistant being much more capable now.

![MC2-Assistant1](https://user-images.githubusercontent.com/1319013/118747769-7ca2db00-b80f-11eb-97ef-1527f6b9e723.png)

![MC2-Assistant2](https://user-images.githubusercontent.com/1319013/118747774-7f9dcb80-b80f-11eb-98d6-50a7634dc40d.png)

![MC2-Assistant3](https://user-images.githubusercontent.com/1319013/118747850-a3611180-b80f-11eb-8f2c-a72dd6457493.png)

![MC2-Assistant4](https://user-images.githubusercontent.com/1319013/118747853-a5c36b80-b80f-11eb-99c8-f61c9217056b.png)

![MC2-Assistant5](https://user-images.githubusercontent.com/1319013/118747860-a825c580-b80f-11eb-83eb-70a276191dbd.png)

Should be much easier to use now. Feedback welcome.

**Comment by VINISHVV** [comment]
Great work @Ylianst & @krayon007 
Since our office is closed for 2 days, so we will share the feedback soon.

**Comment by Ylianst** [comment]
FYI. Just added MeshCentral Assistant to agent invitation page.

![MC2-Assistant6](https://user-images.githubusercontent.com/1319013/119066043-c0265200-b993-11eb-853c-5cfc0872d0d7.png)

**Comment by Mfinadmin** [comment]
Wow its a nice tool with lots of good features. Big thanks to Ylian & all teams behind meshcentral projects for implementing unimaginable features in this webbased tool.

I have noticed below issue (Point 1) and i have a feature request (point 2)

1) While trying to download the assistant fom Invite url i am getting a zip file insted of the executable files.
2) please implement two types of assistant application like meshagent ( background and interactive, background only ).

**Comment by VINISHVV** [comment]
Dear Ylian,

I have checked the Assistant in Windows server 2019 & 2012. In both servers the **Select Agent ( Direct connect)  ** option is not available.
