### ISSUE TITLE
MeshCentral 0.8.63~0.8.65 . [issus]  [garbled text]

### ISSUE THREAD

**Issue by Jacky0400143** [Ylianst/MeshCentral#2793]
Hello Sir, 
I just installed the system on my Raspberry Pi 4 recently.Currently in the testing phase.I have encountered some problems and would like to ask for help. 

BTW Forgive my bad English, because I am not an Native English speaker

And ,this system is really amazing, thank you very much for your Develop with heart.

I have submitted many questions separately to ISSUE,Sorry for the inconvenience.

> MeshCentral version 0.8.63~0.8.65 , all agents are up to date
Server : Raspberry Pi 4 2GB RAM , Linux raspberrypi 5.10.17-v7l+ #"1421 SMP Thu May 27 14:00:13 BST 2021 armv7l GNU/Linux

> Using Firefox 64bit 89.0 and Edge based on Chromium 64bit 91.0.864.48

Issus : 

> [garbled text]

some garbled text  in Traditional Chinese ,display like this "¥d¤ڴµ°򧋶Oª© - OK"
;

**Comment by Jacky0400143** [comment]
New Issue

> [Agent]

Sometimes the newly installed agent will not be discovered by the server after installation. The existing agent will not be affected. After restarting MC, some newly installed agents will appear, but some must be reinstalled.
The error message at that time can be seen below.
;
> [Error Logs]
-------- 2021/6/17 下午9:17:16 ---- 0.8.65 --------

ERROR: MeshCentral Intel(R) AMT server port 4433 is not available.


2021/6/17 下午9:25:40: Watchdog timer timeout, 1301ms.
2021/6/17 下午9:31:19: Watchdog timer timeout, 1082ms.
2021/6/17 下午9:35:51: Watchdog timer timeout, 1110ms.
2021/6/17 下午9:50:44: Watchdog timer timeout, 471ms.
2021/6/17 下午9:54:33: Watchdog timer timeout, 1558ms.
2021/6/17 下午10:30:05: Watchdog timer timeout, 3394ms.
2021/6/17 下午10:31:57: Watchdog timer timeout, 1117ms.
2021/6/17 下午10:32:32: Watchdog timer timeout, 2000ms.
2021/6/17 下午10:33:50: Watchdog timer timeout, 857ms.
2021/6/17 下午10:34:25: Watchdog timer timeout, 1284ms.
2021/6/18 上午9:49:30: Watchdog timer timeout, 805ms.

- After Reboot Service

-------- 2021/6/18 上午10:27:41 ---- 0.8.65 --------

/home/XX/node_modules/meshcentral/db.js:1566
        else if (parent.args.mariadb.database) { dbname = parent.args.mariadb.database; }
                                     ^

TypeError: Cannot read property 'database' of undefined
    at Object.obj.getBackupConfig (/home/XX/node_modules/meshcentral/db.js:1566:38)
    at WebSocket.processWebSocketData (/home/XX/node_modules/meshcentral/meshuser.js:1441:43)
    at WebSocket.emit (events.js:198:13)
    at Receiver.receiverOnMessage (/home/XX/node_modules/ws/lib/websocket.js:718:20)
    at Receiver.emit (events.js:198:13)
    at Receiver.dataMessage (/home/XX/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/home/XX/node_modules/ws/lib/receiver.js:346:17)
    at Receiver.startLoop (/home/XX/node_modules/ws/lib/receiver.js:133:22)
    at Receiver._write (/home/XX/node_modules/ws/lib/receiver.js:69:10)
    at doWrite (_stream_writable.js:415:12)

Many Thanks.

**Comment by VINISHVV** [comment]
@Jacky0400143 - One suggestion, Please create separate task instead of mentioning all issues in single task.
 This will helps to track the issues in better way.

**Comment by Jacky0400143** [comment]
I will correct it immediately , Thank you

**Comment by Ylianst** [comment]
Can you provide a screen shot of the garble text? Is you can provide steps to replicate the problem, that would be great. Thanks.

**Comment by Jacky0400143** [comment]
@Ylianst 
Thank you for your comment even during vacation.

> [S1] is Capture at  My Devices General.

-  [S1] ![圖片](https://user-images.githubusercontent.com/75102529/122623569-9158e400-d0d7-11eb-8d75-56c8b4af12ae.png)
- 
`<td class="style9">Windows Defender - <span style="color:red">Disabled</span><br>COMODO Antivirus - <span style="color:red">Disabled</span><br>¥d¤ڴµ°򧋶Oª© - <span style="color:green">OK</span></td>`

The Original Words in Traditional Chinese should be "卡巴斯基防毒軟體" (Kaspersky Anti-Virus)
;

> [S2] Using MeshCentral Assistant , Before 0.8.63 , It Show up garbled text in Traditional Chinese, but now in 0.8.65 works fine. Not sure what changes have been made between this, or the version has been updated and corrected?

- [S2] ![圖片](https://user-images.githubusercontent.com/75102529/122625976-dd5d5600-d0e2-11eb-9d68-913c061df65f.png)
;

>  Agent detection system version wrong

And Also I found that the Agent detection system version seems to be wrong, because most of my computers have reached Windows 10 (21H1) 19043, but MeshCentral show all of PCs are in Windows 10 2009

**Comment by Ylianst** [comment]
Ok, it does look like UTF8 is not working correctly for the anti-virus name, that is certainly a bug.

**Comment by Jacky0400143** [comment]
@Ylianst 
Similar garbled characters also appeared in the player

> ![圖片](https://user-images.githubusercontent.com/75102529/123090277-ed6a9200-d462-11eb-985d-f750ac16371a.png)

Many Thanks
