### ISSUE TITLE
Docker installation won't start (TextEncoder is not defined)

### ISSUE THREAD

**Issue by mwllgr** [Ylianst/MeshCentral#3068]
Hi, I am using typhonragewind/meshcentral and am receiving the following error on start:

```
Installing mongodb...
ERR: /opt/meshcentral/node_modules/whatwg-url/dist/encoding.js:2
const utf8Encoder = new TextEncoder();
                    ^

ReferenceError: TextEncoder is not defined
    at Object.<anonymous> (/opt/meshcentral/node_modules/whatwg-url/dist/encoding.js:2:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/opt/meshcentral/node_modules/whatwg-url/dist/url-state-machine.js:5:34)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
{ Error: Command failed: /usr/bin/node /opt/meshcentral/node_modules/meshcentral --launch 472
/opt/meshcentral/node_modules/whatwg-url/dist/encoding.js:2
const utf8Encoder = new TextEncoder();
                    ^
```

Does this have something to do with MeshCentral itself or do you suspect a issue in the image?
Also: Is there an official Docker image yet?

**Comment by Ylianst** [comment]
Do you know that version of NodeJS you are using? I can try to replicate this.

**Comment by Ylianst** [comment]
I am getting the same problem with NodeJS v10.15.1... looking into it.

**Comment by nzalev** [comment]
https://github.com/jsdom/whatwg-url/issues/195

**Comment by nzalev** [comment]
This error occurs since MongoDB (which uses whatwg-url to do its uri parsing) upgraded from 4.1.0 to 4.1.1 last week.

**Comment by nzalev** [comment]
I have put in a pull request which should fix this issue.

**Comment by Ylianst** [comment]
Thanks you @nzalev. Publishing MeshCentral v0.9.15 now with your fix.

**Comment by Ylianst** [comment]
I can confirm this fixed my server update.

**Comment by mwllgr** [comment]
Have to wait until the new image build is here. Will report back. Thanks for now, guys!

**Comment by mwllgr** [comment]
Up and running again. Thanks again!
