### ISSUE TITLE
Error installing plugin with 0.9.26: TypeError: require(...).ObjectID is not a function

### ISSUE THREAD

**Issue by CloudlySimon** [Ylianst/MeshCentral#3134]
Hello,
Running MeshCentral 0.9.26 and just attempted to install the ScriptTask plugin (among others).  They load correctly (as in appear in the plugin page), but when you attempt to install or delete, the server crashes.   Error is logged below

Running on Ubuntu 18.04, with mongodb 3.6.3 (have tried 4.4 but no luck).

This occurs when meshcentral is running under systemd or started manually from the console.

Everything else is (has been) running perfectly.

Would appreciate any suggestions.  Thanks

versions
{
    "node": "16.9.1",
    "v8": "9.3.345.16-node.12",
    "uv": "1.42.0",
    "zlib": "1.2.11",
    "brotli": "1.0.9",
    "ares": "1.17.2",
    "modules": "93",
    "nghttp2": "1.42.0",
    "napi": "8",
    "llhttp": "6.0.2",
    "openssl": "1.1.1l+quic",
    "cldr": "39.0",
    "icu": "69.1",
    "tz": "2021a",
    "unicode": "13.0",
    "ngtcp2": "0.1.0-DEV",
    "nghttp3": "0.1.0-DEV"
}

`-------- 9/14/2021, 7:57:31 PM ---- 0.9.26 --------

/home/meshcentral/node_modules/meshcentral/db.js:1504
                obj.getPlugin = function (id, func) { id = require('mongodb').ObjectID(id); obj.pluginsfile.find({ _id: id }).sort({ name: 1 }).toArray(func); }; // Get plugin
                                                                              ^

TypeError: require(...).ObjectID is not a function
    at Object.obj.getPlugin (/home/meshcentral/node_modules/meshcentral/db.js:1504:79)
    at Object.obj.removePlugin (/home/meshcentral/node_modules/meshcentral/pluginHandler.js:508:19)
    at WebSocket.processWebSocketData (/home/meshcentral/node_modules/meshcentral/meshuser.js:4917:45)
    at WebSocket.emit (events.js:198:13)
    at Receiver.receiverOnMessage (/home/meshcentral/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (events.js:198:13)
    at Receiver.dataMessage (/home/meshcentral/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/home/meshcentral/node_modules/ws/lib/receiver.js:346:17)
    at Receiver.startLoop (/home/meshcentral/node_modules/ws/lib/receiver.js:133:22)
    at Receiver._write (/home/meshcentral/node_modules/ws/lib/receiver.js:69:10)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Receiver.Writable.write (_stream_writable.js:299:11)
    at TLSSocket.socketOnData (/home/meshcentral/node_modules/ws/lib/websocket.js:795:35)
    at TLSSocket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)`

**Comment by ryanblenis** [comment]
I've submitted a pull request to fix this issue. #3143 

Once the fix is approved and there is a new version number, I'll also be pushing new plugins project updates for compatibility with the new dependencies.
