### ISSUE TITLE
Error install plugins for database version 5.0.3 Mongodb

### ISSUE THREAD

**Issue by sistemmsn** [Ylianst/MeshCentral#3148]
When I try to install a plugin in the meshcentral it tends to stop

MongoDB server version: 5.0.3

MeshCentral v0.7.89, LAN mode.
WARNING: SMTP server has limited use in LAN mode.
Server has no users, next new account will be site administrator.
MeshCentral HTTPS server running on port 443.
SMTP mail server smtp.gmail.com working as expected.
ERR: /opt/meshcentral/node_modules/meshcentral/db.js:1361
                obj.getPlugin = function (id, func) { id = require('mongodb').ObjectID(id); obj.pluginsfile.find({ _id: id }).sort({ name: 1 }).toArray(func); }; // Get plugin
                                                                              ^

TypeError: require(...).ObjectID is not a function
    at Object.obj.getPlugin (/opt/meshcentral/node_modules/meshcentral/db.js:1361:79)
    at Object.obj.installPlugin (/opt/meshcentral/node_modules/meshcentral/pluginHandler.js:356:19)
    at WebSocket.processWebSocketData (/opt/meshcentral/node_modules/meshcentral/meshuser.js:5189:45)
    at WebSocket.emit (node:events:394:28)
    at Receiver.receiverOnMessage (/opt/meshcentral/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (node:events:394:28)
    at Receiver.dataMessage (/opt/meshcentral/node_modules/ws/lib/receiver.js:414:14)
    at /opt/meshcentral/node_modules/ws/lib/receiver.js:371:23
    at /opt/meshcentral/node_modules/ws/lib/permessage-deflate.js:307:9
    at /opt/meshcentral/node_modules/ws/lib/permessage-deflate.js:389:7
ERROR: Unable to write to mesherrors.txt.
Error: Command failed: /usr/bin/node /opt/meshcentral/node_modules/meshcentral --launch 34467
/opt/meshcentral/node_modules/meshcentral/db.js:1361
                obj.getPlugin = function (id, func) { id = require('mongodb').ObjectID(id); obj.pluginsfile.find({ _id: id }).sort({ name: 1 }).toArray(func); }; // Get plugin
                                                                              ^

TypeError: require(...).ObjectID is not a function
    at Object.obj.getPlugin (/opt/meshcentral/node_modules/meshcentral/db.js:1361:79)
    at Object.obj.installPlugin (/opt/meshcentral/node_modules/meshcentral/pluginHandler.js:356:19)
    at WebSocket.processWebSocketData (/opt/meshcentral/node_modules/meshcentral/meshuser.js:5189:45)
    at WebSocket.emit (node:events:394:28)
    at Receiver.receiverOnMessage (/opt/meshcentral/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (node:events:394:28)
    at Receiver.dataMessage (/opt/meshcentral/node_modules/ws/lib/receiver.js:414:14)
    at /opt/meshcentral/node_modules/ws/lib/receiver.js:371:23
    at /opt/meshcentral/node_modules/ws/lib/permessage-deflate.js:307:9
    at /opt/meshcentral/node_modules/ws/lib/permessage-deflate.js:389:7

    at ChildProcess.exithandler (node:child_process:397:12)
    at ChildProcess.emit (node:events:406:35)
    at maybeClose (node:internal/child_process:1064:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:394:28)
    at Pipe.<anonymous> (node:net:672:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: '/usr/bin/node /opt/meshcentral/node_modules/meshcentral --launch 34467'
}

**Comment by Ylianst** [comment]
@ryanblenis has a fix for this, #3143. I am on vacation until October 6th, but will accept and publish this fix as soon as I get back.

**Comment by si458** [comment]
should all be fixed
please update to latest version 1.1.20, and use node 18 or above, try again,
if issue still persists, please let us know
