### ISSUE TITLE
npm install meshcentral not working

### ISSUE THREAD

**Issue by radha402** [Ylianst/MeshCentral#3209]
ubnt@ubnt:~$ npm install meshcentral
loadDep:underscore → requ ▐ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine mkdirp@1.0.4: wanted: {"node":">=10"} (current: {"node":"8.10.0","np                                                                                                             npm ERR! Linux 4.15.0-159-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "meshcentral"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-meta                                                                                                             data.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package                                                                                                             -metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.                                                                                                             js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-packag                                                                                                             e-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package                                                                                                             -metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fe                                                                                                             tch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at                                                                                                             :
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubnt/npm-debug.log
ubnt@ubnt:~$ node -version
node: bad option: -version
ubnt@ubnt:~$ node -v
v8.10.0
ubnt@ubnt:~$ npm -v
3.5.2
ubnt@ubnt:~$

**Comment by Ylianst** [comment]
You are currently using NodeJS 8.10.0, however MeshCentral requires NodeJS 10.0.0 at a minimum. You can see the error here:

```
wanted: {"node":">=10"} (current: {"node":"8.10.0","np npm ERR! Linux 4.15.0-159-generic
```

Update to NodeJS 10.0.0 or higher and try again.
