### ISSUE TITLE
Recently, Desktop/terminal connects to black screen only. Server is running: 0.9.64 (Latest)

### ISSUE THREAD

**Issue by itsmedakshesh** [Ylianst/MeshCentral#3416]
When I hit connect - it does not connect to screen instead shows black screen. Screenshot is as below:

![Screenshot_68](https://user-images.githubusercontent.com/78626086/148435882-75a5f4a1-64fb-4b51-aecb-dba40949d16b.png)

**Comment by itsmedakshesh** [comment]
I found the following error ( Sorry just noticed)

-------- 1/6/2022, 8:08:29 PM ---- 0.9.64 --------

internal/validators.js:124
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null
    at validateString (internal/validators.js:124:11)
    at Object.basename (path.js:1281:5)
    at render (/home/pmasters/node_modules/meshcentral/webserver.js:7541:56)
    at dbGetFunc (/home/pmasters/node_modules/meshcentral/webserver.js:2744:17)
    at /home/pmasters/node_modules/meshcentral/db.js:1539:29
    at /home/pmasters/node_modules/mongodb/lib/utils.js:530:9
    at /home/pmasters/node_modules/mongodb/lib/cursor/abstract_cursor.js:244:32
    at /home/pmasters/node_modules/mongodb/lib/cursor/abstract_cursor.js:484:55
    at /home/pmasters/node_modules/mongodb/lib/utils.js:530:9
    at /home/pmasters/node_modules/mongodb/lib/sessions.js:136:24 {
  code: 'ERR_INVALID_ARG_TYPE'
}


-------- 1/6/2022, 8:08:34 PM ---- 0.9.64 --------

internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module '/home/pmasters/node_modules/meshcentral/meshcentral'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}


-------- 1/6/2022, 8:08:39 PM ---- 0.9.64 --------

internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module '/home/pmasters/node_modules/meshcentral/meshcentral'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}


-------- 1/6/2022, 8:08:44 PM ---- 0.9.64 --------

internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module '/home/pmasters/node_modules/meshcentral/meshcentral'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}


-------- 1/6/2022, 8:08:49 PM ---- 0.9.64 --------

internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module '/home/pmasters/node_modules/meshcentral/meshcentral'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by nzalev** [comment]
```
Error: Cannot find module '/home/pmasters/node_modules/meshcentral/meshcentral'
```
It looks like the server is running from the wrong location. Generally, it should be `.../installdir/node_modules/meshcentral`, not `.../node_modules/meshcentral/meshcentral/`.

I'm not sure at first glance if that's a red herring or not, though.

**Comment by Ylianst** [comment]
100% agree. Go to your install directory and run MeshCentral like this:

```
node node_modules/meshcentral
```

It's tempting to enter the `node_modules` folder to run MeshCentral, but you should not do that.

**Comment by itsmedakshesh** [comment]
Hello all,

I did very the issue and yes, I must agree that it was one of the reason that my MeshCentral was not running from the correct path which I resolved but the issue did remain as it is. 

Later, I found that one of our tools, we have AV installed which was blocking the outbound connection. We resolved this issue.

Thank you everyone for trying to help and me direct me in the right direction. 

Please consider this issue as resolved.

@Ylianst @nzalev
