### ISSUE TITLE
BUG: meshctrl.js list device with group and filter with csv flag

### ISSUE THREAD

**Issue by kpetrow** [Ylianst/MeshCentral#3491]
any two out of three combinations(group,filter,csv) seem to work but not all three.
Command:
`NODE meshctrl.js ListDevices --url wss://MYSERVER.com:444 --loginuser admin --loginpass LuggageCombo --filter atag:14-61 --group site27 --csv`

Hangs for a bit then throws this:
   ```
console.log('\"' + settings.xmeshes[i]._id.split('/')[2] + '\",\"' + settings.xmeshes[i].name.split('\"').join('') + '\",\"' + n._id.split('/')[2] + '\",\"' + n.name.split('\"').join('') + '\",' + (n.icon ? n.icon : 0) + ',' + (n.conn ? n.conn : 0) + ',' + (n.pwr ? n.pwr : 0));
                                                                       ^

TypeError: Cannot read properties of undefined (reading 'mesh//@fyHbzS4556465464ieeoGSTP45646546545ic@ypH8fRs03iL6yndVD$T03fVWHo50pCTFo')
    at WebSocket.incoming (C:\inetpub\stable\utilities\mesh_central\meshctrl.js:2031:72)
←[90m    at WebSocket.emit (node:events:390:28)←[39m
    at Receiver.ontext (C:\Windows\System32\config\systemprofile\AppData\Roaming\npm\node_modules\←[4mws←[24m\lib\WebSocket.js:841:10)
    at C:\Windows\System32\config\systemprofile\AppData\Roaming\npm\node_modules\←[4mws←[24m\lib\Receiver.js:536:18
    at Receiver.applyExtensions (C:\Windows\System32\config\systemprofile\AppData\Roaming\npm\node_modules\←[4mws←[24m\lib\Receiver.js:371:5)
    at C:\Windows\System32\config\systemprofile\AppData\Roaming\npm\node_modules\←[4mws←[24m\lib\Receiver.js:508:14
    at Receiver.flush (C:\Windows\System32\config\systemprofile\AppData\Roaming\npm\node_modules\←[4mws←[24m\lib\Receiver.js:347:3)
    at Receiver.finish (C:\Windows\System32\config\systemprofile\AppData\Roaming\npm\node_modules\←[4mws←[24m\lib\Receiver.js:541:12)
    at Receiver.expectHandler (C:\Windows\System32\config\systemprofile\AppData\Roaming\npm\node_modules\←[4mws←[24m\lib\Receiver.js:499:31)
    at Receiver.add (C:\Windows\System32\config\systemprofile\AppData\Roaming\npm\node_modules\←[4mws←[24m\lib\Receiver.js:103:24)
```

Thanks!

**Comment by JSuenram** [comment]
Just tested with build 0.9.72 and can confirm that with filter and group and cdv used together it fails with error:

`root@MESH:/etc/meshcentral#  node ./node_modules/meshcentral/meshctrl.js listdevices --loginkeyfile key.txt --loginuser bilbo --filter tag:Client --group "Staff Users" --csv
/etc/meshcentral/node_modules/meshcentral/meshctrl.js:2051
                                    console.log('\"' + settings.xmeshes[i]._id.split('/')[2] + '\",\"' + settings.xmeshes[i].name.split('\"').join('') + '\",\"' + n._id.split('/')[2] + '\",\"' + n.name.split('\"').join('') + '\",' + (n.icon ? n.icon : 0) + ',' + (n.conn ? n.conn : 0) + ',' + (n.pwr ? n.pwr : 0));
                                                                       ^

TypeError: Cannot read property 'mesh//g32HuuB6oTCFBEJSdXQXU9$57SXUrH2uKbvMJY1nyhk8jnt9CiH30C0hDAgD7P4E' of undefined
    at WebSocket.incoming (/etc/meshcentral/node_modules/meshcentral/meshctrl.js:2051:72)
    at WebSocket.emit (events.js:314:20)
    at Receiver.receiverOnMessage (/etc/meshcentral/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (events.js:314:20)
    at Receiver.dataMessage (/etc/meshcentral/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/etc/meshcentral/node_modules/ws/lib/receiver.js:346:17)
    at Receiver.startLoop (/etc/meshcentral/node_modules/ws/lib/receiver.js:133:22)
    at Receiver._write (/etc/meshcentral/node_modules/ws/lib/receiver.js:69:10)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
`

**Comment by Ylianst** [comment]
I get the same problem, working on it now!

**Comment by Ylianst** [comment]
Just pushed a fix for this in GItHub, will be in MeshCentral v0.9.73 or you can [download latest meshctrl.js here](https://github.com/Ylianst/MeshCentral/blob/master/meshctrl.js).

**Comment by JSuenram** [comment]
Maybe there is an additional issue?

root@MESH:/etc/meshcentral# node ./node_modules/meshcentral/meshctrl.js listdevices --loginkeyfile key.txt --loginuser J.Suenram --filter tag:Client

Device group: "*removed name for security*"
id, name, icon, conn, pwr
-------------------------
/etc/meshcentral/node_modules/meshcentral/meshctrl.js:2096
                                        console.log('\"' + n._id.split('/')[2] + '\", \"' + n.name.split('\"').join('') + '\", ' + (n.icon ? n.icon : 0) + ', ' + (n.conn ? n.conn : 0) + ', ' + (n.pwr ? n.pwr : 0));
                                                                 ^

TypeError: Cannot read property 'split' of undefined
    at WebSocket.incoming (/etc/meshcentral/node_modules/meshcentral/meshctrl.js:2096:66)
    at WebSocket.emit (events.js:314:20)
    at Receiver.receiverOnMessage (/etc/meshcentral/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (events.js:314:20)
    at Receiver.dataMessage (/etc/meshcentral/node_modules/ws/lib/receiver.js:414:14)
    at /etc/meshcentral/node_modules/ws/lib/receiver.js:371:23
    at /etc/meshcentral/node_modules/ws/lib/permessage-deflate.js:307:9
    at /etc/meshcentral/node_modules/ws/lib/permessage-deflate.js:389:7
    at afterWrite (_stream_writable.js:490:5)
    at onwrite (_stream_writable.js:470:7)

**Comment by universumsolution** [comment]
I'm not sure if this is along the same line but I'm getting a similar error just listing devices. 

/opt/node_modules/meshcentral/meshctrl.js:2171
                                    if (settings.xmeshes) { console.log('\r\nDevice group: \"' + settings.xmeshes[i].name.split('\"').join('') + '\"'); }
                                                                                                                     ^

TypeError: Cannot read property 'name' of undefined
    at WebSocket.incoming (/opt/node_modules/meshcentral/meshctrl.js:2171:118)
    at WebSocket.emit (events.js:375:28)
    at Receiver.receiverOnMessage (/opt/node_modules/meshcentral/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (events.js:375:28)
    at Receiver.dataMessage (/opt/node_modules/meshcentral/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/opt/node_modules/meshcentral/node_modules/ws/lib/receiver.js:346:17)
    at Receiver.startLoop (/opt/node_modules/meshcentral/node_modules/ws/lib/receiver.js:133:22)
    at Receiver._write (/opt/node_modules/meshcentral/node_modules/ws/lib/receiver.js:69:10)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Receiver.Writable.write (internal/streams/writable.js:303:10)

for context I'm on the latest server version 1.1.5

**Comment by si458** [comment]
closing as stale,
please try the latest version 1.1.22 and use node 18 or above,
if issue persists, please reply back
