### ISSUE TITLE
PostgreSQL syntax error in User Traffic Usage report

### ISSUE THREAD

**Issue by NiceGuyIT** [Ylianst/MeshCentral#3585]
The User Traffic Usage report does not run because a PostgreSQLl error is emitted.

Here is the stack trace from the console logged in `journalctl`.
```text
Feb 02 08:48:27 ns-v18-tactical node[8562]: SELECT doc FROM events WHERE ((domain = ?) AND (time BETWEEN ? AND ?)) ORDER BY time [ '', 2022-01-26T13:48:27.000Z, 2022-02-02T13:48:27.000Z ] error: syntax error at or near ")"
Feb 02 08:48:27 ns-v18-tactical node[8562]:     at Parser.parseErrorMessage (/meshcentral/node_modules/pg-protocol/dist/parser.js:287:98)
Feb 02 08:48:27 ns-v18-tactical node[8562]:     at Parser.handlePacket (/meshcentral/node_modules/pg-protocol/dist/parser.js:126:29)
Feb 02 08:48:27 ns-v18-tactical node[8562]:     at Parser.parse (/meshcentral/node_modules/pg-protocol/dist/parser.js:39:38)
Feb 02 08:48:27 ns-v18-tactical node[8562]:     at Socket.<anonymous> (/meshcentral/node_modules/pg-protocol/dist/index.js:11:42)
Feb 02 08:48:27 ns-v18-tactical node[8562]:     at Socket.emit (events.js:400:28)
Feb 02 08:48:27 ns-v18-tactical node[8562]:     at addChunk (internal/streams/readable.js:293:12)
Feb 02 08:48:27 ns-v18-tactical node[8562]:     at readableAddChunk (internal/streams/readable.js:267:9)
Feb 02 08:48:27 ns-v18-tactical node[8562]:     at Socket.Readable.push (internal/streams/readable.js:206:10)
Feb 02 08:48:27 ns-v18-tactical node[8562]:     at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
Feb 02 08:48:27 ns-v18-tactical node[8562]:   length: 90,
Feb 02 08:48:27 ns-v18-tactical node[8562]:   severity: 'ERROR',
Feb 02 08:48:27 ns-v18-tactical node[8562]:   code: '42601',
Feb 02 08:48:27 ns-v18-tactical node[8562]:   detail: undefined,
Feb 02 08:48:27 ns-v18-tactical node[8562]:   hint: undefined,
Feb 02 08:48:27 ns-v18-tactical node[8562]:   position: '42',
Feb 02 08:48:27 ns-v18-tactical node[8562]:   internalPosition: undefined,
Feb 02 08:48:27 ns-v18-tactical node[8562]:   internalQuery: undefined,
Feb 02 08:48:27 ns-v18-tactical node[8562]:   where: undefined,
Feb 02 08:48:27 ns-v18-tactical node[8562]:   schema: undefined,
Feb 02 08:48:27 ns-v18-tactical node[8562]:   table: undefined,
Feb 02 08:48:27 ns-v18-tactical node[8562]:   column: undefined,
Feb 02 08:48:27 ns-v18-tactical node[8562]:   dataType: undefined,
Feb 02 08:48:27 ns-v18-tactical node[8562]:   constraint: undefined,
Feb 02 08:48:27 ns-v18-tactical node[8562]:   file: 'scan.l',
Feb 02 08:48:27 ns-v18-tactical node[8562]:   line: '1176',
Feb 02 08:48:27 ns-v18-tactical node[8562]:   routine: 'scanner_yyerror'
Feb 02 08:48:27 ns-v18-tactical node[8562]: }
```

Here is the error thrown by postgres.
```text
2022-02-02 08:38:58.448 EST [8093] hrvnqxbj@meshcentral ERROR:  syntax error at or near ")" at character 71
2022-02-02 08:38:58.448 EST [8093] hrvnqxbj@meshcentral STATEMENT:  SELECT doc FROM events WHERE ((domain = $1) AND (time BETWEEN $2 AND ?)) ORDER BY time
```

Here is the WS log in the console after enabling trace.
```text
meshcentral.js:59:47
{
  "action": "report",
  "type": 2,
  "groupBy": 1,
  "start": 1643204338,
  "end": 1643809138,
  "tz": "America/New_York",
  "tf": 300,
  "l": "en-US",
  "devGroup": null,
  "showTraffic": false
}
```

The third parameter is a `?` instead of `$3`. Changing it to `$3` works. This is line [1433 in db.js](https://github.com/Ylianst/MeshCentral/blob/master/db.js#L1433).

```JavaScript
            obj.GetEventsTimeRange = function (ids, domain, msgids, start, end, func) {
                if (ids.indexOf('*') >= 0) {
                    sqlDbQuery('SELECT doc FROM events WHERE ((domain = $1) AND (time BETWEEN $2 AND $3)) ORDER BY time', [domain, start, end], func);
                } else {
                    sqlDbQuery('SELECT doc FROM events JOIN eventids ON id = fkid WHERE ((domain = $1) AND (target = ANY ($2)) AND (time BETWEEN $3 AND $4)) GROUP BY id ORDER BY time', [domain, ids, start, end], func);
                }
            };
```

I'm running MeshCentral v0.9.73 which is not the absolute latest. The current line in `db.js` uses `?`'s instead of `$1`, but that did not work on my system.

**Comment by Ylianst** [comment]
Thanks for reporting this. I put in the fix in GitHub and will be in the next release.
