### ISSUE TITLE
Handle database errors gracefully

### ISSUE THREAD

**Issue by NiceGuyIT** [Ylianst/MeshCentral#3645]
I'm using PostgreSQL with MeshCentral and ran into an instance where the database died bringing down MeshCentral with it. It would be nice if MeshCentral handles errors gracefully.

It looks like there are two separate problems. First, the initial failure which caused MeshCentral to restart (did it really restart?) and the subsequent connect failed. The second is when starting and the database is not available, MeshCentral will not retry the connection to the database. In the instance below, MeshCentral started first, failed to connect to Posgres, and then Postgres was started. Even though Postgres is available a few seconds after MeshCentral is started, MeshCentral is not doing anything and does not try to reconnect.

I like Gitea's approach to this. The `gitea` process stays running and tries to reconnect to the database indefinitely while serving HTTP 500 errors to all clients. Once the database is available, `gitea` connects and makes their services available.

MeshCentral version: 0.9.79

`cat /etc/os-release`
```text
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

`apt-cache policy postgresql`
```text
postgresql:
  Installed: (none)
  Candidate: 14+238.pgdg20.04+1
  Version table:
     14+238.pgdg20.04+1 500
        500 https://apt.postgresql.org/pub/repos/apt focal-pgdg/main amd64 Packages
     12+214ubuntu0.1 500
        500 http://mirror.math.princeton.edu/pub/ubuntu focal-updates/main amd64 Packages
        500 http://mirror.math.princeton.edu/pub/ubuntu focal-security/main amd64 Packages
     12+214 500
        500 http://mirror.math.princeton.edu/pub/ubuntu focal/main amd64 Packages
```

Postgres log showing the error.
```text
2022-02-13 21:49:21.380 EST [14392] efftqfln@tacticalrmm LOG:  duration: 597.389 ms  statement: UPDATE "agents_agent" SET "last_seen" = '2022-02-14T02:49:20.773342+00:00'::timestamptz WHERE "agents_agent"."id" = 2
2022-02-13 21:51:36.724 EST [281] ERROR:  could not open file "pg_wal/0000000100000000000000A3": Permission denied
2022-02-13 21:53:21.843 EST [14481] efftqfln@tacticalrmm LOG:  duration: 46.719 ms  statement: UPDATE "agents_agent" SET "last_seen" = '2022-02-14T02:53:21.786364+00:00'::timestamptz WHERE "agents_agent"."id" = 2
2022-02-13 21:56:40.489 EST [281] ERROR:  could not open file "pg_wal/0000000100000000000000A3": Permission denied
2022-02-13 21:58:39.108 EST [1118] efftqfln@tacticalrmm PANIC:  could not open file "pg_wal/0000000100000000000000A3": Permission denied
2022-02-13 21:58:39.114 EST [234] LOG:  server process (PID 1118) was terminated by signal 6: Aborted
2022-02-13 21:58:39.114 EST [234] DETAIL:  Failed process was running: 
                                                UPDATE agents_agent SET services=$1 WHERE agents_agent.agent_id=$2;
2022-02-13 21:58:39.114 EST [234] LOG:  terminating any other active server processes
2022-02-13 21:58:39.114 EST [312] efftqfln@tacticalrmm WARNING:  terminating connection because of crash of another server process
2022-02-13 21:58:39.114 EST [312] efftqfln@tacticalrmm DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2022-02-13 21:58:39.114 EST [312] efftqfln@tacticalrmm HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2022-02-13 21:58:39.114 EST [312] efftqfln@tacticalrmm STATEMENT:  
                                                UPDATE agents_agent SET services=$1 WHERE agents_agent.agent_id=$2;
2022-02-13 21:58:39.116 EST [365] hrvnqxbj@meshcentral WARNING:  terminating connection because of crash of another server process
2022-02-13 21:58:39.116 EST [365] hrvnqxbj@meshcentral DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2022-02-13 21:58:39.116 EST [365] hrvnqxbj@meshcentral HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2022-02-13 21:58:39.116 EST [284] WARNING:  terminating connection because of crash of another server process
2022-02-13 21:58:39.116 EST [284] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2022-02-13 21:58:39.116 EST [284] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2022-02-13 21:58:39.119 EST [14588] efftqfln@tacticalrmm FATAL:  the database system is in recovery mode
2022-02-13 21:58:39.122 EST [234] LOG:  all server processes terminated; reinitializing
2022-02-13 21:58:39.157 EST [14589] LOG:  database system was interrupted; last known up at 2022-02-13 21:56:40 EST
2022-02-13 21:58:39.574 EST [14589] LOG:  database system was not properly shut down; automatic recovery in progress
2022-02-13 21:58:39.600 EST [14589] LOG:  redo starts at 0/A2FEAD98
2022-02-13 21:58:39.627 EST [14589] LOG:  redo done at 0/A2FFFF38
2022-02-13 21:58:39.804 EST [14589] FATAL:  could not open file "pg_wal/0000000100000000000000A3": Permission denied
2022-02-13 21:58:39.807 EST [234] LOG:  startup process (PID 14589) exited with exit code 1
2022-02-13 21:58:39.807 EST [234] LOG:  aborting startup due to startup process failure
```

MeshCentral logs during the error.
```text
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]: ERR: events.js:377
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]:       throw er; // Unhandled 'error' event
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]:       ^
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]: Error: Connection terminated unexpectedly
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]:     at Connection.<anonymous> (/meshcentral/node_modules/pg/lib/client.js:132:73)
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]:     at Object.onceWrapper (events.js:519:28)
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]:     at Connection.emit (events.js:400:28)
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]:     at Socket.<anonymous> (/meshcentral/node_modules/pg/lib/connection.js:107:12)
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]:     at Socket.emit (events.js:412:35)
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]:     at endReadableNT (internal/streams/readable.js:1334:12)
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]:     at processTicksAndRejections (internal/process/task_queues.js:82:21)
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]: Emitted 'error' event on Client instance at:
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]:     at Client._handleErrorEvent (/meshcentral/node_modules/pg/lib/client.js:319:10)
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]:     at Connection.<anonymous> (/meshcentral/node_modules/pg/lib/client.js:149:16)
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]:     at Object.onceWrapper (events.js:519:28)
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]:     [... lines matching original stack trace ...]
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]:     at processTicksAndRejections (internal/process/task_queues.js:82:21)
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]: Error: Command failed: /usr/bin/node /meshcentral/node_modules/meshcentral --launch 224
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]: events.js:377
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]:       throw er; // Unhandled 'error' event
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]:       ^
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]: Error: Connection terminated unexpectedly
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]:     at Connection.<anonymous> (/meshcentral/node_modules/pg/lib/client.js:132:73)
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]:     at Object.onceWrapper (events.js:519:28)
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]:     at Connection.emit (events.js:400:28)
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]:     at Socket.<anonymous> (/meshcentral/node_modules/pg/lib/connection.js:107:12)
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]:     at Socket.emit (events.js:412:35)
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]:     at endReadableNT (internal/streams/readable.js:1334:12)
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]:     at processTicksAndRejections (internal/process/task_queues.js:82:21)
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]: Emitted 'error' event on Client instance at:
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]:     at Client._handleErrorEvent (/meshcentral/node_modules/pg/lib/client.js:319:10)
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]:     at Connection.<anonymous> (/meshcentral/node_modules/pg/lib/client.js:149:16)
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]:     at Object.onceWrapper (events.js:519:28)
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]:     [... lines matching original stack trace ...]
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]:     at processTicksAndRejections (internal/process/task_queues.js:82:21)
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]:     at ChildProcess.exithandler (child_process.js:383:12)
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]:     at ChildProcess.emit (events.js:412:35)
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]:     at maybeClose (internal/child_process.js:1058:16)
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]:     at Socket.<anonymous> (internal/child_process.js:443:11)
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]:     at Socket.emit (events.js:400:28)
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]:     at Pipe.<anonymous> (net.js:686:12) {
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]:   killed: false,
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]:   code: 1,
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]:   signal: null,
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]:   cmd: '/usr/bin/node /meshcentral/node_modules/meshcentral --launch 224'
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]: }
Feb 13 21:58:39 ns-v18-tactical meshcentral[224]: ERROR: MeshCentral failed with critical error, check mesherrors.txt. Restarting in 5 seconds...
Feb 13 21:58:45 ns-v18-tactical meshcentral[224]: ERR: (node:14593) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:5432
Feb 13 21:58:45 ns-v18-tactical meshcentral[224]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
Feb 13 21:58:45 ns-v18-tactical meshcentral[224]: (Use `node --trace-warnings ...` to show where the warning was created)
Feb 13 21:58:45 ns-v18-tactical meshcentral[224]: ERR: (node:14593) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

After a reboot, the database was not available causing MeshCentral to fail the initial connection, but without persistent retries, it never initializes.
```text
-- Reboot --
Feb 13 23:02:14 ns-v18-tactical meshcentral[136]: ERR: (node:168) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:5432
Feb 13 23:02:14 ns-v18-tactical meshcentral[136]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
Feb 13 23:02:14 ns-v18-tactical meshcentral[136]: (Use `node --trace-warnings ...` to show where the warning was created)
Feb 13 23:02:14 ns-v18-tactical meshcentral[136]: ERR: (node:168) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
Feb 13 23:02:14 ns-v18-tactical meshcentral[136]: (node:168) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Feb 13 23:02:14 ns-v18-tactical meshcentral[136]: (node:168) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:5432
Feb 13 23:02:14 ns-v18-tactical meshcentral[136]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
Feb 13 23:02:14 ns-v18-tactical meshcentral[136]: (node:168) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
Feb 13 23:02:14 ns-v18-tactical meshcentral[136]: SELECT doc FROM main WHERE id = $1 [ 'DatabaseIdentifier' ] Error: Connection terminated unexpectedly
Feb 13 23:02:14 ns-v18-tactical meshcentral[136]:     at Connection.<anonymous> (/meshcentral/node_modules/pg/lib/client.js:132:73)
Feb 13 23:02:14 ns-v18-tactical meshcentral[136]:     at Object.onceWrapper (events.js:519:28)
Feb 13 23:02:14 ns-v18-tactical meshcentral[136]:     at Connection.emit (events.js:400:28)
Feb 13 23:02:14 ns-v18-tactical meshcentral[136]:     at Socket.<anonymous> (/meshcentral/node_modules/pg/lib/connection.js:57:12)
Feb 13 23:02:14 ns-v18-tactical meshcentral[136]:     at Socket.emit (events.js:400:28)
Feb 13 23:02:14 ns-v18-tactical meshcentral[136]:     at TCP.<anonymous> (net.js:686:12)
Feb 13 23:02:14 ns-v18-tactical meshcentral[136]: SELECT doc FROM main WHERE id = $1 [ 'SchemaVersion' ] Error: Connection terminated unexpectedly
Feb 13 23:02:14 ns-v18-tactical meshcentral[136]:     at Connection.<anonymous> (/meshcentral/node_modules/pg/lib/client.js:132:73)
Feb 13 23:02:14 ns-v18-tactical meshcentral[136]:     at Object.onceWrapper (events.js:519:28)
Feb 13 23:02:14 ns-v18-tactical meshcentral[136]:     at Connection.emit (events.js:400:28)
Feb 13 23:02:14 ns-v18-tactical meshcentral[136]:     at Socket.<anonymous> (/meshcentral/node_modules/pg/lib/connection.js:57:12)
Feb 13 23:02:14 ns-v18-tactical meshcentral[136]:     at Socket.emit (events.js:400:28)
Feb 13 23:02:14 ns-v18-tactical meshcentral[136]:     at TCP.<anonymous> (net.js:686:12)
```

`systemctl status --full meshcentral.service`
```text
● meshcentral.service - MeshCentral Server
     Loaded: loaded (/etc/systemd/system/meshcentral.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2022-02-13 23:02:12 EST; 14h ago
   Main PID: 136 (node)
     CGroup: /system.slice/meshcentral.service
             ├─136 /usr/bin/node node_modules/meshcentral
             └─168 /usr/bin/node /meshcentral/node_modules/meshcentral --launch 136

Feb 13 23:02:14 ns-v18-tactical meshcentral[136]:     at Socket.<anonymous> (/meshcentral/node_modules/pg/lib/connection.js:57:12)
Feb 13 23:02:14 ns-v18-tactical meshcentral[136]:     at Socket.emit (events.js:400:28)
Feb 13 23:02:14 ns-v18-tactical meshcentral[136]:     at TCP.<anonymous> (net.js:686:12)
Feb 13 23:02:14 ns-v18-tactical meshcentral[136]: SELECT doc FROM main WHERE id = $1 [ 'SchemaVersion' ] Error: Connection terminated unexpectedly
Feb 13 23:02:14 ns-v18-tactical meshcentral[136]:     at Connection.<anonymous> (/meshcentral/node_modules/pg/lib/client.js:132:73)
Feb 13 23:02:14 ns-v18-tactical meshcentral[136]:     at Object.onceWrapper (events.js:519:28)
Feb 13 23:02:14 ns-v18-tactical meshcentral[136]:     at Connection.emit (events.js:400:28)
Feb 13 23:02:14 ns-v18-tactical meshcentral[136]:     at Socket.<anonymous> (/meshcentral/node_modules/pg/lib/connection.js:57:12)
Feb 13 23:02:14 ns-v18-tactical meshcentral[136]:     at Socket.emit (events.js:400:28)
Feb 13 23:02:14 ns-v18-tactical meshcentral[136]:     at TCP.<anonymous> (net.js:686:12)
```

`systemctl status --full postgresql.service`
```text
● postgresql.service - PostgreSQL RDBMS
     Loaded: loaded (/lib/systemd/system/postgresql.service; enabled; vendor preset: enabled)
     Active: active (exited) since Sun 2022-02-13 23:02:13 EST; 14h ago
    Process: 160 ExecStart=/bin/true (code=exited, status=0/SUCCESS)
   Main PID: 160 (code=exited, status=0/SUCCESS)

Feb 13 23:02:13 ns-v18-tactical systemd[1]: Starting PostgreSQL RDBMS...
Feb 13 23:02:13 ns-v18-tactical systemd[1]: Finished PostgreSQL RDBMS.
```

**Comment by jsastriawan** [comment]
Not sure if throwing error 500 is helpful either. Database is a critical element of Meshcentral and there is no point continuing running Meshcentral if it cannot serve its purpose.

**Comment by Ylianst** [comment]
In MeshCentral v1 a long time ago, I would retry a query 3 times and if it failed, I would put the server on "hold" until the database came back online. This was pretty much required for running on MSSQL at the time.

This request makes sense to me. I need an artificial way to make PostgreSQL cause an error to I can test graceful handling... maybe I can just shutdown the DB and launch it back up after a few seconds.

**Comment by NiceGuyIT** [comment]
Would it make sense to use an ORM considering MeshCentral supports multiple database backends? If the ORM handles the database connection and queries, then the disconnected database and retry logic should work for all database types supported. I've worked with [TypeORM](https://github.com/typeorm/typeorm) because it provides typescript support with ESM. MeshCentral isn't TypeScript and uses CJS (I think, haven't looked closely), so TypeORM is just an example. If MeshCentral supports neDB, then [waterline](https://github.com/balderdashy/waterline) may work (although neDB is mentioned in their GitHub page it is not listed as an available database adapter in the docs.)
