### ISSUE TITLE
Server Crash / Node Error

### ISSUE THREAD

**Issue by PetieM** [Ylianst/MeshCentral#3653]
It seems that at some point overnight, my server crashed and isn't coming back up. The following is shown when attempting to restart it:

```
SQLERR5 Error: Cannot find module 'promise'
Require stack:
- /home/meshcentral/server/node_modules/meshcentral/pluginHandler.js
- /home/meshcentral/server/node_modules/meshcentral/meshcentral.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/meshcentral/server/node_modules/meshcentral/pluginHandler.js:16:1)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /home/meshcentral/server/node_modules/meshcentral/meshcentral.js:1418:37
    at /home/meshcentral/server/node_modules/meshcentral/db.js:1358:246
    at Query.<anonymous> (/home/meshcentral/server/node_modules/meshcentral/db.js:1108:39)
    at Query.<anonymous> (/home/meshcentral/server/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/home/meshcentral/server/node_modules/mysql/lib/Connection.js:488:16) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/meshcentral/server/node_modules/meshcentral/pluginHandler.js',
    '/home/meshcentral/server/node_modules/meshcentral/meshcentral.js'
  ]
}
```

Please let me know if you need anything else from my end. Thanks!

**Comment by JSuenram** [comment]
Can you please run Meshcentral from Command-Line with DEBUG enabled?
 "node node_modules/meshcentral --debug"
 from the MC-Install-Folder should do this.
Please post the output then.
What version is your MeshCentral?

**Comment by PetieM** [comment]
Basically the same output with the addition of two DB lines (and one line I accidentally deleted from the previous output):
```DB: Checking tables...
DB: Checking indexes...
SQLERR5 Error: Cannot find module 'promise'
```

Not sure of the version as I can't open it  to check but I believe it's current.

**Comment by JSuenram** [comment]
Had the same this morning:
SQLERR5 Error: Cannot find module 'promise'

Fix is easy... .one moment... will update... just getting the command I ran....

**Comment by Ylianst** [comment]
Thank you @JSuenram for handling this! Much appreciated. I did just put in a fix for this. The promise module was only needed for very old versions of NodeJS. Now that we require NodeJV v10 or above, promise support is built-in and no need for this module anymore. v0.9.84 will have the fix for this.
