### ISSUE TITLE
Meshcentral 0.9.83 crashes on load

### ISSUE THREAD

**Issue by routerino** [Ylianst/MeshCentral#3657]
Hi, 

I have noticed when I start up the latest build of meshcentral via [https://github.com/GuruComputing/meshcentral-docker](https://github.com/GuruComputing/meshcentral-docker), it crashes on load. Some notes about this crashing:

* It does *not* happen on a fresh run with no existing configuration. This suggests it's a problem with the plugins that get loaded at runtime.
* This problem does not happen with version 0.9.81 or stable (0.9.52)

```log
---- Starting Meshcentral ----
Installing archiver@4.0.2...
Installing passport...
Installing passport-saml...
Installing mongodb@4.1.0...
Installing saslprep...
Installing semver...
Installing nodemailer...
Installing otplib@10.2.3...
ERR: node:internal/modules/cjs/loader:936
  throw err;
  ^
Error: Cannot find module 'promise'
Require stack:
- /meshcentral/node_modules/meshcentral/pluginHandler.js
- /meshcentral/node_modules/meshcentral/meshcentral.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/meshcentral/node_modules/meshcentral/pluginHandler.js:16:1)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/meshcentral/node_modules/meshcentral/pluginHandler.js',
    '/meshcentral/node_modules/meshcentral/meshcentral.js'
  ]
}
Node.js v17.5.0
Error: Command failed: /usr/local/bin/node /meshcentral/node_modules/meshcentral/meshcentral.js --launch 9
node:internal/modules/cjs/loader:936
  throw err;
  ^
Error: Cannot find module 'promise'
Require stack:
- /meshcentral/node_modules/meshcentral/pluginHandler.js
- /meshcentral/node_modules/meshcentral/meshcentral.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/meshcentral/node_modules/meshcentral/pluginHandler.js:16:1)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/meshcentral/node_modules/meshcentral/pluginHandler.js',
    '/meshcentral/node_modules/meshcentral/meshcentral.js'
  ]
}
Node.js v17.5.0
    at ChildProcess.exithandler (node:child_process:399:12)
    at ChildProcess.emit (node:events:538:35)
    at maybeClose (node:internal/child_process:1090:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:526:28)
    at Pipe.<anonymous> (node:net:687:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: '/usr/local/bin/node /meshcentral/node_modules/meshcentral/meshcentral.js --launch 9'
}
ERROR: MeshCentral failed with critical error, check mesherrors.txt. Restarting in 5 seconds...
```

Sanitized configuration below:

Configuration:
```json
{
  "settings": {
    "Cert": "mesh.<meshcentral-domain>.com.au",
    "MongoDb": "mongodb://meshcentral-db:27017/meshcentral",
    "SessionKey": "<Session Key>",
    "DbEncryptKey": "<DB Encrypt Key>",
    "Port": 443,
    "agentPort": 8800,
    "TrustedProxy": "172.16.1.250",
    "WebRTC": false,
    "SelfUpdate": false,
    "_MeshErrorLogPath": "/meshcentral",
    "AllowHighQualityDesktop": true,
    "plugins": {
    	"enabled": true
    },
    "_Redirects": {
      "meshcommander": "https://www.meshcommander.com/"
    }
  },
  "domains": {
    "": {
      "Title": "<Company>",
      "Title2": "Remote Server",
      "_TitlePicture": "title-sample.png",
      "NewAccounts": false,
      "_NewAccountsRights": [ "nonewgroups", "notools" ],
      "Footer": "<Company>",
      "passwordRequirements": {
        "force2factor": true
      },
      "authStrategies": {
        "saml": {
          "callbackurl": "https://mesh.<meshcentral-domain>.com.au/auth-saml-callback",
          "entityid": "meshcentral",
          "idpurl": "https://auth.<meshcentral-domain>.com.au/auth/realms/master/protocol/saml",
          "cert": "keycloak.pem"
        }
      }
    }
  },
  "smtp": {
    "host": "smtp-relay.gmail.com",
    "port": 465,
    "from": "meshcentral@<meshcentral-domain>.com.au",
    "tls": true
  }
}

```

An identical deployment with no `config.json` runs fine, as does a minimal config with the mongodb database:
```
---- Detected File Permission Mismatch ----
---- Forcing File Permissions to the node user ----
---- No config.json file detected. Creating based on Environment Variables ----
---- Starting Meshcentral ----
Installing archiver@4.0.2...
Installing otplib@10.2.3...
MeshCentral HTTP redirection server running on port 80.
MeshCentral v0.9.83, Hybrid (LAN + WAN) mode.
MeshCentral Intel(R) AMT server running on mesh.gurucomputing.com.au:4433.
Server has no users, next new account will be site administrator.
MeshCentral HTTPS server running on mesh.gurucomputing.com.au:443.
```

**Comment by routerino** [comment]
As an update, after some additional testing, meshcentral seems to take exception (hah!) to the following configuration:

```
"plugins": {
    	"enabled": true
    },
```

Removing the plugins subsection fixes the issue.

**Comment by Ylianst** [comment]
This is a duplicate of #3653, I will have a fix for this in v0.9.84 that I will release in a few minutes.

**Comment by Ylianst** [comment]
Fixed in v0.9.84 that was released.

**Comment by JSuenram** [comment]
@routerino can you please verify and close?
This has been fixed.

**Comment by routerino** [comment]
I had taken out the plugins directive earlier, but I stuck it in just to test and appears fine in 0.9.84.
