### ISSUE TITLE
crashes on load

### ISSUE THREAD

**Issue by wutaijieing** [Ylianst/MeshCentral#3684]
-------- Mon Feb 21 2022 19:03:58 GMT+0800 (CST) ---- 0.9.84 --------

internal/encoding.js:468
          throw new ERR_NO_ICU('"fatal" option');
          ^

TypeError [ERR_NO_ICU]: "fatal" option is not supported on Node.js compiled without ICU
    at new NodeError (internal/errors.js:322:7)
    at new TextDecoder (internal/encoding.js:468:17)
    at Object.<anonymous> (/tmp/npmm/node_modules/cbor/lib/utils.js:21:14)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/tmp/npmm/node_modules/cbor/lib/commented.js:5:15) {
  code: 'ERR_NO_ICU'
}

**Comment by wutaijieing** [comment]
These problems have now been sorted，system icu compile to  nodejs 
![system icu](https://user-images.githubusercontent.com/41360380/154974166-fc62a89e-d544-40e0-8ea8-cd8ef2d12520.png)

**Comment by Ylianst** [comment]
Ok, I will close. This does not seem to be MeshCentral related and I am not familiar with this.
