### ISSUE TITLE
Feature Request: Choose Assistant version type for Assistant invites

### ISSUE THREAD

**Issue by Brodur** [Ylianst/MeshCentral#3718]
When using the add agent dialogue, you can specify which version to use. Ideally for invite links, emails, and codes you should also have a mechanism for this.
![image](https://user-images.githubusercontent.com/49418324/155913479-5522dd41-7a47-4f50-b267-a80a514a6c1e.png)

Failing that, I would like a way to specify the default version of assistant that gets shipped with an invite, as right now by default it is the system tray app which is not conducive to use as a one-off remote support tool as users may be confused or unclear on how to find the application running in the system tray after launching it. I'd prefer the application (always connected) be the default, as it does require user consent before a session can be started.

**Comment by KBCACheia** [comment]
Good idea, any news about it?

**Comment by svewa** [comment]
Came to make the same issue, good to see it's already open :-)
For an assistant situation I also can only see the application/always connected as desirable..

**Comment by si458** [comment]
just thinking outloud,
would an option under `domains` like `assistantTypeInvite` and setting it to say `0,1,2,3,4` be ok?
each number would link to the different types,
then when set for that domain, all invite links will add th extra bit to download that type of assistant?

**Comment by Brodur** [comment]
> just thinking outloud, would an option under `domains` like `assistantTypeInvite` and setting it to say `0,1,2,3,4` be ok? each number would link to the different types, then when set to a certain number for that domain, all invite agent links will add the extra bit to download that type of assistant?

So long as the solution is documented, good enough for me!

**Comment by si458** [comment]
PR done! only 2 years late, lets not rush this now...

`assistantTypeAgentInvite` must be integer, and default is 0, can be set PER DOMAIN
0 = System Tray, Connect on user request
1 = System Tray, Always Connected
2 = Application, Connect on user request
3 = Application, Always connected
4 = System Tray, Monitor Only

**Comment by Brodur** [comment]
> PR done! only 2 years late, lets not rush this now...
> 
> `assistantTypeAgentInvite` must be integer, and default is 0 (left as 0 for backwards compatibility), can be set PER DOMAIN 0 = System Tray, Connect on user request 1 = System Tray, Always Connected 2 = Application, Connect on user request 3 = Application, Always connected 4 = System Tray, Monitor Only

Good day. I'm testing this out now and I'm not seeing the expected results. The agent seems to still default to the system tray application when I specify the following in the config:

```
  "domains": {
        "": {
                "agentInviteCodes": true,
                "assistantTypeAgentInvite": 3
        }
  },
```

Am I missing something in the formatting? I'd expect this config to yield the Application, Always Connected.

**Comment by si458** [comment]
have you updated to the latest release 1.1.18?

**Comment by Brodur** [comment]
Yes, I verified server version 1.1.18 before testing. I used the inbuilt upgrade as I'm running on the typhonragewind/meshcentral docker image and that doesn't seem to be at release 1.1.18 yet.

Unsure on relevance, but I'll include this anyway - I did have an error occur during the upgrade, looks to be with node mailer.
```
-------- 1/14/2024, 3:58:45 PM ---- 1.1.18 --------

node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module 'nodemailer'
Require stack:
- /opt/meshcentral/node_modules/meshcentral/meshmail.js
- /opt/meshcentral/node_modules/meshcentral/meshcentral.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at module.exports.CreateMeshMail (/opt/meshcentral/node_modules/meshcentral/meshmail.js:53:32)
    at RandomBytesJob.<anonymous> (/opt/meshcentral/node_modules/meshcentral/meshcentral.js:1766:67)
    at RandomBytesJob.<anonymous> (node:internal/crypto/random:113:5)
    at RandomBytesJob.onJobDone (node:internal/crypto/random:308:3) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/meshcentral/node_modules/meshcentral/meshmail.js',
    '/opt/meshcentral/node_modules/meshcentral/meshcentral.js'
  ]
}

Node.js v20.11.0
```

**Comment by si458** [comment]
yes we are aware the built-in upgrade might break!
try the official docker image https://github.com/Ylianst/MeshCentral/pkgs/container/meshcentral
in theory its a like for like - `ghcr.io/ylianst/meshcentral:1.1.18`

**Comment by Brodur** [comment]
> yes we are aware the built-in upgrade might break! try the official docker image https://github.com/Ylianst/MeshCentral/pkgs/container/meshcentral in theory its a like for like - `ghcr.io/ylianst/meshcentral:1.1.18` **ALSO NOTE: NEVER USE THE WEB-UPGRADE IN DOCKER AS IT WILL DEFO BREAK!** **im going to do a PR to warn users if they are using docker to NOT use this option!**

I wasn't aware there was an official docker, nice! Updated my compose to use that - no change in behaviour observed though unfortunately. I also confirmed my config is loading - I see the line when I "Show server configuration."
Sidenote - I've had the upgrades work in the past on docker, they just never persist past a container restart as one would expect.

**Comment by si458** [comment]
if you check the url on the agentinvite page for the assistant link, 
does it include `&ac=NUMBER` at the end of it or does the link not include it at all?
if is not including it at all, you must be on an old version still or maybe the page needs a CTRL+F5 or private mode
if it does but its the wrong number then its something else

**Comment by Brodur** [comment]
The download link for the agent does appear to have the &ac=3 appended to the end. For a sanity test, I tried downloading the assistant agent from the add agent pane, and I think I may see an issue there - that download does not have the expected behavior either. When selecting application always connected there, I instead receive the system tray application.

**Comment by si458** [comment]
fuck! i know what ive done wrong 
i implemented a fix for it always running in direct connect mode when you asked for monitor only https://github.com/Ylianst/MeshCentral/pull/5693
i have a feeling this had fucked up the ac= option now, as its not right when u download it from the web ui now rather than the agentinvite!

**Comment by si458** [comment]
just pushed the fix for you! https://github.com/Ylianst/MeshCentral/commit/0b0f2999db123fe48e43d2449beed676006407f1
i commited the wrong line in the original PR, it was a late night!
so you can either patch the `webserver.js` manually 
OR
wait for a new release
OR
try the `master` docker image
(this gets built every time we push a commit to the master branch so you can test new featres/bug fixes)

**Comment by Brodur** [comment]
I'm fine with waiting, thanks for the fix! I'll give it another whirl when the next release hits.

**Comment by si458** [comment]
the latest `master` image has been built if you wanted to try that,
it has the fix included AND get clipboard over the web-rdp haha

**Comment by Brodur** [comment]
Confirmed working as intended on 1.1.20

**Comment by silversword411** [comment]
https://github.com/Ylianst/MeshCentral/pull/5788

**Comment by demkr** [comment]
I think there is a bug. In my configuration it is set as:

"agentInviteCodes": true,
"assistantTypeAgentInvite": 3,

Which is 3 = Application, Always connected

When I send MeshCentral Assistant Invite using Invitation type as Link Invitation then I download correct Assistant type that is desktop standaalone application which is automatically connected when double clicked.

When I send MeshCentral Assistant Invite using Invitation type as Email invitation then MeshCentral Assistant type is 0 therefore 0= System Tray, Connect on user request. 

I thing that "assistantTypeAgentInvite" field should apply for both Invite type options.

**Comment by si458** [comment]
@demkr open a new enhancement issue with the request and we look into it for you
