### ISSUE TITLE
MeshCentral critical error after closing Web-RDP

### ISSUE THREAD

**Issue by jvwag** [Ylianst/MeshCentral#3719]
After closing a Web-RDP screen in the browser the MeshCentral server dies.

Running: docker image digest (019f536ef1f5e004540db7a19a4a1cce1f5518dfe656a745e32b5fca52d4176c), tag: latest, version 0.9.91

Remote RDP connection was to updated Windows 10 device.

```
ERR: {"name":"node-rdpjs","hostname":"ed915f133c59","pid":77,"level":40,"msg":"undefined","time":"2022-02-28T08:29:59.802Z","v":0}
ERR: /opt/meshcentral/node_modules/meshcentral/apprelays.js:65
            const username = (user != null) ? user.name : null;e
                                                               ^

ReferenceError: e is not defined
    at Object.obj.close (/opt/meshcentral/node_modules/meshcentral/apprelays.js:65:64)
    at WebSocket.<anonymous> (/opt/meshcentral/node_modules/meshcentral/apprelays.js:251:104)
    at WebSocket.emit (events.js:203:15)
    at WebSocket.emitClose (/opt/meshcentral/node_modules/ws/lib/websocket.js:172:10)
    at Socket.socketOnClose (/opt/meshcentral/node_modules/ws/lib/websocket.js:781:15)
    at Socket.emit (events.js:198:13)
    at TCP._handle.close (net.js:607:12)
{ Error: Command failed: /usr/bin/node /opt/meshcentral/node_modules/meshcentral --launch 7
{"name":"node-rdpjs","hostname":"ed915f133c59","pid":77,"level":40,"msg":"undefined","time":"2022-02-28T08:29:59.802Z","v":0}
/opt/meshcentral/node_modules/meshcentral/apprelays.js:65
            const username = (user != null) ? user.name : null;e
                                                               ^

ReferenceError: e is not defined
    at Object.obj.close (/opt/meshcentral/node_modules/meshcentral/apprelays.js:65:64)
    at WebSocket.<anonymous> (/opt/meshcentral/node_modules/meshcentral/apprelays.js:251:104)
    at WebSocket.emit (events.js:203:15)
    at WebSocket.emitClose (/opt/meshcentral/node_modules/ws/lib/websocket.js:172:10)
    at Socket.socketOnClose (/opt/meshcentral/node_modules/ws/lib/websocket.js:781:15)
    at Socket.emit (events.js:198:13)
    at TCP._handle.close (net.js:607:12)

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:203:15)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:607:12)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   '/usr/bin/node /opt/meshcentral/node_modules/meshcentral --launch 7' }
ERROR: MeshCentral failed with critical error, check mesherrors.txt. Restarting in 5 seconds...
```

**Comment by Ylianst** [comment]
Oh dear! Thanks for reporting, will fix right away!

**Comment by Ylianst** [comment]
Just put in a fix for this, will be in MeshCentral v0.9.92.

**Comment by jvwag** [comment]
🥇 

Thank you, I will validate when a new docker image is available!

**Comment by Ylianst** [comment]
MeshCentral v0.9.92 is out with the fix for this.

**Comment by Ylianst** [comment]
Any feedback? Can this be closed?

**Comment by jvwag** [comment]
Hi Ylian,

I would love to give feedback, but I don't have enough time to build the Docker image. I'm relying on the `typhonragewind/meshcentral` docker repository, but this was not updated since v0.9.91. I will give the docker author a ping.

Keep this ticket open if you want a confirmation on this issue, or close if you love your tickets metrics ;)

Thanks again for the quick response!
