### ISSUE TITLE
MeshCentral on AWS Instance crashing as of 3/9/2022 12:40AM(EST)

### ISSUE THREAD

**Issue by southeasterntech** [Ylianst/MeshCentral#3748]
As of 3/9/2022, the MeshCentral service on our AWS instance has begun crashing.  (AutoUpdate is on).    It crashes and restarts every 10 seconds.  This is displayed in the mesherrors.txt.  Any idea how to troubleshoot this?  Is this a result of a recent update?  Disk is not full and is at 61% of 8GB.  

Any help appreciated.

-------- 3/9/2022, 12:51:22 AM ---- 0.9.96 --------

/home/ec2-user/node_modules/meshcentral/meshagent.js:2098
            if (domain.meshAgentBinaries[10005]) {
                                        ^

TypeError: Cannot read properties of undefined (reading '10005')
    at compareAgentBinaryHash (/home/ec2-user/node_modules/meshcentral/meshagent.js:2098:41)
    at WebSocket.<anonymous> (/home/ec2-user/node_modules/meshcentral/meshagent.js:272:47)
    at WebSocket.emit (node:events:390:28)
    at Receiver.receiverOnMessage (/home/ec2-user/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (node:events:390:28)
    at Receiver.dataMessage (/home/ec2-user/node_modules/ws/lib/receiver.js:405:14)
    at Receiver.getData (/home/ec2-user/node_modules/ws/lib/receiver.js:346:17)
    at Receiver.startLoop (/home/ec2-user/node_modules/ws/lib/receiver.js:133:22)
    at Receiver._write (/home/ec2-user/node_modules/ws/lib/receiver.js:69:10)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Receiver.Writable.write (node:internal/streams/writable:334:10)
    at TLSSocket.socketOnData (/home/ec2-user/node_modules/ws/lib/websocket.js:795:35)
    at TLSSocket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)

-------- 3/9/2022, 12:51:32 AM ---- 0.9.96 --------

/home/ec2-user/node_modules/meshcentral/meshagent.js:2098
            if (domain.meshAgentBinaries[10005]) {
                                        ^

TypeError: Cannot read properties of undefined (reading '10005')
    at compareAgentBinaryHash (/home/ec2-user/node_modules/meshcentral/meshagent.js:2098:41)
    at WebSocket.<anonymous> (/home/ec2-user/node_modules/meshcentral/meshagent.js:272:47)
    at WebSocket.emit (node:events:390:28)
    at Receiver.receiverOnMessage (/home/ec2-user/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (node:events:390:28)
    at Receiver.dataMessage (/home/ec2-user/node_modules/ws/lib/receiver.js:405:14)
    at Receiver.getData (/home/ec2-user/node_modules/ws/lib/receiver.js:346:17)
    at Receiver.startLoop (/home/ec2-user/node_modules/ws/lib/receiver.js:133:22)
    at Receiver._write (/home/ec2-user/node_modules/ws/lib/receiver.js:69:10)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Receiver.Writable.write (node:internal/streams/writable:334:10)
    at TLSSocket.socketOnData (/home/ec2-user/node_modules/ws/lib/websocket.js:795:35)
    at TLSSocket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)

**Comment by southeasterntech** [comment]
Followup:
Tried reinstalling MC by deleting node_modules and running "npm install meshcentral" and still getting the same above error after starting the server.  It just cycles up and down every 10 seconds.  I suppose going to try installing a new version of node next?

**Comment by southeasterntech** [comment]
Running node v16.13.2
running MC 0.9.96

I suspected that the latest version of MC in node had some bug.  So I previously deleted the node_modules folder and then reinstalled via "npm install meshcentral" which then presumably downloaded a new "node_modules" and the latest version of MC.  

This failed with the same error.  

I have another working MC server on AWS, that is working.  (Both have self update enabled).  I downloaded a copy of the node_modules\meshcentral folder and uploaded it to the crashing server.  Set self update = false,  all appeared to work, then after about 3-4 minutes it crashed again with the same error.  

Is this a node problem? 

Thanks..

**Comment by southeasterntech** [comment]
@krayon007 @Ylianst Seems there is an issue with line 2098 in meshagent.js.  Is this a bad agent problem, or something in the latest update that breaks this?

**Comment by Ylianst** [comment]
Working on this now!!

**Comment by Ylianst** [comment]
This is high priority, as soon as I fix it, I will have a release out.

**Comment by Ylianst** [comment]
New version will be out in a few minutes.

**Comment by southeasterntech** [comment]
do you need to see my config.json?  I have 2 MC servers, running the same version of MC on AWS, both with different configs... this one crashes, the other does not.  The only differences are the config.json is different and the version of node on the non-crashing server is 14.7.6  Crashing server is 16.13.2, and they have different agents connecting

**Comment by Ylianst** [comment]
MeshCentral v0.9.97 is out with the fix. The problem only occurred on servers with MacOS agents connecting. Update and let me know if it works.

**Comment by southeasterntech** [comment]
Ahh!!  makes sense, why the other doesn't crash.  No MacOSX agents...
--Confirmed fixed!--
Been up and running without issue for about 10 mins.  Thank you good sir.  Amazing service, try getting that kind of service anywhere else.

**Comment by Ylianst** [comment]
Thanks. Yes, I am pretty confident that would fix it. Should be fine now. Thanks for reporting back.

**Comment by jimbolimbo13** [comment]
Thanks for the quick fix! Just wanted to confirm another case. I was seeing the same error, and one of my agents runs MacOS. 
`npm install meshcentral` got me the latest version and it's working again!
