### ISSUE TITLE
User duplicate login LDAP

### ISSUE THREAD

**Issue by informaticavera** [Ylianst/MeshCentral#3811]
Hi, we use meshcentral with ldap authentication.

I think by changing the password in the ldap I now have 2 users in meshcentral.

```
# node node_modules/meshcentral/meshcentral.js --listuserids
Starting meshcentral syslog.
Starting meshcentral-json JSON syslog.
Starting meshcentral-auth auth syslog.
user//admin
user//Antonio Miguel Ramos Flores
user//Antonio Miguel Ramos Flores Flores
```

I thought that by logging in as admin I could delete the duplicate user but when I try to reset the password of the admin user I get this error:

```
# node node_modules/meshcentral/meshcentral.js --resetaccount "admin" --pass 123456
Starting meshcentral syslog.
Starting meshcentral-json JSON syslog.
Starting meshcentral-auth auth syslog.
ERR: /home/antram/node_modules/meshcentral/meshcentral.js:850
                            delete user.phone; delete user.otpekey; delete user.otpsecret; delete user.otpkeys; delete user.otphkeys; delete user2.otpdev; delete user2.otpsms; // Disable 2FA
                                                                                                                                      ^

ReferenceError: user2 is not defined
    at /home/antram/node_modules/meshcentral/meshcentral.js:850:135
    at /home/antram/node_modules/meshcentral/db.js:1577:29
    at wrapper (/home/antram/node_modules/mongodb/lib/utils.js:530:9)
    at next (/home/antram/node_modules/mongodb/lib/cursor/abstract_cursor.js:244:32)
    at cleanupCursor (/home/antram/node_modules/mongodb/lib/cursor/abstract_cursor.js:484:55)
    at wrapper (/home/antram/node_modules/mongodb/lib/utils.js:530:9)
    at utils_1.maybePromise.done (/home/antram/node_modules/mongodb/lib/sessions.js:136:24)
    at Object.maybePromise (/home/antram/node_modules/mongodb/lib/utils.js:516:5)
    at ClientSession.endSession (/home/antram/node_modules/mongodb/lib/sessions.js:133:24)
    at cleanupCursor (/home/antram/node_modules/mongodb/lib/cursor/abstract_cursor.js:530:32)
ERROR: Unable to write to mesherrors.txt.
{ Error: Command failed: /usr/bin/node /home/antram/node_modules/meshcentral/meshcentral.js --resetaccount admin --pass 123456 --launch 5390
/home/antram/node_modules/meshcentral/meshcentral.js:850
                            delete user.phone; delete user.otpekey; delete user.otpsecret; delete user.otpkeys; delete user.otphkeys; delete user2.otpdev; delete user2.otpsms; // Disable 2FA
                                                                                                                                      ^

ReferenceError: user2 is not defined
    at /home/antram/node_modules/meshcentral/meshcentral.js:850:135
    at /home/antram/node_modules/meshcentral/db.js:1577:29
    at wrapper (/home/antram/node_modules/mongodb/lib/utils.js:530:9)
    at next (/home/antram/node_modules/mongodb/lib/cursor/abstract_cursor.js:244:32)
    at cleanupCursor (/home/antram/node_modules/mongodb/lib/cursor/abstract_cursor.js:484:55)
    at wrapper (/home/antram/node_modules/mongodb/lib/utils.js:530:9)
    at utils_1.maybePromise.done (/home/antram/node_modules/mongodb/lib/sessions.js:136:24)
    at Object.maybePromise (/home/antram/node_modules/mongodb/lib/utils.js:516:5)
    at ClientSession.endSession (/home/antram/node_modules/mongodb/lib/sessions.js:133:24)
    at cleanupCursor (/home/antram/node_modules/mongodb/lib/cursor/abstract_cursor.js:530:32)

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:203:15)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   '/usr/bin/node /home/antram/node_modules/meshcentral/meshcentral.js --resetaccount admin --pass 123456 --launch 5390' }
```

I also can't make the duplicate user admin because I don't understand how to use the command.

```
# node node_modules/meshcentral/meshcentral.js --adminaccount "user//Antonio Miguel Ramos Flores Flores" --domain "vera.es"
Starting meshcentral syslog.
Starting meshcentral-json JSON syslog.
Starting meshcentral-auth auth syslog.
Invalid userid, usage: --adminaccount [username] --domain (domain)
```

thanks in advance and congratulations on the project

**Comment by Ylianst** [comment]
Oh dear. User identifiers should not have spaces in them. If I understand correctly, you setup LDAP using the user's real name as the user identifier, I don't think that would work. Also, you want to use as a unique identifier something that does not change when the user change's it's name.

In the config.json, use the "ldapUserKey" to select a unique identifier like a account GUID. This way, you user id will look like: "user//xxx-xxxx-xxx" or something like that.

For account removal, what database are you using? If it's NeDB, stop the server, edit "meshcentral-data\meshcentral.db" and find the account lines and remove them. Make sure to backup the file first.

I am looking at the code now for this "user2" exception.

**Comment by informaticavera** [comment]
Thanks Ylianst, I use mongodb. Can I connect to the database and modify the usernames to match the value of "ldapUserKey" ? would this work?
