### ISSUE TITLE
Can't download MeshAgent installer after upgrading to 1.0.9

### ISSUE THREAD

**Issue by PathfinderNetworks** [Ylianst/MeshCentral#3884]
I just updated to 1.0.9 from 1.0.5.  Right after the update I tried to download an agent installer by clicking the Add Agent button like I normally would.  The Add Mesh Agent selection popup appears as expected. However, when you click the link for either the 32bit or 64bit installer the popup disappears and then nothing happens.  If you click the copy Agent link URL to clipboard and then paste that link in to a browser you see this error.  My MeshCentral server is installed at C:\Program Files\MeshCentral on Server 2022. 

```
TypeError: Assignment to constant variable.
    at Object.CreateMeshCentralServer.obj.decodeCookie (c:\Program Files\MeshCentral\node_modules\meshcentral\meshcentral.js:3107:28)
    at obj.handleMeshAgentRequest (c:\Program Files\MeshCentral\node_modules\meshcentral\webserver.js:4953:45)
    at Layer.handle [as handle_request] (c:\Program Files\MeshCentral\node_modules\express\lib\router\layer.js:95:5)
    at next (c:\Program Files\MeshCentral\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (c:\Program Files\MeshCentral\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (c:\Program Files\MeshCentral\node_modules\express\lib\router\layer.js:95:5)
    at c:\Program Files\MeshCentral\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (c:\Program Files\MeshCentral\node_modules\express\lib\router\index.js:335:12)
    at next (c:\Program Files\MeshCentral\node_modules\express\lib\router\index.js:275:10)
    at c:\Program Files\MeshCentral\node_modules\meshcentral\webserver.js:5863:20
    at Layer.handle [as handle_request] (c:\Program Files\MeshCentral\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (c:\Program Files\MeshCentral\node_modules\express\lib\router\index.js:317:13)
    at c:\Program Files\MeshCentral\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (c:\Program Files\MeshCentral\node_modules\express\lib\router\index.js:335:12)
    at next (c:\Program Files\MeshCentral\node_modules\express\lib\router\index.js:275:10)
    at _cookieSession (c:\Program Files\MeshCentral\node_modules\meshcentral\node_modules\cookie-session\index.js:126:5)
```

**Comment by Ylianst** [comment]
Working on it now!

**Comment by Ylianst** [comment]
Fix will be released in a few minutes...

**Comment by Ylianst** [comment]
v1.0.10 is out with a fix for this. Thank you for reporting it!

**Comment by PathfinderNetworks** [comment]
Thank you Ylian, I just updated to 1.0.10 and this issue is resolved. Thanks for the very speedy response!
