### ISSUE TITLE
MeshRouter not connecting

### ISSUE THREAD

**Issue by rowds15** [Ylianst/MeshCentral#4005]
Hi Not sure if it's just me, but I'm unable to get MeshCentralRouter to connect.
I'm just getting Unable to Connect on MeshCentralRouter. I don't know what logs I need to look at.

Tested on 2 different computer with 2 different Administrator Accounts

Running Version 1.0.23 no plugins

**Comment by Ylianst** [comment]
Try adding this line in the "settings" section of the config.json file:

```
"CookieIpCheck": "none"
```

Let me know if that fixes it.

**Comment by Ylianst** [comment]
Are you using standard port 443? Can you connect using a browser on the same computer? You can run MeshCentral with -debug like this:

```
MeshCentralRouter.exe -debug
```

This will generate a log file. Once done, send the file over and maybe we can see what is going on.

**Comment by rowds15** [comment]
Running on Standard port 443. Nginx reverse proxy TLS1.2. yes I can get the the site using Firefox, & Chrome.

below the debug log.

Connect-wss://xxxxxxx.xxx/control.ashx
12:54:PM.7348: WebSocket: Websocket TCP connected, doing TLS...
12:54:PM.7726: WebSocket: Websocket TLS failed: System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The function requested is not supported
   --- End of inner exception stack trace ---
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at MeshCentralRouter.webSocketClient.OnTlsSetupSink(IAsyncResult ar)

**Comment by rowds15** [comment]
I've tried Windows 7, Windows 10 20H2, 21H1, as mentioned i can successfully use the same MeshCentralRouter and connect to meshcentral.com server and also another meshcentral server on my own internal network running the same version of meshcentral server
