### ISSUE TITLE
RDP to alternative port crash the server

### ISSUE THREAD

**Issue by smartekIT** [Ylianst/MeshCentral#4022]
Hi,
we have a windows server 2008 R2 which accepts RDP connections on port 29010.
So in meshcentral we right clicked the RDP button or the Web-RDP link and we set the alternative port to 29010

now when we click RDP connect or Web-RDP then the whole Meshcentral Server crash. and here is the log:

<pre>
-------- 5/20/2022, 12:21:19 PM ---- 1.0.24 --------

node:events:505
      throw er; // Unhandled 'error' event
      ^

-------- 5/20/2022, 12:21:19 PM ---- 1.0.24 --------

ProtocolError: Failure code:2 (see https://msdn.microsoft.com/en-us/library/cc240507.aspx)
    at new ProtocolError (/home/node/meshcentral/node_modules/meshcentral/rdp/core/error.js:40:8)
    at Client.recvConnectionConfirm (/home/node/meshcentral/node_modules/meshcentral/rdp/protocol/x224.js:221:9)
    at TPKT.<anonymous> (/home/node/meshcentral/node_modules/meshcentral/rdp/protocol/x224.js:202:8)
    at Object.onceWrapper (node:events:642:26)
    at TPKT.emit (node:events:527:28)
    at TPKT.recvData (/home/node/meshcentral/node_modules/meshcentral/rdp/protocol/tpkt.js:109:7)
    at BufferLayer.<anonymous> (/home/node/meshcentral/node_modules/meshcentral/rdp/protocol/tpkt.js:100:8)
    at Object.onceWrapper (node:events:642:26)
    at BufferLayer.emit (node:events:527:28)
    at BufferLayer.recv (/home/node/meshcentral/node_modules/meshcentral/rdp/core/layer.js:105:8)
    at Socket.<anonymous> (/home/node/meshcentral/node_modules/meshcentral/rdp/core/layer.js:41:9)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
Emitted 'error' event on Client instance at:
    at Client.<anonymous> (/home/node/meshcentral/node_modules/meshcentral/rdp/protocol/pdu/cliprdr.js:42:12)
    at Client.emit (node:events:539:35)
    at Client.<anonymous> (/home/node/meshcentral/node_modules/meshcentral/rdp/protocol/t125/mcs.js:168:8)
    at Client.emit (node:events:527:28)
    at TPKT.<anonymous> (/home/node/meshcentral/node_modules/meshcentral/rdp/protocol/x224.js:151:8)
    at TPKT.emit (node:events:527:28)
    at BufferLayer.<anonymous> (/home/node/meshcentral/node_modules/meshcentral/rdp/protocol/tpkt.js:49:8)
    at BufferLayer.emit (node:events:527:28)
    at Socket.<anonymous> (/home/node/meshcentral/node_modules/meshcentral/rdp/core/layer.js:45:9)
    at Socket.emit (node:events:527:28)
    [... lines matching original stack trace ...]
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  code: 'NODE_RDP_PROTOCOL_X224_NEG_FAILURE'
}

Node.js v17.8.0

</pre>

in the remote machine the default RDP port is changed in the registry:
HKLM\System\CurrentControlSet\Control\TerminalServer\WinStations\RDP-Tcp\PortNumber
value: 29010

using normal windows remote desktop to connect to that machine on port 29010 works fine.

**Comment by Ylianst** [comment]
The key is this `NODE_RDP_PROTOCOL_X224_NEG_FAILURE`. I need to handle this error better but in any case, there have been reports that MeshCentral's RDP client can't connect to Windows Server. I still need to figure out why this is.

**Comment by smartekIT** [comment]
we do have other Win 2008 R2 servers, yes that's true it doesn't connect to them since latest updates but it doesn't crash the meshcentral when try to connect to them as they using the standard rdp port. this alternative rdp port and failing to connect crashes the whole meshcentral server.

**Comment by Ylianst** [comment]
Oh! Ok. I need to handle that error correctly for sure!

**Comment by smartekIT** [comment]
Thanks @Ylianst

**Comment by Ylianst** [comment]
Working on this now.

**Comment by Ylianst** [comment]
instead of a server crash, we get a much better error message now. Will be in v1.0.26.

![image](https://user-images.githubusercontent.com/1319013/169635513-012e1827-5f58-4a66-9967-5afec1c46956.png)

**Comment by smartekIT** [comment]
Thanks

**Comment by Ylianst** [comment]
MeshCentral v1.0.26 also includes the RDP improvements. This will not fix the root cause, but let me know what error you see now.

**Comment by smartekIT** [comment]
Thanks, this is the error we get now:
![image](https://user-images.githubusercontent.com/70715469/169644153-11c8cad0-eae1-4aa2-8c66-95b21cdc5fbe.png)

**Comment by smartekIT** [comment]
closing this ticket, issue still exist but no fix.

**Comment by gogglespisano** [comment]
I found a solution for some cases; the RDP security layer setting.

Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp

SecurityLayer
0 = RDP encryption : Doesn't work and generates the "SSL not allowed by server" message.
1 = Negotiate : Works
2 = TLS Required : Works

https://learn.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/microsoft-windows-terminalservices-rdp-winstationextensions-securitylayer

There may be more to the problem, but changing from 0 to 1 or 2 fixed the issue on Win 10, 11.
