### ISSUE TITLE
server crash on file upload - file permissions related.

### ISSUE THREAD

**Issue by Speedg33k** [Ylianst/MeshCentral#4030]
This is in no way urgent and has a very simple workaround, but I thought you might want to see this.

I was adding a large number of files directly into a user folder on the server side.
They were not visible when I logged in, so I uploaded one through the interface, and the server crashed.
Apparently if the server cannot stat the files it becomes quite offended and leaves.

Having proper permissions on the files makes them visible and as an added bonus the server does not crash.

```
-------- 5/21/2022, 1:25:38 PM ---- 1.0.21 --------

internal/fs/utils.js:230
    throw err;
    ^

Error: EPERM: operation not permitted, stat 'C:\Program Files\Open Source\MeshCentral\meshcentral-files\domain\user-nacho/Applications'
    at Object.statSync (fs.js:933:3)
    at readTotalFileSize (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\webserver.js:4723:31)
    at C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\webserver.js:3961:29
    at C:\Program Files\Open Source\MeshCentral\node_modules\multiparty\index.js:139:9
    at C:\Program Files\Open Source\MeshCentral\node_modules\multiparty\index.js:118:9
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  errno: -4048,
  syscall: 'stat',
  code: 'EPERM',
  path: 'C:\\Program Files\\Open Source\\MeshCentral\\meshcentral-files\\domain\\user-nacho/Applications'
} 
```

**Comment by Ylianst** [comment]
I put in a fix for this, will be in MeshCentral v1.0.27.
