### ISSUE TITLE
Crash after upgrade to 1.0.29

### ISSUE THREAD

**Issue by kiroubel-girma** [Ylianst/MeshCentral#4065]
After upgrading from 1.0.28 to 1.0.29 I encountered a crash.
Looks like the new agent signing (authenticode.js) code crashes.
Went back to previous version 1.0.28 and all is working.

````
node node_modules/meshcentral
MeshCentral HTTP redirection server running on port 1024.
MeshCentral v1.0.29, Hybrid (LAN + WAN) mode.
ERR: /opt/meshcentral/node_modules/meshcentral/authenticode.js:221
                    for (var j in pkcs7.rawCapture.authenticatedAttributes[i].value[1].value[0].value) {
                                                                                                ^

TypeError: Cannot read property 'value' of undefined
    at openFile (/opt/meshcentral/node_modules/meshcentral/authenticode.js:221:97)
    at Object.createAuthenticodeHandler (/opt/meshcentral/node_modules/meshcentral/authenticode.js:558:13)
    at Object.CreateMeshCentralServer.obj.updateMeshAgentsTable (/opt/meshcentral/node_modules/meshcentral/meshcentral.js:2908:75)
    at Object.CreateMeshCentralServer.obj.StartEx4 (/opt/meshcentral/node_modules/meshcentral/meshcentral.js:1620:13)
    at Object.CreateMeshCentralServer.obj.StartEx3 (/opt/meshcentral/node_modules/meshcentral/meshcentral.js:1568:17)
    at /opt/meshcentral/node_modules/meshcentral/meshcentral.js:1480:21
    at Object.obj.GetMeshServerCertificate (/opt/meshcentral/node_modules/meshcentral/certoperations.js:986:43)
    at CreateMeshCentralServer.obj.StartEx2 (/opt/meshcentral/node_modules/meshcentral/meshcentral.js:1477:35)
    at Server.<anonymous> (/opt/meshcentral/node_modules/meshcentral/redirserver.js:143:13)
    at Object.onceWrapper (events.js:420:28)
ERROR: Unable to write to mesherrors.txt.
Error: Command failed: /usr/bin/node /opt/meshcentral/node_modules/meshcentral --launch 17925
/opt/meshcentral/node_modules/meshcentral/authenticode.js:221
                    for (var j in pkcs7.rawCapture.authenticatedAttributes[i].value[1].value[0].value) {
                                                                                                ^

TypeError: Cannot read property 'value' of undefined
    at openFile (/opt/meshcentral/node_modules/meshcentral/authenticode.js:221:97)
    at Object.createAuthenticodeHandler (/opt/meshcentral/node_modules/meshcentral/authenticode.js:558:13)
    at Object.CreateMeshCentralServer.obj.updateMeshAgentsTable (/opt/meshcentral/node_modules/meshcentral/meshcentral.js:2908:75)
    at Object.CreateMeshCentralServer.obj.StartEx4 (/opt/meshcentral/node_modules/meshcentral/meshcentral.js:1620:13)
    at Object.CreateMeshCentralServer.obj.StartEx3 (/opt/meshcentral/node_modules/meshcentral/meshcentral.js:1568:17)
    at /opt/meshcentral/node_modules/meshcentral/meshcentral.js:1480:21
    at Object.obj.GetMeshServerCertificate (/opt/meshcentral/node_modules/meshcentral/certoperations.js:986:43)
    at CreateMeshCentralServer.obj.StartEx2 (/opt/meshcentral/node_modules/meshcentral/meshcentral.js:1477:35)
    at Server.<anonymous> (/opt/meshcentral/node_modules/meshcentral/redirserver.js:143:13)
    at Object.onceWrapper (events.js:420:28)

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:326:22)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: '/usr/bin/node /opt/meshcentral/node_modules/meshcentral --launch 17925'
}
ERROR: MeshCentral failed with critical error, check mesherrors.txt. Restarting in 5 seconds...
```

**Comment by PathfinderNetworks** [comment]
I suspect this may be what I'm seeing as well with issue 4066.
https://github.com/Ylianst/MeshCentral/issues/4066

**Comment by kiroubel-girma** [comment]
MeshCentral v1.0.30 fixes the bug.
