### ISSUE TITLE
Auto Upgrade Broke System

### ISSUE THREAD

**Issue by ctv99** [Ylianst/MeshCentral#4098]
ERR: /home/ubuntu/node_modules/meshcentral/authenticode.js:198
            obj.header.peWindows.imageBase = optinalHeader.readBigUInt64LE(24);
                                                           ^

TypeError: optinalHeader.readBigUInt64LE is not a function
    at openFile (/home/ubuntu/node_modules/meshcentral/authenticode.js:198:60)
    at Object.createAuthenticodeHandler (/home/ubuntu/node_modules/meshcentral/authenticode.js:1061:13)
    at Object.CreateMeshCentralServer.obj.updateMeshAgentsTable (/home/ubuntu/node_modules/meshcentral/meshcentral.js:2905:68)
    at Object.CreateMeshCentralServer.obj.StartEx4 (/home/ubuntu/node_modules/meshcentral/meshcentral.js:1620:13)
    at /home/ubuntu/node_modules/meshcentral/meshcentral.js:1560:29
    at IncomingMessage.<anonymous> (/home/ubuntu/node_modules/meshcentral/certoperations.js:519:46)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
{ Error: Command failed: /usr/bin/node /home/ubuntu/node_modules/meshcentral --debug cert --launch 2373
/home/ubuntu/node_modules/meshcentral/authenticode.js:198
            obj.header.peWindows.imageBase = optinalHeader.readBigUInt64LE(24);
                                                           ^

TypeError: optinalHeader.readBigUInt64LE is not a function
    at openFile (/home/ubuntu/node_modules/meshcentral/authenticode.js:198:60)
    at Object.createAuthenticodeHandler (/home/ubuntu/node_modules/meshcentral/authenticode.js:1061:13)
    at Object.CreateMeshCentralServer.obj.updateMeshAgentsTable (/home/ubuntu/node_modules/meshcentral/meshcentral.js:2905:68)
    at Object.CreateMeshCentralServer.obj.StartEx4 (/home/ubuntu/node_modules/meshcentral/meshcentral.js:1620:13)
    at /home/ubuntu/node_modules/meshcentral/meshcentral.js:1560:29
    at IncomingMessage.<anonymous> (/home/ubuntu/node_modules/meshcentral/certoperations.js:519:46)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:203:15)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   '/usr/bin/node /home/ubuntu/node_modules/meshcentral --debug cert --launch 2373' }
ERROR: MeshCentral failed with critical error, check mesherrors.txt. Restarting in 5 seconds...

**Comment by ctv99** [comment]
sorry node rolled back

**Comment by theoneandonly-vector** [comment]
> sorry node rolled back

what did you do to fix this?

**Comment by ctv99** [comment]
I reinstalled node 16

**Comment by Ylianst** [comment]
Just published v1.0.36 with a fix for this. Also, a workaround it to add:

```
"webPageLengthRandomization": false
```

In the settings section of the config.json. You can then update and remove that line.

**Comment by theoneandonly-vector** [comment]
I actually use  nodejs 16 but still need this:
"""webPageLengthRandomization": false""

node -v
v16.15.1


> For anyone else running anything older than NodeJS v16, I just published v1.0.36 with a fix for this. Also, a workaround it to add:
> 
> ```
> "webPageLengthRandomization": false
> ```
> 
> In the settings section of the config.json. You can then update and remove that line.
