### ISSUE TITLE
MeshCentral cannot start after 1.0.38 upgrade

### ISSUE THREAD

**Issue by PathfinderNetworks** [Ylianst/MeshCentral#4148]
I upgraded to 1.0.38 and now my MeshCentral install will not start.  Restoring to a previous version via backup does not resolve the issue as the issue seems to be within the modules folder files.  
This is the error I am seeing when trying to manually start MeshCentral: 
`C:\Program Files\MeshCentral\WinService\daemon>node node_modules/meshcentral
node:internal/modules/cjs/loader:942
  throw err;
  ^

Error: Cannot find module 'C:\Program Files\MeshCentral\WinService\daemon\node_modules\meshcentral'
←[90m    at Module._resolveFilename (node:internal/modules/cjs/loader:939:15)←[39m
←[90m    at Module._load (node:internal/modules/cjs/loader:780:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)←[39m
←[90m    at node:internal/main/run_main_module:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}

Node.js v18.3.0`

**Comment by PathfinderNetworks** [comment]
If I look at the meshcentral.err.log located in the \WinService\daemon folder I'm seeing this.  It's a slightly different error. 

`Node.js v18.3.0
node:internal/modules/cjs/loader:942
  throw err;
  ^

Error: Cannot find module 'c:\Program Files\MeshCentral\node_modules\node-windows\lib\wrapper.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:939:15)
    at Module._load (node:internal/modules/cjs/loader:780:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
`
Looking at my folder structure I can see that the \node-windows\ folder doesn't exist at all under C:\Program Files\MeshCentral\Node_Modules\

**Comment by PathfinderNetworks** [comment]
Even more strangeness.  I restored the node-windows folder from a backup image.  Then started the MeshCentral server.  It started but then, within a few seconds of starting, the node-windows folder was deleted once again. So something about 1.0.38 is trying to make changes to or upgrade the node-windows folder and its contents but is failing to do so.  
I just restored the node-windows folder again and also restored the meshcentral-data folder from a backup and now it's running as normal.  
The VERY strange thing is the meshcentral-data backup I restored reports that it is very 1.0.38.  
So I have no idea what in the world is going on there.  For now I am up and running.

**Comment by rowds15** [comment]
Well i got a different error again. upgrading from 1.0.36 to 1.0.38, node 16.15.1 but mine did restart correctly after the error.

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'mongodb'
Require stack:
- /home/ec2-user/node_modules/meshcentral/db.js
- /home/ec2-user/node_modules/meshcentral/meshcentral.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.module.exports.CreateDB (/home/ec2-user/node_modules/meshcentral/db.js:733:9)
    at Object.CreateMeshCentralServer.obj.StartEx (/home/ec2-user/node_modules/meshcentral/meshcentral.js:803:28)
    at Object.CreateMeshCentralServer.obj.Start (/home/ec2-user/node_modules/meshcentral/meshcentral.js:433:66)
    at /home/ec2-user/node_modules/meshcentral/meshcentral.js:3712:24
    at InstallModules (/home/ec2-user/node_modules/meshcentral/meshcentral.js:3501:121)
    at /home/ec2-user/node_modules/meshcentral/meshcentral.js:3523:9 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/ec2-user/node_modules/meshcentral/db.js',
    '/home/ec2-user/node_modules/meshcentral/meshcentral.js'
  ]
}

**Comment by rowds15** [comment]
No, the mongodb folder was there.

**Comment by PathfinderNetworks** [comment]
> That is super weird, I have not made any changes to this area of the code in ages. The last [node-windows](https://www.npmjs.com/package/node-windows) was released 3 months back, so it's not because of a change in that library.
> 
> Just for kicks, to you have sufficient free space on the drive? (I know, it's dumb question, but it did happen before).
> 
> Also, you could run:
> 
> ```
> npm cache clean --force
> ```
> 
> To clear the NPM cache, just in case something got corrupt. After that, rename your `node_modules` to `node_modules_bak` and run `npm install meshcentral` to get a clean version.

I just did this and something is still not right.  After running npm install meshcentral it does recreate the node_modules folder but never creates the node-windows folder.  So Mesh is not able to start.  

If I manually copy the node-windows folder from the original node_modules.bak then I can start MeshCentral correctly. 

Here is the log from installing MeshCentral with NPM.:
`C:\Program Files\MeshCentral>npm install meshcentral
npm WARN npm npm does not support Node.js v18.3.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11, 12.
npm WARN npm You can find the latest version at https://nodejs.org/

> cpu-features@0.0.4 install C:\Program Files\MeshCentral\node_modules\cpu-features
> node buildcheck.js > buildcheck.gypi && node-gyp rebuild

C:\Program Files\MeshCentral\node_modules\buildcheck\lib\index.js:133
        throw new Error('Unable to detect compiler type');
        ^

Error: Unable to detect compiler type
    at new BuildEnvironment (C:\Program Files\MeshCentral\node_modules\buildcheck\lib\index.js:133:15)
    at Object.<anonymous> (C:\Program Files\MeshCentral\node_modules\cpu-features\buildcheck.js:5:12)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

Node.js v18.3.0
npm WARN MeshCentral No description
npm WARN MeshCentral No repository field.
npm WARN MeshCentral No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: cpu-features@0.0.4 (node_modules\cpu-features):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: cpu-features@0.0.4 install: `node buildcheck.js > buildcheck.gypi && node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ meshcentral@1.0.38
updated 1 package and audited 177 packages in 10.675s
found 0 vulnerabilities`

**Comment by PathfinderNetworks** [comment]
Also, not certain this is related- but now, when installing MeshCentral on new devices, the agent version is showing up as 'MeshCore Recovery'.  It never updates to Mar 25 2022 2265086444 version like my other devices.

**Comment by PathfinderNetworks** [comment]
I noticed my version of NPM was out of date- was version 6.x (can't remember the exact version number).  I updated to version 8.12.2 and tried again.  The install still didn't create the node-windows folder.  However, I manually started Mesh using `node node_modules/meshcentral`. While Mesh still errored out I noticed that this did create the node-windows folder.  Running node node_modules/meshcentral a second time (after the initial run created the node-windows folder) it did start and is running correctly.  It also starts and runs correctly using the Windows service.  
So not sure if maybe the outdated version of NPM was causing this?

**Comment by energywave** [comment]
I also was in the same exact error about node-windows. I've described it here from this comment ongoing: https://github.com/Ylianst/MeshCentral/issues/4133#issuecomment-1161596120
I'll try to update to the latest 1.0.41 to see if it's ok or not and edit this comment accordingly.

**Comment by dinger1986** [comment]
@si458 old version, can close

**Comment by si458** [comment]
need to run at least node 18 now to support all new modules, and use the latest meshcentral as well to fix module installs
