### ISSUE TITLE
InviteCodes option generates broken URL after 1.0.45 update

### ISSUE THREAD

**Issue by smartekIT** [Ylianst/MeshCentral#4233]
**Describe the bug**
Invite Codes Option in the group page generates invalid URL which doesn't work. all start happening after v1.0.45

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to group page
2. Click on Invite Codes
3. Set the invite code then copy the invitation code
4. paste the generated URL into web browser, e.g. https://subdomain.example.com/invite

**Expected behaviour**
Normally you should see a page asking for the invite code you sat earlier in the group page, but instead you get a page of a system error.

the following error generated by the system when trying to reach the page : https://subdomain.example.com/invite

<pre>
-------- 7/7/2022, 10:07:16 AM ---- 1.0.47 --------

TypeError: Cannot read properties of undefined (reading 'inviteCode')
    at handleInviteRequest (/home/node/meshcentral/node_modules/meshcentral/webserver.js:1933:23)
    at Layer.handle [as handle_request] (/home/node/meshcentral/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/node/meshcentral/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/node/meshcentral/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/node/meshcentral/node_modules/express/lib/router/layer.js:95:5)
    at /home/node/meshcentral/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/node/meshcentral/node_modules/express/lib/router/index.js:341:12)
    at next (/home/node/meshcentral/node_modules/express/lib/router/index.js:275:10)
    at /home/node/meshcentral/node_modules/meshcentral/webserver.js:5918:20
    at Layer.handle [as handle_request] (/home/node/meshcentral/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/node/meshcentral/node_modules/express/lib/router/index.js:323:13)
    at /home/node/meshcentral/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/node/meshcentral/node_modules/express/lib/router/index.js:341:12)
    at next (/home/node/meshcentral/node_modules/express/lib/router/index.js:275:10)
    at _cookieSession (/home/node/meshcentral/node_modules/cookie-session/index.js:126:5)
    at Layer.handle [as handle_request] (/home/node/meshcentral/node_modules/express/lib/router/layer.js:95:5)
</pre>

**Comment by pggsadmin** [comment]
+1

**Comment by VINISHVV** [comment]
+1

**Comment by Ylianst** [comment]
Oh! i am working on it now!! Thank for reporting this. The web relay DNS feature almost certainly caused this.

**Comment by Ylianst** [comment]
Indeed, I see the same problem...

**Comment by smartekIT** [comment]
> Oh! i am working on it now!! Thank for reporting this. The web relay DNS feature almost certainly caused this.

Thanks mate. I appreciate your help.

sorry to bother you @Ylianst  and I know it's different topic but I got another ticket been for 29 days and never been looked at. it's here #4089 

Cheers.

**Comment by Ylianst** [comment]
Just put in a fix for this one, will be publishing v1.0.48 shortly.

@smartekIT Noted on #4089. Looks like an easy one, working on it now.

**Comment by smartekIT** [comment]
Thanks @Ylianst I appreciate it.

**Comment by Ylianst** [comment]
MeshCentral v1.0.48 is out.
