### ISSUE TITLE
update 1.0.60 AMT error after update

### ISSUE THREAD

**Issue by arduin0guru** [Ylianst/MeshCentral#4325]
Hi I updated from 1.0.54 to 1.0.60 . Now I am getting this log msg..

------- 7/24/2022,---- 1.0.60 --------

TypeError: Cannot read property 'status' of undefined
    at Object.<anonymous> (D:\MeshCentral\node_modules\meshcentral\amtmanager.js:1380:56)
    at Object.<anonymous> (D:\MeshCentral\node_modules\meshcentral\amt\amt.js:149:186)
    at _EnumContinueSink (D:\MeshCentral\node_modules\meshcentral\amt\amt.js:104:39)
    at D:\MeshCentral\node_modules\meshcentral\amt\amt.js:99:88
    at Array.<anonymous> (D:\MeshCentral\node_modules\meshcentral\amt\amt-wsman.js:51:17)
    at Object.CreateWsmanComm.obj.gotNextMessages (D:\MeshCentral\node_modules\meshcentral\amt\amt-wsman-comm.js:512:55)
    at Object.CreateWsmanComm.obj.xxProcessHttpResponse (D:\MeshCentral\node_modules\meshcentral\amt\amt-wsman-comm.js:442:17)
    at Object.CreateWsmanComm.obj.xxOnSocketData (D:\MeshCentral\node_modules\meshcentral\amt\amt-wsman-comm.js:414:25)
    at TLSSocket.<anonymous> (D:\MeshCentral\node_modules\meshcentral\amt\amt-wsman-comm.js:255:75)
    at TLSSocket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at TLSSocket.Readable.push (_stream_readable.js:209:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)
    at Duplex.ondata (internal/js_stream_socket.js:72:22)
    at Duplex.emit (events.js:310:20)

**Comment by Ylianst** [comment]
Thanks for reporting this. I am traveling now, will be back in a few days and will fix this ASAP.

**Comment by arduin0guru** [comment]
Not urgent as all thing looks like working

**Comment by Ylianst** [comment]
Working on this one now.

**Comment by Ylianst** [comment]
Thanks for reporting this, I just put in a fix. Will be in v1.0.61.

**Comment by dinger1986** [comment]
@si458 fixed can close
