### ISSUE TITLE
server crashes at login

### ISSUE THREAD

**Issue by smartekIT** [Ylianst/MeshCentral#4346]
I had v1.0.57 and all was working fine, until today on the login screen whenever I try to sign in then MC crashes.
tried many browsers and different machines but still the same. so I had to ssh into the server then issue an install / update command from ssh.  <pre>npm install meshcentral@1.0.61</pre>

here is the error I'm getting, Even though now all the sudden it starts to work again after asking me for the 2FA. but before didn't even reach to the stage where it's asking for 2FA but rather crashes straight away.

<pre>
-------- 7/31/2022, 1:19:30 PM ---- 1.0.57 --------

/home/node/meshcentral/node_modules/meshcentral/webserver.js:983
        const sec = parent.decryptSessionData(req.session.e);
                                                          ^

TypeError: Cannot read properties of null (reading 'e')
    at getHardwareKeyChallenge (/home/node/meshcentral/node_modules/meshcentral/webserver.js:983:59)
    at handleRootRequestEx (/home/node/meshcentral/node_modules/meshcentral/webserver.js:2895:25)
    at Timeout._onTimeout (/home/node/meshcentral/node_modules/meshcentral/webserver.js:1154:56)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)

Node.js v17.8.0

-------- 7/31/2022, 1:23:55 PM ---- 1.0.61 --------

/home/node/meshcentral/node_modules/meshcentral/webserver.js:983
        const sec = parent.decryptSessionData(req.session.e);
                                                          ^

TypeError: Cannot read properties of null (reading 'e')
    at getHardwareKeyChallenge (/home/node/meshcentral/node_modules/meshcentral/webserver.js:983:59)
    at handleRootRequestEx (/home/node/meshcentral/node_modules/meshcentral/webserver.js:2895:25)
    at Timeout._onTimeout (/home/node/meshcentral/node_modules/meshcentral/webserver.js:1154:56)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)

Node.js v17.8.0

</pre>

**Comment by Ylianst** [comment]
Thanks for reporting this. I will get on this tomorrow as high priority.

**Comment by smartekIT** [comment]
> Thanks for reporting this. I will get on this tomorrow as high priority.

Thanks heaps. I normally tick the box to remember credentials for the next 30 days. Now I guess this happened because the 30 days are over and server failed to prompt for the 2FA submission on login screen due to:
<pre>const sec = parent.decryptSessionData(req.session.e);</pre>

**Comment by Ylianst** [comment]
Thanks for reporting this. I just put in a fix for this, will be in MeshCentral v1.0.62.

**Comment by smartekIT** [comment]
Thanks
