### ISSUE TITLE
mongodb problem while creating users and groups

### ISSUE THREAD

**Issue by johnjcool** [Ylianst/MeshCentral#4429]
**Describe the bug**
we have setup mehcentral 1.0.70 with 3 peers and mongodb v6 replicaSet. meshcentral starts fine but if we create a user or group we get the following error:
```
MeshCentral HTTP redirection server running on port 80.
MeshCentral v1.0.70, Hybrid (LAN + WAN) mode, Production mode.
MeshCentral Intel(R) AMT server running on mps.xyz.local:9080, alias port 443.
Loaded web certificate from "https://mesh.xyz.local/", host: "mesh.xyz.local"
  SHA384 cert hash: 
  SHA384 key hash: 
MeshCentral HTTP server running on port 8080, alias port 443.
ERR: /opt/meshcentral/node_modules/meshcentral/db.js:3262
        for (var i in user) { muser[i] = user[i]; }
                                       ^

TypeError: Cannot set properties of undefined (setting '_id')
    at dbUserChange (/opt/meshcentral/node_modules/meshcentral/db.js:3262:40)
    at ChangeStream.<anonymous> (/opt/meshcentral/node_modules/meshcentral/db.js:893:48)
    at ChangeStream.emit (node:events:513:28)
    at processNewChange (/opt/meshcentral/node_modules/mongodb/lib/change_stream.js:395:29)
    at Readable.<anonymous> (/opt/meshcentral/node_modules/mongodb/lib/change_stream.js:363:33)
    at Readable.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Readable.push (node:internal/streams/readable:228:10)
    at /opt/meshcentral/node_modules/mongodb/lib/cursor/abstract_cursor.js:620:30
Error: Command failed: /usr/local/bin/node /opt/meshcentral/node_modules/meshcentral --launch 1
/opt/meshcentral/node_modules/meshcentral/db.js:3262
```

**To Reproduce**
1. install mongodb replicaSet
2. connect meshcentral with 3 peers to mongodb
3. create group

**Expected behavior**
no error occurs while creating groups or users works

**Server Software (please complete the following information):**
 - OS: node:lts-alpine
 - Virtualization: Docker, Kubernetes
 - Network: hybrid, ssl offload
 - Version: 1.0.70
 - Node: v16.17.0

**Your config.json file**
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "peers": {
    "servers": {
      "mesh-central-1": { "url": "ws://mesh-central-1:8080/" },
      "mesh-central-2": { "url": "ws://mesh-central-2:8080/" },
      "mesh-central-0": { "url": "ws://mesh-central-0:8080/" }
    }
  },
  "settings": {
    "agentTimeStampProxy": "http://proxy.xyz.local:80",
    "autoBackup": false,
    "allowFraming": true,
    "mongoDb": "mongodb://username:password@mesh-central-mongodb-0.mesh-central-mongodb-headless:27017,mesh-central-mongodb-1.mesh-central-mongodb-headless:27017/meshcentral?replicaSet=rs0",
    "mongoDbChangeStream": true,
    "sessionKey": "sessionKey",
    "cert": "mesh.xyz.local",
    "port": 8080,
    "aliasPort": 443,
    "redirPort": 80,
    "redirAliasPort": 80,
    "tlsOffload": true,
    "trustedProxy": "mesh.xyz.local",
    "mpsPort": 9080,
    "mpsAliasPort": 443,
    "mpsAliasHost": "mps.xyz.local",
    "mpsTlsOffload": true
  },
  "domains": {
    "": {
      "title": "AMT powered by",
      "title2": "XYZ",
      "certUrl": "https://mesh.xyz.local/",
      "minify": true,
      "autoRemoveInactiveDevices": 30,
      "amtAcmActivation": {
        "log": "amtactivation.log",
        "certs": {
          "provisionserver.xyz.local": {
            "certfiles": [
              "digicert-intermediate-ca.crt",
              "digicert-root-ca.crt",
              "provisionserver.xyz.crt"
            ],
            "keyfile": "provisionserver.xyz.key"
          }
        }
      },
      "authStrategies": {
        "saml": {
          "callbackurl": "https://mesh.xyz.local/auth-saml-callback",
          "newAccounts": true,
          "newAccountsRights": [ "nonewgroups", "notools" ],
          "entityid": "meshcentral",
          "idpurl": "https://iam.xyz.local/auth/realms/test/protocol/saml/clients/meshcentral",
          "cert": "saml-sso.pem"
        }
      },
      "amtManager": {
        "adminAccounts": [
          {
            "user": "username",
            "pass": "password"
          }
        ]
      }
    }
  }
}
```

**Comment by johnjcool** [comment]
are these lines really right:
- https://github.com/Ylianst/MeshCentral/blob/9d21823e5fa94162cb235a2f673d3e363a42f1b8/db.js#L3261
- https://github.com/Ylianst/MeshCentral/blob/9d21823e5fa94162cb235a2f673d3e363a42f1b8/db.js#L3278
- https://github.com/Ylianst/MeshCentral/blob/9d21823e5fa94162cb235a2f673d3e363a42f1b8/db.js#L3241

this ``` for (var i in usergroup) { uusergroup[i] = usergroup[i]; } ``` is an map operation but it in my opinion it isn't a map...
we have added som debug logs:
```
usergroup: {
  _id: 'ugrp//TtYDd5EdBYADrUd8$@H4OFbo3BMCGtZB0nXR9NhqmbVnASCY6gz9cxEqpHzSYN@N',
  type: 'ugrp',
  name: 'abcdef',
  desc: '',
  domain: '',
  links: {}
}
uusergroup: undefined
ERR: /opt/meshcentral/node_modules/meshcentral/db.js:3281
        for (var i in usergroup) { uusergroup[i] = usergroup[i]; }
                                                 ^

TypeError: Cannot set properties of undefined (setting '_id')
```

**Comment by Ylianst** [comment]
I just put in a fix for this. Will be in v1.0.72.

**Comment by johnjcool** [comment]
i think you have also to change this:
https://github.com/Ylianst/MeshCentral/blob/master/db.js#L3298
to this:
```
var usergroup2 = Object.assign({}, usergroup);
usergroup2.action = (added ? 'createusergroup' : 'usergroupchange');
usergroup2.ugrpid = usergroup2._id;
usergroup2.nolog = 1;
delete usergroup2.type;
delete usergroup2._id;
parent.DispatchEvent(['*', usergroup2.ugrpid], obj, usergroup2);
```
because if you want to change the name directly after creation it won't work. you first have to restart the server. i think the ui need a clone like CloneSafeUser (call by reference instead of call by value).

**Comment by johnjcool** [comment]
is it possible to make this part working? whether you delete e.g. a group, after a page reload you get all items from the cache, which isn't updated:
https://github.com/Ylianst/MeshCentral/blob/master/db.js#L900

**Comment by Ylianst** [comment]
v1.0.72 is out, can you give it a try and let me know what you see on that version?

**Comment by smartekIT** [comment]
@Ylianst By the way, would you consider making a youtube video on how to link multiple meshcentral servers instances, peers.

Thanks heaps.

**Comment by Ylianst** [comment]
Sure :) [MeshCentral Server Peering](https://www.youtube.com/watch?v=j8xIRGScju0).

**Comment by dinger1986** [comment]
@si458 can close
