### ISSUE TITLE
Custom SMS API configuration

### ISSUE THREAD

**Issue by drlight17** [Ylianst/MeshCentral#4478]
Hello! Thank you for your masterpiece work!

**Is your feature request related to a problem? Please describe.**
 I would like to request an ability to config some custom self hosted sms api in addition to commercial Twilio, Plivo and others.

**Describe the solution you'd like**
I think it could be simple to just give the administrator some kind of such api url configuration in config.json:

```
"sms": {
    "provider": "Custom_provider",
    "api-url": "http://own-sms-portal.site/api.php?auth='+apikey+'phone='+to+'&message='+msg"
}
```

**Comment by Ylianst** [comment]
ok, just checked in a solution for this. In v1.0.78 there is a new "url" provider, you use it like this:

```
  "sms": {
    "provider": "url",
    "url": "https://localhost/?phone={{phone}}&message={{message}}"
  }
```

The `{{phone}}` and `{{message}}` will be replaced with the right URL encoded values. Once released, let me know if that works.

**Comment by Ylianst** [comment]
MeshCentral v1.0.78 is now out.

![MC2-GenericSmsGateway](https://user-images.githubusercontent.com/1319013/188021403-a8084deb-d3f3-4bc1-9c1e-59cabb5a71bb.png)

Note that is the SMS GET receives a 200 OK message, MeshCentral will indicate that the SMS was send successfully, otherwise it will indicate as failed.

**Comment by drlight17** [comment]
> MeshCentral v1.0.78 is now out.
> 
>
> 
> Note that is the SMS GET receives a 200 OK message, MeshCentral will indicate that the SMS was send successfully, otherwise it will indicate as failed.

Wow! So fast! Just tested with the following config:
  "sms": {
    "provider": "url",
    "url": "http://sms.ksc.loc/api.php?phone={{phone}}&message={{message}}"
  }
SMS has sent and rceived but there is an error in meshcentral console right after this action and app has restarted:
```
root@rd:/home/samoilov# sudo -u samoilov node ./node_modules/meshcentral
MeshCentral HTTP redirection server running on port 80.
MeshCentral v1.0.78, Hybrid (LAN + WAN) mode.
MeshCentral Intel(R) AMT server running on rd.ksc.ru:4433.
MeshCentral HTTPS server running on rd.ksc.ru:443.
ERR: /home/samoilov/node_modules/meshcentral/meshsms.js:147
                const request = require('http').request(options, function (res) { parent.debug('email', 'SMS result: ' + res.statusCode); func(res.statusCode == 200, (res.statusCode == 200) ? null : res.statusCode, null); res.on('data', function (d) { }); });
                                                                                                                                          ^

TypeError: func is not a function
    at ClientRequest.<anonymous> (/home/samoilov/node_modules/meshcentral/meshsms.js:147:139)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:314:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:601:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:122:17)
    at Socket.socketOnData (_http_client.js:474:22)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
Error: Command failed: /usr/bin/node /home/samoilov/node_modules/meshcentral --launch 5606
/home/samoilov/node_modules/meshcentral/meshsms.js:147
                const request = require('http').request(options, function (res) { parent.debug('email', 'SMS result: ' + res.statusCode); func(res.statusCode == 200, (res.statusCode == 200) ? null : res.statusCode, null); res.on('data', function (d) { }); });
                                                                                                                                          ^

TypeError: func is not a function
    at ClientRequest.<anonymous> (/home/samoilov/node_modules/meshcentral/meshsms.js:147:139)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:314:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:601:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:122:17)
    at Socket.socketOnData (_http_client.js:474:22)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:326:22)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: '/usr/bin/node /home/samoilov/node_modules/meshcentral --launch 5606'
}
ERROR: MeshCentral failed with critical error, check mesherrors.txt. Restarting in 5 seconds...
MeshCentral HTTP redirection server running on port 80.
MeshCentral v1.0.78, Hybrid (LAN + WAN) mode.
MeshCentral Intel(R) AMT server running on rd.ksc.ru:4433.
MeshCentral HTTPS server running on rd.ksc.ru:443.
ERR: /home/samoilov/node_modules/meshcentral/meshsms.js:147
                const request = require('http').request(options, function (res) { parent.debug('email', 'SMS result: ' + res.statusCode); func(res.statusCode == 200, (res.statusCode == 200) ? null : res.statusCode, null); res.on('data', function (d) { }); });
                                                                                                                                          ^

TypeError: func is not a function
    at ClientRequest.<anonymous> (/home/samoilov/node_modules/meshcentral/meshsms.js:147:139)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:314:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:601:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:122:17)
    at Socket.socketOnData (_http_client.js:474:22)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
Error: Command failed: /usr/bin/node /home/samoilov/node_modules/meshcentral --launch 5606
/home/samoilov/node_modules/meshcentral/meshsms.js:147
                const request = require('http').request(options, function (res) { parent.debug('email', 'SMS result: ' + res.statusCode); func(res.statusCode == 200, (res.statusCode == 200) ? null : res.statusCode, null); res.on('data', function (d) { }); });
                                                                                                                                          ^

TypeError: func is not a function
    at ClientRequest.<anonymous> (/home/samoilov/node_modules/meshcentral/meshsms.js:147:139)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:314:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:601:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:122:17)
    at Socket.socketOnData (_http_client.js:474:22)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:326:22)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: '/usr/bin/node /home/samoilov/node_modules/meshcentral --launch 5606'
}
ERROR: MeshCentral failed with critical error, check mesherrors.txt. Restarting in 5 seconds...
MeshCentral HTTP redirection server running on port 80.
MeshCentral v1.0.78, Hybrid (LAN + WAN) mode.
MeshCentral Intel(R) AMT server running on rd.ksc.ru:4433.
MeshCentral HTTPS server running on rd.ksc.ru:443.
^CServer Ctrl-C exit...
```
Also the received sms has some charset troubles after "MeshCentral" word before ": code" (my locale is RU).

**Comment by Ylianst** [comment]
Your right, just push a fix for this. Will be in MeshCentral v1.0.79.

**Comment by drlight17** [comment]
> Your right, just push a fix for this. Will be in MeshCentral v1.0.79. You can also look at the fix in GitHub and make the same change to try it out.

Yes, works like a charm, thank you! And what about charset of sms? It now looks like this:
![photo_2022-09-02_16-57-37](https://user-images.githubusercontent.com/37434652/188165377-98203c70-910b-4e37-8d40-f31adade2dc3.jpg)

**Comment by Ylianst** [comment]
Ok, I cut & pasted from Chinese characters from Wikipedia to send as an SMS:

![image](https://user-images.githubusercontent.com/1319013/188240507-4d7a54a2-0793-4782-a1e2-9224eeb14db0.png)

The generated URL I got was this:

https://sample.com/?phone=xxx-xxx-xxxx&msg=%E4%B8%AD%E6%96%87%E7%B6%AD%E5%9F%BA%E7%99%BE%E7%A7%91

The message portion is UTF-8 characters that are URL encoded. The HEX value is:

E4B8ADE69687E7B6ADE59FBAE799BEE7A791

I then used [this page](https://onlinehextools.com/convert-hex-to-utf8) to convert the HEX back to UTF-8:

![image](https://user-images.githubusercontent.com/1319013/188240672-1e14913c-8036-4ecb-a653-857fea39f922.png)

I got the right characters back. So, everything looks good. Your going to have to take the URL you get and convert it correctly for your provider, I don't think there is anything else I can do.

**Comment by drlight17** [comment]
> Ok, I cut & pasted some Chinese characters from Wikipedia to send as an SMS:
> 
> I got the right characters back. So, everything looks good. Your going to have to take the URL you get and convert it correctly for your provider, I don't think there is anything else I can do.

Just found out: in my smstools web interface I did utf-8 to windows-1251, but I forgot to add this conversion in it's API. Thank you for your attention and work!
