### ISSUE TITLE
ReferenceError: TextEncoder is not defined

### ISSUE THREAD

**Issue by aaronzufall** [Ylianst/MeshCentral#4499]
Hello,

I've started getting this error and MeshCentral is failing to start:

```
ReferenceError: TextEncoder is not defined
    at Object.<anonymous> (/opt/meshcentral/node_modules/whatwg-url/lib/encoding.js:2:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17) 
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/opt/meshcentral/node_modules/whatwg-url/lib/url-state-machine.js:5:34)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
```

This happens on both Node 16.17.0 and Node 18.8.0. This seems related to #3068 and [whatwg-url/issues/195](https://github.com/jsdom/whatwg-url/issues/195), but I don't see any clear way of resolving this through server configuration.

This started evening EST on 9/3, I'm assuming something auto-updated at that time.

MeshCentral version 1.0.81.

**Comment by aaronzufall** [comment]
Rolling back to 1.0.79 seems to fix the issue, so I'm thinking it might be connected to the MongoDB version changes in 1.0.80.

**Comment by Ylianst** [comment]
[Found this](https://stackoverflow.com/questions/69482210/referenceerror-textencoder-is-not-defined-with-mongodb-nodes), looking into this now.

**Comment by Ylianst** [comment]
I just push MeshCentral v1.0.82 with a fix for this. I was only able to replicate this error on older NodeJS v10.4.0, but not on newer NodeJS v16 and v18. This leads me to wonder what version of NodeJS is actually being used. You can go in the "My Server / Console" tab and type "info" to see the actual NodeJS used.

![image](https://user-images.githubusercontent.com/1319013/188407803-143a69ca-6844-4e5a-9aae-ff017f27c716.png)

**Comment by aaronzufall** [comment]
Ah, yep--it is in fact running Node 10.19.0. My server must have multiple versions installed. I'll have to figure that one out. Apologies for that.

The issue does appear to be resolved with the update. Thank you! And thank you so much for this tool, really appreciate it.
