### ISSUE TITLE
New install using postgres errors

### ISSUE THREAD

**Issue by dinger1986** [Ylianst/MeshCentral#4507]
I have created the database and added the config for postgres to config.json below, and mesh works fine but the database doesnt work and after restarting the mesh service I need to setup a user every time.

    "postgres": {
      "user": "username",
      "password": "password",
      "port": "5432",
      "host": "localhost"
    }

This is the output of journalctl -u meshcentral

meshcentral.service: Consumed 7.552s CPU time.
Started MeshCentral Server.
Installing pg@8.7.1...
Installing pgtools@0.3.2...
Installing pg@8.7.1...
SELECT doc FROM main WHERE id = $1 [ 'DatabaseIdentifier' ] error: relation "main" does not exist
 at Parser.parseErrorMessage (/opt/meshcentral/node_modules/pg-protocol/dist/parser.js:287:98)
 at Parser.handlePacket (/opt/meshcentral/node_modules/pg-protocol/dist/parser.js:126:29)
 at Parser.parse (/opt/meshcentral/node_modules/pg-protocol/dist/parser.js:39:38)
 at Socket.<anonymous> (/opt/meshcentral/node_modules/pg-protocol/dist/index.js:11:42)
 at Socket.emit (node:events:513:28)
 at addChunk (node:internal/streams/readable:315:12)
 at readableAddChunk (node:internal/streams/readable:289:9)
 at Socket.Readable.push (node:internal/streams/readable:228:10)
 at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
 length: 103,
 severity: 'ERROR',
 code: '42P01',
 detail: undefined,
 hint: undefined,
 position: '17',
 internalPosition: undefined,
 internalQuery: undefined,
 where: undefined,
 schema: undefined,
 table: undefined,
 column: undefined,
 dataType: undefined,
 constraint: undefined,
 file: 'parse_relation.c',
 line: '1373',
 routine: 'parserOpenTable'
}
SELECT doc FROM main WHERE id = $1 [ 'SchemaVersion' ] error: relation "main" does not exist
 at Parser.parseErrorMessage (/opt/meshcentral/node_modules/pg-protocol/dist/parser.js:287:98)
 at Parser.handlePacket (/opt/meshcentral/node_modules/pg-protocol/dist/parser.js:126:29)
 at Parser.parse (/opt/meshcentral/node_modules/pg-protocol/dist/parser.js:39:38)

**Comment by Ylianst** [comment]
Looking at the code, if the `meshcentral` database does not exist, MeshCentral will create it and create all of the tables and indexes. If `meshcentral` already exists, it assumes that all of the tables and indexes are also already created.

In your case, it seems like there is a `meshcentral` database, but no tables. I am going to rework the code now so that if the first query to the `main` table fails, it will try to create the tables and indexes.

**Comment by dinger1986** [comment]
Great thanks, I had come to a similar conclusion and was testing ways round it but your solution sounds best.

Issue with Postgres and MySQL I guess is a user should only have access to one database ideally not using root for it so db needs to be created before hand.

I actually tried importing from nedb but that didn't work as well.

I am writing an install script for mesh to hopefully help users deploy it

**Comment by Ylianst** [comment]
I just pushed a fix for this, will be in MeshCentral v1.0.83. Your absolutely right that you should not be giving MeshCentral admin access to the database. Right now, you have to give it admin on the first run to create the DB, tables and indexes and lower the access rights on the second run.

**Comment by dinger1986** [comment]
That's great thank you!

**Comment by dinger1986** [comment]
I have tested this and its working absolutely fine. will this also work for mysql now?

Thansk again

**Comment by Ylianst** [comment]
Thanks. I did not add the same for MySQL, I will work on adding it.

**Comment by Ylianst** [comment]
I just checked and for MySQL, I check is tables/indexes exist every time, so there should not be any issues.

**Comment by dinger1986** [comment]
working, thanks for your speedy resolve
