### ISSUE TITLE
Reset 2FA/TOTP with LDAP-Users.

### ISSUE THREAD

**Issue by JSuenram** [Ylianst/MeshCentral#4543]
node node_modules/meshcentral/meshcentral.js --resetaccount user//Username --domain --pass "1234"
Trying to reset 2FA for LDAP-User brings following error

SQLERR5 TypeError [ERR_INVALID_ARG_TYPE]: The "digest" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at validateString (node:internal/validators:120:11)
    at check (node:internal/crypto/pbkdf2:90:3)
    at Object.pbkdf2 (node:internal/crypto/pbkdf2:43:5)
    at Object.exports.hash (/etc/meshcentral/node_modules/meshcentral/pass.js:34:20)
    at /etc/meshcentral/node_modules/meshcentral/meshcentral.js:872:51
    at /etc/meshcentral/node_modules/meshcentral/db.js:2001:246
    at Query.<anonymous> (/etc/meshcentral/node_modules/meshcentral/db.js:1242:39)
    at Query.<anonymous> (/etc/meshcentral/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/etc/meshcentral/node_modules/mysql/lib/Connection.js:488:16) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by mstrhakr** [comment]
It looks like you are missing user.salt going into that reset here due to the user being created by the LDAP flow. Try --hashpassword to pre-hash a password and use the results with `--hashpass` (should output [salt],[pre-hashed pass]) instead of `--pass`

Like this:
```
node node_modules/meshcentral/meshcentral.js --hashpassword "1234"
>[salt],[pre-hashed pass]
node node_modules/meshcentral/meshcentral.js --resetaccount user//Username --domain --hashpass "[salt],[pre-hashed pass]"
>[Success/Failure Message]
```

**Comment by si458** [comment]
the was a bug where 2fa wasnt reset using `resetaccount` which was fixed recently
but you are also trying to set the users password using `--pass`
and this isnt possible because you are using LDAP
meshcentral doesnt store any passwords when using external auth methods

this is infact a bug as it shouldnt of attempted to change ur password if its set to LDAP or external auths
