### ISSUE TITLE
MongoDb fresh install

### ISSUE THREAD

**Issue by Christ010101** [Ylianst/MeshCentral#4584]
Hi,
i have a fresh install MeshCentral on Ubuntu 20.04
Install ok no problem but when i connect to mongoDb i have this error 
`
Resetting power events indexes...
Resetting main indexes...
ERR: /root/node_modules/mongodb/lib/utils.js:365
                    throw error;
                    ^

TypeError: Object.fromEntries is not a function
    at CreateIndexesOperation.indexes.indexes.map.userIndex (/root/node_modules/mongodb/lib/operations/indexes.js:92:46)
    at Array.map (<anonymous>)
    at new CreateIndexesOperation (/root/node_modules/mongodb/lib/operations/indexes.js:88:32)
    at new CreateIndexOperation (/root/node_modules/mongodb/lib/operations/indexes.js:128:9)
    at Collection.createIndex (/root/node_modules/mongodb/lib/collection.js:258:78)
    at /root/node_modules/meshcentral/db.js:944:39
    at wrapper (/root/node_modules/mongodb/lib/utils.js:361:17)
    at session.endSession.endSessionError (/root/node_modules/mongodb/lib/operations/execute_operation.js:71:66)
    at wrapper (/root/node_modules/mongodb/lib/utils.js:371:9)
    at completeEndSession (/root/node_modules/mongodb/lib/sessions.js:154:17)
{ Error: Command failed: /usr/bin/node /root/node_modules/meshcentral --launch 14913
/root/node_modules/mongodb/lib/utils.js:365
                    throw error;
                    ^

TypeError: Object.fromEntries is not a function
    at CreateIndexesOperation.indexes.indexes.map.userIndex (/root/node_modules/mongodb/lib/operations/indexes.js:92:46)
    at Array.map (<anonymous>)
    at new CreateIndexesOperation (/root/node_modules/mongodb/lib/operations/indexes.js:88:32)
    at new CreateIndexOperation (/root/node_modules/mongodb/lib/operations/indexes.js:128:9)
    at Collection.createIndex (/root/node_modules/mongodb/lib/collection.js:258:78)
    at /root/node_modules/meshcentral/db.js:944:39
    at wrapper (/root/node_modules/mongodb/lib/utils.js:361:17)
    at session.endSession.endSessionError (/root/node_modules/mongodb/lib/operations/execute_operation.js:71:66)
    at wrapper (/root/node_modules/mongodb/lib/utils.js:371:9)
    at completeEndSession (/root/node_modules/mongodb/lib/sessions.js:154:17)

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:203:15)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:607:12)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   '/usr/bin/node /root/node_modules/meshcentral --launch 14913' }
ERROR: MeshCentral failed with critical error, check mesherrors.txt. Restarting in 5 seconds...
`

config.json

{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
    "_cert": "myserver.mydomain.com",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },

thanks :)

**Comment by dinger1986** [comment]
Setup Mongo apt sources
```wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | sudo apt-key add -
echo "deb http://repo.mongodb.org/apt/ubuntu $(lsb_release -cs)/mongodb-org/5.0" multiverse | sudo tee /etc/apt/sources.list.d/mongodb-org-5.0.list```

Install Mongo 
```sudo apt-get update
sudo apt-get install -y mongodb-org
sudo systemctl enable mongod
sudo systemctl start mongod```

Config needed
```"MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
"MongoDbCol": "meshcentral",```

I wrote an install script https://github.com/techahold/Meshcentral-Installer

**Comment by dinger1986** [comment]
perfect
