### ISSUE TITLE
LDAP Integration, Unable to Login

### ISSUE THREAD

**Issue by danielvizcarra00** [Ylianst/MeshCentral#4636]
**Describe your issue**
I am attempting to integrate LDAP but having issues. The server is joined to the domain. I try starting the server and I get the error that it can't parse the file (removed sensitive ldap info)

**Server Software (please complete the following information):**
 - OS: Windows 10 (Baremetal)
 - Network: LAN
 
**Your config.json file**
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
    "cert": "0.0.0.0",
    "WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "title": "MeshCentral",
      "_title2": "Servername",
      "_loginPicture": "title-sample.png",
      "welcomePicture": "hazard.png",
      "nightMode": 1,
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true

      "auth": "ldap",
      "_ldapUserName": "{{{givenName}}} {{{sn}}}",
      "_ldapUserBinaryKey": "objectSid",
      "_ldapUserEmail": "mail",
      "_ldapUserRealname": "{{{givenName}}} {{{sn}}}",
      "_ldapUserPhoneNumber": "telephoneNumber",
      "_ldapUserImage": "thumbnailPhoto",
      "_ldapSaveUserToFile": "C:\\tmp\\ldapuser-save.txt",
      "_ldapUserGroups": "memberOf",
      "_ldapUserRequiredGroupMembership": [ "CN=Domain Admins,OU=MeshCentral_,DC=com,DC=com" ],
      "_ldapSyncWithUserGroups": { "filter": [ "CN=MeshCentral_Admins" ] },
      "ldapOptions": {
        "url": "ldaps://0.0.0.0:636/",
        "tlsOptions": { "rejectUnauthorized": false },
        "bindDN": "cn=MeshCentral LDAP,ou=ServiceAccounts,dc=com,dc=com",
        "bindCredentials": "P@ssw0rd",
        "searchBase": "cn=users,dc=com,dc=com",
        "searchFilter": "(name={{username}})",
        "reconnect": true

    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}

**Comment by beefliver** [comment]
Okay, I was finally able to get it to parse the file (my error)

I am now receiving an LDAP Error: InvalidCredentialsError: 80090308: LdapErr: DSID=0C090439....

Unsure what may be causing the issue, the login creds are 100% correct

**Comment by TerAnYu** [comment]
Try using a filter:
```
"searchFilter": "(&(objectcategory=person)(objectclass=user)(|(samaccountname={{username}})(mail={{username}})))",
```

maybe these options:
```
      "ldapUserBinaryKey": "objectSid",
      "ldapUserName": "name",
      "ldapUserKey": "objectSid",
      "ldapUserEmail": "mail",
      "ldapUserRealname": "name",
      "ldapUserPhoneNumber": "telephoneNumber",
      "ldapUserImage": "thumbinalPhoto",
      "ldapUserGroups": "memberOf",
```

**Comment by beefliver** [comment]
I tried different variations of what you listed (with the proper adjustments)

I run it in --debug ldap but it doesn't display any errors through CMD, simply says that it's incorrect username or password (they're 100% correct)

This section here:
 "bindDN": "cn=meshuser,ou=sys-users,ou=users,dc=domainname,dc=loc",
        "bindCredentials": "P@ssw0rd",
        "searchBase": "ou=users,dc=domainname,dc=local",
        "searchFilter": "(&(objectcategory=person)(objectclass=user)(|(samaccountname={{username}})(mail={{username}})))",
        "reconnect": true
        
        The "searchBase" is that where it searches for the account that will provide the credentials for this integration, for example a service account strictly for this or is this asking for the location of the users that will login?

**Comment by beefliver** [comment]
Here's a screenshot
![image](https://user-images.githubusercontent.com/40252596/195888415-e9a14bc4-241c-4ad0-87ed-7dacf1e9ec22.png)

**Comment by beefliver** [comment]
This is where the group is located
![image](https://user-images.githubusercontent.com/40252596/195894737-35df8e8c-712b-4a17-aebb-82cb293c0f50.png)

**Comment by TerAnYu** [comment]
Use the program [Active Directory Explorer](https://learn.microsoft.com/en-us/sysinternals/downloads/adexplorer) to determine the exact full path for the user and/or group.

**Comment by beefliver** [comment]
Unable to install apps on AD, is there an alternative route to find out what the path is

**Comment by beefliver** [comment]
I have the correct paths, can't figure out why it doesn't connect. I start the server with --debug ldap and nothing displays when I attempt to login

**Comment by beefliver** [comment]
After restarting the PC, I now get an AssertionError

`AssertionError [ERR_ASSERTION]: Search filter not defined (opts.searchFilter)
    at new LdapAuth (C:\MeshCentral\node_modules\ldapauth-fork\lib\ldapauth.js:82:10)
    at Object.obj.authenticate (C:\MeshCentral\node_modules\meshcentral\webserver.js:698:28)
    at handleLoginRequest (C:\MeshCentral\node_modules\meshcentral\webserver.js:1110:13)
    at handleRootPostRequest (C:\MeshCentral\node_modules\meshcentral\webserver.js:3292:29)
    at Layer.handle [as handle_request] (C:\MeshCentral\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\MeshCentral\node_modules\express\lib\router\route.js:144:13)
    at C:\MeshCentral\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (C:\MeshCentral\node_modules\raw-body\index.js:231:16)
    at done (C:\MeshCentral\node_modules\raw-body\index.js:220:7)`

**Comment by TerAnYu** [comment]
Might be a strange question, but
```
npm install authenticode-js
```
done after installing MeshCentral?

**Comment by beefliver** [comment]
Nope, I did not run that command after installing.

I am able to login locally just fine, but once I try to login via LDAP - I'm greeted with errors. As mentioned, I verified that the paths are correct, just unsure what I may be doing wrong.

**Comment by null6process** [comment]
Hello beefliver,

you can change ldaps to ldap ? 
"url": "ldaps://127.0.0.1:636", to "url": "ldap://127.0.0.1:389",

delete the ssl protocol and try a gain.
