### ISSUE TITLE
Minify config error with agent invite

### ISSUE THREAD

**Issue by davscot** [Ylianst/MeshCentral#465]
Hi there,

Firstly I'd like to say fantastic work on MeshCentral, really awesome tool!

I believe I may have come across a bug when enabling config option minify.

Unless config.json option `"Minify": 1,` has other dependencies, when enabled and trying to use agent invitation method the below error is displayed in browser. 

`TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at extname (path.js:1231:5)
    at new View (/opt/meshcentral/node_modules/express/lib/view.js:56:14)
    at Function.render (/opt/meshcentral/node_modules/express/lib/application.js:570:12)
    at ServerResponse.render (/opt/meshcentral/node_modules/express/lib/response.js:1012:7)
    at handleAgentInviteRequest (/opt/meshcentral/node_modules/meshcentral/webserver.js:1176:17)
    at Layer.handle [as handle_request] (/opt/meshcentral/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/meshcentral/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/opt/meshcentral/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/opt/meshcentral/node_modules/express/lib/router/layer.js:95:5)`

When this config option is turned off agent invite works as normal.

**My system/application specs below:**
OS: CentOS 7
NPM version: 6.10.2
Node.JS version: 12.9.1
MeshCentral: 0.4.0-k

Thanks and keep up the great work!

**Comment by Ylianst** [comment]
Good catch. I will get that fixes. I am traveling now. Regular updates will resume September 12th.

**Comment by Ylianst** [comment]
I see the same problem, working on it now.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.1-b with a fix for this. By the way, thank you for the detailed report and version numbers. That was a solid bug report.

**Comment by davscot** [comment]
@Ylianst Thanks for looking into this, I can confirm this is now fixed.

Thanks also for the feedback, I'm always happy to help!

David.
