### ISSUE TITLE
MeshCentral fails to start when using signed certs by FNMT-RCM

### ISSUE THREAD

**Issue by jehweb** [Ylianst/MeshCentral#4681]
The certs are created by fnmt-rcm
I replace the certs in the meshcentral-data:

```
webserver-cert-private.key
webserver-cert-public.crt
```

but when i restart the service it fails

In the logs shows:
```
Oct 27 12:57:37 soporte systemd[1]: Started MeshCentral Server.
Oct 27 12:57:38 soporte node[28150]: Starting meshcentral syslog.
Oct 27 12:57:38 soporte meshcentral[28180]: MeshCentral v1.0.90 Server Start
Oct 27 12:57:38 soporte meshcentral-auth[28180]: MeshCentral v1.0.90 Server Start
Oct 27 12:57:38 soporte meshcentral-auth[28180]: MeshCentral v1.0.90 Server Start
Oct 27 12:57:38 soporte node[28150]: Starting meshcentral-json JSON syslog.
Oct 27 12:57:38 soporte node[28150]: Starting meshcentral-auth auth syslog.
Oct 27 12:57:38 soporte node[28150]: MeshCentral HTTP redirection server running on port 80.
Oct 27 12:57:38 soporte meshcentral-auth[28180]: Server listening on 0.0.0.0 port 80.
Oct 27 12:57:38 soporte node[28150]: ERR: /home/antram/node_modules/meshcentral/certoperations.js:925
Oct 27 12:57:38 soporte node[28150]:             r.WebIssuer = webCertificate.issuer.getField('CN').value;
Oct 27 12:57:38 soporte node[28150]:                                                               ^
Oct 27 12:57:38 soporte node[28150]: TypeError: Cannot read property 'value' of null
Oct 27 12:57:38 soporte node[28150]:     at Object.obj.GetMeshServerCertificate (/home/antram/node_modules/meshcentral/certoperations.js:925:63)
Oct 27 12:57:38 soporte node[28150]:     at CreateMeshCentralServer.obj.StartEx2 (/home/antram/node_modules/meshcentral/meshcentral.js:1533:35)
Oct 27 12:57:38 soporte node[28150]:     at Server.<anonymous> (/home/antram/node_modules/meshcentral/redirserver.js:146:13)
Oct 27 12:57:38 soporte node[28150]:     at Object.onceWrapper (events.js:519:28)
Oct 27 12:57:38 soporte node[28150]:     at Server.emit (events.js:400:28)
Oct 27 12:57:38 soporte node[28150]:     at emitListeningNT (net.js:1365:10)
Oct 27 12:57:38 soporte node[28150]:     at processTicksAndRejections (internal/process/task_queues.js:81:21)
Oct 27 12:57:38 soporte node[28150]: ERROR: Unable to write to mesherrors.txt.
Oct 27 12:57:38 soporte node[28150]: Error: Command failed: /usr/bin/node /home/antram/node_modules/meshcentral --launch 28150
Oct 27 12:57:38 soporte node[28150]: /home/antram/node_modules/meshcentral/certoperations.js:925
Oct 27 12:57:38 soporte node[28150]:             r.WebIssuer = webCertificate.issuer.getField('CN').value;
Oct 27 12:57:38 soporte node[28150]:                                                               ^
Oct 27 12:57:38 soporte node[28150]: TypeError: Cannot read property 'value' of null
Oct 27 12:57:38 soporte node[28150]:     at Object.obj.GetMeshServerCertificate (/home/antram/node_modules/meshcentral/certoperations.js:925:63)
Oct 27 12:57:38 soporte node[28150]:     at CreateMeshCentralServer.obj.StartEx2 (/home/antram/node_modules/meshcentral/meshcentral.js:1533:35)
Oct 27 12:57:38 soporte node[28150]:     at Server.<anonymous> (/home/antram/node_modules/meshcentral/redirserver.js:146:13)
Oct 27 12:57:38 soporte node[28150]:     at Object.onceWrapper (events.js:519:28)
Oct 27 12:57:38 soporte node[28150]:     at Server.emit (events.js:400:28)
Oct 27 12:57:38 soporte node[28150]:     at emitListeningNT (net.js:1365:10)
Oct 27 12:57:38 soporte node[28150]:     at processTicksAndRejections (internal/process/task_queues.js:81:21)
Oct 27 12:57:38 soporte node[28150]:     at ChildProcess.exithandler (child_process.js:383:12)
Oct 27 12:57:38 soporte node[28150]:     at ChildProcess.emit (events.js:412:35)
Oct 27 12:57:38 soporte node[28150]:     at maybeClose (internal/child_process.js:1088:16)
Oct 27 12:57:38 soporte node[28150]:     at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5) {
Oct 27 12:57:38 soporte node[28150]:   killed: false,
Oct 27 12:57:38 soporte node[28150]:   code: 1,
Oct 27 12:57:38 soporte node[28150]:   signal: null,
Oct 27 12:57:38 soporte node[28150]:   cmd: '/usr/bin/node /home/antram/node_modules/meshcentral --launch 28150'
Oct 27 12:57:38 soporte node[28150]: }
Oct 27 12:57:38 soporte node[28150]: ERROR: MeshCentral failed with critical error, check mesherrors.txt. Restarting in 5 seconds...
```

My question is, could be the fnmt certificate incompatible?

If create my own certificate in a ubuntu22.04 and i replace them in meshcentral-data, i restart the service and it works well

**Comment by Ylianst** [comment]
Hi. The files `webserver-cert-private.key` and `webserver-cert-public.crt` are PKCS formatted, so they are text files that you can open with a text editor. Open the originals with a text editor and take a look at the general format and make sure your new certificates are in the same format.

If that looks ok, let me know. I am not familiar with `fnmt-rcm`, but I can't image their certificate would not include a issuer common name (CN), that would be super weird. If you still see the problem, if you want, [you can mail me](https://www.meshcommander.com/contact-information) the public part of your certificate (NOT the private key) and I will make sure MeshCentral can work with it.

**Comment by Ylianst** [comment]
I got the certificate and your right. Fix will be in MeshCentral v1.0.96.

**Comment by jehweb** [comment]
Thank you very much, i will test it in the next release

**Comment by jehweb** [comment]
I have tested it and it works very well, problem solved, thank you
