### ISSUE TITLE
RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: NaN

### ISSUE THREAD

**Issue by si458** [Ylianst/MeshCentral#4696]
**Describe the bug**
I setup a group to relay through an agent, added my printer, clicked https to relay, got a blank white page,
refreshed page a few times, then i get server disconnected error,
check mesherrors.txt and see the following errors (also the meshcentral server restarted itself)
```
-------- 11/1/2022, 3:11:17 PM ---- 1.0.93 --------
node:_http_server:314
    throw new ERR_HTTP_INVALID_STATUS_CODE(originalStatusCode);
    ^
RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: NaN
    at new NodeError (node:internal/errors:387:5)
    at ServerResponse.writeHead (node:_http_server:314:11)
    at ServerResponse.writeHead (/home/simon/meshcentral/node_modules/on-headers/index.js:44:26)
    at ServerResponse.writeHead (/home/simon/meshcentral/node_modules/on-headers/index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:305:8)
    at ServerResponse.write (/home/simon/meshcentral/node_modules/compression/index.js:84:14)
    at processHttpResponse (/home/simon/meshcentral/node_modules/meshcentral/apprelays.js:724:41)
    at Object.obj.close (/home/simon/meshcentral/node_modules/meshcentral/apprelays.js:396:13)
    at WebSocket.<anonymous> (/home/simon/meshcentral/node_modules/meshcentral/apprelays.js:498:124)
    at WebSocket.emit (node:events:513:28)
    at WebSocket.emitClose (/home/simon/meshcentral/node_modules/ws/lib/websocket.js:172:10)
    at TLSSocket.socketOnClose (/home/simon/meshcentral/node_modules/ws/lib/websocket.js:781:15)
    at TLSSocket.emit (node:events:525:35)
    at node:net:301:12
    at TCP.done (node:_tls_wrap:588:7) {
  code: 'ERR_HTTP_INVALID_STATUS_CODE'
}
```

**To Reproduce**

**Expected behavior**
to relay the https web panel of my printer to my laptop

**Screenshots**

**Server Software (please complete the following information):**
 - OS: Ubuntu 22.04.1
 - Virtualization: None
 - Network: Hybrid Mode, No Proxy, Direct Connect, SSL
 - Version: 1.0.93
 - Node: 16.18.0

**Client Device (please complete the following information):**
 - Device: Laptop
 - OS: Windows 11 Home
 - Network: WAN
 - Browser: Firefox
 - MeshCentralRouter Version: [if applicable] N/A

**Remote Device (please complete the following information):**
 - Device:  Agent is server 2012 r2 x64, relayed device is Ricoh Printer
 - OS: Agent is server 2012 r2 x64, relayed device is Ricoh Printer
 - Network: WAN
 - Current Core Version (if known): [**HINT**: Go to a device then `console` Tab then type `info`] Aug 25 2022, 461107747

**Additional context**

**Your config.json file**
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "cert": "meshcentral.myserver.com",
    "sessionKey": "myserver",
    "port": 443,
    "noAgentUpdate": 1,
    "redirPort": 80,
    "AgentPong": 300,
    "authLog": "authlog.log",
    "relayDNS": "relay.meshcentral.myserver.com",
    "autoBackup": {
      "backupIntervalHours": 12,
      "keepLastDaysBackup": 7,
      "backupPath": "meshcentral-backup"
    }
  },
  "domains": {
    "": {
      "agentInviteCodes": true,
      "title": "myserver",
      "agentCustomization": {
        "companyName": "myserver Ltd",
        "image": "128x128.png"
      },
      "assistantCustomization": {
        "image": "128x128.png"
      },
      "androidCustomization": {
        "image": "128x128.png"
      }
    }
  },
  "letsencrypt": {
    "email": "simon@myserver.com",
    "names": "meshcentral.myserver.com,relay.myserver.mefoo.com",
    "skipChallengeVerification": false,
    "production": true
  }
}
```

**Comment by Ylianst** [comment]
Ok, I think I fixed it. I also notices that web relay did not work when using with local device groups, so I also fixed that. Once MeshCentral v1.0.95 is out, let me know if you see this again.
