### ISSUE TITLE
Lets encrypt certificates installation failed

### ISSUE THREAD

**Issue by 315i** [Ylianst/MeshCentral#47]
Hi, I have some issues with installing Letsencrypt certificates.ERROR: Unable to setup GreenLock module. aapears. Folder letsencrypt is created, but no certs are installed.

This is my letsencrypt config file part

"letsencrypt": {
    "email": "my@email.com",
    "names": "mydomain.com",
    "rsaKeySize": 3072,
    "production": false
  },

This is what log file says on tarting the service.
-- The start-up result is done.
Dec 05 15:18:02 subdomain.mydomain.com polkitd[1669]: Unregistered Authentication Agent for unix-process:6210:200860242 (sy
Dec 05 15:18:03 subdomain.mydomain.com meshstart.sh[6216]: Installing greenlock...
Dec 05 15:18:12 subdomain.mydomain.com meshstart.sh[6216]: Installing le-store-certbot...
Dec 05 15:18:15 subdomain.mydomain.com meshstart.sh[6216]: Installing le-acme-core...
Dec 05 15:18:23 subdomain.mydomain.com meshstart.sh[6216]: Installing le-store-certbot...
Dec 05 15:18:26 subdomain.mydomain.com meshstart.sh[6216]: MeshCentral HTTP redirection web server running on port 80.
Dec 05 15:18:26 subdomain.mydomain.com meshstart.sh[6216]: ERROR: Unable to setup GreenLock module.
Dec 05 15:18:26 subdomain.mydomain.com meshstart.sh[6216]: MeshCentral Intel(R) AMT server running on subdomain.mydomain.com:
Dec 05 15:18:26 subdomain.mydomain.com meshstart.sh[6216]: MeshCentral HTTPS web server running on subdomain.mydomain.com:443

GreenLog is installed.

[root@myhost meshcentral-data]# npm list | grep green
+-T greenlock@2.4.10

-------- 12/5/2018, 3:35:51 PM ---- 0.2.2-t --------

TypeError: util.promisify is not a function
    at Object.<anonymous> (/opt/meshcentral/node_modules/le-store-certbot/index.js:18:24)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.module.exports.CreateLetsEncrypt (/opt/meshcentral/node_modules/meshcentral/letsencrypt.js:34:51)
    at /opt/meshcentral/node_modules/meshcentral/meshcentral.js:390:38
    at Object.obj.GetMeshServerCertificate (/opt/meshcentral/node_modules/meshcentral/certoperations.js:263:43)
    at CreateMeshCentralServer.obj.StartEx2 (/opt/meshcentral/node_modules/meshcentral/meshcentral.js:385:35)
    at Server.<anonymous> (/opt/meshcentral/node_modules/meshcentral/redirserver.js:108:13)
    at Server.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Server.emit (events.js:185:7)

  OS is CentOS 7 with latest patches.

**Comment by Ylianst** [comment]
Hi. It looks like you are using an older version of MeshCentral v0.2.2-t. Current version is 0.2.4-c and I think I fixed this problem a few weeks back. Your probably using node 6.x or 7.x and promisify does not exist in these versions. However, I poly filled it if needed in the latest MeshCentral.

Can you try upgrading MeshCentral and try again? - Thanks.

**Comment by 315i** [comment]
@Ylianst ,
thanks for your prompt response. After upgrade to  0.2.4-c  now everything works fine.
Thanks for your time and good work.
