### ISSUE TITLE
Telegram proxy error

### ISSUE THREAD

**Issue by bravery-only** [Ylianst/MeshCentral#4703]
This error is created in the mesh error file:

```
C:\Program Files\Open Source\MeshCentral\node_modules\telegram\extensions\PromisedNetSockets.js:37
                    throw new Error(`Invalid sockets params. ${proxy.ip}, ${proxy.port}, ${proxy.socksType}`);
                          ^

Error: Invalid sockets params. xx.xx.xx.xx, xxxx, undefined
    at new PromisedNetSockets (C:\Program Files\Open Source\MeshCentral\node_modules\telegram\extensions\PromisedNetSockets.js:37:27)
    at new Connection (C:\Program Files\Open Source\MeshCentral\node_modules\telegram\network\connection\Connection.js:31:23)
    at new ConnectionTCPFull (C:\Program Files\Open Source\MeshCentral\node_modules\telegram\network\connection\TCPFull.js:50:9)
    at TelegramClient.connect (C:\Program Files\Open Source\MeshCentral\node_modules\telegram\client\TelegramClient.js:1055:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.start (C:\Program Files\Open Source\MeshCentral\node_modules\telegram\client\auth.js:32:9)
    at async setupTelegram (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\meshmessaging.js:159:21)
```

-------------------------
My Config.json Telegram codes:

```
 "messaging": {
      "telegram": {
         "apiid": 1111111, 
         "apihash": "abc", 
         "bottoken": "abc:ahjdhfhhfh", 
         "useWSS": false, 
         "proxy": {
            "ip": "xx.xx.xx.xx", 
            "port": xxxx, 
            "MTProxy": true, 
            "secret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 
            "socksType": 5, 
            "timeout": 2
         }
      }
   }

```

**Comment by Ylianst** [comment]
You can see [the exact instructions here](https://gram.js.org/getting-started/authorization#using-mtproxies-and-socks5-proxies) from the Telegram library I use. If you have a test proxy settings you want to send me privately, I can give it a try. [My contact info is here](https://www.meshcommander.com/contact-information).

Note that the error is not in MeshCentral, but in the Telegram library I use, but I can try to help.

**Comment by paolor1965** [comment]
hi 
i configured dante socks server and for testing i configured firefox with the settings of the socks server and socks work

dante config
logoutput: syslog
user.privileged: root
user.unprivileged: nobody

# The listening network interface or address.
internal: ens18

# The proxying network interface or address.
external: ens18

# socks-rules determine what is proxied through the external interface.
socksmethod: username

# client-rules determine who can connect to the internal interface.

#authentication methods
clientmethod: none
method: none




client pass {
    from: 0.0.0.0/0 to: 0.0.0.0/0
}

#socks pass {
#    from: 0.0.0.0/0 to: 0.0.0.0/0
#}

socks pass {
from: 0.0.0.0/0 to: 0.0.0.0/0
command: bind connect udpassociate bindreply udpreply    (setting found  on forum)
log: error connect
}




"messaging": {
    "telegram": {
      "apiid": xxx,
      "apihash": "xxx",
      "session": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "useWSS": false,
      "proxy": {
      "ip":"xxx.xxx.xxx.xxx",
      "port":1080,
     "MTProxy":false,
     "secret":"00000000000000000000000000000000",
     "socksType": 5,
     "timeout": 5
        }
        }
},



i configured mesh by adding proxy options: mesh starts with the following error



(node:107887) UnhandledPromiseRejectionWarning: Error: Invalid sockets params. xxx.xxx.xxx.xxx, 1080, undefined
    at new PromisedNetSockets (/srv/meshcentral/node_modules/telegram/extensions/PromisedNetSockets.js:41:27)
    at new Connection (/srv/meshcentral/node_modules/telegram/network/connection/Connection.js:31:23)
    at new ConnectionTCPFull (/srv/meshcentral/node_modules/telegram/network/connection/TCPFull.js:50:9)
    at TelegramClient.connect (/srv/meshcentral/node_modules/telegram/client/TelegramClient.js:1059:28)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.start (/srv/meshcentral/node_modules/telegram/client/auth.js:36:9)
    at async setupTelegram (/srv/meshcentral/node_modules/meshcentral/meshmessaging.js:151:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:107887) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:107887) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Ylianst** [comment]
Thank you, that is good details. Looking into it now.

**Comment by Ylianst** [comment]
Ok, found the problem. Working on a fix for it.

**Comment by Ylianst** [comment]
Fixed, will be in MeshCentral v1.0.96.

**Comment by bravery-only** [comment]
> Fixed, will be in MeshCentral v1.0.96.

@Ylianst , we are still waiting for the release of version 1.0.96

**Comment by si458** [comment]
@bravery-only please be patient, @Ylianst is a 1 man band!

**Comment by Ylianst** [comment]
I got distracted today in a big way. I will release 1.0.96 tomorrow.

**Comment by paolor1965** [comment]
after upgrade to 1.0.97 i get the following error using proxy telegram


-------- 11/7/2022, 9:45:46 AM ---- 1.0.97 --------

(node:113115) UnhandledPromiseRejectionWarning: Error: Connection to telegram failed after 5 time(s)
    at MTProtoSender._connect (/srv/meshcentral/node_modules/telegram/network/MTProtoSender.js:255:19)
    at async MTProtoSender.connect (/srv/meshcentral/node_modules/telegram/network/MTProtoSender.js:147:13)
    at async TelegramClient.connect (/srv/meshcentral/node_modules/telegram/client/TelegramClient.js:1068:15)
    at async Object.start (/srv/meshcentral/node_modules/telegram/client/auth.js:36:9)
    at async setupTelegram (/srv/meshcentral/node_modules/meshcentral/meshmessaging.js:152:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:113115) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:113115) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
