### ISSUE TITLE
Issue enabling MongoDB on fresh install in Ubuntu 20.04

### ISSUE THREAD

**Issue by astrugatch** [Ylianst/MeshCentral#4772]
**Describe your issue**
Cannot enable MongoDB after installing MeshCentral on ubuntu 20.04

**Server Software (please complete the following information):**
 - OS: Ubuntu 20.04
 - Virtualization: VMWare
 - Network: Local
 - Version: Latest
 - Node: 10.19.0

**Your config.json file**
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
    "_cert": "myserver.mydomain.com",
    "WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}
```
Doing a clean install of Mesh Central following the wiki here:https://meshcentral-community.com/doku.php?id=howto:installation:manual:ubuntu

At the point of enabling mongo db. Removed the _ from MongoDb and WANonly per the example. 
When trying to run `node ./node_modules/meshcentral` I get the following error:

```
Resetting main indexes...
Resetting server stats indexes...
ERR: /home/meshadmin/node_modules/mongodb/lib/operations/indexes.js:92
            const validIndexOptions = Object.fromEntries(Object.entries({ ...userIndex }).filter(([optionName]) => VALID_INDEX_OPTIONS.has(optionName)));
                                             ^

TypeError: Object.fromEntries is not a function
    at CreateIndexesOperation.indexes.indexes.map.userIndex (/home/meshadmin/node_modules/mongodb/lib/operations/indexes.js:92:46)
    at Array.map (<anonymous>)
    at new CreateIndexesOperation (/home/meshadmin/node_modules/mongodb/lib/operations/indexes.js:88:32)
    at new CreateIndexOperation (/home/meshadmin/node_modules/mongodb/lib/operations/indexes.js:128:9)
    at Collection.createIndex (/home/meshadmin/node_modules/mongodb/lib/collection.js:258:78)
    at /home/meshadmin/node_modules/meshcentral/db.js:844:34
    at wrapper (/home/meshadmin/node_modules/mongodb/lib/utils.js:371:9)
    at session.endSession.endSessionError (/home/meshadmin/node_modules/mongodb/lib/operations/execute_operation.js:71:66)
    at wrapper (/home/meshadmin/node_modules/mongodb/lib/utils.js:371:9)
    at completeEndSession (/home/meshadmin/node_modules/mongodb/lib/sessions.js:154:17)
{ Error: Command failed: /usr/bin/node /home/meshadmin/node_modules/meshcentral --launch 1050
/home/meshadmin/node_modules/mongodb/lib/operations/indexes.js:92
            const validIndexOptions = Object.fromEntries(Object.entries({ ...userIndex }).filter(([optionName]) => VALID_INDEX_OPTIONS.has(optionName)));
                                             ^

TypeError: Object.fromEntries is not a function
    at CreateIndexesOperation.indexes.indexes.map.userIndex (/home/meshadmin/node_modules/mongodb/lib/operations/indexes.js:92:46)
    at Array.map (<anonymous>)
    at new CreateIndexesOperation (/home/meshadmin/node_modules/mongodb/lib/operations/indexes.js:88:32)
    at new CreateIndexOperation (/home/meshadmin/node_modules/mongodb/lib/operations/indexes.js:128:9)
    at Collection.createIndex (/home/meshadmin/node_modules/mongodb/lib/collection.js:258:78)
    at /home/meshadmin/node_modules/meshcentral/db.js:844:34
    at wrapper (/home/meshadmin/node_modules/mongodb/lib/utils.js:371:9)
    at session.endSession.endSessionError (/home/meshadmin/node_modules/mongodb/lib/operations/execute_operation.js:71:66)
    at wrapper (/home/meshadmin/node_modules/mongodb/lib/utils.js:371:9)
    at completeEndSession (/home/meshadmin/node_modules/mongodb/lib/sessions.js:154:17)

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:203:15)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:607:12)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   '/usr/bin/node /home/meshadmin/node_modules/meshcentral --launch 1050' }
ERROR: MeshCentral failed with critical error, check mesherrors.txt. Restarting in 5 seconds...
```

**Comment by UFOTyler** [comment]
Same issue on new install here as well... also running Ubuntu 20.04 LTS..

**Comment by Levynger** [comment]
SAme issue on Clean INstall, Unable to connect to local MongoDB.
Same exact Error

**Comment by rpppng** [comment]
Same issue... How we can resolve this?

**Comment by levyalon** [comment]
eventually, i ended up using this script:
https://github.com/techahold/Meshcentral-Installer

**Comment by matt-pathr** [comment]
I saw this on updating an existing installation to 1.1.0,  Was there specific Fix?

**Comment by rajanJain1991** [comment]
@Ylianst Hi 
I am facing the same issue after updating meshcentral as my old version was not supporting letsencrypt. But now I have run into trouble with this and my machines are not showing anymore. I had tried to reinstall mongodb@4.12.1 looking at the errors. Not sure what went wrong.

**Comment by github0004** [comment]
Any fix for this on a docker container?
