### ISSUE TITLE
UserAllowedIP error

### ISSUE THREAD

**Issue by wh1te909** [Ylianst/MeshCentral#48]
OS: Centos 7.5
node v: 10.14.1
MeshCentral: v0.2.4-e

Added an IP address to UserAllowedIP and it appeared to be working since when trying to access from another IP, got "Unauthorized"
However once logged in with an allowed IP, node throws the following error and the page keeps reloading and eventually says server disconnected:

`TypeError: Cannot read property 'startsWith' of undefined
    at checkUserIpAddressEx (/meshcentral/node_modules/meshcentral/webserver.js:285:20)
    at checkUserIpAddress (/meshcentral/node_modules/meshcentral/webserver.js:297:17)
    at PerformWSSessionAuth (/meshcentral/node_modules/meshcentral/webserver.js:1886:26)
    at /meshcentral/node_modules/meshcentral/webserver.js:1846:63
    at /meshcentral/node_modules/express-ws/lib/wrap-middleware.js:13:9
    at Layer.handle [as handle_request] (/meshcentral/node_modules/express/lib/router/layer.js:95:5)
    at next (/meshcentral/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/meshcentral/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/meshcentral/node_modules/express/lib/router/layer.js:95:5)
    at /meshcentral/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/meshcentral/node_modules/express/lib/router/index.js:335:12)
    at next (/meshcentral/node_modules/express/lib/router/index.js:275:10)
    at /meshcentral/node_modules/meshcentral/webserver.js:1812:20
    at Layer.handle [as handle_request] (/meshcentral/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/meshcentral/node_modules/express/lib/router/index.js:317:13)
    at /meshcentral/node_modules/express/lib/router/index.js:284:7`

**Comment by jsastriawan** [comment]
I think the culprit is 
``
if (ip.startsWith('::ffff:')) { ip = ip.substring(7); } // Fix IPv4 IP's encoded in IPv6 form
``

it should have been
``
if (ip !=null && ip.startsWith('::ffff:')) { ip = ip.substring(7); } // Fix IPv4 IP's encoded in IPv6 form
``

**Comment by Ylianst** [comment]
Just published MeshCentral v0.2.4-f with a fix for this. The change above will just skip the security check which is not a fix. Instead the IP address for a web socket needs to be retrieved and checked correctly.
