### ISSUE TITLE
Cannot install plugins in dockerized meshcentral

### ISSUE THREAD

**Issue by stavros-k** [Ylianst/MeshCentral#4843]
**Describe the bug**

While trying to install the plugin (any plugin) in meshcentral running in Docker (Dockerfile from MC repo), I got the following:

```shell
Error instantiating new plugin:  Error: Cannot find module 'mongodb'
Require stack:
- /opt/meshcentral/meshcentral-data/plugins/scripttask/db.js
- /opt/meshcentral/meshcentral-data/plugins/scripttask/scripttask.js
- /opt/meshcentral/meshcentral/pluginHandler.js
- /opt/meshcentral/meshcentral/meshcentral.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.module.exports.CreateDB (/opt/meshcentral/meshcentral-data/plugins/scripttask/db.js:254:7)
    at Object.obj.server_startup (/opt/meshcentral/meshcentral-data/plugins/scripttask/scripttask.js:38:85)
    at Timeout._onTimeout (/opt/meshcentral/meshcentral/pluginHandler.js:427:146)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/meshcentral/meshcentral-data/plugins/scripttask/db.js',
    '/opt/meshcentral/meshcentral-data/plugins/scripttask/scripttask.js',
    '/opt/meshcentral/meshcentral/pluginHandler.js',
    '/opt/meshcentral/meshcentral/meshcentral.js'
  ]
}       
```

I resolved it by copying 
`/opt/meshcentral/meshcentral/node_modules` to `/opt/meshcentral/meshcentral-data/plugins/`

Of course this is not a permanent solution, and I'd like to ask if it's possible to update plugins, to resolve node_modules from the original path.

**To Reproduce**
1. Go to Server -> Plugins
2. Install any plugin
3. See error

**Expected behavior**

Plugin to install without errors

**Screenshots**

**Server Software (please complete the following information):**
 - OS: Truenas SCALE
 - Virtualization: Docker / Kubernetes
 - Network: [e.g. LAN/WAN, reverse proxy, cloudflare, ssl offload, etc...] Reverse Proxy
 - Version: [e.g. 1.0.43] 1.1.0
 - Node: [e.g. 18.4.0] v16.17.1

**Client Device (please complete the following information):**
 - Device: [e.g. Laptop]
 - OS: [e.g. Ubuntu]
 - Network: [e.g. Local to Meshcentral, Remote over WAN]
 - Browser: [e.g. Google Chrome]
 - MeshCentralRouter Version: [if applicable]

**Remote Device (please complete the following information):**
 - Device: [e.g. Laptop]
 - OS: [e.g. Windows 10 21H2]
 - Network: [e.g. Local to Meshcentral, Remote over WAN]
 - Current Core Version (if known): [**HINT**: Go to a device then `console` Tab then type `info`]

**Additional context**

**Your config.json file**
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "domains": {
    "": {
      "agentConfig": [
        "webSocketMaskOverride=1"
      ],
      "agentCustomization": {
        "backgroundColor": "40,40,40",
        "companyName": "TrueCharts Mesh Agent",
        "description": "TrueCharts Mesh Agent Background Service",
        "displayName": "TrueCharts MeshCentral Agent",
        "fileName": "truecharts_meshagent",
        "foregroundColor": "0,149,213",
        "serviceName": "TrueCharts Mesh Agent"
      },
      "certUrl": "https://mesh.DOMAIN.me",
      "clipboardGet": true,
      "clipboardSet": true,
      "deviceMeshRouterLinks": {
        "rdp": true,
        "scp": true,
        "ssh": true
      },
      "geoLocation": true,
      "ipkvm": false,
      "localSessionRecording": true,
      "minify": true,
      "mobileSite": true,
      "mstsc": true,
      "myServer": {
        "Backup": true,
        "Console": true,
        "ErrorLog": true,
        "Restore": true,
        "Trace": true,
        "Upgrade": false
      },
      "newAccounts": false,
      "nightMode": 0,
      "novnc": true,
      "siteStyle": 2,
      "ssh": true,
      "title": "MeshCentral",
      "title2": "TrueCharts",
      "userNameIsEmail": false,
      "welcomeText": "Welcome to TrueCharts MeshCentral"
    }
  },
  "settings": {
    "LANonly": false,
    "WANonly": false,
    "agentCoreDump": false,
    "agentLogDump": false,
    "agentWsCompression": true,
    "aliasPort": 443,
    "allowFraming": false,
    "allowHighQualityDesktop": true,
    "allowLoginToken": false,
    "autobackup": {
      "backupIntervalHours": 24,
      "backupPath": "/opt/meshcentral/meshcentral-backup",
      "keepLastDaysBackup": 10,
      "mongoDumpPath": "/usr/bin/mongodump"
    },
    "cert": "mesh.DOMAIN.me",
    "cleanNpmCacheOnUpdate": false,
    "compression": true,
    "dbExpire": {
      "events": 1728000,
      "powerevents": 864000,
      "statsevents": 2592000
    },
    "keepCerts": false,
    "maxInvalid2fa": {
      "coolofftime": 30,
      "count": 10,
      "time": 10
    },
    "maxInvalidLogin": {
      "coolofftime": 30,
      "count": 10,
      "time": 10
    },
    "mongoDB": "mongodb://meshcentral:somebigpass@meshcentral-mongodb:27017/meshcentral",
    "mongoDbBulkOperations": true,
    "mongoDbName": "meshcentral",
    "newAccounts": false,
    "nice404": true,
    "plugins": {
      "enabled": true
    },
    "port": 10205,
    "selfUpdate": false,
    "sessionKey": somebigkey",
    "sessionSameSite": "lax",
    "sessionTime": 60,
    "tlsOffload": "traefik.ix-traefik.svc.cluster.local",
    "trustedProxy": "traefik.ix-traefik.svc.cluster.local",
    "webRTC": true,
    "wsCompression": true
  }
```

**Comment by yourh3ro** [comment]
I also use meshcentral + mongodb in the same docker-compose file and plugins are installed normally.

You can show your docker-compose.yml? I have a suspicion that you have not moved /opt/meshcentral/meshcentral-data/ to a separate volume... Well, or something similar. Show your docker-compose file

**Comment by stavros-k** [comment]
> I also use meshcentral + mongodb in the same docker-compose file and plugins are installed normally.
> 
> You can show your docker-compose.yml? I have a suspicion that you have not moved /opt/meshcentral/meshcentral-data/ to a separate volume... Well, or something similar. Show your docker-compose file

It's in kubernetes. But I do have seperate volume for that path

https://github.com/truecharts/charts/blob/ce12b962cf538097b143c8236f159e12dc24f970/charts/stable/meshcentral/values.yaml#L978-L1003

**Comment by si458** [comment]
did you resolve this?

**Comment by stavros-k** [comment]
Nope, 
I don't personally use it containerized currently, but it was a bug report in our [catalog](https://github.com/truecharts/charts)

**Comment by si458** [comment]
thanks @stavros-k 
im looking into trying to fix the docker image but its bloody complicated as so many different options and combinations

**Comment by jacobalberty** [comment]
@si458 did you ever make any progress on this? I am still seeing this issue. I'm willing to take a look myself but I don't work with nodejs much so if you had any notes from this it would be helpful. The workaround of copying node_modules does still work. Maybe we can get an errata here in the docs for the docker-compose setup. A one-liner like
```
docker compose exec meshcentral cp -a /opt/meshcentral/meshcentral/node_modules /opt/meshcentral/meshcentral-data/plugins/
```
Fixes plugins  but of course it must be rerun any time the modules change so not a good longterm fix

**Comment by si458** [comment]
@jacobalberty plugins are not officially supported by meshcentral, the interface api for plugins is provided as is.
Also from what I'm aware some of the plugins like scripttask don't actually work at the moment with the latest version of meshcentral even run in a normal environment with npm rather than docker
But I will try have a look next week when I get chance

**Comment by si458** [comment]
@jacobalberty that's fine have a cracking and if u make any progress do let us no or provide PR 😉

**Comment by Pshemas** [comment]
I'm experiencing the same issue, npm can't install / update components. The issue seems to be not with MC, but with npm. Which on my end is a big deal - I use oidc to manage users, so without working plugins I don't have working MC.

It seems `registry.npmjs.org` has some tricky proxy setup and npm inside container couldn't resolve this address. Don't know the proper solution, but here's my workaround.

I checked to what ip(s) `registry.npmjs.org` resolves on my regular desktop by issueing `host registry.npmjs.org` command.
I've noted the address and added entry in compose file:

```
extra_hosts:
 - "registry.npmjs.org:<IP_OF_REGISTRY>"
```

After restarting the container all worked normally.

**Comment by DaanSelen** [comment]
Can you try this again in the new master image? It should have been built by now!

**Comment by DaanSelen** [comment]
https://github.com/Ylianst/MeshCentral/actions/runs/15393495690/job/43308263561 its still running!

**Comment by DaanSelen** [comment]
I think this is fixed.

**Comment by si458** [comment]
should be fixed in next release now!
