### ISSUE TITLE
Error: EACCES: permision denied

### ISSUE THREAD

**Issue by cRubianco** [Ylianst/MeshCentral#4935]
**_Hi
I have the following error:_**

"Error: EACCES: permission denied, open '/home/tecnico/meshcentral-data/meshagent'
Emitted 'error' event on WriteStream instance at:
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at WriteStream.onerror (_stream_readable.js:754:7)
    at WriteStream.emit (events.js:314:20)
    at internal/fs/streams.js:361:12
    at FSReqCallback.oncomplete (fs.js:156:23) {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/home/tecnico/meshcentral-data/meshagent'
}"

_**Server Software**_ 
 - OS: [Ubuntu 22.04]
 - Virtualization: [none]
 - Network: [LAN/WAN]
 - Version: [1.0.72]
 - Node: [v12.22.9]
"

**_I need your help for restore previuos state, thank you_**

**Comment by nzalev** [comment]
It does not have permission to open the specified file path.

Make sure that the user which is running the meshcentral service has access to the file path `/home/tecnico/meshcentral-data/meshagent`

There is either an issue with the permissions or file ownership. The issue can be in any of the directories in the hierarchy.

**Comment by cRubianco** [comment]
Thanks Nzalev, I was able to solve it.
