### ISSUE TITLE
MeshCentralRouter - Unhandled Exception during login

### ISSUE THREAD

**Issue by fornax-a** [Ylianst/MeshCentral#4947]
When attempting to login via MeshCentralRouter we find the application exists unexpectedly, with an unhandled exception reported by the .NET Runtime.

**To Reproduce**

1. Download the MeshCentralRouter binary from your MeshCentral 'My Devices' page.
2. Launch the executable.
3. Enter your server/credential details and \<click\> login.
4. Observe the application exit without warning. 

**debug.log**
```
UnhandledExceptionEventSink: System.NullReferenceException: Object reference not set to an instance of an object.
   at MeshCentralRouter.webSocketClient.OnConnectSink(IAsyncResult ar)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Sockets.Socket.ConnectCallback()
   at System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback(Object state, Boolean timedOut)
```

**Expected behavior**

Application should connect to server and list available devices.

**Screenshots**

![MeshCentralRouter](https://user-images.githubusercontent.com/94235837/215282471-4e44ea7e-426b-424f-aa84-1daeab956e56.gif)

**Server Software (please complete the following information):**

 - OS: Ubuntu 22.04 LTS
 - Virtualization: Proxmox LXC
 - Network: LAN
 - Version: 1.1.2
 - Node: 12.22.9

**Client Device (please complete the following information):**

 - Device: Laptop
 - OS: Windows 10 21H2
 - Network:  Remote over VPN (Natting involved)
 - Browser: Edge
 - MeshCentralRouter Version: 1.8.8332

**Remote Device (please complete the following information):**

N/A

**Additional context**
This may be anecdotal - But soon before this issue was identified MeshCentral was upgraded to v1.1.2 - MeshCentralRouter has functioned previously, with the existing setup otherwise unchanged, however the last connection via this method was several months ago.

**Your config.json file**

N/A - _Will be provided at a future point if necessary._

**Comment by PathfinderNetworks** [comment]
What happens when, instead of launching the MeshCentralrouter.exe directly and manually entering your logon info you click on the 'Launch MeshCentral Router' button in that popup?  Doing so enters the logon token automatically as the application starts.  I suspect there may be something going on with 2FA (assuming you have that enabled?) when trying to manually log in to the MeshCentral router. 
When I run the MeshCentralrouter.exe using the Launch MeshCentral Router button it works perfectly.
