### ISSUE TITLE
JavaScript heap out of memory again

### ISSUE THREAD

**Issue by github0004** [Ylianst/MeshCentral#4958]
Running into this problem I keep seeing everywhere but no confirmed fix.

Things I've tried:
- Used different docker images
- Using MongoDB currently
- Tried https://stackoverflow.com/questions/38558989/node-js-heap-out-of-memory
- Tried npm install increase-memory-limit and ran it with confirmed results it increased meshcentral bin file.
- Tried upgrading npm

```
Installing` otplib@10.2.3...
MeshCentral HTTP redirection server running on port 80.
MeshCentral v1.0.85, Hybrid (LAN + WAN) mode, Production mode.
Code signed MeshCmd.exe.

<--- Last few GCs --->

[41:0x1d82a70]    38571 ms: Mark-sweep 1365.0 (1417.8) -> 1364.6 (1417.8) MB, 765.0 / 0.0 ms  (average mu = 0.120, current mu = 0.007) allocation failure scavenge might not succeed
[41:0x1d82a70]    39344 ms: Mark-sweep 1365.3 (1417.8) -> 1364.9 (1418.3) MB, 768.8 / 0.0 ms  (average mu = 0.066, current mu = 0.006) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x0ae0fff2ee11 <JSObject>
    0: builtin exit frame: stringify(this=0x0ae0fff3c8a9 <Object map = 0x1f28f38cac9>,0x014461b825d9 <undefined>,0x06de5c451f89 <JSFunction (sfi = 0x33b10ebd8be1)>,0x37c373c36ca1 <Object map = 0x3341ddb345b1>,0x0ae0fff3c8a9 <Object map = 0x1f28f38cac9>)

    1: arguments adaptor frame: 2->3
    2: /* anonymous */ [0x154caf82201] [/opt/meshcentral/node_modules/@yetzt/nedb/lib/persistence.js:~128]...
ERR: FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
ERR:  1: 0x7fbe7000946c node::Abort() [/lib/x86_64-linux-gnu/libnode.so.64]
 2: 0x7fbe700094b5  [/lib/x86_64-linux-gnu/libnode.so.64]
 3: 0x7fbe70235e6a v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/lib/x86_64-linux-gnu/libnode.so.64]
 4: 0x7fbe702360e1 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/lib/x86_64-linux-gnu/libnode.so.64]
 5: 0x7fbe705d0c66  [/lib/x86_64-linux-gnu/libnode.so.64]
 6: 0x7fbe705e2043 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/lib/x86_64-linux-gnu/libnode.so.64]
 7: 0x7fbe705e2930 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/lib/x86_64-linux-gnu/libnode.so.64]
 8: 0x7fbe705e491d v8::internal::Heap::AllocateRawWithLigthRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/lib/x86_64-linux-gnu/libnode.so.64]
 9: 0x7fbe705e4975 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/lib/x86_64-linux-gnu/libnode.so.64]
10: 0x7fbe705b0b25 v8::internal::Factory::AllocateRawWithAllocationSite(v8::internal::Handle<v8::internal::Map>, v8::internal::PretenureFlag, v8::internal::Handle<v8::internal::AllocationSite>) [/lib/x86_64-linux-gnu/libnode.so.64]
11: 0x7fbe705bd51d v8::internal::Factory::NewJSObjectFromMap(v8::internal::Handle<v8::internal::Map>, v8::internal::PretenureFlag, v8::internal::Handle<v8::internal::AllocationSite>) [/lib/x86_64-linux-gnu/libnode.so.64]
12: 0x7fbe7069f011 v8::internal::JsonStringifier::CurrentHolder(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) [/lib/x86_64-linux-gnu/libnode.so.64]
13: 0x7fbe706a0552 v8::internal::JsonStringifier::ApplyReplacerFunction(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) [/lib/x86_64-linux-gnu/libnode.so.64]
14: 0x7fbe706a46c1 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<false>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [/lib/x86_64-linux-gnu/libnode.so.64]
15: 0x7fbe706a6723 v8::internal::JsonStringifier::Stringify(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) [/lib/x86_64-linux-gnu/libnode.so.64]
16: 0x7fbe702f78fd  [/lib/x86_64-linux-gnu/libnode.so.64]
17: 0x6a34e25464b
{ Error: Command failed: /usr/bin/node /opt/meshcentral/node_modules/meshcentral --launch 7
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x7fbe7000946c node::Abort() [/lib/x86_64-linux-gnu/libnode.so.64]
 2: 0x7fbe700094b5  [/lib/x86_64-linux-gnu/libnode.so.64]
 3: 0x7fbe70235e6a v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/lib/x86_64-linux-gnu/libnode.so.64]
 4: 0x7fbe702360e1 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/lib/x86_64-linux-gnu/libnode.so.64]
 5: 0x7fbe705d0c66  [/lib/x86_64-linux-gnu/libnode.so.64]
 6: 0x7fbe705e2043 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/lib/x86_64-linux-gnu/libnode.so.64]
 7: 0x7fbe705e2930 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/lib/x86_64-linux-gnu/libnode.so.64]
 8: 0x7fbe705e491d v8::internal::Heap::AllocateRawWithLigthRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/lib/x86_64-linux-gnu/libnode.so.64]
 9: 0x7fbe705e4975 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/lib/x86_64-linux-gnu/libnode.so.64]
10: 0x7fbe705b0b25 v8::internal::Factory::AllocateRawWithAllocationSite(v8::internal::Handle<v8::internal::Map>, v8::internal::PretenureFlag, v8::internal::Handle<v8::internal::AllocationSite>) [/lib/x86_64-linux-gnu/libnode.so.64]
11: 0x7fbe705bd51d v8::internal::Factory::NewJSObjectFromMap(v8::internal::Handle<v8::internal::Map>, v8::internal::PretenureFlag, v8::internal::Handle<v8::internal::AllocationSite>) [/lib/x86_64-linux-gnu/libnode.so.64]
12: 0x7fbe7069f011 v8::internal::JsonStringifier::CurrentHolder(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) [/lib/x86_64-linux-gnu/libnode.so.64]
13: 0x7fbe706a0552 v8::internal::JsonStringifier::ApplyReplacerFunction(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) [/lib/x86_64-linux-gnu/libnode.so.64]
14: 0x7fbe706a46c1 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<false>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [/lib/x86_64-linux-gnu/libnode.so.64]
15: 0x7fbe706a6723 v8::internal::JsonStringifier::Stringify(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) [/lib/x86_64-linux-gnu/libnode.so.64]
16: 0x7fbe702f78fd  [/lib/x86_64-linux-gnu/libnode.so.64]
17: 0x6a34e25464b

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:203:15)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: null,
  signal: 'SIGABRT',
  cmd:
   '/usr/bin/node /opt/meshcentral/node_modules/meshcentral --launch 7' }
ERROR: MeshCentral failed with critical error, check mesherrors.txt. Restarting in 5 seconds...
MeshCentral HTTP redirection server running on port 80.
MeshCentral v1.0.85, Hybrid (LAN + WAN) mode, Production mode.

<--- Last few GCs --->

[52:0x1bcca70]    40379 ms: Mark-sweep 1364.8 (1417.8) -> 1364.4 (1417.8) MB, 938.9 / 0.0 ms  (average mu = 0.107, current mu = 0.005) allocation failure scavenge might not succeed
[52:0x1bcca70]    41321 ms: Mark-sweep 1365.1 (1418.3) -> 1364.7 (1418.3) MB, 936.8 / 0.0 ms  (average mu = 0.057, current mu = 0.005) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3750bff2ee11 <JSObject>
    0: builtin exit frame: stringify(this=0x3750bff3c8a9 <Object map = 0x3d1bd00cac9>,0x0732976025d9 <undefined>,0x0028532d0f41 <JSFunction (sfi = 0x3d48d9878131)>,0x2db965f11819 <Object map = 0x26bde3834661>,0x3750bff3c8a9 <Object map = 0x3d1bd00cac9>)

    1: arguments adaptor frame: 2->3
    2: /* anonymous */ [0x17d59b8c40b1] [/opt/meshcentral/node_modules/@yetzt/nedb/lib/persistence.js:~128...
ERR: FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
ERR:  1: 0x7f758876546c node::Abort() [/lib/x86_64-linux-gnu/libnode.so.64]
ERR:  2: 0x7f75887654b5  [/lib/x86_64-linux-gnu/libnode.so.64]
ERR:  3: 0x7f7588991e6a v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/lib/x86_64-linux-gnu/libnode.so.64]
ERR:  4: 0x7f75889920e1 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/lib/x86_64-linux-gnu/libnode.so.64]
ERR:  5: 0x7f7588d2cc66  [/lib/x86_64-linux-gnu/libnode.so.64]
ERR:  6: 0x7f7588d3e043 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/lib/x86_64-linux-gnu/libnode.so.64]
ERR:  7: 0x7f7588d3e930 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/lib/x86_64-linux-gnu/libnode.so.64]
ERR:  8: 0x7f7588d4091d v8::internal::Heap::AllocateRawWithLigthRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/lib/x86_64-linux-gnu/libnode.so.64]
ERR:  9: 0x7f7588d40975 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/lib/x86_64-linux-gnu/libnode.so.64]
ERR: 10: 0x7f7588d0cb25 v8::internal::Factory::AllocateRawWithAllocationSite(v8::internal::Handle<v8::internal::Map>, v8::internal::PretenureFlag, v8::internal::Handle<v8::internal::AllocationSite>) [/lib/x86_64-linux-gnu/libnode.so.64]
ERR: 11: 0x7f7588d1951d v8::internal::Factory::NewJSObjectFromMap(v8::internal::Handle<v8::internal::Map>, v8::internal::PretenureFlag, v8::internal::Handle<v8::internal::AllocationSite>) [/lib/x86_64-linux-gnu/libnode.so.64]
ERR: 12: 0x7f7588d19f3f v8::internal::Factory::NewJSArray(v8::internal::ElementsKind, v8::internal::PretenureFlag) [/lib/x86_64-linux-gnu/libnode.so.64]
ERR: 13: 0x7f7588d1a309 v8::internal::Factory::NewJSArray(v8::internal::ElementsKind, int, int, v8::internal::ArrayStorageAllocationMode, v8::internal::PretenureFlag) [/lib/x86_64-linux-gnu/libnode.so.64]
ERR: 14: 0x7f7588dfaa2c v8::internal::JsonStringifier::JsonStringifier(v8::internal::Isolate*) [/lib/x86_64-linux-gnu/libnode.so.64]
ERR: 15: 0x7f7588a53857  [/lib/x86_64-linux-gnu/libnode.so.64]
16: 0x1a8b13dd464b
{ Error: Command failed: /usr/bin/node /opt/meshcentral/node_modules/meshcentral --launch 7
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x7f758876546c node::Abort() [/lib/x86_64-linux-gnu/libnode.so.64]
 2: 0x7f75887654b5  [/lib/x86_64-linux-gnu/libnode.so.64]
 3: 0x7f7588991e6a v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/lib/x86_64-linux-gnu/libnode.so.64]
 4: 0x7f75889920e1 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/lib/x86_64-linux-gnu/libnode.so.64]
 5: 0x7f7588d2cc66  [/lib/x86_64-linux-gnu/libnode.so.64]
 6: 0x7f7588d3e043 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/lib/x86_64-linux-gnu/libnode.so.64]
 7: 0x7f7588d3e930 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/lib/x86_64-linux-gnu/libnode.so.64]
 8: 0x7f7588d4091d v8::internal::Heap::AllocateRawWithLigthRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/lib/x86_64-linux-gnu/libnode.so.64]
 9: 0x7f7588d40975 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/lib/x86_64-linux-gnu/libnode.so.64]
10: 0x7f7588d0cb25 v8::internal::Factory::AllocateRawWithAllocationSite(v8::internal::Handle<v8::internal::Map>, v8::internal::PretenureFlag, v8::internal::Handle<v8::internal::AllocationSite>) [/lib/x86_64-linux-gnu/libnode.so.64]
11: 0x7f7588d1951d v8::internal::Factory::NewJSObjectFromMap(v8::internal::Handle<v8::internal::Map>, v8::internal::PretenureFlag, v8::internal::Handle<v8::internal::AllocationSite>) [/lib/x86_64-linux-gnu/libnode.so.64]
12: 0x7f7588d19f3f v8::internal::Factory::NewJSArray(v8::internal::ElementsKind, v8::internal::PretenureFlag) [/lib/x86_64-linux-gnu/libnode.so.64]
13: 0x7f7588d1a309 v8::internal::Factory::NewJSArray(v8::internal::ElementsKind, int, int, v8::internal::ArrayStorageAllocationMode, v8::internal::PretenureFlag) [/lib/x86_64-linux-gnu/libnode.so.64]
14: 0x7f7588dfaa2c v8::internal::JsonStringifier::JsonStringifier(v8::internal::Isolate*) [/lib/x86_64-linux-gnu/libnode.so.64]
15: 0x7f7588a53857  [/lib/x86_64-linux-gnu/libnode.so.64]
16: 0x1a8b13dd464b

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:203:15)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: null,
  signal: 'SIGABRT',
  cmd:
   '/usr/bin/node /opt/meshcentral/node_modules/meshcentral --launch 7' }
ERROR: MeshCentral failed with critical error, check mesherrors.txt. Restarting in 5 seconds...
MeshCentral HTTP redirection server running on port 80.
MeshCentral v1.0.85, Hybrid (LAN + WAN) mode, Production mode.```

**Comment by silversword411** [comment]
This is on the server? How much RAM are you allocating?

**Comment by github0004** [comment]
> This is on the server? How much RAM are you allocating?

16GB RAM server and I'm running this via docker so it should be getting everything it needs. HTOP has my server running at 8.8g/15.g while meshcentral is up and crashing

**Comment by github0004** [comment]
Well, I figured out that my config.json somehow didn't have MongoDB.  I can't import that data for whatever reason.

```
docker exec meshcentral node_modules/meshcentral --dbimport meshcentral-data/meshcentral.db.jso

OCI runtime exec failed: exec failed: container_linux.go:367: starting container process caused: exec: "node_modules/meshcentral": permission denied: unknow
```

```
TypeError: Object.fromEntries is not a function
    at CreateIndexesOperation.indexes.indexes.map.userIndex (/opt/meshcentral/node_modules/mongodb/lib/operations/indexes.js:92:46)
    at Array.map (<anonymous>)
    at new CreateIndexesOperation (/opt/meshcentral/node_modules/mongodb/lib/operations/indexes.js:88:32)
    at new CreateIndexOperation (/opt/meshcentral/node_modules/mongodb/lib/operations/indexes.js:128:9)
    at Collection.createIndex (/opt/meshcentral/node_modules/mongodb/lib/collection.js:258:78)
    at /opt/meshcentral/node_modules/meshcentral/db.js:846:34
    at wrapper (/opt/meshcentral/node_modules/mongodb/lib/utils.js:371:9)
    at session.endSession.endSessionError (/opt/meshcentral/node_modules/mongodb/lib/operations/execute_operation.js:71:66)
    at wrapper (/opt/meshcentral/node_modules/mongodb/lib/utils.js:371:9)
    at completeEndSession (/opt/meshcentral/node_modules/mongodb/lib/sessions.js:154:17)
{ Error: Command failed: /usr/bin/node /opt/meshcentral/node_modules/meshcentral --launch 8
/opt/meshcentral/node_modules/mongodb/lib/operations/indexes.js:92
            const validIndexOptions = Object.fromEntries(Object.entries({ ...userIndex }).filter(([optionName]) => VALID_INDEX_OPTIONS.has(optionName)));
                                             ^

TypeError: Object.fromEntries is not a function
    at CreateIndexesOperation.indexes.indexes.map.userIndex (/opt/meshcentral/node_modules/mongodb/lib/operations/indexes.js:92:46)
    at Array.map (<anonymous>)
    at new CreateIndexesOperation (/opt/meshcentral/node_modules/mongodb/lib/operations/indexes.js:88:32)
    at new CreateIndexOperation (/opt/meshcentral/node_modules/mongodb/lib/operations/indexes.js:128:9)
    at Collection.createIndex (/opt/meshcentral/node_modules/mongodb/lib/collection.js:258:78)
    at /opt/meshcentral/node_modules/meshcentral/db.js:846:34
    at wrapper (/opt/meshcentral/node_modules/mongodb/lib/utils.js:371:9)
    at session.endSession.endSessionError (/opt/meshcentral/node_modules/mongodb/lib/operations/execute_operation.js:71:66)
    at wrapper (/opt/meshcentral/node_modules/mongodb/lib/utils.js:371:9)
    at completeEndSession (/opt/meshcentral/node_modules/mongodb/lib/sessions.js:154:17)

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:203:15)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   '/usr/bin/node /opt/meshcentral/node_modules/meshcentral --launch 8' }
ERROR: MeshCentral failed with critical error, check mesherrors.txt. Restarting in 5 seconds...
Resetting power events indexes...
Resetting main indexes...
ERR: /opt/meshcentral/node_modules/mongodb/lib/utils.js:365
                    throw error;
                    ^

TypeError: Object.fromEntries is not a function
    at CreateIndexesOperation.indexes.indexes.map.userIndex (/opt/meshcentral/node_modules/mongodb/lib/operations/indexes.js:92:46)
    at Array.map (<anonymous>)
    at new CreateIndexesOperation (/opt/meshcentral/node_modules/mongodb/lib/operations/indexes.js:88:32)
    at new CreateIndexOperation (/opt/meshcentral/node_modules/mongodb/lib/operations/indexes.js:128:9)
    at Collection.createIndex (/opt/meshcentral/node_modules/mongodb/lib/collection.js:258:78)
    at /opt/meshcentral/node_modules/meshcentral/db.js:944:39
    at wrapper (/opt/meshcentral/node_modules/mongodb/lib/utils.js:361:17)
    at session.endSession.endSessionError (/opt/meshcentral/node_modules/mongodb/lib/operations/execute_operation.js:71:66)
    at wrapper (/opt/meshcentral/node_modules/mongodb/lib/utils.js:371:9)
    at completeEndSession (/opt/meshcentral/node_modules/mongodb/lib/sessions.js:154:17)
{ Error: Command failed: /usr/bin/node /opt/meshcentral/node_modules/meshcentral --launch 8
/opt/meshcentral/node_modules/mongodb/lib/utils.js:365
                    throw error;
                    ^

TypeError: Object.fromEntries is not a function
    at CreateIndexesOperation.indexes.indexes.map.userIndex (/opt/meshcentral/node_modules/mongodb/lib/operations/indexes.js:92:46)
    at Array.map (<anonymous>)
    at new CreateIndexesOperation (/opt/meshcentral/node_modules/mongodb/lib/operations/indexes.js:88:32)
    at new CreateIndexOperation (/opt/meshcentral/node_modules/mongodb/lib/operations/indexes.js:128:9)
    at Collection.createIndex (/opt/meshcentral/node_modules/mongodb/lib/collection.js:258:78)
    at /opt/meshcentral/node_modules/meshcentral/db.js:944:39
    at wrapper (/opt/meshcentral/node_modules/mongodb/lib/utils.js:361:17)
    at session.endSession.endSessionError (/opt/meshcentral/node_modules/mongodb/lib/operations/execute_operation.js:71:66)
    at wrapper (/opt/meshcentral/node_modules/mongodb/lib/utils.js:371:9)
    at completeEndSession (/opt/meshcentral/node_modules/mongodb/lib/sessions.js:154:17)

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:203:15)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   '/usr/bin/node /opt/meshcentral/node_modules/meshcentral --launch 8' }
ERROR: MeshCentral failed with critical error, check mesherrors.txt. Restarting in 5 seconds...
Resetting power events indexes...
Resetting main indexes...
ERR: /opt/meshcentral/node_modules/mongodb/lib/utils.js:365
                    throw error;
                    ^

TypeError: Object.fromEntries is not a function
    at CreateIndexesOperation.indexes.indexes.map.userIndex (/opt/meshcentral/node_modules/mongodb/lib/operations/indexes.js:92:46)
    at Array.map (<anonymous>)
    at new CreateIndexesOperation (/opt/meshcentral/node_modules/mongodb/lib/operations/indexes.js:88:32)
    at new CreateIndexOperation (/opt/meshcentral/node_modules/mongodb/lib/operations/indexes.js:128:9)
    at Collection.createIndex (/opt/meshcentral/node_modules/mongodb/lib/collection.js:258:78)
    at /opt/meshcentral/node_modules/meshcentral/db.js:944:39
    at wrapper (/opt/meshcentral/node_modules/mongodb/lib/utils.js:361:17)
    at session.endSession.endSessionError (/opt/meshcentral/node_modules/mongodb/lib/operations/execute_operation.js:71:66)
    at wrapper (/opt/meshcentral/node_modules/mongodb/lib/utils.js:371:9)
    at completeEndSession (/opt/meshcentral/node_modules/mongodb/lib/sessions.js:154:17)
{ Error: Command failed: /usr/bin/node /opt/meshcentral/node_modules/meshcentral --launch 8
/opt/meshcentral/node_modules/mongodb/lib/utils.js:365
                    throw error;
                    ^

TypeError: Object.fromEntries is not a function
    at CreateIndexesOperation.indexes.indexes.map.userIndex (/opt/meshcentral/node_modules/mongodb/lib/operations/indexes.js:92:46)
    at Array.map (<anonymous>)
    at new CreateIndexesOperation (/opt/meshcentral/node_modules/mongodb/lib/operations/indexes.js:88:32)
    at new CreateIndexOperation (/opt/meshcentral/node_modules/mongodb/lib/operations/indexes.js:128:9)
    at Collection.createIndex (/opt/meshcentral/node_modules/mongodb/lib/collection.js:258:78)
    at /opt/meshcentral/node_modules/meshcentral/db.js:944:39
    at wrapper (/opt/meshcentral/node_modules/mongodb/lib/utils.js:361:17)
    at session.endSession.endSessionError (/opt/meshcentral/node_modules/mongodb/lib/operations/execute_operation.js:71:66)
    at wrapper (/opt/meshcentral/node_modules/mongodb/lib/utils.js:371:9)
    at completeEndSession (/opt/meshcentral/node_modules/mongodb/lib/sessions.js:154:17)

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:203:15)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:607:12)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   '/usr/bin/node /opt/meshcentral/node_modules/meshcentral --launch 8' }
ERROR: MeshCentral failed with critical error, check mesherrors.txt. Restarting in 5 seconds...
Resetting main indexes...
Resetting power events indexes...
ERR: /opt/meshcentral/node_modules/mongodb/lib/operations/indexes.js:92
            const validIndexOptions = Object.fromEntries(Object.entries({ ...userIndex }).filter(([optionName]) => VALID_INDEX_OPTIONS.has(optionName)));
                                             ^

TypeError: Object.fromEntries is not a function
    at CreateIndexesOperation.indexes.indexes.map.userIndex (/opt/meshcentral/node_modules/mongodb/lib/operations/indexes.js:92:46)
    at Array.map (<anonymous>)
    at new CreateIndexesOperation (/opt/meshcentral/node_modules/mongodb/lib/operations/indexes.js:88:32)
    at new CreateIndexOperation (/opt/meshcentral/node_modules/mongodb/lib/operations/indexes.js:128:9)
    at Collection.createIndex (/opt/meshcentral/node_modules/mongodb/lib/collection.js:258:78)
    at /opt/meshcentral/node_modules/meshcentral/db.js:846:34
    at wrapper (/opt/meshcentral/node_modules/mongodb/lib/utils.js:371:9)
    at session.endSession.endSessionError (/opt/meshcentral/node_modules/mongodb/lib/operations/execute_operation.js:71:66)
    at wrapper (/opt/meshcentral/node_modules/mongodb/lib/utils.js:371:9)
    at completeEndSession (/opt/meshcentral/node_modules/mongodb/lib/sessions.js:154:17)
{ Error: Command failed: /usr/bin/node /opt/meshcentral/node_modules/meshcentral --launch 8
/opt/meshcentral/node_modules/mongodb/lib/operations/indexes.js:92
            const validIndexOptions = Object.fromEntries(Object.entries({ ...userIndex }).filter(([optionName]) => VALID_INDEX_OPTIONS.has(optionName)));
                                             ^

TypeError: Object.fromEntries is not a function
    at CreateIndexesOperation.indexes.indexes.map.userIndex (/opt/meshcentral/node_modules/mongodb/lib/operations/indexes.js:92:46)
    at Array.map (<anonymous>)
    at new CreateIndexesOperation (/opt/meshcentral/node_modules/mongodb/lib/operations/indexes.js:88:32)
    at new CreateIndexOperation (/opt/meshcentral/node_modules/mongodb/lib/operations/indexes.js:128:9)
    at Collection.createIndex (/opt/meshcentral/node_modules/mongodb/lib/collection.js:258:78)
    at /opt/meshcentral/node_modules/meshcentral/db.js:846:34
    at wrapper (/opt/meshcentral/node_modules/mongodb/lib/utils.js:371:9)
    at session.endSession.endSessionError (/opt/meshcentral/node_modules/mongodb/lib/operations/execute_operation.js:71:66)
    at wrapper (/opt/meshcentral/node_modules/mongodb/lib/utils.js:371:9)
    at completeEndSession (/opt/meshcentral/node_modules/mongodb/lib/sessions.js:154:17)

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:203:15)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   '/usr/bin/node /opt/meshcentral/node_modules/meshcentral --launch 8' }
ERROR: MeshCentral failed with critical error, check mesherrors.txt. Restarting in 5 seconds...
```

**Comment by si458** [comment]
@github0004 related issue for mongodb #4772

**Comment by github0004** [comment]
The error I originally posted was caused by a misconfig; I left the underscore next to MongoDB, so it wasn't using that and instead using NeDB. I added plenty of devices and since it can't support that many, I crashed. I posted another error while migrating and @si458 linked to it #4772. I had the same issue and I will be posting how I fixed it over there for docker.
