### ISSUE TITLE
When creating a new LDAP user restarts MeshCentral

### ISSUE THREAD

**Issue by xanpri** [Ylianst/MeshCentral#5057]
**Describe the bug**
Every time when a new LDAP user connects to MeshCentral it restarts the web console.

**To Reproduce**
1. Type username and password and try to log in to MeshCentral.
2. Restarts the web console.

**Expected behavior**
Do not restart the web console.

**Server Software:**
 - OS: SUSE
 - Virtualization: VMWare
 - Network: LAN/WAN
 - Version: SLES 15.3
 - Node: 16.17.1

**Client Device:**
 - Device: any
 - OS: Ubuntu and Windows 10/11
 - Network: Any
 - Browser: Firefox, Google Chrome, Edge

**MeshError:**
MongoServerError: E11000 duplicate key error collection: meshcentral.meshcentral index: _id_ dup key: { : "user/domain1/user1" }
    at /opt/meshcentral/node_modules/mongodb/lib/operations/update.js:132:33
    at /opt/meshcentral/node_modules/mongodb/lib/cmap/connection_pool.js:333:25
    at /opt/meshcentral/node_modules/mongodb/lib/sdam/server.js:212:17
    at handleOperationResult (/opt/meshcentral/node_modules/mongodb/lib/sdam/server.js:328:20)
    at Connection.onMessage (/opt/meshcentral/node_modules/mongodb/lib/cmap/connection.js:239:9)
    at MessageStream.<anonymous> (/opt/meshcentral/node_modules/mongodb/lib/cmap/connection.js:60:60)
    at MessageStream.emit (node:events:513:28)
    at processIncomingData (/opt/meshcentral/node_modules/mongodb/lib/cmap/message_stream.js:125:16)
    at MessageStream._write (/opt/meshcentral/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
    at writeOrBuffer (node:internal/streams/writable:391:12) {
  index: 0,
  code: 11000,
  [Symbol(errorLabels)]: Set(0) {}
}

-------- 3/24/2023, 3:57:10 PM ---- 1.1.4 --------

/opt/meshcentral/node_modules/mongodb/lib/operations/update.js:132
                return callback(new error_1.MongoServerError(res.writeErrors[0]));
                                ^

MongoServerError: E11000 duplicate key error collection: meshcentral.meshcentral index: _id_ dup key: { : "user/domain2/user2" }
    at /opt/meshcentral/node_modules/mongodb/lib/operations/update.js:132:33
    at /opt/meshcentral/node_modules/mongodb/lib/cmap/connection_pool.js:333:25
    at /opt/meshcentral/node_modules/mongodb/lib/sdam/server.js:212:17
    at handleOperationResult (/opt/meshcentral/node_modules/mongodb/lib/sdam/server.js:328:20)
    at Connection.onMessage (/opt/meshcentral/node_modules/mongodb/lib/cmap/connection.js:239:9)
    at MessageStream.<anonymous> (/opt/meshcentral/node_modules/mongodb/lib/cmap/connection.js:60:60)
    at MessageStream.emit (node:events:513:28)
    at processIncomingData (/opt/meshcentral/node_modules/mongodb/lib/cmap/message_stream.js:125:16)
    at MessageStream._write (/opt/meshcentral/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
    at writeOrBuffer (node:internal/streams/writable:391:12) {
  index: 0,
  code: 11000,
  [Symbol(errorLabels)]: Set(0) {}
}

```

**Comment by xanpri** [comment]
In addition, when creating new user groups, it restarts MeshCentral.
