### ISSUE TITLE
Telegram flood response causing the server to crash

### ISSUE THREAD

**Issue by smartekIT** [Ylianst/MeshCentral#5127]
I was working on the server code and involving in restarting the instance multiple times. after a number of restarts I had the server crashes at startup and never allowed me to login again. at that time I thought it was my code changes causing this crash, reverting my changes back didn't make any difference and the server still crashing at startup.

digging into the server error logs, I found an interesting point, the server was crashing not from my changes but because of multiple restarts in a short time, telegram has sent a "FLOOD" response to me server which then my server failed to start because of that. it was my mistake I forgot to disable Telegram implementation before trying my changes.

But can we do something about that. so the server never crash upon start if there is a "FLOOD" response from Telegram.

here is the error in my log:

<pre>
-------- 5/14/2023, 6:21:51 AM ---- 1.1.5 --------

/home/node/meshcentral/node_modules/telegram/errors/index.js:25
            return new Cls({ request: request, capture: capture });
                   ^

FloodWaitError: A wait of 940 seconds is required (caused by auth.ImportBotAuthorization)
    at RPCMessageToError (/home/node/meshcentral/node_modules/telegram/errors/index.js:25:20)
    at MTProtoSender._handleRPCResult (/home/node/meshcentral/node_modules/telegram/network/MTProtoSender.js:517:58)
    at MTProtoSender._processMessage (/home/node/meshcentral/node_modules/telegram/network/MTProtoSender.js:442:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MTProtoSender._recvLoop (/home/node/meshcentral/node_modules/telegram/network/MTProtoSender.js:418:17) {
  code: 420,
  errorMessage: 'FLOOD',
  seconds: 940
}

Node.js v17.8.0
</pre>

**Comment by si458** [comment]
it is indeed a BUG as telegram has protected itself from spam but then meshcentral can no longer start as it doesnt no what to do with the FLOOD message

development is on PAUSE at the moment,
but if you can fix it yaself and submit a PR im sure @Ylianst would appreciate it 

FYI, your nodejs version 17 is not LTS and ended support - https://endoflife.date/nodejs

**Comment by smartekIT** [comment]
Thanks
