### ISSUE TITLE
New Debian stable Bookworm

### ISSUE THREAD

**Issue by stefanocallegari** [Ylianst/MeshCentral#5201]
Hi, 
a few days ago I have updated my Meshcentral server to last Debian stable.

After that, meshcentral  has stopped.

So I've tried to know what was wrong, until I've tried to re-install meshcentral.

The error

```
node:internal/modules/cjs/loader:1302
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: libnode.so.72: cannot open shared object file: No such file or directory
    at Module._extensions..node (node:internal/modules/cjs/loader:1302:18)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/opt/meshcentral/node_modules/modern-syslog/index.js:9:12)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12) {
  code: 'ERR_DLOPEN_FAILED'
}
```

The new stable update the libnode from 72 to 108 and there is no way to have both. A simple workaround is to make a symlink 

```
root@ra:/opt/meshcentral# ls -l /usr/lib/x86_64-linux-gnu/libnode.so*
lrwxrwxrwx 1 root root       14 11 gen 17.42 /usr/lib/x86_64-linux-gnu/libnode.so -> libnode.so.108
-rw-r--r-- 1 root root 46276224 11 gen 17.42 /usr/lib/x86_64-linux-gnu/libnode.so.108
lrwxrwxrwx 1 root root       10 16 giu 10.41 /usr/lib/x86_64-linux-gnu/libnode.so.72 -> libnode.so
```

On restart, a new error on modern-syslog who meshcentral try to install

```
node:internal/modules/cjs/loader:1302
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '/opt/meshcentral/node_modules/modern-syslog/build/Release/core.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 108. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Module._extensions..node (node:internal/modules/cjs/loader:1302:18)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/opt/meshcentral/node_modules/modern-syslog/index.js:9:12)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12) {
  code: 'ERR_DLOPEN_FAILED'
}
```

Debian has own deb for modern-syslog node, but it seems not work with meshcentral (for me).

However, a 

`npm rebuild modern-syslog`

solves.

Now it seems to work.

Thanks.

Stefano

**Server Software **
 - OS: Debian 12 Bookworm
 - Network: LAN/WAN
 - Version: 1.1.6
 - Node: 18.13.0+dfsg1-1

p.s. my installation use a proxy for meshcentral to have the port 80 reusable (so I also can use letsencrypt).

config.json file
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "ra.stefanocallegari.it",
    "_WANonly": true,
    "_LANonly": true,
    "sessionKey": "**************",
    "port": 4444,
    "aliasPort": 443,
    "redirPort": 4443,
    "_redirAliasPort": 80,
    "AgentPong": 300,
    "syslog": true,
    "syslogjson": false,
    "WebRTC": true,
    "TlsOffload": "127.0.0.1",
    "_ExactPorts": "true"
  },
  "domains": {
    "": {
      "title": "Stefano Callegari",
      "title2": "MeshCentral",
      "minify": true,
      "newAccounts": false,
      "_userNameIsEmail": true,
      "mstsc": true,
      "ssh": true,
      "certUrl": "https://ra.stefanocallegari.it/",
      "agentCustomization": {
        "displayName": "Mesh Agent SC",
        "description": "Stefano Callegari Meshcentral Agent.",
        "companyName": "Stefano Callegari IT",
        "serviceName": "MeshAgentSC",
        "fileName": "meshagent_sc"
      }
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "*****@stefanocallegari.it",
    "_names": "*******",
    "production": true
  },
  "smtp": {
    "host": "*******",
    "port": 25,
    "from": "*******@stefanocallegari.it",
    "tls": false,
    "tlscertcheck": false,
    "tlsstrict": false
  }
}
```

**Comment by si458** [comment]
have u tested to see if the latest version of meshcentral still has this issue?

**Comment by stefanocallegari** [comment]
Hi...

Hmmm... I'll try to upgrade to 1.1.11 (the latest, not stable) and remove the symlink, but I can't test it for the node modern-syslog, maybe I'll need purge all and reinstall....

Upgraded!

Oops, it seems that the symlink just missing and work with 1.1.6 too. I don't remember to have deleted the symlink.

I hope help you.

Ciao

**Comment by si458** [comment]
Thanks, so your issue is fixed. I'll close the issue
