### ISSUE TITLE
ERROR: Unable to install required module

### ISSUE THREAD

**Issue by PatrickATS** [Ylianst/MeshCentral#5346]
**Describe the bug**
after install of 1.1.11, modules reinstall on every startup:
/opt/meshcentral$ sudo node ./node_modules/meshcentral
Installing mongodb@4.13.0...
Installing ua-parser-js@1.0.35...

So when starting the service normally I get:
Sep 12 15:25:46 remote systemd[1]: Started MeshCentral Server.
Sep 12 15:25:47 remote node[1227]: Installing mongodb@4.13.0...
Sep 12 15:25:48 remote node[1227]: ERROR: Unable to install required module

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server Software (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - Virtualization: [e.g. Docker]
 - Network: [e.g. LAN/WAN, reverse proxy, cloudflare, ssl offload, etc...]
 - Version: [e.g. 1.0.43]
 - Node: [e.g. 18.4.0]

**Client Device (please complete the following information):**
 - Device: [e.g. Laptop]
 - OS: [e.g. Ubuntu]
 - Network: [e.g. Local to Meshcentral, Remote over WAN]
 - Browser: [e.g. Google Chrome]
 - MeshCentralRouter Version: [if applicable]

**Remote Device (please complete the following information):**
 - Device: [e.g. Laptop]
 - OS: [e.g. Windows 10 21H2]
 - Network: [e.g. Local to Meshcentral, Remote over WAN]
 - Current Core Version (if known): [**HINT**: Go to a device then `console` Tab then type `info`]

**Additional context**

**Your config.json file**
```

**Comment by PatrickATS** [comment]
{
  "__comment__" : "This is a sample configuration file, edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "settings": {
    "Cert": "remote.agiletechs.com",
    "MongoDb": "mongodb://127.0.0.1:27017",
    "MongoDbName": "meshcentral",
    "_MongoDbChangeStream": true,
    "WANonly": true,
    "DesktopMultiplexor": true, 
   "_LANonly": true,
    "_Minify": 1,
    "SessionTime": 480,
    "_SessionKey": "MyReallySecretPassword1",
    "_SessionSameSite": "strict",
    "_DbEncryptKey": "MyReallySecretPassword2",
    "_DbRecordsEncryptKey": "MyReallySecretPassword",
    "_DbRecordsDecryptKey": "MyReallySecretPassword",
    "_DbExpire": {
      "events": 1728000,
      "powerevents": 864000
    },
    "Port": 443,
    "_RelayDNS": [ "relay1.agiletechs.com", "relay2.agiletechs.com" ],
    "RedirPort": 80,
    "_AllowLoginToken": true,
    "_AllowFraming": true,
    "_WebRTC": false,
    "_Nice404": false,
    "_ClickOnce": false,
    "_SelfUpdate": true,
    "_AgentPing": 60,
    "_AgentPong": 60,
    "_AgentIdleTimeout": 150,
    "_MeshErrorLogPath": "c:\\tmp",
    "_NpmPath": "c:\\npm.exe",
    "_NpmProxy": "http://1.2.3.4:80",
    "_AllowHighQualityDesktop": true,
    "_UserAllowedIP": "127.0.0.1,192.168.1.0/24",
    "_UserBlockedIP": "127.0.0.1,::1,192.168.0.100",
    "_AgentAllowedIP": "192.168.0.100/24",
    "_AgentBlockedIP": "127.0.0.1,::1",
    "_LocalDiscovery": {
      "name": "Local server name",
      "info": "Information about this server"
    },
    "_TlsOffload": true,
    "_MpsPort": 44330,
    "_MpsAliasPort": 4433,
    "_MpsAliasHost": "mps.mydomain.com",
    "_MpsTlsOffload": true,
    "_No2FactorAuth": true,
    "_Log": "main,web,webrequest,cert",
    "_WebRtConfig": {
      "iceServers": [
        { "urls": "stun:stun.services.mozilla.com" },
        { "urls": "stun:stun.l.google.com:19302" }
      ]
    },
    "_AutoBackup": {
      "backupIntervalHours": 24,
      "keepLastDaysBackup": 10,
      "zipPassword": "MyReallySecretPassword3",
      "_backupPath": "C:\\backups"
    },
    "_Redirects": {
      "meshcommander": "https://www.meshcommander.com/"
    },
    "__MaxInvalidLogin": "Time in minutes, max amount of bad logins from a source IP in the time before logins are rejected.",
    "MaxInvalidLogin": { "time": 10, "count": 10, "coolofftime": 10 },
    "_Plugins": {
        "enabled": true
    }
  },
  "domains": {
    "": {
      "Title": "Agile Remote Support",
      "Title2": "",
      "_TitlePicture": "title-sample.png",
      "SiteStyle": 2,
      "agentCustomization": {
	"displayName": "Agile Agent",
	"description": "Agile Remote Support Agent",
	"companyName": "Agile",
	"serviceName": "agileremote",
	"fileName": "agileagent",
	"image": "agent-logo.png",
	"installText": "Click the button below to install or uninstall the Agile Remote Support Agent"
	},
      "_UserQuota": 1048576,
      "_MeshQuota": 248576,
      "_NewAccounts": true,
      "_UserNameIsEmail": true,
      "_NewAccountEmailDomains": [ "sample.com" ],
      "_NewAccountsRights": [ "nonewgroups", "notools" ],
      "_Footer": "<a href='https://twitter.com/mytwitter'>Twitter</a>",
      "_CertUrl": "https://192.168.2.106:443/",
      "PasswordRequirements": { "min": 8, "max": 128, "upper": 1, "lower": 1, "numeric": 1, "nonalpha": 0, "reset": 90, "force2factor": true, "skip2factor": "127.0.0.1,192.168.20.0/24" },
      "_AgentNoProxy": true,
      "_GeoLocation": true,
      "_UserAllowedIP": "127.0.0.1,192.168.1.0/24",
      "_UserBlockedIP": "127.0.0.1,::1,192.168.0.100",
      "_AgentAllowedIP": "192.168.0.100/24",
      "_AgentBlockedIP": "127.0.0.1,::1",
      "___UserSessionIdleTimeout__" : "Number of user idle minutes before auto-disconnect",
      "_UserSessionIdleTimeout" : 30,
      "__UserConsentFlags__" : "Set to: 1 for desktop, 2 for terminal, 3 for files, 7 for all",
      "_UserConsentFlags" : 7,
      "mstsc": true,
      "ssh": true,
      "_Limits": {
        "_MaxDevices": 100,
        "_MaxUserAccounts": 100,
        "_MaxUserSessions": 100,
        "_MaxAgentSessions": 100,
        "MaxSingleUserSessions": 10
      },
      "_AmtAcmActivation": {
        "log": "amtactivation.log",
        "certs": {
          "mycertname": {
            "certfiles": [ "amtacm-leafcert.crt", "amtacm-intermediate1.crt", "amtacm-intermediate2.crt", "amtacm-rootcert.crt" ],
            "keyfile": "amtacm-leafcert.key"
          }
        }
      },
      "_Redirects": {
        "meshcommander": "https://www.meshcommander.com/"
      },
      "_yubikey": { "id": "0000", "secret": "xxxxxxxxxxxxxxxxxxxxx", "_proxy": "http://myproxy.domain.com:80" },
      "_httpheaders": {
        "Strict-Transport-Security": "max-age=360000",
        "x-frame-options": "SAMEORIGIN",
        "Content-Security-Policy": "default-src 'none'; script-src 'self' 'unsafe-inline'; connect-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; frame-src 'self'; media-src 'self'"
      },
      "_agentConfig": [ "webSocketMaskOverride=1" ],
      "_SessionRecording": {
        "_filepath": "C:\\temp",
        "__protocols__": "Is an array: 1 = Terminal, 2 = Desktop, 5 = Files, 100 = Intel AMT WSMAN, 101 = Intel AMT Redirection",
        "protocols": [ 1, 2, 101 ]
      }
    },
    "_customer1": {
      "_DNS": "customer1.myserver.com",
      "_Title": "Customer1",
      "_Title2": "TestServer",
      "_NewAccounts": 1,
      "_Auth": "sspi",
      "_Footer": "Test",
      "_CertUrl": "https://192.168.2.106:443/"
    },
    "_info": {
      "_share": "C:\\ExtraWebSite"
    }
  },
  "letsencrypt": {
    "__comment__": "Requires NodeJS 10.12 or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "patrick@agiletechs.com",
    "names": "remote.agiletechs.com",
    "rsaKeySize": 3072,
    "production": true
  },
  "_peers": {
    "serverId": "server1",
    "servers": {
      "server1": { "url": "wss://192.168.2.133:443/" },
      "server2": { "url": "wss://192.168.1.106:443/" }
    }
  },
  "smtp": {
    "host": "agiletechs-com.mail.protection.outlook.com",
    "port": 25,
    "from": "remote@agiletechs.com",
    "__tls__": "When 'tls' is set to true, TLS is used immidiatly when connecting. For SMTP servers that use TLSSTART, set this to 'false' and TLS will still be used.",
    "tls": false,
    "___tlscertcheck__": "When set to false, the TLS certificate of the SMTP server is not checked.",
    "_tlscertcheck": false,
    "__tlsstrict__": "When set to true, TLS cypher setup is more limited, SSLv2 and SSLv3 are not allowed.",
    "_tlsstrict": true
  }
}

**Comment by PatrickATS** [comment]
We also utilize the "Improved Security Installation on Ubuntu"

**Comment by PatrickATS** [comment]
I uploaded file instead of copying text

**Comment by si458** [comment]
we are aware of the issue of packages being reinstalled on startup 
sadly this is due to npm being silly and installing newer versions of software we asked for

HOWEVER i cant replicate your issue of `ERROR: Unable to install required module`

can you please edit the first comment and add in extra info for us like node version, server os, etc to try replicate your issue?

**Comment by PatrickATS** [comment]
Our install follows the guide for "Improved Security Installation on Ubuntu".
https://meshcentral-community.com/doku.php?id=howto:installation:manual:ubuntu:moresecure#improved_security_installation_on_ubuntu

Meshcentral is setup as a service to autostart.  But the service does not have permissions to update files, therefor installation of packages will fail on service startup:
Sep 12 15:25:46 remote systemd[1]: Started MeshCentral Server.
Sep 12 15:25:47 remote node[1227]: Installing mongodb@4.13.0...
Sep 12 15:25:48 remote node[1227]: ERROR: Unable to install required module

If we run the meshcentral from the command line:
sudo node ./node_modules/meshcentral
it installs the two modules and loads successfully.

Until this version, we have used the following update procedure successfully for years:
https://meshcentral-community.com/doku.php?id=howto:installation:manual:ubuntu:moresecure#updating_meshcentral

**Comment by si458** [comment]
> Our install follows the guide for "Improved Security Installation on Ubuntu".
> https://meshcentral-community.com/doku.php?id=howto:installation:manual:ubuntu:moresecure#improved_security_installation_on_ubuntu
> 
> Meshcentral is setup as a service to autostart.  But the service does not have permissions to update files, therefor installation of packages will fail on service startup:
> Sep 12 15:25:46 remote systemd[1]: Started MeshCentral Server.
> Sep 12 15:25:47 remote node[1227]: Installing mongodb@4.13.0...
> Sep 12 15:25:48 remote node[1227]: ERROR: Unable to install required module
> 
> If we run the meshcentral from the command line:
> sudo node ./node_modules/meshcentral
> it installs the two modules and loads successfully.
> 
> Until this version, we have used the following update procedure successfully for years:
> https://meshcentral-community.com/doku.php?id=howto:installation:manual:ubuntu:moresecure#updating_meshcentral

That website is an unofficial website, so the instructions will differ from device to device and os to os 

If you can run it fine from the command line. Then, there will be an issue with your service script then possibly

**Comment by PatrickATS** [comment]
fixed it
changed the home directory for user meshcentral to /opt/meshcentral
also changed permissions to 755

**Comment by si458** [comment]
reopening as im seeing the same thing now but installing `node-pushover` ?

**Comment by openncomp** [comment]
I got the same error when upgrading from 1.1.10 to 1.1.11 in Debian Bullseye.
_npm list_ output:
├── image-size@1.0.2
├── mariadb@3.2.1
├── meshcentral@1.1.11
├── nodemailer@6.9.5
├── otplib@10.2.3
├── ssh2@1.14.0
└── **ua-parser-js@1.0.36**

But for some reason, when running _node /opt/meshcentral/node_modules/meshcentral_, it tries to install **ua-parser-js@1.0.35** , which is an older version.

**Comment by openncomp** [comment]
Update error log:

```
Installing ua-parser-js@1.0.35...
Installing mariadb...
Installing ua-parser-js@1.0.35...
Installing mariadb...
ERR: /opt/meshcentral/node_modules/lru-cache/dist/cjs/index.js:52
            this.signal.onabort?.(reason);
                                ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/meshcentral/node_modules/mariadb/lib/lru-prepare-cache.js:5:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
Error: Command failed: /usr/bin/node /opt/meshcentral/node_modules/meshcentral --launch 5974
/opt/meshcentral/node_modules/lru-cache/dist/cjs/index.js:52
            this.signal.onabort?.(reason);
                                ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/meshcentral/node_modules/mariadb/lib/lru-prepare-cache.js:5:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:326:22)
    at maybeClose (internal/child_process.js:1022:16)
    at Socket.<anonymous> (internal/child_process.js:444:11)
    at Socket.emit (events.js:314:20)
    at Pipe.<anonymous> (net.js:676:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: '/usr/bin/node /opt/meshcentral/node_modules/meshcentral --launch 5974'
}
ERROR: MeshCentral failed with critical error, check mesherrors.txt. Restarting in 5 seconds...
```

**Comment by si458** [comment]
@openncomp this looks like a mariadb package update issue with npm!
Please can you run `npm list` from your root meshcentral folder and let me have the reply?
(The Folder containing the node_modules, meshcentral-data, meshcentral-backups, etc...)

**Comment by si458** [comment]
@openncomp the is an issue where for some reason we ask to install a certain version of a package and its installing the latest version?
also the error you are having is the latest mariadb package
as 3.2.1 was only released 24 hours ago, and wasnt updated in 3 months

**Comment by si458** [comment]
@openncomp i cant seem to get it to error out here like here?
what version of nodejs are you using?
you should be using the latest LTS version of 18 at least

**Comment by openncomp** [comment]
> @openncomp i cant seem to get it to error out here like here? what version of nodejs are you using? you should be using the latest LTS version of 18 at least

node -v
v12.22.12

I'm going to try to upgrade to version 18 now and see if I can upgrade MeshCentral, thanks for the hint!

**Comment by si458** [comment]
> > @openncomp i cant seem to get it to error out here like here? what version of nodejs are you using? you should be using the latest LTS version of 18 at least
> 
> node -v v12.22.12
> 
> I'm going to try to upgrade to version 18 now and see if I can upgrade MeshCentral, thanks for the hint!

OOO your just on the boarder of there requirements!
```
  "engines": {
    "node": ">= 12"
  },
```

**Comment by openncomp** [comment]
@si458 After updating nodejs to version 18.17.1, when running _node /opt/meshcentral/node_modules/meshcentral_, I get a segmentation error.

**Comment by si458** [comment]
> @si458 After updating nodejs to version 18.17.1, when running _node /opt/meshcentral/node_modules/meshcentral_, I get a segmentation error.

That seems to me a nodejs install error?

Also you should be running `node node_modules/meshcentral` from `/opt/meshcentral`

**Comment by openncomp** [comment]
There were no errors when installing nodejs. I tried updating in two ways:
```
npm cache clean -f
npm install -g n
n stable
```
and

```
wget https://nodejs.org/dist/v18.17.1/node-v18.17.1-linux-x64.tar.xz
tar -C /usr/local --strip-components 1 -xJf node-v18.17.1-linux-x64.tar.xz
```

In both cases, node -v showed version 18.17.1.

My MeshCentral Startup Command
`node /opt/meshcentral/node_modules/meshcentral`, as you wrote.

**Comment by openncomp** [comment]
I realized what my problem was.
In version 18.17.1, the path to nodejs has changed.
**Note: the node command change location and the old location may be remembered in your current shell.
old : /usr/bin/node
new : /usr/local/bin/node**
After updating nodejs from version 12.22.12 to 18.17.1, I did not change the _/etc/systemd/system/meshcentral.service_ file and it started the MeshCentral service under nodejs v12.22.12.
After replacing the new nodejs, I get the same segmentation error even on version 1.1.10 of MeshCentral.

**Comment by si458** [comment]
did you resolve this?
