### ISSUE TITLE
New MeshCentral instance and Postgres database do not work

### ISSUE THREAD

**Issue by 3ndexe** [Ylianst/MeshCentral#5498]
**Server Software (please complete the following information):**
 - OS: Ubuntu 20.04
 - Virtualization: Docker
 - Version: latest

I am currently trying to create a new Meshcentral instance which has a Postgres database.
I am using Docker Compose for this.
As soon as I run the command "docker compose up" I always get the following plus after that the container freezes:

**Docker Compose log**
```
meshcentral_db  | The files belonging to this database system will be owned by user "postgres".
meshcentral_db  | This user must also own the server process.
meshcentral_db  |
meshcentral_db  | The database cluster will be initialized with locale "en_US.utf8".
meshcentral_db  | The default database encoding has accordingly been set to "UTF8".
meshcentral_db  | The default text search configuration will be set to "english".
meshcentral_db  |
meshcentral_db  | Data page checksums are disabled.
meshcentral_db  |
meshcentral_db  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
meshcentral_db  | creating subdirectories ... ok
meshcentral_db  | selecting dynamic shared memory implementation ... posix
meshcentral_db  | selecting default max_connections ... 100
meshcentral_db  | selecting default shared_buffers ... 128MB
meshcentral_db  | selecting default time zone ... UTC
meshcentral_db  | creating configuration files ... ok
meshcentral_db  | running bootstrap script ... ok
meshcentral     | Installing modules...
meshcentral_db  | sh: locale: not found
meshcentral_db  | 2023-11-02 15:48:54.733 UTC [30] WARNING:  no usable system locales were found
meshcentral_db  | performing post-bootstrap initialization ... ok
meshcentral_db  | syncing data to disk ... ok
meshcentral_db  |
meshcentral_db  |
meshcentral_db  | Success. You can now start the database server using:
meshcentral_db  |
meshcentral_db  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
meshcentral_db  |
meshcentral_db  | initdb: warning: enabling "trust" authentication for local connections
meshcentral_db  | You can change this by editing pg_hba.conf or using the option -A, or
meshcentral_db  | --auth-local and --auth-host, the next time you run initdb.
meshcentral_db  | waiting for server to start....2023-11-02 15:48:55.597 UTC [36] LOG:  starting PostgreSQL 13.12 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, 64-bit
meshcentral_db  | 2023-11-02 15:48:55.602 UTC [36] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
meshcentral_db  | 2023-11-02 15:48:55.625 UTC [37] LOG:  database system was shut down at 2023-11-02 15:48:55 UTC
meshcentral_db  | 2023-11-02 15:48:55.630 UTC [36] LOG:  database system is ready to accept connections
meshcentral_db  |  done
meshcentral_db  | server started
meshcentral_db  |
meshcentral_db  | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
meshcentral_db  |
meshcentral_db  | waiting for server to shut down....2023-11-02 15:48:55.684 UTC [36] LOG:  received fast shutdown request
meshcentral_db  | 2023-11-02 15:48:55.689 UTC [36] LOG:  aborting any active transactions
meshcentral_db  | 2023-11-02 15:48:55.691 UTC [36] LOG:  background worker "logical replication launcher" (PID 43) exited with exit code 1
meshcentral_db  | 2023-11-02 15:48:55.692 UTC [38] LOG:  shutting down
meshcentral_db  | 2023-11-02 15:48:55.735 UTC [36] LOG:  database system is shut down
meshcentral_db  |  done
meshcentral_db  | server stopped
meshcentral_db  |
meshcentral_db  | PostgreSQL init process complete; ready for start up.
meshcentral_db  |
meshcentral_db  | 2023-11-02 15:48:55.810 UTC [1] LOG:  starting PostgreSQL 13.12 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, 64-bit
meshcentral_db  | 2023-11-02 15:48:55.810 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
meshcentral_db  | 2023-11-02 15:48:55.810 UTC [1] LOG:  listening on IPv6 address "::", port 5432
meshcentral_db  | 2023-11-02 15:48:55.821 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
meshcentral_db  | 2023-11-02 15:48:55.845 UTC [49] LOG:  database system was shut down at 2023-11-02 15:48:55 UTC
meshcentral_db  | 2023-11-02 15:48:55.851 UTC [1] LOG:  database system is ready to accept connections
meshcentral     | ERR: /opt/meshcentral/meshcentral/node_modules/bluebird/js/release/async.js:49
meshcentral     |         fn = function () { throw arg; };
meshcentral     |                            ^
meshcentral     |
meshcentral     | TypeError: Datastore.getConnection is not a function
meshcentral     |     at sqlDbBatchExec (/opt/meshcentral/meshcentral/db.js:1320:23)
meshcentral     |     at postgreSqlCreateTables (/opt/meshcentral/meshcentral/db.js:1168:9)
meshcentral     |     at /opt/meshcentral/meshcentral/db.js:796:17
meshcentral     |     at tryCatcher (/opt/meshcentral/meshcentral/node_modules/bluebird/js/release/util.js:16:23)
meshcentral     |     at Promise.successAdapter [as _fulfillmentHandler0] (/opt/meshcentral/meshcentral/node_modules/bluebird/js/release/nodeify.js:23:30)
meshcentral     |     at Promise._settlePromise (/opt/meshcentral/meshcentral/node_modules/bluebird/js/release/promise.js:601:21)
meshcentral     |     at Promise._settlePromise0 (/opt/meshcentral/meshcentral/node_modules/bluebird/js/release/promise.js:649:10)
meshcentral     |     at Promise._settlePromises (/opt/meshcentral/meshcentral/node_modules/bluebird/js/release/promise.js:729:18)
meshcentral     |     at _drainQueueStep (/opt/meshcentral/meshcentral/node_modules/bluebird/js/release/async.js:93:12)
meshcentral     |     at _drainQueue (/opt/meshcentral/meshcentral/node_modules/bluebird/js/release/async.js:86:9)
meshcentral     |     at Async._drainQueues (/opt/meshcentral/meshcentral/node_modules/bluebird/js/release/async.js:102:5)
meshcentral     |     at Async.drainQueues (/opt/meshcentral/meshcentral/node_modules/bluebird/js/release/async.js:15:14)
meshcentral     |     at process.processImmediate (node:internal/timers:476:21)
meshcentral     |
meshcentral     | Node.js v18.18.2
meshcentral     | Error: Command failed: /usr/bin/node /opt/meshcentral/meshcentral/meshcentral --configfile config.json --launch 6
meshcentral     | /opt/meshcentral/meshcentral/node_modules/bluebird/js/release/async.js:49
meshcentral     |         fn = function () { throw arg; };
meshcentral     |                            ^
meshcentral     |
meshcentral     | TypeError: Datastore.getConnection is not a function
meshcentral     |     at sqlDbBatchExec (/opt/meshcentral/meshcentral/db.js:1320:23)
meshcentral     |     at postgreSqlCreateTables (/opt/meshcentral/meshcentral/db.js:1168:9)
meshcentral     |     at /opt/meshcentral/meshcentral/db.js:796:17
meshcentral     |     at tryCatcher (/opt/meshcentral/meshcentral/node_modules/bluebird/js/release/util.js:16:23)
meshcentral     |     at Promise.successAdapter [as _fulfillmentHandler0] (/opt/meshcentral/meshcentral/node_modules/bluebird/js/release/nodeify.js:23:30)
meshcentral     |     at Promise._settlePromise (/opt/meshcentral/meshcentral/node_modules/bluebird/js/release/promise.js:601:21)
meshcentral     |     at Promise._settlePromise0 (/opt/meshcentral/meshcentral/node_modules/bluebird/js/release/promise.js:649:10)
meshcentral     |     at Promise._settlePromises (/opt/meshcentral/meshcentral/node_modules/bluebird/js/release/promise.js:729:18)
meshcentral     |     at _drainQueueStep (/opt/meshcentral/meshcentral/node_modules/bluebird/js/release/async.js:93:12)
meshcentral     |     at _drainQueue (/opt/meshcentral/meshcentral/node_modules/bluebird/js/release/async.js:86:9)
meshcentral     |     at Async._drainQueues (/opt/meshcentral/meshcentral/node_modules/bluebird/js/release/async.js:102:5)
meshcentral     |     at Async.drainQueues (/opt/meshcentral/meshcentral/node_modules/bluebird/js/release/async.js:15:14)
meshcentral     |     at process.processImmediate (node:internal/timers:476:21)
meshcentral     |
meshcentral     | Node.js v18.18.2
meshcentral     |
meshcentral     |     at ChildProcess.exithandler (node:child_process:422:12)
meshcentral     |     at ChildProcess.emit (node:events:529:35)
meshcentral     |     at maybeClose (node:internal/child_process:1098:16)
meshcentral     |     at Socket.<anonymous> (node:internal/child_process:450:11)
meshcentral     |     at Socket.emit (node:events:517:28)
meshcentral     |     at Pipe.<anonymous> (node:net:350:12) {
meshcentral     |   code: 1,
meshcentral     |   killed: false,
meshcentral     |   signal: null,
meshcentral     |   cmd: '/usr/bin/node /opt/meshcentral/meshcentral/meshcentral --configfile config.json --launch 6'
meshcentral     | }
meshcentral     | ERROR: MeshCentral failed with critical error, check mesherrors.txt. Restarting in 5 seconds...
meshcentral_db  | 2023-11-02 15:49:52.639 UTC [59] ERROR:  database "meshcentral" already exists
meshcentral_db  | 2023-11-02 15:49:52.639 UTC [59] STATEMENT:  CREATE DATABASE "meshcentral"
meshcentral_db  | 2023-11-02 15:49:52.654 UTC [60] ERROR:  relation "main" does not exist at character 17
meshcentral_db  | 2023-11-02 15:49:52.654 UTC [60] STATEMENT:  SELECT doc FROM main WHERE id = $1
meshcentral     | SELECT doc FROM main WHERE id = $1 [ 'DatabaseIdentifier' ] error: relation "main" does not exist
meshcentral     |     at Parser.parseErrorMessage (/opt/meshcentral/meshcentral/node_modules/pg-protocol/dist/parser.js:287:98)
meshcentral     |     at Parser.handlePacket (/opt/meshcentral/meshcentral/node_modules/pg-protocol/dist/parser.js:126:29)
meshcentral     |     at Parser.parse (/opt/meshcentral/meshcentral/node_modules/pg-protocol/dist/parser.js:39:38)
meshcentral     |     at Socket.<anonymous> (/opt/meshcentral/meshcentral/node_modules/pg-protocol/dist/index.js:11:42)
meshcentral     |     at Socket.emit (node:events:517:28)
meshcentral     |     at addChunk (node:internal/streams/readable:335:12)
meshcentral     |     at readableAddChunk (node:internal/streams/readable:308:9)
meshcentral     |     at Readable.push (node:internal/streams/readable:245:10)
meshcentral     |     at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
meshcentral     |   length: 103,
meshcentral     |   severity: 'ERROR',
meshcentral     |   code: '42P01',
meshcentral     |   detail: undefined,
meshcentral     |   hint: undefined,
meshcentral     |   position: '17',
meshcentral     |   internalPosition: undefined,
meshcentral     |   internalQuery: undefined,
meshcentral     |   where: undefined,
meshcentral     |   schema: undefined,
meshcentral     |   table: undefined,
meshcentral     |   column: undefined,
meshcentral     |   dataType: undefined,
meshcentral     |   constraint: undefined,
meshcentral     |   file: 'parse_relation.c',
meshcentral     |   line: '1373',
meshcentral     |   routine: 'parserOpenTable'
meshcentral     | }
meshcentral     | SQLERR4 TypeError: Datastore.getConnection is not a function
meshcentral     |     at sqlDbBatchExec (/opt/meshcentral/meshcentral/db.js:1320:23)
meshcentral     |     at postgreSqlCreateTables (/opt/meshcentral/meshcentral/db.js:1168:9)
meshcentral     |     at /opt/meshcentral/meshcentral/db.js:800:71
meshcentral     |     at Query.callback (/opt/meshcentral/meshcentral/db.js:1264:37)
meshcentral     |     at Query.handleError (/opt/meshcentral/meshcentral/node_modules/pg/lib/query.js:128:19)
meshcentral     |     at Client._handleErrorMessage (/opt/meshcentral/meshcentral/node_modules/pg/lib/client.js:335:17)
meshcentral     |     at Connection.emit (node:events:517:28)
meshcentral     |     at /opt/meshcentral/meshcentral/node_modules/pg/lib/connection.js:114:12
meshcentral     |     at Parser.parse (/opt/meshcentral/meshcentral/node_modules/pg-protocol/dist/parser.js:40:17)
meshcentral     |     at Socket.<anonymous> (/opt/meshcentral/meshcentral/node_modules/pg-protocol/dist/index.js:11:42)
meshcentral     |     at Socket.emit (node:events:517:28)
meshcentral     |     at addChunk (node:internal/streams/readable:335:12)
meshcentral     |     at readableAddChunk (node:internal/streams/readable:308:9)
meshcentral     |     at Readable.push (node:internal/streams/readable:245:10)
meshcentral     |     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

The connection between Meshcentral and Postgres seems to work in my opinion because the log shows that Meshcentral is trying to create the table "meshcentral".
```
meshcentral_db  | 2023-11-02 15:49:52.639 UTC [59] ERROR:  database "meshcentral" already exists
meshcentral_db  | 2023-11-02 15:49:52.639 UTC [59] STATEMENT:  CREATE DATABASE "meshcentral"
meshcentral_db  | 2023-11-02 15:49:52.654 UTC [60] ERROR:  relation "main" does not exist at character 17
meshcentral_db  | 2023-11-02 15:49:52.654 UTC [60] STATEMENT:  SELECT doc FROM main WHERE id = $1
```

I don't know if this is a bug or an error on my part but I have tried it in various ways but always get the same result.
If any information is missing please let me know

Thanks in advance for the help!

**docker-compose.yml file**
```
version: '3'

networks:
  back:
    driver: bridge

services:
  postgres:
    image: postgres:13-alpine
    restart: always
    container_name: meshcentral_db
    environment:
      - POSTGRES_PASSWORD=*******
    volumes:
      - ./meshcentral/postgres_data:/var/lib/postgresql/data
    networks:
      - back

  meshcentral:
    restart: always
    container_name: meshcentral
    image: ghcr.io/ylianst/meshcentral:latest
    depends_on:
      - 'postgres'
    env_file:
      - .env
    ports:
      # MeshCentral will moan and try everything not to use port 80, but you can also use it if you so desire, just change the config.json according to your needs
      - 8086:443
    volumes:
      # config.json and other important files live here. A must for data persistence
      - ./meshcentral/data:/opt/meshcentral/meshcentral-data
      # where file uploads for users live
      - ./meshcentral/user_files:/opt/meshcentral/meshcentral-files
      # location for the meshcentral-backups - this should be mounted to an external storage
      - ./meshcentral/backup:/opt/meshcentral/meshcentral-backups
      # location for site customization files
      - ./meshcentral/web:/opt/meshcentral/meshcentral-web
    networks:
      - back
```

**config.json file**
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "cert": "neu-ils-meshcentral.corp.ils-gmbh.net",
    "_WANonly": true,
    "_LANonly": true,
    "sessionKey": "qTi0dLHeQ?*C>X:^P(0isP>oBZy|yj5O",
    "port": 443,
    "_aliasPort": 443,
    "redirPort": 80,
    "_redirAliasPort": 80,
    "AgentPong": 300,
    "TLSOffload": false,
    "SelfUpdate": false,
    "AllowFraming": false,
    "WebRTC": false,
    "postgres": {
       "host": "postgres",
       "user": "postgres",
       "port": 5432,
       "password": "*******"
    }
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "NewAccounts": "true",
      "_userNameIsEmail": true,
      "_certUrl": "my.reverse.proxy"
      }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before>",
    "_email": "myemail@mydomain.com",
    "_names": "myserver.mydomain.com",
    "production": true
  }
}
```

**Comment by si458** [comment]
i mad a BOOBOO the other week when fixing mysql/mariadb, which in turn, broke postgres,
the fix has been pushed already, so if you want to try it quickly, use the `master` tag until a new release is pushed next month!
sorry about this, i dont use postgres, i only use sqlite and mysql, so didnt catch it before hand!
`ghcr.io/ylianst/meshcentral:master`
