### ISSUE TITLE
Postgresql Error

### ISSUE THREAD

**Issue by thermionic** [Ylianst/MeshCentral#5511]
**Describe the bug**
Changing to posresql fails

Existing is on Ubuntu 20.04 and using mongodb, so want to move to postgresql before upgrading to 22.04
Have already installed node 16 from node PPA to upgrade to 1.1.15 from 1.1.10

**To Reproduce**
1. Created copy of config.json deleting mongodb and adding postgresql stanzas
2. Started meshcentral, which then errors 

```
xclocal@mc-01:/opt/meshcentral$ sudo -u meshcentral node ./node_modules/meshcentral
Installing modules...
Installing modules...
SELECT doc FROM main WHERE id = $1 [ 'DatabaseIdentifier' ] error: relation "main" does not exist
    at Parser.parseErrorMessage (/opt/meshcentral/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/opt/meshcentral/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/opt/meshcentral/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/opt/meshcentral/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 103,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '17',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1191',
  routine: 'parserOpenTable'
}
SQLERR4 TypeError: Datastore.getConnection is not a function
    at sqlDbBatchExec (/opt/meshcentral/node_modules/meshcentral/db.js:1320:23)
    at postgreSqlCreateTables (/opt/meshcentral/node_modules/meshcentral/db.js:1168:9)
    at /opt/meshcentral/node_modules/meshcentral/db.js:800:71
    at Query.callback (/opt/meshcentral/node_modules/meshcentral/db.js:1264:37)
    at Query.handleError (/opt/meshcentral/node_modules/pg/lib/query.js:128:19)
    at Client._handleErrorMessage (/opt/meshcentral/node_modules/pg/lib/client.js:335:17)
    at Connection.emit (node:events:513:28)
    at /opt/meshcentral/node_modules/pg/lib/connection.js:114:12
    at Parser.parse (/opt/meshcentral/node_modules/pg-protocol/dist/parser.js:40:17)
    at Socket.<anonymous> (/opt/meshcentral/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
^CServer Ctrl-C exit...
```
After finding #4507 deleted the database that was pre-created and gave the account access to create databases, then re-ran

```
xclocal@mc-01:/opt/meshcentral$ sudo -u meshcentral node ./node_modules/meshcentral
Installing modules...
Installing modules...
ERR: /opt/meshcentral/node_modules/bluebird/js/release/async.js:49
        fn = function () { throw arg; };
                           ^

TypeError: Datastore.getConnection is not a function
    at sqlDbBatchExec (/opt/meshcentral/node_modules/meshcentral/db.js:1320:23)
    at postgreSqlCreateTables (/opt/meshcentral/node_modules/meshcentral/db.js:1168:9)
    at /opt/meshcentral/node_modules/meshcentral/db.js:796:17
    at tryCatcher (/opt/meshcentral/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (/opt/meshcentral/node_modules/bluebird/js/release/nodeify.js:23:30)
    at Promise._settlePromise (/opt/meshcentral/node_modules/bluebird/js/release/promise.js:601:21)
    at Promise._settlePromise0 (/opt/meshcentral/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/opt/meshcentral/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/opt/meshcentral/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/opt/meshcentral/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/opt/meshcentral/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues (/opt/meshcentral/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:466:21)
Error: Command failed: /usr/bin/node /opt/meshcentral/node_modules/meshcentral --launch 3317
/opt/meshcentral/node_modules/bluebird/js/release/async.js:49
        fn = function () { throw arg; };
                           ^

TypeError: Datastore.getConnection is not a function
    at sqlDbBatchExec (/opt/meshcentral/node_modules/meshcentral/db.js:1320:23)
    at postgreSqlCreateTables (/opt/meshcentral/node_modules/meshcentral/db.js:1168:9)
    at /opt/meshcentral/node_modules/meshcentral/db.js:796:17
    at tryCatcher (/opt/meshcentral/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (/opt/meshcentral/node_modules/bluebird/js/release/nodeify.js:23:30)
    at Promise._settlePromise (/opt/meshcentral/node_modules/bluebird/js/release/promise.js:601:21)
    at Promise._settlePromise0 (/opt/meshcentral/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/opt/meshcentral/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/opt/meshcentral/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/opt/meshcentral/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/opt/meshcentral/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues (/opt/meshcentral/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:466:21)

    at ChildProcess.exithandler (node:child_process:402:12)
    at ChildProcess.emit (node:events:525:35)
    at maybeClose (node:internal/child_process:1100:16)
    at Socket.<anonymous> (node:internal/child_process:458:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:301:12) {
  code: 1,
  killed: false,
  signal: null,
  cmd: '/usr/bin/node /opt/meshcentral/node_modules/meshcentral --launch 3317'
}
ERROR: MeshCentral failed with critical error, check mesherrors.txt. Restarting in 5 seconds...
Installing modules...
SELECT doc FROM main WHERE id = $1 [ 'DatabaseIdentifier' ] error: relation "main" does not exist
    at Parser.parseErrorMessage (/opt/meshcentral/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/opt/meshcentral/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/opt/meshcentral/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/opt/meshcentral/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 103,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '17',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1191',
  routine: 'parserOpenTable'
}
SQLERR4 TypeError: Datastore.getConnection is not a function
    at sqlDbBatchExec (/opt/meshcentral/node_modules/meshcentral/db.js:1320:23)
    at postgreSqlCreateTables (/opt/meshcentral/node_modules/meshcentral/db.js:1168:9)
    at /opt/meshcentral/node_modules/meshcentral/db.js:800:71
    at Query.callback (/opt/meshcentral/node_modules/meshcentral/db.js:1264:37)
    at Query.handleError (/opt/meshcentral/node_modules/pg/lib/query.js:128:19)
    at Client._handleErrorMessage (/opt/meshcentral/node_modules/pg/lib/client.js:335:17)
    at Connection.emit (node:events:513:28)
    at /opt/meshcentral/node_modules/pg/lib/connection.js:114:12
    at Parser.parse (/opt/meshcentral/node_modules/pg-protocol/dist/parser.js:40:17)
    at Socket.<anonymous> (/opt/meshcentral/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
^CServer Ctrl-C exit...
```
On checking, the database was created, but no tables were created.

**Expected behavior**
meshcentral startup as per with working mongodb

**Screenshots**
n/a

**Server Software (please complete the following information):**
 - OS: Ubuntu 20.04
 - Virtualization: none
 - Network: n/a
 - Version: 1.1.15
 - Node: v16.20.2

**Client Device (please complete the following information):**
n/a

**Remote Device (please complete the following information):**
n/a

**Additional context**

**Your config.json file**
```
{
    "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
    "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
    "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
    "settings": {
        "postgres": {
            "user": "mcpostgres",
            "password": "SuperSekritPassword",
            "port": "5432",
            "host": "localhost"
        },
        "_WANonly": true,
        "_LANonly": true,
        "Port": 443,
        "authlog": "/var/log/meshcentral/auth.log",
        "RedirPort": 80,
        "AllowLoginToken": true,
        "AllowFraming": false,
        "_UserAllowedIP": "127.0.0.1,::1,192.168.53.0/24,10.201.253.0/24",
        "cert": "mc.publicdomain.com",
        "_MpsCert": "publicdomain.com",
        "tlsOffload": "192.168.53.54",
        "mpsHighSecurity": false,
        "crowdsec": {
            "url": "http://localhost:8080",
            "apiKey": "SuperSekritPassword",
            "fallbackRemediation": "captcha"
        }
    },
    "domains": {
        "": {
            "minify": true,
            "certUrl": "https://mc.publicdomain.com:443/"
        }
    },
    "_letsencrypt": {
        "email": "ssl@publicdomain.net",
        "names": "mc.publicdomain.com",
        "production": true
    },
    "smtp": {
        "host": "smtp.publicdomain.com",
        "port": 25,
        "from": "mc@publicdomain.com"
    }
}

```

**Comment by si458** [comment]
you cant just swop the database engine!
i dont believe the data gets migrated
the only option thats built into meshcentral to to migrate from nedb to a database
so you have to migrate your data from mongodb to postgresql FIRST,
then change your `config.json` to use postgresql,
this will avoid having to 'recreate' the database/structure

**Comment by si458** [comment]
have you tried the dbexport/dbimport? (sorry wasnt aware this feature exists)
https://ylianst.github.io/MeshCentral/meshcentral/#database-import

**Comment by si458** [comment]
SO SORRY ABOUT THIS!!! FIXED NOW!!!
