### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'CloneSafeNode')

### ISSUE THREAD

**Issue by kno005** [Ylianst/MeshCentral#5591]
**Describe the bug**
I get the below error when starting a second node with peering. It doesn't matter which of my 2 nodes start first the second always throws this error. After trying to start 2-3 times the node will eventually start. You cannot click on a machine that is connected to a different node than you are. 

```
WARNING: Agent hash checking is being skipped, this is unsafe.
MeshCentral HTTP redirection server running on port 80.
MeshCentral v1.1.16, Hybrid (LAN + WAN) mode, Production mode.
ERR: E:\MeshCentral\node_modules\meshcentral\db.js:3308
        parent.DispatchEvent(['*', node.meshid], obj, { etype: 'node', action: (added ? 'addnode' : 'changenode'), node: parent.webserver.CloneSafeNode(node), nodeid: node._id, domain: node.domain, nolog: 1 });
                                                                                                                                          ^

TypeError: Cannot read properties of null (reading 'CloneSafeNode')
    at dbNodeChange (E:\MeshCentral\node_modules\meshcentral\db.js:3308:139)
    at ChangeStream.<anonymous> (E:\MeshCentral\node_modules\meshcentral\db.js:864:48)
    at ChangeStream.emit (node:events:517:28)
    at ReadableCursorStream.<anonymous> (E:\MeshCentral\node_modules\mongodb\lib\change_stream.js:293:22)
    at ReadableCursorStream.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:335:12)
    at readableAddChunk (node:internal/streams/readable:308:9)
    at Readable.push (node:internal/streams/readable:245:10)
    at E:\MeshCentral\node_modules\mongodb\lib\cursor\abstract_cursor.js:657:26
    at next (E:\MeshCentral\node_modules\mongodb\lib\cursor\abstract_cursor.js:507:9)
Emitted 'error' event on ChangeStream instance at:
    at ReadableCursorStream.<anonymous> (E:\MeshCentral\node_modules\mongodb\lib\change_stream.js:296:22)
    at ReadableCursorStream.emit (node:events:517:28)
    [... lines matching original stack trace ...]
    at next (E:\MeshCentral\node_modules\mongodb\lib\cursor\abstract_cursor.js:507:9)
    at E:\MeshCentral\node_modules\mongodb\lib\cursor\abstract_cursor.js:538:9
    at E:\MeshCentral\node_modules\mongodb\lib\cursor\change_stream_cursor.js:110:13
    at E:\MeshCentral\node_modules\mongodb\lib\utils.js:349:28

Node.js v18.18.2
Error: Command failed: C:\Program Files\nodejs\node.exe E:\MeshCentral\node_modules\meshcentral --launch 13568
E:\MeshCentral\node_modules\meshcentral\db.js:3308
        parent.DispatchEvent(['*', node.meshid], obj, { etype: 'node', action: (added ? 'addnode' : 'changenode'), node: parent.webserver.CloneSafeNode(node), nodeid: node._id, domain: node.domain, nolog: 1 });
                                                                                                                                          ^

TypeError: Cannot read properties of null (reading 'CloneSafeNode')
    at dbNodeChange (E:\MeshCentral\node_modules\meshcentral\db.js:3308:139)
    at ChangeStream.<anonymous> (E:\MeshCentral\node_modules\meshcentral\db.js:864:48)
    at ChangeStream.emit (node:events:517:28)
    at ReadableCursorStream.<anonymous> (E:\MeshCentral\node_modules\mongodb\lib\change_stream.js:293:22)
    at ReadableCursorStream.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:335:12)
    at readableAddChunk (node:internal/streams/readable:308:9)
    at Readable.push (node:internal/streams/readable:245:10)
    at E:\MeshCentral\node_modules\mongodb\lib\cursor\abstract_cursor.js:657:26
    at next (E:\MeshCentral\node_modules\mongodb\lib\cursor\abstract_cursor.js:507:9)
Emitted 'error' event on ChangeStream instance at:
    at ReadableCursorStream.<anonymous> (E:\MeshCentral\node_modules\mongodb\lib\change_stream.js:296:22)
    at ReadableCursorStream.emit (node:events:517:28)
    [... lines matching original stack trace ...]
    at next (E:\MeshCentral\node_modules\mongodb\lib\cursor\abstract_cursor.js:507:9)
    at E:\MeshCentral\node_modules\mongodb\lib\cursor\abstract_cursor.js:538:9
    at E:\MeshCentral\node_modules\mongodb\lib\cursor\change_stream_cursor.js:110:13
    at E:\MeshCentral\node_modules\mongodb\lib\utils.js:349:28

Node.js v18.18.2

    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:529:35)
    at maybeClose (node:internal/child_process:1098:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:517:28)
    at Pipe.<anonymous> (node:net:350:12) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'C:\\Program Files\\nodejs\\node.exe E:\\MeshCentral\\node_modules\\meshcentral --launch 13568'
}
ERROR: MeshCentral failed with critical error, check mesherrors.txt. Restarting in 5 seconds...
```

**To Reproduce**

1. Start first node.
2. Start second node.
3. Get error

**Expected behavior**
Second node should start without error.

**Screenshots**

**Server Software (please complete the following information):**
 - OS: Server 2022
 - Virtualization: VM
 - Network: LAN, Big-IP F5 for load balancing
 - Version: 1.1.16
 - Node: 18.18.2
 - DB: MongoDB 6.0.8

**Client Device (please complete the following information):**
 - Device: Laptop/Desktop
 - OS: Windows 10/11
 - Network: Local network
 - Browser: Chrome/Firefox
 - MeshCentralRouter Version: N/A

**Remote Device (please complete the following information):**
 - Device: Laptop/Desktop/VM
 - OS: Windows 10/11
 - Network: Local
 - Current Core Version (if known): Dec 9 2022, 1928065373

**Additional context**
I am able to run a dbexport however I get the same error when trying to run a dbimport on a different server. If I turn off changestream in the config the dbimport succeeds. 

**Your config.json file**
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "peers": {
    "servers": {
      "ServerA": { "url": "ws://xxx.xxx.xxx.xxx:4430/" },
      "ServerB": { "url": "ws://xxx.xxx.xxx.xxx:4430/" }
    }
  },
  "settings": {
    "cert": "loadbalancer.url",
	"ignoreagenthashcheck": true,
	"WebRTC": false,
    "_WANonly": true,
    "_LANonly": true,
    "sessionKey": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "port": 4430,
    "aliasPort": 443,
    "redirPort": 80,
    "redirAliasPort": 800,
	"MpsPort": 4433,
    "mpsAliasHost": "ServerA",
	"_MpsAliasPort": 4433,
	"MpsTlsOffload": false,
	"TlsOffload": "loadbalancer.url",
	"trustedproxy": "loadbalancer.internal.ip",
	"exactPorts": true,
	"mongodb": "mongodb://user:pass@DB.IP:27017/?replicaSet=rs0",
	"MongodbBulkOperations": true,
    "mongoDbName": "meshcentral",
    "mongoDbChangeStream": true,
	"ManageAllDeviceGroups": [ "user//xxx", "user//yyy", "user//zzz" ],
	"ManageCrossDomain": [ "user//xxx", "user//yyy", "user//zzz" ],
    "autoBackup": {
      "mongoDumpPath": "C:\\Program Files\\MongoDB\\Tools\\100\\bin\\mongodump.exe",
      "backupIntervalHours": 24,
      "keepLastDaysBackup": 90,
      "backupPath": "E:\\MeshCentral\\meshcentral-backup"
    }
  },

  "domains": {
    "": {
      "title": "Our MeshCentral",
      "loginPicture": "logo.png",
      "welcomeText": "Our MeshCentral Server.",
      "AutoRemoveInactiveDevices": 37,
	  "Config" : false,
	  "DeviceSearchBarServerAndClientName": true,
	  "certUrl": "https://loadbalancer.url:443/",
      "newAccountsRights": [ "nonewgroups", "notools" ],
      "auth": "ldap",
      "LDAPUserName": "displayName",
	  "LDAPUserBinaryKey": "objectSid",
      "LDAPUserEmail": "mail",
	  "LDAPUserRealName": "displayName",
	  "LDAPUserPhoneNumber": "telephoneNumber",
      "LDAPUserGroups": "memberOf",
      "LDAPSiteAdminGroups": [ "CN=MeshAdmin,OU=Groups,OU=IT,DC=sub,DC=co,DC=local" ],
      "LDAPSyncWithUserGroups": { "filter": [ 
		"CN=Group1",
		"CN=Group2",
		"CN=Group3",
		] },
      "ldapOptions": {
        "url": "ldap://sub.co.local:389",
        "bindDN": "CN=MeshServiceAccount,OU=Service Accounts,DC=sub,DC=co,DC=local",
        "bindCredentials": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "searchBase": "DC=sub,DC=co,DC=local",
        "searchFilter": "(&(sAMAccountName={{username}})(memberOf:1.2.840.113556.1.4.1941:=CN=MeshCentralAccess,OU=Groups,DC=sub,DC=co,DC=local))"
      },
	  "agenttag": {
		  "______Comment____": "0=Ignore, 1=Set, 2=SetIfEmpty (For Desc and Tags), 3=Append (Only for Tags)",
		  "ServerName": 1,
		  "ServerDesc": 1,
		  "ServerTags": 0
	  },		  
      "passwordRequirements": {
        "force2factor": true,
        "twoFactorTimeout": 300,
		"loginTokens": false
      },
	  "twoFactorCookieDurationDays": 90,
    }
  },
```

**Comment by si458** [comment]
i noticed this bug while trying to fix https://github.com/Ylianst/MeshCentral/issues/5714 

from my testing, you cant start the servers, one after another straight away,
you need to leave like 2-3 seconds in between each before it starts

so what we might need to do is just add a random delay between 1 and 5 seconds for each server IF you are using `peers`

**Comment by si458** [comment]
all fixed! 1 line was missing,
the return func was in all the other functions expect this one!

**Comment by kno005** [comment]
I can confirm that the error is no longer present. Thanks!
