### ISSUE TITLE
Add button in mesh options to copy a sanitized config.json for use in issues

### ISSUE THREAD

**Issue by silversword411** [Ylianst/MeshCentral#5594]
Currently a user has to get their json, copy it. Then remove all the sensitive info like:
Email configs, passwords, server URLs, 3rd party service urls etc if they don't want to share that info.

Make that easier! 1-button json sanitizer :)

**Comment by NiceGuyIT** [comment]
This can be done easily with [Nushell](https://github.com/nushell/nushell/) until something more permanent comes along. The download can be scripted easily for Linux/Mac/Windows. What fields need to be redacted?

```bash
open config.json
  | update settings.Cert "REDACTED"
  | update settings.postgres.password "REDACTED"
  | to json
```

**Comment by si458** [comment]
The is loads of fields like for example pushover and it's apikey, email server password, ur sessionkey

**Comment by silversword411** [comment]
Based on https://github.com/Ylianst/MeshCentral/blob/master/sample-config-advanced.json

I'd probably do
```
cert
certificatePrivateKeyPassword
sessionKey
dbEncryptKey
dbRecordsEncryptKey
dbRecordsDecryptKey
relayDNS
agentAliasDNS
npmProxy
webPush
userAllowedIP
agentAllowedIP
InterUserMessaging
manageAllDeviceGroups
manageCrossDomain
localDiscovery
mpsAliasHost
zipPassword
webdav
AmtProvisioningServer
crowdsec
certUrl
PreconfiguredRemoteInput
agentCustomization
agentFileInfo
assistantCustomization
androidCustomization
userAllowedIP
agentAllowedIP
amtManager
yubikey
authStrategies
```

Not sure about how to handle multi-customers

**Comment by NiceGuyIT** [comment]
I went down the rabbit hole of seeing if there were any TypeScript libraries that can validate JSON using a schema. I figured that would be a good start, to make sure the config is valid before redacting parts of it. Unfortunately, it turned into much larger endeavor than I had planned because most libraries expect you to use their libraries to enforce the types. Without creating types for the config, which wouldn't be a bad idea, here are some libraries that are able to validate the JSON. In the long run, it would be nice to use a good typing system.

These require [deno](https://github.com/denoland/deno) to run.

    Note: I specifically do not use try/catch because the stack trace has much better output than catching the error.

## [ajv](https://github.com/ajv-validator/ajv/)

I could not get ajv working.

## [io-ts](https://github.com/gcanti/io-ts)

I could not get io-ts working.

## [joi](https://github.com/hapijs/joi)

```bash
deno run --allow-read validate-config-joi.ts
```

```TypeScript
// validate-config-joi.ts
import meshSchema from "./meshcentral-config-schema.json" with {type: "json"};
import meshConfig from "./sample-config.json" with {type: "json"};

// https://github.com/hapijs/joi
import Joi from 'https://esm.sh/joi@17.11.0';

const schema = Joi.compile(meshSchema);
const valid = schema.validate(meshConfig);
if (valid.error) {
	console.log(valid.error);
} else {
	console.log('Schema is valid');
	console.log(valid);
}
```

<details>
  <summary>Joi output</summary>

```text
[ValidationError: "$schema" must be [http://json-schema.org/draft-04/schema#]] {
  _original: {
    "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
    __comment1__: "This is a simple configuration file, all values and sections that start with underscore (_) are igno"... 97 more characters,
    __comment2__: "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
    settings: {
      _cert: "myserver.mydomain.com",
      _WANonly: true,
      _LANonly: true,
      _sessionKey: "MyReallySecretPassword1",
      _port: 443,
      _aliasPort: 443,
      _redirPort: 80,
      _redirAliasPort: 80
    },
    domains: {
      "": {
        _title: "MyServer",
        _title2: "Servername",
        _minify: true,
        _newAccounts: true,
        _userNameIsEmail: true
      }
    },
    _letsencrypt: {
      __comment__: "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
      email: "myemail@mydomain.com",
      names: "myserver.mydomain.com",
      skipChallengeVerification: true,
      production: false
    }
  },
  details: [
    {
      message: '"$schema" must be [http://json-schema.org/draft-04/schema#]',
      path: [ "$schema" ],
      type: "any.only",
      context: {
        valids: [ "http://json-schema.org/draft-04/schema#" ],
        label: "$schema",
        value: "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
        key: "$schema"
      }
    }
  ]
}
```

</details>

## [jsonschema](https://github.com/tdegrunt/jsonschema)

`jsonschema` doesn't check if "extra" values exist. For example, comments beginning with `_` are not reported as an error even though they technically are an error because they are not included in the schema.

When there is a clear error, the stack trace does not point to what the error is. It is not user friendly.

```bash
deno run --allow-read validate-config-jsonschema.ts
```

```TypeScript
// validate-config-jsonschema.ts
import meshSchema from "./meshcentral-config-schema.json" with {type: "json"};
import meshConfig from "./sample-config.json" with {type: "json"};

// When it errors, the stack trace does not point to the actual error. Instead, it's a cryptic error.
// See: https://github.com/tdegrunt/jsonschema
import JsonSchema from "https://esm.sh/jsonschema@1.4.1";

const result = JsonSchema.validate(meshConfig, meshSchema, {required: true, throwFirst: true, throwAll: true, throwError: true});
console.log(result);
if (result.valid) {
	console.log('config is valid and conforms to the schema');
} else {
	console.log('config is invalid');
}
```

<details>
  <summary>Joi output</summary>

```text
{
  instance: {
    "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
    __comment1__: "This is a simple configuration file, all values and sections that start with underscore (_) are igno"... 97 more characters,
    __comment2__: "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
    settings: {
      _cert: "myserver.mydomain.com",
      _WANonly: true,
      _LANonly: true,
      _sessionKey: "MyReallySecretPassword1",
      _port: 443,
      _aliasPort: 443,
      _redirPort: 80,
      _redirAliasPort: 80
    },
    domains: {
      "": {
        _title: "MyServer",
        _title2: "Servername",
        _minify: true,
        _newAccounts: true,
        _userNameIsEmail: true
      }
    },
    _letsencrypt: {
      __comment__: "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
      email: "myemail@mydomain.com",
      names: "myserver.mydomain.com",
      skipChallengeVerification: true,
      production: false
    }
  },
  schema: {
    id: "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
    "$schema": "http://json-schema.org/draft-04/schema#",
    description: "MeshCentral configuration file schema",
    type: "object",
    required: [ "settings", "domains" ],
    properties: {
      settings: {
        type: "object",
        properties: {
          cert: [Object],
          keepCerts: [Object],
          mongoDb: [Object],
          mongoDbName: [Object],
          mongoDbChangeStream: [Object],
          mongoDbBulkOperations: [Object],
          mariaDB: [Object],
          sqlite3: [Object],
          mySQL: [Object],
          postgres: [Object],
          acebase: [Object],
          WANonly: [Object],
          LANonly: [Object],
          maintenanceMode: [Object],
          certificatePrivateKeyPassword: [Object],
          sessionTime: [Object],
          sessionKey: [Object],
          sessionSameSite: [Object],
          dbEncryptKey: [Object],
          dbRecordsEncryptKey: [Object],
          dbRecordsDecryptKey: [Object],
          dbExpire: [Object],
          port: [Object],
          portBind: [Object],
          aliasPort: [Object],
          redirPort: [Object],
          redirPortBind: [Object],
          redirAliasPort: [Object],
          relayPort: [Object],
          relayAliasPort: [Object],
          relayDNS: [Object],
          agentPort: [Object],
          agentPortBind: [Object],
          agentAliasPort: [Object],
          agentAliasDNS: [Object],
          agentPortTls: [Object],
          agentLogDump: [Object],
          agentCoreDump: [Object],
          agentCoreDumpUsers: [Object],
          agentSignLock: [Object],
          agentTimeStampServer: [Object],
          agentTimeStampProxy: [Object],
          lockAgentDownload: [Object],
          ignoreAgentHashCheck: [Object],
          exactPorts: [Object],
          allowLoginToken: [Object],
          StrictTransportSecurity: [Object],
          allowFraming: [Object],
          cookieIpCheck: [Object],
          cookieEncoding: [Object],
          webRTC: [Object],
          nice404: [Object],
          selfUpdate: [Object],
          cleanNpmCacheOnUpdate: [Object],
          browserPing: [Object],
          browserPong: [Object],
          agentsInRam: [Object],
          agentPing: [Object],
          agentPong: [Object],
          amtManager: [Object],
          orphanAgentUser: [Object],
          agentIdleTimeout: [Object],
          webPageLengthRandomization: [Object],
          compression: [Object],
          wsCompression: [Object],
          agentWsCompression: [Object],
          noAgentUpdate: [Object],
          agentUpdateSystem: [Object],
          temporaryAgentUpdate: [Object],
          amtScanner: [Object],
          meshScanner: [Object],
          meshErrorLogPath: [Object],
          npmPath: [Object],
          npmProxy: [Object],
          allowHighQualityDesktop: [Object],
          webPush: [Object],
          RunOnServerStarted: [Object],
          RunOnServerUpdated: [Object],
          RunOnServerError: [Object],
          publicPushNotifications: [Object],
          desktopMultiplex: [Object],
          ipBlockedUserRedirect: [Object],
          userAllowedIP: [Object],
          userBlockedIP: [Object],
          agentAllowedIP: [Object],
          agentBlockedIP: [Object],
          authLog: [Object],
          InterUserMessaging: [Object],
          manageAllDeviceGroups: [Object],
          manageCrossDomain: [Object],
          localDiscovery: [Object],
          tlsOffload: [Object],
          trustedProxy: [Object],
          mpsPort: [Object],
          mpsPortBind: [Object],
          mpsAliasPort: [Object],
          mpsAliasHost: [Object],
          mpsTlsOffload: [Object],
          mpsHighSecurity: [Object],
          no2FactorAuth: [Object],
          log: [Object],
          syslog: [Object],
          syslogauth: [Object],
          syslogjson: [Object],
          syslogtcp: [Object],
          webrtcConfig: [Object],
          crowdsec: [Object],
          autoBackup: [Object],
          rootCertCommonName: [Object],
          redirects: [Object],
          maxInvalidLogin: [Object],
          maxInvalid2fa: [Object],
          amtProvisioningServer: [Object],
          plugins: [Object]
        }
      },
      domaindefaults: { "$ref": "#/properties/domains/items" },
      domains: {
        type: "object",
        items: { type: "object", properties: [Object] }
      },
      letsEncrypt: {
        title: "Built-in Let's Encrypt support",
        description: "If your server has a proper DNS name and it public facing on the Internet with a public facing HTTP "... 54 more characters,
        type: "object",
        additionalProperties: false,
        properties: {
          email: [Object],
          names: [Object],
          skipChallengeVerification: [Object],
          production: [Object]
        },
        required: [ "email", "names" ]
      },
      peers: {
        title: "Server peering",
        description: "Setup peer server for load-balancing between many servers.",
        type: "object",
        minProperties: 1,
        propertyNames: { pattern: "^[A-Za-z_][A-Za-z0-9_]*$" },
        additionalProperties: false,
        properties: { serverId: [Object], servers: [Object] },
        required: [ "serverId", "servers" ]
      },
      sendgrid: {
        title: "SendGrid.com Email server",
        description: "Connects MeshCentral to the SendGrid email server, allows MeshCentral to send email messages for 2FA"... 22 more characters,
        type: "object",
        properties: { from: [Object], apikey: [Object], verifyemail: [Object] },
        required: [ "from", "apikey" ]
      },
      smtp: {
        title: "SMTP email server",
        description: "Connects MeshCentral to a SMTP email server, allows MeshCentral to send email messages for 2FA or us"... 16 more characters,
        type: "object",
        properties: {
          host: [Object],
          port: [Object],
          from: [Object],
          tls: [Object],
          tlscertcheck: [Object],
          tlsstrict: [Object],
          verifyemail: [Object]
        },
        required: [ "host", "port", "from", "tls" ]
      },
      sms: {
        title: "SMS provider",
        description: "Connects MeshCentral to a SMS text messaging provider, allows MeshCentral to send SMS messages for 2"... 24 more characters,
        oneOf: [ [Object], [Object], [Object], [Object] ]
      },
      messaging: {
        title: "Messaging server",
        description: "This section allow MeshCentral to send messages over user messaging networks like Telegram",
        type: "object",
        properties: {
          telegram: [Object],
          discord: [Object],
          xmpp: [Object],
          callmebot: [Object],
          slack: [Object],
          pushover: [Object],
          ntfy: [Object],
          zulip: [Object]
        }
      }
    }
  },
  options: {
    required: true,
    throwFirst: true,
    throwAll: true,
    throwError: true
  },
  path: [],
  propertyPath: "instance",
  errors: [],
  throwError: true,
  throwFirst: true,
  throwAll: true,
  disableFormat: false
}
config is valid and conforms to the schema
```

</details>

## [typebox](https://github.com/sinclairzx81/typebox)

I could not get Typebox working.

## [yup](https://github.com/jquense/yup)

yup provides the best output. The ValidationError explains exactly how the JSON violates the schema.

```bash
deno run --allow-read validate-config-yup.ts
```

```TypeScript
// validate-config-yup.ts
import meshSchema from "./meshcentral-config-schema.json" assert {type: "json"};
import meshConfig from "./sample-config.json" assert {type: "json"};

import * as yup from "https://esm.sh/yup@1.3.3";

// noUnknown() is needed to strip Prototype properties from the object.
// See: https://github.com/jquense/yup/issues/660
const schema = yup.object(meshSchema).noUnknown(true);
// Strict parsing is required.
const validation = await schema.validate(meshConfig, {strict: true});
```

<details>
  <summary>yup output</summary>

```text
error: Uncaught (in promise) ValidationError: this field has unspecified keys: __comment1__, __comment2__, settings, domains, _letsencrypt
    at Object.te [as createError] (https://esm.sh/v135/yup@1.3.3/denonext/yup.mjs:2:6287)
    at Object.test (https://esm.sh/v135/yup@1.3.3/denonext/yup.mjs:5:17947)
    at e (https://esm.sh/v135/yup@1.3.3/denonext/yup.mjs:2:6634)
    at Z.runTests (https://esm.sh/v135/yup@1.3.3/denonext/yup.mjs:5:818)
    at https://esm.sh/v135/yup@1.3.3/denonext/yup.mjs:5:481
    at c (https://esm.sh/v135/yup@1.3.3/denonext/yup.mjs:5:674)
    at https://esm.sh/v135/yup@1.3.3/denonext/yup.mjs:5:889
    at B (https://esm.sh/v135/yup@1.3.3/denonext/yup.mjs:2:6538)
    at e (https://esm.sh/v135/yup@1.3.3/denonext/yup.mjs:2:6930)
    at Z.runTests (https://esm.sh/v135/yup@1.3.3/denonext/yup.mjs:5:818)
```

</details>

## [zod](https://github.com/colinhacks/zod)

I could not get zod working.
