### ISSUE TITLE
help with error logging

### ISSUE THREAD

**Issue by geanferrani123** [Ylianst/MeshCentral#562]
Guys, good morning!

Can anyone explain to me what this logging would be?

node:7261) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7261) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

and this record:

/etc/meshcentral/node_modules/meshcentral/meshrelay.js:201
                                        relayinfo.peer1.ws.logfile = ws.logfile = { fd: fd, lock: false };
                                                                   ^

TypeError: Cannot set property 'logfile' of undefined
    at /etc/meshcentral/node_modules/meshcentral/meshrelay.js:201:68
    at /etc/meshcentral/node_modules/meshcentral/meshrelay.js:352:82
    at FSReqWrap.wrapper [as oncomplete] (fs.js:685:5)

I am using version W.

**Comment by geanferrani123** [comment]
and these:

(node:1542) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)

and these:

(node:1542) UnhandledPromiseRejectionWarning: Error: key user//gean.ferrani must not contain '.'
    at serializeInto (/etc/meshcentral/node_modules/bson/lib/bson/parser/serializer.js:913:19)
    at serializeObject (/etc/meshcentral/node_modules/bson/lib/bson/parser/serializer.js:347:18)
    at serializeInto (/etc/meshcentral/node_modules/bson/lib/bson/parser/serializer.js:937:17)
    at serializeObject (/etc/meshcentral/node_modules/bson/lib/bson/parser/serializer.js:347:18)
    at serializeInto (/etc/meshcentral/node_modules/bson/lib/bson/parser/serializer.js:727:17)
    at serializeObject (/etc/meshcentral/node_modules/bson/lib/bson/parser/serializer.js:347:18)
    at serializeInto (/etc/meshcentral/node_modules/bson/lib/bson/parser/serializer.js:937:17)
    at BSON.serialize (/etc/meshcentral/node_modules/bson/lib/bson/bson.js:64:28)
    at Msg.serializeBson (/etc/meshcentral/node_modules/mongodb/lib/core/connection/msg.js:124:22)
    at Msg.makeDocumentSegment (/etc/meshcentral/node_modules/mongodb/lib/core/connection/msg.js:116:33)
(node:1542) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)

**Comment by Ylianst** [comment]
I fixed the "/etc/meshcentral/node_modules/meshcentral/meshrelay.js:201" error, thanks for reporting that. Fix will be in the next published version z later today.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.2-d that should fix this. Please report if you see any new exceptions in the mesherror.txt file after the update.

**Comment by geanferrani123** [comment]
very good, I will test and already talk to you.

**Comment by geanferrani123** [comment]
Ylianst, so far not had, I think we can close this topic, thanks for the attention

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.2-g with more server fixes and performance improvements. v0.4.2-d broke device group creation and some other operations, this is now fixed.
