### ISSUE TITLE
MCR connecting via SSH (putty and other SSH clients)

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#586]
**Running MC2 0.4.2-t / MCR v1.0.7083 on Windows 10 client (MC2 running on Linux)**
I can set up a putty connection through MCR to a remote server's port 22 and when I click Open on the MCR GUI, I get to accept the servers' fingerprint, get prompted for username / password etc and then I'm in.

However if I wanted to use a different SSH client, I'm a little stuck and I never seem to get very far at all:

1. Open up MCR
1. Select Add Map...
1. Protocol: TCP
1. Local Port: 0
1. Device group: (my group)
1. Remove device: (my server - same as the putty one)
1. Application: Custom (this removes the "Open..." option when the map gets listed in the GUI)
1. Remote Port: 22

When I try to connect to the port that's then listed in the GUI, nothing happens. I check netstat to see if I can see the ports being opened, but on both the putty or my alternative client connection I don't see the local port being opened, so perhaps that's a red herring.

Ultimately I want to use an alternative SSH client to my remote server's SSH port, as well as MySQL Workbench to the remote server's MySQL port. I thought the SSH side of things would be easier, but I'm falling on my @rse at the first hurdle!

**Comment by D4V3M0NK** [comment]
Oddly enough, MySQL connections work perfectly!

**Comment by D4V3M0NK** [comment]
And when attempting to set up a MySQL Workbench (6.3.7/8.0.18) connection to my remote host, the only thing I can add here is the following from the MySQL log file (wb.log):
Workbench 6.3.7:
> 18:07:42 [INF][     SSH tunnel]: Existing SSH tunnel not found, opening new one
> 18:07:49 [INF][     SSH tunnel]: Opening SSH tunnel to 127.0.0.1:51544
> 18:07:49 [ERR][sshtunnel.py:notify_exception_error:234]: Traceback (most recent call last):
>   File "C:\Program Files\MySQL\MySQL Workbench 6.3 CE\sshtunnel.py", line 302, in _connect_ssh
>     look_for_keys=has_key, allow_agent=has_key)
>   File "C:\Program Files\MySQL\MySQL Workbench 6.3 CE/python/site-packages\paramiko\client.py", line 325, in connect
>     t.start_client()
>   File "C:\Program Files\MySQL\MySQL Workbench 6.3 CE/python/site-packages\paramiko\transport.py", line 492, in start_client
>     raise e
> SSHException: Error reading SSH protocol banner
> 
> 18:07:50 [INF][     SSH tunnel]: TunnelManager.wait_connection authentication error: Authentication error, unhandled exception caught in tunnel manager, please refer to logs for details
> 18:07:50 [ERR][     SSH tunnel]: Authentication error opening SSH tunnel: Authentication error, unhandled exception caught in tunnel manager, please refer to logs for details
> 18:07:51 [INF][      WBContext]: Connection to test cancelled by user: Tunnel connection cancelled

Workbench 8.0.18

> 18:19:15 [INF][      Workbench]: UI is up
> 18:19:16 [INF][      Workbench]: Running the application
> 18:19:28 [INF][SSHTunnelManager]: Wakeup socket port created: 51701
> 18:19:28 [INF][     SSH tunnel]: Starting tunnel
> 18:19:28 [INF][     SSH tunnel]: Existing SSH tunnel not found, opening new one
> 18:19:33 [INF][     SSH tunnel]: Opening SSH tunnel to 127.0.0.1:51544
> 18:19:33 [INF][      SSHCommon]: libssh: ssh_connect ssh_connect: libssh 0.8.7 (c) 2003-2018 Aris Adamantiadis, Andreas Schneider and libssh contributors. Distributed under the LGPL, please refer to COPYING file for information about your rights, using threading threads_stdthread
> 18:19:33 [INF][      SSHCommon]: libssh: ssh_socket_connect ssh_socket_connect: Nonblocking connection socket: 1996
> 18:19:33 [INF][      SSHCommon]: libssh: ssh_connect ssh_connect: Socket connecting, now waiting for the callbacks to work
> 18:19:33 [ERR][     SSHSession]: Unable to connect: 127.0.0.1:51544
> Error was: Socket error: disconnected
> 18:19:33 [ERR][     SSH tunnel]: Unable to open SSH tunnel: Socket error: disconnected
> 18:19:33 [ERR][SQL Editor Form]: SQL editor could not be connected: Cannot open SSH Tunnel: Socket error: disconnected
> 18:19:33 [ERR][SQL Editor Form]: Your connection attempt failed for user 'root' to the MySQL server at 127.0.0.1:3306:
>   Cannot open SSH Tunnel: Socket error: disconnected
> 
> Please:
> 1 Check that MySQL is running on address 127.0.0.1
> 2 Check that MySQL is reachable on port 3306 (note: 3306 is the default, but this can be changed)
> 3 Check the user root has rights to connect to 127.0.0.1 from your address (MySQL rights define what clients can connect to the server and from which machines) 
> 4 Make sure you are both providing a password if needed and using the correct password for 127.0.0.1 connecting from the host address you're connecting from
>

**Comment by D4V3M0NK** [comment]
Oddly enough, what I thought would be harder, ended up being reasonably easy. For those reading this, setting up remote MySQL connections can be performed simply by using a "standard TCP/IP connection", replacing the normal port (3306) to the published port on the MCR GUI.
