### ISSUE TITLE
Self-Update error : 0.1.4-k to 0.1.4-m

### ISSUE THREAD

**Issue by LinkPhoenix** [Ylianst/MeshCentral#6]
after an attempt to update my meshcentral server this one to the following errors:

```
path.js:1177
          cwd = process.cwd();
                        ^

Error: ENOENT: no such file or directory, uv_cwd
    at Object.resolve (path.js:1177:25)
    at Function.Module._resolveLookupPaths (module.js:418:17)
    at Function.Module._resolveFilename (module.js:532:20)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at getConfig (/root/meshcentral/node_modules/meshcentral/meshcentral.js:1055:5)
    at /root/meshcentral/node_modules/meshcentral/meshcentral.js:1089:18
    at InstallModules (/root/meshcentral/node_modules/meshcentral/meshcentral.js:1061:103)
    at InstallModule (/root/meshcentral/node_modules/meshcentral/meshcentral.js:1079:5)

```

**Comment by jsastriawan** [comment]
Similar issue happens when you try to run something from an already deleted folder. It seems node_modules/meshcentral was already deleted and when you tried to run process.cwd() on that folder while being updated, this error popped up.

We nee to figure out a more robust way of doing self update. I think calling process.cwd() early then move 2 folder up and run "npm install meshcentral" is better.

Will discuss with Ylian when he is back from holiday. :)

**Comment by LinkPhoenix** [comment]
Thank you for this answer, I do not know the JavaScript language at all, so I can not or do not understand the errors.

I hope that the problems that I bring back to you will help you to identify the problems so that you build a stable and solid new Meshcentral.

Yes Ylian informed me that he was on vacation, I hope you find a solution with him.

Good day :)

**Comment by LinkPhoenix** [comment]
I try "self-update" via the my web browser and all is good now 👍
