### ISSUE TITLE
[BUG] WebRelay HTTP Connection Crashing Server - "Header name must be a valid HTTP token"

### ISSUE THREAD

**Issue by GraphicHealer** [Ylianst/MeshCentral#6305]
**Describe the bug**
I am using MeshCentral's WebRelay with `"relayDNS": "meshrelay.mydomain.com"`

When I try to access a SuperMicro IPMI's Web Interface via HTTP, I encounter this bug:

```
-------- 8/5/2024, 10:24:36 AM ---- 1.1.27 --------

node:internal/errors:541
      throw error;
      ^

TypeError [ERR_INVALID_HTTP_TOKEN]: Header name must be a valid HTTP token [" content-length"]
    at ServerResponse.setHeader (node:_http_outgoing:705:3)
    at ServerResponse.header (/opt/meshcentral/node_modules/express/lib/response.js:795:10)
    at processHttpResponse (/opt/meshcentral/node_modules/meshcentral/apprelays.js:720:71)
    at processHttpData (/opt/meshcentral/node_modules/meshcentral/apprelays.js:575:17)
    at processRawHttpData (/opt/meshcentral/node_modules/meshcentral/apprelays.js:521:13)
    at WebSocket.<anonymous> (/opt/meshcentral/node_modules/meshcentral/apprelays.js:498:21)
    at WebSocket.emit (node:events:519:28)
    at Receiver.receiverOnMessage (/opt/meshcentral/node_modules/ws/lib/websocket.js:1211:20)
    at Receiver.emit (node:events:519:28)
    at Receiver.dataMessage (/opt/meshcentral/node_modules/ws/lib/receiver.js:567:14) {
  code: 'ERR_INVALID_HTTP_TOKEN'
}

Node.js v21.7.3
```

It seems that MeshCentral is running into some sort of "Invalid HTTP Header", and this causes MeshCentral to completely crash.

I am using HTTP instead of HTTPS on the SuperMicro IPMI, as something with the way it runs HTTPS was not liking the MeshCentral Relay, and it was causing a "Session Timeout" on the IPMI.

**To Reproduce**
1. Setup WebRelay on MeshCentral
2. Create a WebRelay Group
3. Add the HTTP Device
4. Try to connect via HTTP
5. MeshCentral Crashes

**Expected behavior**
I should be able to access the IPMI device over HTTP with the MeshCentral Relay.

**Server Software:**
 - OS: UnRAID
 - Virtualization: Docker
 - Network: Cloudflare Proxy (Via Cloudflared)
 - Version: 1.1.27
 - Node: v21.7.3

**Client Device:**
 - Device: Laptop
 - OS: Windows
 - Network: Remote to Cloudflare Proxy
 - Browser: Google Chrome

**Remote Agent:**
 - Device: Desktop
 - OS: Windows
 - Network: Remote Network
 - Current Core Version: Dec 9 2022, 3451659882

**Relayed Device:**
 - Device: SuperMicro IPMI
 - OS: IPMI Firmware
 - Network: Remote Network (Same as agent)
 - Firmware Version: 03.46

**Your config.json file**
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "cert": "mesh.mydomain.com",
    "WANonly": true,
    "_LANonly": true,
    "sessionKey": "****************************************************************",
    "port": 8086,
    "aliasPort": 443,
    "redirPort": 0,
    "redirAliasPort": 0,
    "AgentPong": 300,
    "TLSOffload": true,
    "SelfUpdate": false,
    "AllowFraming": "false",
    "WebRTC": "true",
    "TrustedProxy": "CloudFlare",
    "mongodb": "mongodb://mongodb:27017/mesh",
    "mongodbcol": "mesh",
    "amtManager": false,
    "relayDns": "meshrelay.mydomain.com"
  },
  "domains": {
    "": {
      "title": "Server",
      "title2": "Server",
      "_minify": true,
      "NewAccounts": "false",
      "userNameIsEmail": true,
      "certUrl": "https://mesh.mydomain.com"
    }
  }
}
```

**Comment by si458** [comment]
for some reason supermicro is sending the header `"  content-length"` when it should be `"content-length"`
the shouldnt be any blank spaces?

try the following 

replace on line 720 of apprelays.js
`obj.res.set(i, header[i]);` with `obj.res.set(i, header[i].trim());`
then restart meshcentral and try again

**Comment by GraphicHealer** [comment]
> for some reason supermicro is sending the header `" content-length"` when it should be `"content-length"` the shouldnt be any blank spaces?
> 
> try the following and let us know before i push a fix
> 
> replace on line 720 of apprelays.js `obj.res.set(i, header[i]);` with `obj.res.set(i, header[i].trim());` then restart meshcentral and try again

I tried that, no such luck. Still crashes, same exact error.

**Comment by si458** [comment]
ok put it back the way it was please,
can you also uncomment the line 686 saying `console.log('processHttpResponse',...)`
restart meshcentral,
then generate error again, and watch the output and it should spit out loads of info `processHttpResponse`,
can you share that? (might need pastebin if its way too big, and hide any secret info that MIGHT be in it)

**Comment by GraphicHealer** [comment]
Here it is:
```
processHttpResponse {
  Directive: [ 'HTTP/1.1', '200', 'OK' ],
  'content-type': 'application/xml',
  ' content-length': '54 ',
  'transfer-encoding': 'chunked',
  date: 'Mon, 05 Aug 2024 18:58:09 GMT'
} 0 false undefined
ERR: node:internal/errors:541
      throw error;
      ^

TypeError [ERR_INVALID_HTTP_TOKEN]: Header name must be a valid HTTP token [" content-length"]
    at ServerResponse.setHeader (node:_http_outgoing:705:3)
    at ServerResponse.header (/opt/meshcentral/node_modules/express/lib/response.js:795:10)
    at processHttpResponse (/opt/meshcentral/node_modules/meshcentral/apprelays.js:720:71)
    at processHttpData (/opt/meshcentral/node_modules/meshcentral/apprelays.js:575:17)
    at processRawHttpData (/opt/meshcentral/node_modules/meshcentral/apprelays.js:521:13)
    at WebSocket.<anonymous> (/opt/meshcentral/node_modules/meshcentral/apprelays.js:498:21)
    at WebSocket.emit (node:events:519:28)
    at Receiver.receiverOnMessage (/opt/meshcentral/node_modules/ws/lib/websocket.js:1211:20)
    at Receiver.emit (node:events:519:28)
    at Receiver.dataMessage (/opt/meshcentral/node_modules/ws/lib/receiver.js:567:14) {
  code: 'ERR_INVALID_HTTP_TOKEN'
}

Node.js v21.7.3
Error: Command failed: /usr/bin/node /opt/meshcentral/node_modules/meshcentral --launch 10
(node:21) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
node:internal/errors:541
      throw error;
      ^

TypeError [ERR_INVALID_HTTP_TOKEN]: Header name must be a valid HTTP token [" content-length"]
    at ServerResponse.setHeader (node:_http_outgoing:705:3)
    at ServerResponse.header (/opt/meshcentral/node_modules/express/lib/response.js:795:10)
    at processHttpResponse (/opt/meshcentral/node_modules/meshcentral/apprelays.js:720:71)
    at processHttpData (/opt/meshcentral/node_modules/meshcentral/apprelays.js:575:17)
    at processRawHttpData (/opt/meshcentral/node_modules/meshcentral/apprelays.js:521:13)
    at WebSocket.<anonymous> (/opt/meshcentral/node_modules/meshcentral/apprelays.js:498:21)
    at WebSocket.emit (node:events:519:28)
    at Receiver.receiverOnMessage (/opt/meshcentral/node_modules/ws/lib/websocket.js:1211:20)
    at Receiver.emit (node:events:519:28)
    at Receiver.dataMessage (/opt/meshcentral/node_modules/ws/lib/receiver.js:567:14) {
  code: 'ERR_INVALID_HTTP_TOKEN'
}

Node.js v21.7.3

    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:531:35)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: '/usr/bin/node /opt/meshcentral/node_modules/meshcentral --launch 10'
}
ERROR: MeshCentral failed with critical error, check mesherrors.txt. Restarting in 5 seconds...
```

**Comment by si458** [comment]
OK, great, thanks!
I will have a quick look tomorrow.
We just need to trim the headers for spaces at the beginning!
I have no idea WHY there is a space in the header, so I think this is a supermicro bug with their ipmi!

**Comment by GraphicHealer** [comment]
AHA! I played with it a little bit, and I FOUND IT!
Where you had me replace `obj.res.set(i, header[i]);` with `obj.res.set(i, header[i].trim());` on line 720 of apprelays.js, it should have been `obj.res.set(i.trim(), header[i].trim());`.

Aparently `i` is the header name, and `header[i]` is the header value.

I'm about to test it out! I'll let you know what happens!

**Comment by GraphicHealer** [comment]
IT WORKS!!!

Just update line 720 to this!
```js
else if (blockHeaders.indexOf(i) == -1) { obj.res.set(i.trim(), header[i].trim()); } // Set the headers if not blocked
```

**Comment by GraphicHealer** [comment]
Hmm. Another error popped up.
```
ERR: /opt/meshcentral/node_modules/meshcentral/apprelays.js:284
        res.socket.on('end', handleResponseClosure);
                   ^

TypeError: Cannot read properties of null (reading 'on')
    at obj.processRequest (/opt/meshcentral/node_modules/meshcentral/apprelays.js:284:20)
    at tunnel.oncompleted (/opt/meshcentral/node_modules/meshcentral/apprelays.js:196:116)
    at processHttpResponse (/opt/meshcentral/node_modules/meshcentral/apprelays.js:739:44)
    at processHttpData (/opt/meshcentral/node_modules/meshcentral/apprelays.js:617:21)
    at processRawHttpData (/opt/meshcentral/node_modules/meshcentral/apprelays.js:521:13)
    at WebSocket.<anonymous> (/opt/meshcentral/node_modules/meshcentral/apprelays.js:498:21)
    at WebSocket.emit (node:events:519:28)
    at Receiver.receiverOnMessage (/opt/meshcentral/node_modules/ws/lib/websocket.js:1211:20)
    at Receiver.emit (node:events:519:28)
    at Receiver.dataMessage (/opt/meshcentral/node_modules/ws/lib/receiver.js:567:14)

Node.js v21.7.3
Error: Command failed: /usr/bin/node /opt/meshcentral/node_modules/meshcentral --launch 10
(node:21) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
/opt/meshcentral/node_modules/meshcentral/apprelays.js:284
        res.socket.on('end', handleResponseClosure);
                   ^

TypeError: Cannot read properties of null (reading 'on')
    at obj.processRequest (/opt/meshcentral/node_modules/meshcentral/apprelays.js:284:20)
    at tunnel.oncompleted (/opt/meshcentral/node_modules/meshcentral/apprelays.js:196:116)
    at processHttpResponse (/opt/meshcentral/node_modules/meshcentral/apprelays.js:739:44)
    at processHttpData (/opt/meshcentral/node_modules/meshcentral/apprelays.js:617:21)
    at processRawHttpData (/opt/meshcentral/node_modules/meshcentral/apprelays.js:521:13)
    at WebSocket.<anonymous> (/opt/meshcentral/node_modules/meshcentral/apprelays.js:498:21)
    at WebSocket.emit (node:events:519:28)
    at Receiver.receiverOnMessage (/opt/meshcentral/node_modules/ws/lib/websocket.js:1211:20)
    at Receiver.emit (node:events:519:28)
    at Receiver.dataMessage (/opt/meshcentral/node_modules/ws/lib/receiver.js:567:14)

Node.js v21.7.3

    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:531:35)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: '/usr/bin/node /opt/meshcentral/node_modules/meshcentral --launch 10'
}
ERROR: MeshCentral failed with critical error, check mesherrors.txt. Restarting in 5 seconds...
```

**Comment by si458** [comment]
I think it's because you are trimming the `header[i]`.
that's the value that the other device gives meshcentral to relay to ur browser, so you DONT want to trim it

**Comment by GraphicHealer** [comment]
> I think it's because you are trimming the `header[i]`. that's the value that the other device gives meshcentral to relay to ur browser, so you DONT want to trim it

Ahhhh Ok. I'll update that config then.

**Comment by GraphicHealer** [comment]
Yup! That works. Now my revised update to line 720:
```js
else if (blockHeaders.indexOf(i) == -1) { obj.res.set(i.trim(), header[i]); } // Set the headers if not blocked
```

**Comment by si458** [comment]
Glad it's partly working! 
It's still weird that the IPMI is passing the header with a blank space in front of it?
I would report that to supermicro, or see if you have any firmware updates for it due!

**Comment by GraphicHealer** [comment]
> Glad it's partly working! It's still weird that the IPMI is passing the header with a blank space in front of it? I would report that to supermicro, or see if you have any firmware updates for it due!

I already did a firmware update, and it didn't fix it. Unfortunately it seems to be stuck with the issue for now.

But hey! adding that `.trim()` to `i` worked perfectly! And everything works flawlessly now! Thanks for the help!

BTW, should I put in a quick pull request for that fix?

**Comment by si458** [comment]
Thank you! I have merged it for you!
You can close the issue now if it's fixed/resolved!

**Comment by GraphicHealer** [comment]
Thank you so much!

Lol, I can technically say I have contributed to MeshCentral!
(Even though you did most of the work... Lol)

Out of curiosity, how quickly will this update in node?

**Comment by si458** [comment]
it has been merged into the repo, so IF you want to use it straight away,
you need to install the development build `npm install Ylianst/MeshCentral` 
OR use the docker development image `ghcr.io/ylianst/meshcentral:master`
OR wait until the next release of meshcentral!

remember: development builds use everything from the master branch,
so while includes new fixes/features it COULD also include bugs!
