### ISSUE TITLE
ERR: TypeError: Cannot set properties of null (setting 'MpsType')

### ISSUE THREAD

**Issue by b8two** [Ylianst/MeshCentral#6359]
**Describe the bug**
Looking at the meshcentral log;

```
TypeError: Cannot set properties of null (setting 'MpsType')
    at Object.attemptCiraSyncResponse (/opt/meshcentral/node_modules/meshcentral/amtmanager.js:2075:28)
    at Object.<anonymous> (/opt/meshcentral/node_modules/meshcentral/amt/amt.js:149:186)
    at _EnumContinueSink (/opt/meshcentral/node_modules/meshcentral/amt/amt.js:118:22)
    at /opt/meshcentral/node_modules/meshcentral/amt/amt.js:99:88
    at Array.<anonymous> (/opt/meshcentral/node_modules/meshcentral/amt/amt-wsman.js:51:17)
    at CreateWsmanComm.obj.gotNextMessages (/opt/meshcentral/node_modules/meshcentral/amt/amt-wsman-comm.js:513:26)
    at CreateWsmanComm.obj.xxProcessHttpResponse (/opt/meshcentral/node_modules/meshcentral/amt/amt-wsman-comm.js:442:17)
    at CreateWsmanComm.obj.xxOnSocketData (/opt/meshcentral/node_modules/meshcentral/amt/amt-wsman-comm.js:414:25)
    at obj.socket.onData (/opt/meshcentral/node_modules/meshcentral/amt/amt-wsman-comm.js:204:65)
    at ProcessCommand (/opt/meshcentral/node_modules/meshcentral/mpsserver.js:1118:63)
```

This error also exists (But appeared the previous day)

```
TypeError: Cannot read properties of undefined (reading 'DetectionStrings')
    at Object.attemptCiraSyncResponse (/opt/meshcentral/node_modules/meshcentral/amtmanager.js:2059:108)
    at Object.<anonymous> (/opt/meshcentral/node_modules/meshcentral/amt/amt.js:149:186)
    at _EnumContinueSink (/opt/meshcentral/node_modules/meshcentral/amt/amt.js:118:22)
    at /opt/meshcentral/node_modules/meshcentral/amt/amt.js:99:88
    at Array.<anonymous> (/opt/meshcentral/node_modules/meshcentral/amt/amt-wsman.js:51:17)
    at CreateWsmanComm.obj.gotNextMessages (/opt/meshcentral/node_modules/meshcentral/amt/amt-wsman-comm.js:513:26)
    at CreateWsmanComm.obj.xxProcessHttpResponse (/opt/meshcentral/node_modules/meshcentral/amt/amt-wsman-comm.js:442:17)
    at CreateWsmanComm.obj.xxOnSocketData (/opt/meshcentral/node_modules/meshcentral/amt/amt-wsman-comm.js:414:25)
    at obj.socket.onData (/opt/meshcentral/node_modules/meshcentral/amt/amt-wsman-comm.js:204:65)
    at ProcessCommand (/opt/meshcentral/node_modules/meshcentral/mpsserver.js:1118:63)
```

The only reference I found to **MpsType** was in **amtmanager.js**
`server.MpsType = policy['MpsType']; // MpsType was added in Intel AMT 11.6`

Is this an issue for environments with devices that have Intel AMT versions older than 11.6 ?

**Server Software:**
 - OS: Ubuntu
 - Virtualization: Docker
 - Network: WAN, reverse proxy, ssl offload
 - Version: 1.1.27
 - Node: 20.17.0

**Server Console:**

```
> amtstats
Total Intel AMT devices: 370
Un-provisionned: 67
Provisionned: 303
Versions: 
  6.0.3: 10
  7.1: 1
  8.0.4: 1
  8.0.13: 2
  9.0.31: 15
  9.1: 1
  9.1.20: 1
  9.1.41: 26
  10.0.56: 2
  11.6.10: 1
  11.6.12: 1
  11.8: 3
  11.8.50: 85
  11.8.55: 1
  11.8.65: 4
  11.8.83: 1
  11.8.86: 27
  11.8.92: 1
  11.8.94: 1
  12.0.0: 1
  12.0.5: 13
  12.0.35: 1
  12.0.40: 1
  12.0.81: 24
  14.1.53: 118
  14.1.72: 1
  16.1.25: 26
  16.1.30: 1
```

**Comment by si458** [comment]
**you haven't followed the bug template report, you are missing info without it we cannot help**

**Comment by b8two** [comment]
**Expected behavior**
Not to throw errors

**Client Device (please complete the following information):**
N/A - Server log

**Remote Device (please complete the following information):**
 - Device: iAMT
 - OS: iAMT
 - Network: WAN
 - Browser: N/A
 - MeshCentralRouter Version: N/A



**Your config.json file**
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "cert": "mesh.domain",
    "WANonly": true,
    "_LANonly": true,
    "sessionKey": "sessionKey",
    "dbExpire": {
      "events": 7776000,
      "powerevents": 7776000,
      "statsevents": 7776000
    },
    "port": 443,
    "redirPort": 0,
    "relayDns": "relay.domain",
    "_agentAliasDNS": "agents.domain",
    "_agentSignLock": true,
    "IgnoreAgentHashCheck": true,
    "webRTC": true,
    "_browserPing": 120,
    "browserPong": 300,
    "_agentsInRam": false,
    "_agentPing": 60,
    "agentPong": 120,
    "compression": true,
    "wsCompression": true,
    "agentWsCompression": true,
    "desktopMultiplex": true,
    "manageAllDeviceGroups": [
      "user//domain"
    ],
    "manageCrossDomain": [
      "user//domain"
    ],
    "postgres": {
      "host": "domain",
      "user": "user",
      "port": 5432,
      "password": "password"
    },
    "TLSOffload": true,
    "mpsPort": 8080,
    "mpsAliasHost": "mps.domain",
    "SelfUpdate": false,
    "AllowFraming": "true",
    "webrtcConfig": {
      "iceServers": [
        {
          "urls": "stun:stun.services.mozilla.com"
        },
        {
          "urls": "stun:stun.l.google.com:19302"
        }
      ]
    },
    "AutoBackup": {
      "backupPath": "meshcentral-backups",
      "backupIntervalHours": 6,
      "keepLastDaysBackup": "14",
      "_zippassword": "_zippassword"
    }
  },
  "smtp": {
    "host": "mail.smtp",
    "port": 25,
    "from": "alerts@domain",
    "user": "user",
    "pass": "pass",
    "tls": false
  },
  "domains": {
    "": {
      "title": "Mesh ",
      "siteStyle": 2,
      "title2": "",
      "title1": "",
      "_titlePicture": "",
      "_loginPicture": "",
      "certUrl": "https://domains:443/",
      "loginfooter": "This is a private server.",
      "footer": "",
      "hide": 4,
      "showNotesPanel": true,
      "newAccountsRights": [
        "nonewgroups",
        "notools"
      ],
      "minify": true,
      "deviceMeshRouterLinks": {
        "rdp": true,
        "ssh": true,
        "scp": true,
        "extralinks": [
          {
            "name": "LiteManager",
            "protocol": "lmn",
            "port": 5650
          }
        ]
      },
      "passwordRequirements": {
        "min": 8,
        "max": 128,
        "upper": 1,
        "lower": 1,
        "numeric": 1,
        "nonalpha": 1,
        "reset": 90,
        "force2factor": true,
        "skip2factor": "127.0.0.1",
        "oldPasswordBan": 5,
        "banCommonPasswords": false,
        "twoFactorTimeout": 300
      },
      "mstsc": true,
      "twoFactorCookieDurationDays": 9,
      "NewAccounts": "true"
    },
    "_userNameIsEmail": true,
  }
}
```

**Comment by si458** [comment]
@aelfwine88 what type of amt devices do u have?
What version of amt are they running?
