### ISSUE TITLE
Let's Encrypt issue after upgrade

### ISSUE THREAD

**Issue by alesribic73** [Ylianst/MeshCentral#645]
Today i have upgraded to the latest version, but i had trouble starting a server. After all i have to clean install, only meshcentral-data folder i have overwriten. So users and comuters and other setitings are ok, but certificate is an issue. Even non-production option does not create one. I have also deleted folder "letsencrypt" after that the folder "letsencrypt" is recreated with only 1 empty subfolder "webroot". This is the error:

MeshCentral HTTP redirection server running on port 80.
Error: please supply `maintainerEmail` as a contact for security and critical bug notices
    at Object.E.<computed> [as NO_MAINTAINER] (C:\Program Files\Open Source\MeshCentral\node_modules\@root\greenlock\errors.js:7:19)
    at Object.greenlock._create (C:\Program Files\Open Source\MeshCentral\node_modules\@root\greenlock\greenlock.js:31:25)
    at Object.G.create (C:\Program Files\Open Source\MeshCentral\node_modules\@root\greenlock\greenlock.js:509:15)
    at Object.module.exports.CreateLetsEncrypt (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\letsencrypt.js:61:28)
    at C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\meshcentral.js:837:38
    at Object.obj.GetMeshServerCertificate (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\certoperations.js:571:43)
    at CreateMeshCentralServer.obj.StartEx2 (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\meshcentral.js:832:35)
    at Server.<anonymous> (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\redirserver.js:122:13)
    at Object.onceWrapper (events.js:299:28)
    at Server.emit (events.js:210:5) {
  code: 'NO_MAINTAINER',
  context: 'create'
}
ERROR: Unable to setup GreenLock module.
MeshCentral v0.4.3-x, WAN mode.
MeshCentral Intel(R) AMT server running on rdp.hsi.si:4433.
MeshCentral HTTPS server running on rdp.hsi.si:443.

**Comment by PathfinderNetworks** [comment]
I believe this is the same issue reported here:
https://github.com/Ylianst/MeshCentral/issues/629

**Comment by Ylianst** [comment]
I am back in the office for the next 5 days, fixing this will be high priority starting tomorrow.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.4.4-a with GreenLockv3 support, check #629 for details. I am going to close this one since this is a duplicate. Please post on #629 if any issues are encountered.

**Comment by alesribic73** [comment]
Windows installation. Yes it works like a charm. Just update MescCentral. No need to update Node. 
Thanks for this update
