### ISSUE TITLE
Unable to add device groups while using SAML causes crash (email as userid)

### ISSUE THREAD

**Issue by liv-acollins** [Ylianst/MeshCentral#6596]
**Describe the bug**
When creating a new group MeshCentral appears to crash and then restart itself. Error log contains:
````
/opt/meshcentral/node_modules/@seald-io/nedb/lib/model.js:31
  if (k.indexOf('.') !== -1) throw new Error('Field names cannot contain a .')
                                   ^

Error: Field names cannot contain a .
    at checkKey (/opt/meshcentral/node_modules/@seald-io/nedb/lib/model.js:31:36)
    at checkObject (/opt/meshcentral/node_modules/@seald-io/nedb/lib/model.js:50:9)
    at checkObject (/opt/meshcentral/node_modules/@seald-io/nedb/lib/model.js:51:9)
    at Object.checkObject (/opt/meshcentral/node_modules/@seald-io/nedb/lib/model.js:51:9)
    at Datastore._prepareDocumentForInsertion (/opt/meshcentral/node_modules/@seald-io/nedb/lib/datastore.js:737:13)
    at Datastore._insertAsync (/opt/meshcentral/node_modules/@seald-io/nedb/lib/datastore.js:699:30)
    at /opt/meshcentral/node_modules/@seald-io/nedb/lib/datastore.js:800:47
    at /opt/meshcentral/node_modules/@seald-io/nedb/lib/waterfall.js:28:16
````
This has only just started happening. It was either caused by a version update or due to us having 25 groups - this would be our 26th device group.

**To Reproduce**
With 25 groups active. Click 'New' next to Device Groups on My Account. New Device Group popup will appear, enter details, e.g. Name="Test" - Click 'OK'. MeshCentral then changes page to 'Server Disconnected'. The error above mentions a field cannot contain ".", this character isn't being used in the field name so something else is triggering it.

**Expected behavior**
New empty group you should be added.

**Server Software (please complete the following information):**
 - OS: RockyLinux 9.5
 - Virtualization: None (VMWare host)
 - Network: LAN
 - Version: 1.1.35
 - Node: 16.20.2-8.el9_4

**Client Device (please complete the following information):**
 - Device: Desktop + Laptop
 - OS: Windows 10 22H2
 - Network: Local
 - Browser: Firefox
 - MeshCentralRouter Version: N/A

**Remote Device (please complete the following information):**
N/A

**Additional context**

**Your config.json file**
```
{
  "settings": {
    "cert": "xxxx",
    "meshErrorLogPath": "/var/log/meshcentral/",
    "authLog": "/var/log/meshcentral/auth.log",
    "log": "authlog,web"
  },
  "domains": {
    "": {
      "authStrategies": {
        "saml": {
          "callbackUrl": "xxxx",
          "entityid": "xxxx",
          "idpurl": "xxxx",
          "cert": "xxxx"
        }
      },
      "newAccounts": true,
      "showPasswordLogin": false,
      "title": "xxxx",
      "title2": "xxxx",
      "welcomePicture": "welcome.png",
      "footer": "xxxx"
    }
  }
}

```

**Comment by liv-acollins** [comment]
I modified the error to show the value of k.

```
/opt/meshcentral/node_modules/@seald-io/nedb/lib/model.js:31
  if (k.indexOf('.') !== -1) throw new Error('Field names cannot contain a . "' + k + '"')
                                   ^

Error: Field names cannot contain a . "user//~saml:xxx@xxx.xx.xx"
    at checkKey (/opt/meshcentral/node_modules/@seald-io/nedb/lib/model.js:31:36)
    at checkObject (/opt/meshcentral/node_modules/@seald-io/nedb/lib/model.js:50:9)
    at checkObject (/opt/meshcentral/node_modules/@seald-io/nedb/lib/model.js:51:9)
    at Object.checkObject (/opt/meshcentral/node_modules/@seald-io/nedb/lib/model.js:51:9)
    at Datastore._prepareDocumentForInsertion (/opt/meshcentral/node_modules/@seald-io/nedb/lib/datastore.js:737:13)
    at Datastore._insertAsync (/opt/meshcentral/node_modules/@seald-io/nedb/lib/datastore.js:699:30)
    at /opt/meshcentral/node_modules/@seald-io/nedb/lib/datastore.js:800:47
    at /opt/meshcentral/node_modules/@seald-io/nedb/lib/waterfall.js:28:16
```

As we use SAML, our usernames are email addresses which is trigger the "." check

**Comment by si458** [comment]
Ah right ok!

We already have a function built in which should convert the full stops to like fullstops that nedb can understand so we might of missed one :)

Will look at it next week or when I get chance :)

In the mean time the better way is
not use fullstops for things so change it from email to like username or a random id 
OR
Don't use nedb, switch to another database like sqlite or mongodb or something else

**Comment by si458** [comment]
It's very simple,
1. Stop meshcentral
2. Change ur config.json to whichever database u want
3. Run `node node_modules/meshcentral --nedbtodb`
4. (Maybe skip i can't remember) step 3 might quit so start meshcentral, if it doesn't, skip step 4, ur done :)

**Comment by liv-acollins** [comment]
Fantastic, thank you. Will give it a go when I feel brave enough.

**Comment by si458** [comment]
You can also use the database export and import methods too https://ylianst.github.io/MeshCentral/meshcentral/#database
But this is to change between databases rather than from only nedb to another database

**Comment by Habetdin** [comment]
I've encountered the same issue when adding a device group to my MeshCentral instance:

```
Dec 17 21:35:27 mc node[625]: ERR: /opt/meshcentral/node_modules/@seald-io/nedb/lib/model.js:31
Dec 17 21:35:27 mc node[625]:   if (k.indexOf('.') !== -1) throw new Error('Field names cannot contain a .')
Dec 17 21:35:27 mc node[625]:                                    ^
Dec 17 21:35:27 mc node[625]: Error: Field names cannot contain a .
Dec 17 21:35:27 mc node[625]:     at checkKey (/opt/meshcentral/node_modules/@seald-io/nedb/lib/model.js:31:36)
Dec 17 21:35:27 mc node[625]:     at checkObject (/opt/meshcentral/node_modules/@seald-io/nedb/lib/model.js:50:9)
Dec 17 21:35:27 mc node[625]:     at checkObject (/opt/meshcentral/node_modules/@seald-io/nedb/lib/model.js:51:9)
Dec 17 21:35:27 mc node[625]:     at Object.checkObject (/opt/meshcentral/node_modules/@seald-io/nedb/lib/model.js:51:9)
Dec 17 21:35:27 mc node[625]:     at Datastore._prepareDocumentForInsertion (/opt/meshcentral/node_modules/@seald-io/nedb/lib/datastore.js:737:13)
Dec 17 21:35:27 mc node[625]:     at Datastore._insertAsync (/opt/meshcentral/node_modules/@seald-io/nedb/lib/datastore.js:699:30)
Dec 17 21:35:27 mc node[625]:     at /opt/meshcentral/node_modules/@seald-io/nedb/lib/datastore.js:800:47
Dec 17 21:35:27 mc node[625]:     at /opt/meshcentral/node_modules/@seald-io/nedb/lib/waterfall.js:28:16
Dec 17 21:35:27 mc node[625]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Dec 17 21:35:27 mc node[625]: Node.js v18.19.1
Dec 17 21:35:27 mc node[625]: Error: Command failed: /usr/bin/node /opt/meshcentral/node_modules/meshcentral --launch 625
Dec 17 21:35:27 mc node[625]: /opt/meshcentral/node_modules/@seald-io/nedb/lib/model.js:31
Dec 17 21:35:27 mc node[625]:   if (k.indexOf('.') !== -1) throw new Error('Field names cannot contain a .')
Dec 17 21:35:27 mc node[625]:                                    ^
Dec 17 21:35:27 mc node[625]: Error: Field names cannot contain a .
Dec 17 21:35:27 mc node[625]:     at checkKey (/opt/meshcentral/node_modules/@seald-io/nedb/lib/model.js:31:36)
Dec 17 21:35:27 mc node[625]:     at checkObject (/opt/meshcentral/node_modules/@seald-io/nedb/lib/model.js:50:9)
Dec 17 21:35:27 mc node[625]:     at checkObject (/opt/meshcentral/node_modules/@seald-io/nedb/lib/model.js:51:9)
Dec 17 21:35:27 mc node[625]:     at Object.checkObject (/opt/meshcentral/node_modules/@seald-io/nedb/lib/model.js:51:9)
Dec 17 21:35:27 mc node[625]:     at Datastore._prepareDocumentForInsertion (/opt/meshcentral/node_modules/@seald-io/nedb/lib/datastore.js:737:13)
Dec 17 21:35:27 mc node[625]:     at Datastore._insertAsync (/opt/meshcentral/node_modules/@seald-io/nedb/lib/datastore.js:699:30)
Dec 17 21:35:27 mc node[625]:     at /opt/meshcentral/node_modules/@seald-io/nedb/lib/datastore.js:800:47
Dec 17 21:35:27 mc node[625]:     at /opt/meshcentral/node_modules/@seald-io/nedb/lib/waterfall.js:28:16
Dec 17 21:35:27 mc node[625]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Dec 17 21:35:27 mc node[625]: Node.js v18.19.1
Dec 17 21:35:27 mc node[625]:     at ChildProcess.exithandler (node:child_process:422:12)
Dec 17 21:35:27 mc node[625]:     at ChildProcess.emit (node:events:529:35)
Dec 17 21:35:27 mc node[625]:     at maybeClose (node:internal/child_process:1098:16)
Dec 17 21:35:27 mc node[625]:     at ChildProcess._handle.onexit (node:internal/child_process:303:5) {
Dec 17 21:35:27 mc node[625]:   code: 1,
Dec 17 21:35:27 mc node[625]:   killed: false,
Dec 17 21:35:27 mc node[625]:   signal: null,
Dec 17 21:35:27 mc node[625]:   cmd: '/usr/bin/node /opt/meshcentral/node_modules/meshcentral --launch 625'
Dec 17 21:35:27 mc node[625]: }
Dec 17 21:35:27 mc node[625]: ERROR: MeshCentral failed with critical error, check mesherrors.txt. Restarting in 5 seconds...
```

@si458 in my case the step number 3 took forever to finish, so I've went another way:

1. Export data: `node node_modules/meshcentral --dbexport db.json`
2. Stop MeshCentral
3. Update config.json to use another database
4. Import data: `node node_modules/meshcentral --dbimport db.json`
5. Start MeshCentral

**Comment by si458** [comment]
@Habetdin yes indeed the nedbtodb can take forever because it copies all dats including events etc, where as the export and import only does the data no events or graphs etc

**Comment by si458** [comment]
all fixed 👍  https://github.com/Ylianst/MeshCentral/commit/a1854fa07428348632b696eaf289debfc454ea67
it was actually the events that was causing the issue!
it wasnt escaping the mesh value in the dispatchevents properly
