### ISSUE TITLE
Can't login into mesh

### ISSUE THREAD

**Issue by nicrame** [Ylianst/MeshCentral#66]
Today i find out i have problem with loading meshcentral.
On the web browser side, there is info that i can't load site.
Here is error from Opera:
"Your connection is not private
This server could not prove that it is meshaddrs.com; its security certificate does not specify Subject Alternative Names. This may be caused by a misconfiguration or an attacker intercepting your connection.

You cannot proceed because the website operator has requested heightened security for this domain."

I find this in the logs:
-------- 1/3/2019, 1:25:22 PM ---- 0.2.5-l --------

buffer.js:215
    throw new ERR_INVALID_ARG_TYPE('value', 'not number', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "value" argument must not be of type number. Received type number
    at Function.from (buffer.js:215:11)
    at /meshcentral/node_modules/meshcentral/meshagent.js:162:89
    at FSReqWrap.oncomplete (fs.js:171:20)

**Comment by whalehub** [comment]
It looks like this issue is caused by a misconfigured webserver certificate. Can you paste the public part of your certificate (webserver-cert-public.crt) here?
