### ISSUE TITLE
Username with DOTS in them causes MESH to crash

### ISSUE THREAD

**Issue by GRIFFCOMMca** [Ylianst/MeshCentral#6638]
**Describe the bug**
New install (v1.1.35), created a user (firstname.lastname) as full administrator (with email already validated when creating the user), logged in.. try to create a new group, MESH crashes, claiming it doesnt like a field with "." in it.

Log in as admin (the first user), am able to create the group no issues.   The problem is not seen in v1.1.0), which we use live.

**Windows 11 Pro
Fresh install of NODE then MESH (v1.1.35)**

**ERROR seen:**
```
if (k.indexOf('.') !== -1) throw new Error('Field names cannot contain a .')
^
Error: Field names cannot contain a .
at checkKey (C:\meshcentral\node_modules\@seald-io\nedb\lib\model.js:31:36)
at checkObject (C:\meshcentral\node_modules\@seald-io\nedb\lib\model.js:50:9)
at checkObject (C:\meshcentral\node_modules\@seald-io\nedb\lib\model.js:51:9)
at Object.checkObject (C:\meshcentral\node_modules\@seald-io\nedb\lib\model.js:51:9)
at Datastore._prepareDocumentForInsertion (C:\meshcentral\node_modules\@seald-io\nedb\lib\datastore.js:737:13)
at Datastore._insertAsync (C:\meshcentral\node_modules\@seald-io\nedb\lib\datastore.js:699:30)
at C:\meshcentral\node_modules\@seald-io\nedb\lib\datastore.js:800:47
at C:\meshcentral\node_modules\@seald-io\nedb\lib\waterfall.js:28:16
Node.js v22.12.0
```

**CONFIG FILE (removed sensitive info)**
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "settings": {
    "cert": "domain.com",
	"port": 10443
  },
  "domains": {
    "": {
		"title": "GRIFFCOMM Support",
		"title2": "(Canada)",
		"titlePicture": "icon-logo.png",
		"loginPicture": "icon-logo_login.png",
		"_newAccounts": true,
		"_userNameIsEmail": true,
		"welcomeText": "Canada<br>domain.com",
		"loginfooter": "GRIFFCOMM Support v1.1.35",
		"footer": "GRIFFCOMM Support v1.1.35",
		"allowedOrigin": true,
	"agentCustomization": {
		"displayName": "GRIFFCOMM Support (Mesh)",
		"description": "GRIFFCOMM Support agent",
		"companyName": "GRIFFCOMM Inc (Canada)",
		"serviceName": "GRIFFCOMM Support Mesh",
		"installText": "What to put here",
		"fileName": "GRIFFCOMM Support - Mesh Agent (url) "
	}
	}
  },
	"smtp": {
		"name": "domain.com",
        "host": "172.16.0.32",
        "port": 25,
        "from": "alerts@domain.com",
	    "user": "alerts@dopmain.com",
        "pass": "pass",
        "verifyemail": true
	},  
  "letsencrypt": {
    "email": "alerts@domain.com",
    "names": "domain.com",
    "skipChallengeVerification": true,
    "production": false
  }
}
```

**Comment by si458** [comment]
ive just tried to replicate the issue here and i cant seem to replicate it?
node 22, windows 11, did you use the meshcentralinstaller or the `npm install` method?

**Comment by GRIFFCOMMca** [comment]
Downloaded NODE manually, then install mesh from the node command line in Windows, i didnt use the Windows installer method.

**Comment by si458** [comment]
nope just tried it here and works perfectly fine?
1. fresh vm of win 11
2. installed node 22 LTS
3. cd documents
4. mkdir meshcentral
5. cd meshcentral
6. npm install meshcentral
7. node node_modules/meshcentral
8. let it create certificates etc
9. https://localhost
10. create account with username as `simon.smith`
11. click create, logged in no problems ?

**Comment by GRIFFCOMMca** [comment]
Well thats odd, looks like it was fixed 2 weeks ago, but when did the bug appear as the version we are using doesnt have this issue

**Comment by si458** [comment]
I genuinely have no idea when it first started or happened.
The issue was actually to do with the event being saved into the db to say I created a meshgroup, not the actual saving of the group itself

**Comment by GRIFFCOMMca** [comment]
v1.1.36 fixed the issue
