### ISSUE TITLE
crash when trying to clear server error log

### ISSUE THREAD

**Issue by wh1te909** [Ylianst/MeshCentral#71]
version: 0.2.5-v

When trying to clear server error log after doing "Check and click OK to clear error log.", server crashes with following error:

ERROR: MeshCentral failed with critical error, check MeshErrors.txt. Restarting in 5 seconds...
`fs.js:137
    throw new ERR_INVALID_CALLBACK();
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:137:11)
    at Object.unlink (fs.js:939:14)
    at WebSocket.processWebSocketData (/meshcentral/node_modules/meshcentral/meshuser.js:727:42)
    at WebSocket.emit (events.js:182:13)
    at Receiver.receiverOnMessage (/meshcentral/node_modules/express-ws/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (events.js:182:13)
    at Receiver.dataMessage (/meshcentral/node_modules/express-ws/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/meshcentral/node_modules/express-ws/node_modules/ws/lib/receiver.js:346:17)
    at Receiver.startLoop (/meshcentral/node_modules/express-ws/node_modules/ws/lib/receiver.js:133:22)
    at Receiver._write (/meshcentral/node_modules/express-ws/node_modules/ws/lib/receiver.js:69:10)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at Receiver.Writable.write (_stream_writable.js:294:11)
    at TLSSocket.socketOnData (/meshcentral/node_modules/express-ws/node_modules/ws/lib/websocket.js:795:35)
    at TLSSocket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)`

**Comment by Ylianst** [comment]
Published MeshCentral v0.2.5-w with a fix for this. This error would only happen with NodeJS v10 or higher, thank you for the report. Please confirm it's fixed and close the issue if it is. - Thanks.

**Comment by wh1te909** [comment]
fixed thank you!
