### ISSUE TITLE
Mesh Service crashes when Deleting a Node

### ISSUE THREAD

**Issue by asasin114** [Ylianst/MeshCentral#771]
Ran into a strange one this afternoon. I went to delete a node off my server and when I confirmed the deletion of the node the server proceeded to crash and I have the following in the log when the service restarts:

-------- 12/28/2019, 3:48:33 PM ---- 0.4.6-q --------

C:\Program Files\Open Source\MeshCentral\node_modules\mongodb\lib\utils.js:133
      throw err;
      ^

TypeError: Cannot read property 'name' of null
    at C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\meshuser.js:2125:196
    at C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\webserver.js:3921:13
    at C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\db.js:667:79
    at result (C:\Program Files\Open Source\MeshCentral\node_modules\mongodb\lib\operations\execute_operation.js:75:17)
    at executeCallback (C:\Program Files\Open Source\MeshCentral\node_modules\mongodb\lib\operations\execute_operation.js:68:9)
    at handleCallback (C:\Program Files\Open Source\MeshCentral\node_modules\mongodb\lib\utils.js:129:55)
    at cursor.close (C:\Program Files\Open Source\MeshCentral\node_modules\mongodb\lib\operations\to_array.js:36:13)
    at handleCallback (C:\Program Files\Open Source\MeshCentral\node_modules\mongodb\lib\utils.js:129:55)
    at completeClose (C:\Program Files\Open Source\MeshCentral\node_modules\mongodb\lib\cursor.js:859:16)
    at Cursor.close (C:\Program Files\Open Source\MeshCentral\node_modules\mongodb\lib\cursor.js:878:12)
    at cursor._next (C:\Program Files\Open Source\MeshCentral\node_modules\mongodb\lib\operations\to_array.js:35:25)
    at handleCallback (C:\Program Files\Open Source\MeshCentral\node_modules\mongodb\lib\core\cursor.js:32:5)
    at _setCursorNotifiedImpl (C:\Program Files\Open Source\MeshCentral\node_modules\mongodb\lib\core\cursor.js:694:38)
    at self._endSession (C:\Program Files\Open Source\MeshCentral\node_modules\mongodb\lib\core\cursor.js:703:39)
    at Cursor._endSession (C:\Program Files\Open Source\MeshCentral\node_modules\mongodb\lib\core\cursor.js:404:7)
    at _setCursorNotifiedImpl (C:\Program Files\Open Source\MeshCentral\node_modules\mongodb\lib\core\cursor.js:703:10)

For reference, I'm running Windows Server 2019

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.6-r with a fix for this. Thanks for reporting it.

**Comment by asasin114** [comment]
Working great now. Thank you!
