### ISSUE TITLE
Upgrade to 0.4.8-b gives an error

### ISSUE THREAD

**Issue by OutbackMatt** [Ylianst/MeshCentral#881]
-------- 1/28/2020, 5:33:17 PM ---- 0.4.8-b --------

internal/fs/utils.js:453
    throw err;
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type object
    at Object.readdirSync (fs.js:785:3)
    at getRenderList (/etc/meshcentral/node_modules/meshcentral/webserver.js:4404:36)
    at Object.module.exports.CreateWebServer (/etc/meshcentral/node_modules/meshcentral/webserver.js:184:5)
    at AsyncWrap.<anonymous> (/etc/meshcentral/node_modules/meshcentral/meshcentral.js:1148:59)
    at AsyncWrap.wrap.ondone (internal/crypto/random.js:57:8)

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.8-c with the fix.

On a related topic: Your server has a "meshcentral-web" folder, if you happen to have the "meshcentral-web/views" folder with replacements for some .handlebars files, you can now run `node node_modules/meshcentral --translate` to translate the modified files to other languages.
