### ISSUE TITLE
Issue Bis Self Upgrade 0.1.6-d to 0.1.6-j

### ISSUE THREAD

**Issue by LinkPhoenix** [Ylianst/MeshCentral#9]
Again error with SelfUpgrade

```
{ Error: Command failed: /usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshcentral.js --launch
sh: 0: getcwd() failed: No such file or directory
path.js:1167
          cwd = process.cwd();
                        ^

Error: ENOENT: no such file or directory, uv_cwd
    at Object.resolve (path.js:1167:25)
    at Function.Module._resolveLookupPaths (module.js:424:17)
    at Function.Module._resolveFilename (module.js:541:20)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at getConfig (/opt/meshcentral/node_modules/meshcentral/meshcentral.js:1088:5)
    at /opt/meshcentral/node_modules/meshcentral/meshcentral.js:1123:22
    at InstallModules (/opt/meshcentral/node_modules/meshcentral/meshcentral.js:1094:103)
    at InstallModule (/opt/meshcentral/node_modules/meshcentral/meshcentral.js:1112:5)

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:131:20)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshcentral.js --launch' }
ERROR: MeshCentral failed with critical error, check MeshErrors.txt. Restarting in 5 seconds...
```

After CTRL-C and try launch meshcentral

```
root@HOSTNAME:/opt/meshcentral/node_modules/meshcentral# node meshcentral.js
path.js:1167
          cwd = process.cwd();
                        ^

Error: ENOENT: no such file or directory, uv_cwd
    at Object.resolve (path.js:1167:25)
    at startup (bootstrap_node.js:169:32)
    at bootstrap_node.js:609:3
```

After Npm Update and try again launch is ok

**Comment by Ylianst** [comment]
Let me know if this still happens on the latest versions of MeshCentral (v0.2.0 and higher). I have not seen this error, not sure how to go about making it show up on my computer.

**Comment by Ylianst** [comment]
No sure what to do with this report since I have never seen it. I have fixed MeshCentral a while back to detect and not run on any version of Node less than v6. This did solve some problem for me as I sometimes tried to install MeshCentral on older NodeJS. If this still happens, please let me know that OS and NodeJS version you are using.

**Comment by Ylianst** [comment]
I will close this one since I have not seen this in a long time. However, if you see this on recent versions of MeshCentral, please open this again.
