### ISSUE TITLE
MeshCentral do not start after upgrade from 4.7.something

### ISSUE THREAD

**Issue by nicrame** [Ylianst/MeshCentral#939]
Just find that in mesherrors.txt
-------- 2/10/2020, 10:43:09 PM ---- 0.4.8-w --------

/opt/meshcentral/node_modules/meshcentral/amtscanner.js:169
                    const ciraConnection = obj.parent.mpsserver.ciraConnections[doc._id];
                                                               ^

TypeError: Cannot read property 'ciraConnections' of null
    at /opt/meshcentral/node_modules/meshcentral/amtscanner.js:169:64
    at newArguments.(anonymous function) (/opt/meshcentral/node_modules/nedb/lib/executor.js:29:17)
    at Cursor.execFn (/opt/meshcentral/node_modules/nedb/lib/datastore.js:484:12)
    at callback (/opt/meshcentral/node_modules/nedb/lib/cursor.js:126:19)
    at /opt/meshcentral/node_modules/nedb/lib/cursor.js:193:12
    at /opt/meshcentral/node_modules/nedb/lib/datastore.js:329:14
    at Object.async.eachSeries (/opt/meshcentral/node_modules/nedb/node_modules/async/lib/async.js:130:20)
    at /opt/meshcentral/node_modules/nedb/lib/datastore.js:323:11
    at fn (/opt/meshcentral/node_modules/nedb/node_modules/async/lib/async.js:582:34)
    at Immediate.<anonymous> (/opt/meshcentral/node_modules/nedb/node_modules/async/lib/async.js:498:34)

**Comment by Ylianst** [comment]
Working on this now!!!

**Comment by jsastriawan** [comment]
I think we need to create MPS server before starting amt-scanner because recently we add cira connection checking.

**Comment by Ylianst** [comment]
MPS server is not always present. In LAN mode, it is never present.

**Comment by Ylianst** [comment]
Thank you for the report! Just rushed MeshCentral v0.4.8-x out to fix this. Let me know if it works.

**Comment by Ylianst** [comment]
@jsastriawan pull request #936 was the cause of this. My fault for not catching this.

**Comment by nicrame** [comment]
Working fine now, thank You for super ultra fast fix!

**Comment by southeasterntech** [comment]
that works!  please close and thanks
